import Link from 'next/link'
import { SiteHeader } from '@/components/SiteHeader'
import { SiteFooter } from '@/components/SiteFooter'
import { ScrollReveals } from '@/components/Motion'
import { ScrollSpy } from '@/components/ScrollSpy'
import { LeadModal } from '@/components/LeadModal'
import { areaSlug, serviceAreas, testimonials } from '@/content/site'

const services = [
  ['Buying a Home', 'Real-time listings, pre-approval guidance, saved searches, and support through closing.', '/home-buyers/'],
  ['Selling a Home', 'Market analysis, staging, marketing, negotiation, and focused closing support.', '/seller-services/'],
  ['Homes for Rent', 'Neighborhood guidance, rental listings, leasing, and property management.', '/homes-for-rent/'],
  ['New Construction', 'Builder guidance and experienced representation from plans to closing.', '/new-home-construction/'],
]

const faqs = [
  ['How do I get started with buying a home?', 'Get pre-approved by a mortgage banker for the amount you want, then use our real-time MLS Home Search to explore homes for sale and rent. We guide you through offers, contingencies, addendums, and closing.'],
  ['What is a free Market Analysis?', 'We review your home, neighborhood, and recent sales to recommend a competitive price and a marketing plan — at no cost and with no obligation.'],
  ['Do you help with rentals and property management?', 'Yes. We handle real-time rental listings, tenant interviews, background checks, leases, deposits, maintenance, and repairs for owners.'],
  ['Which areas do you serve?', 'We serve Clear Lake NASA and surrounding communities including League City, Friendswood, Seabrook, Kemah, Nassau Bay, Galveston, Pearland, and more.'],
  ['Are you a full-service brokerage?', 'Family owned since 2004, we represent buyers, sellers, renters, and commercial clients with over 100 years of combined experience.'],
]

export default function Home() {
  return <div className="site-shell"><SiteHeader /><main>
    <section className="hero"><div className="hero-bg" style={{ backgroundImage: "url('/assets/reference/leaguecityhomesforsale.jpg')" }} aria-hidden="true" /><div className="hero-glow" aria-hidden="true" /><div className="hero-content"><p className="hero-badge">Family owned since 2004 · Clear Lake NASA</p><h1>Real estate guidance that feels <em>personal.</em></h1><p className="hero-sub">Top 3% Realtors in Clear Lake, great reviews, and real-time listings for the next move in your story.</p><div className="hero-actions"><Link className="button button-primary" href="/contact/">Contact a Realtor <span>↗</span></Link><Link className="button button-outline" href="/home-search/">Search homes <span>↗</span></Link></div><div className="hero-trust"><div className="avatar-stack"><img src="/assets/reference/agents/David-Karstedt.jpg" alt="David Karstedt" /><img src="/assets/reference/agents/Mark-Bocado.jpg" alt="Mark Bocado" /><img src="/assets/reference/agents/Nancy-Estes.jpg" alt="Nancy Estes" /><img src="/assets/reference/agents/Matt-Bradley.jpg" alt="Matt Bradley" /></div><div><span className="stars" aria-label="Rated 5 out of 5 stars">★★★★★</span><small>Trusted by families across Clear Lake NASA</small></div></div><div className="hero-features"><div><strong>Family owned</strong><small>Since 2004 in Clear Lake</small></div><div><strong>Top 3% Realtors</strong><small>Clear Lake NASA expertise</small></div><div><strong>Real-time listings</strong><small>Homes for sale &amp; rent</small></div></div><p className="hero-notes">Family owned since 2004 · 100+ years combined experience · Real-time MLS listings</p></div><img className="hero-person" src="/assets/reference/1st-tx-realtors-couple-slider.png" alt="David and Simone Karstedt of 1st Texas Realtors" /></section>
    <div className="marquee" aria-label="Service areas"><div className="marquee-track">{[...serviceAreas.slice(0, 9), ...serviceAreas.slice(0, 9)].map((area, i) => <Link key={`${area}-${i}`} href={`/realtors-in-${areaSlug(area)}/`} tabIndex={i < 9 ? undefined : -1}>{area}</Link>)}</div></div>
    <section className="section intro-section reveal" id="welcome"><div className="section-heading"><p className="eyebrow">Welcome to 1st Texas Realtors</p><h2>Clarity for buying, selling, and everything between.</h2><p><strong>Family owned since 2004,</strong> we provide expert Realtors in Clear Lake, dedicated customer service, and real-time listings of homes for sale and rent.</p></div><div className="intro-copy"><p><strong>David Karstedt and wife Simone</strong> work as a team, bringing exceptional responsiveness, deep knowledge, strong negotiation skills, and patient service to each client.</p><div className="stats-band"><div className="stat"><strong>20+</strong><small>Years serving Clear Lake</small></div><div className="stat"><strong>100+</strong><small>Years combined experience</small></div><div className="stat"><strong>Top 3%</strong><small>Realtor ranking</small></div></div><Link className="text-link" href="/realtor-reviews/">Read our testimonials <span>↗</span></Link></div></section>
    <section className="section section-tint reveal" id="services"><div className="section-heading"><p className="eyebrow">How we help</p><h2>A better way forward.</h2></div><div className="service-grid">{services.map(([title, body, href], index) => <article className="service-card" key={title}><span className="step-badge">{index + 1}</span><h3>{title}</h3><p>{body}</p><Link href={href}>Explore service <span>↗</span></Link></article>)}</div></section>
    <section className="section split-section reveal" id="team"><div><p className="eyebrow">Local knowledge</p><h2>People who know the place.</h2><p>From Clear Lake City and Friendswood to League City, Kemah, Seabrook, and Galveston, we know the neighborhoods, schools, grocery stores, commutes, and local people.</p><Link className="button button-dark" href="/agents/">Meet our Realtors <span>↗</span></Link></div><img src="/assets/reference/1st-Texas-Realtors-Team2.png" alt="The 1st Texas Realtors team" /></section>
    <section className="section section-dark reveal" id="reviews"><div className="section-heading"><p className="eyebrow">Great reviews &amp; testimonials</p><h2>Service people remember.</h2></div><div className="testimonial-grid">{testimonials.slice(0, 3).map(review => <blockquote key={review.author}><span className="stars" aria-label="Rated 5 out of 5 stars">★★★★★</span><p>“{review.quote}”</p><cite>{review.author}</cite></blockquote>)}</div><Link className="button button-light" href="/realtor-reviews/">Read all testimonials <span>↗</span></Link></section>
    <section className="section reveal" id="next-move"><div className="cta-showcase"><p className="eyebrow">Your next move</p><h2>Let’s make a plan.</h2><p>Call us for immediate assistance or explore our service areas and real-time home search.</p><div className="cta-links"><Link href="/register/"><span>01</span>Register <b>↗</b></Link><Link href="/home-search/"><span>02</span>Home search <b>↗</b></Link><Link href="/contact/"><span>03</span>Contact us <b>↗</b></Link></div></div></section>
    <section className="section faq-section reveal" id="faq"><div className="section-heading"><p className="eyebrow">Common questions</p><h2>Answers before you ask.</h2><p>Everything you need to know about buying, selling, renting, and working with our team.</p></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="section areas-section reveal" id="areas"><div className="section-heading"><p className="eyebrow">Serving the region</p><h2>Local Realtors across Clear Lake NASA.</h2></div><div className="area-grid">{serviceAreas.map(area => <Link key={area} href={`/realtors-in-${areaSlug(area)}/`}>{area}<span>↗</span></Link>)}</div></section>
  </main><SiteFooter /><ScrollReveals /><ScrollSpy /><LeadModal /></div>
}
