import Link from 'next/link'
import { SiteHeader } from '@/components/SiteHeader'
import { SiteFooter } from '@/components/SiteFooter'
import { ScrollReveals } from '@/components/Motion'
import { areaSlug, serviceAreas, testimonials } from '@/content/site'

const services = [
  ['Buying a Home', 'Real-time listings, pre-approval guidance, saved searches, and support through closing.', '/home-buyers/'],
  ['Selling a Home', 'Market analysis, staging, marketing, negotiation, and focused closing support.', '/seller-services/'],
  ['Homes for Rent', 'Neighborhood guidance, rental listings, leasing, and property management.', '/homes-for-rent/'],
  ['New Construction', 'Builder guidance and experienced representation from plans to closing.', '/new-home-construction/'],
]

export default function Home() {
  return <div className="site-shell"><SiteHeader /><main>
    <section className="hero"><div className="hero-glow" aria-hidden="true" /><div className="hero-content"><p className="hero-badge">Family owned since 2004 · Clear Lake NASA</p><h1>Real estate guidance that feels personal.</h1><p className="hero-sub">Top 3% Realtors in Clear Lake, great reviews, and real-time listings for the next move in your story.</p><div className="hero-actions"><Link className="button" href="/contact/">Contact a Realtor <span>↗</span></Link><Link className="button button-outline" href="/home-search/">Search homes <span>↗</span></Link></div><div className="hero-features"><div><strong>Family owned</strong><small>Since 2004 in Clear Lake</small></div><div><strong>Top 3% Realtors</strong><small>Clear Lake NASA expertise</small></div><div><strong>Real-time listings</strong><small>Homes for sale &amp; rent</small></div></div></div><img className="hero-person" src="/assets/reference/1st-tx-realtors-couple-slider.png" alt="David and Simone Karstedt of 1st Texas Realtors" /></section>
    <nav className="community-nav" aria-label="Service areas">{serviceAreas.slice(0, 9).map(area => <Link key={area} href={`/realtors-in-${areaSlug(area)}/`}>{area}</Link>)}</nav>
    <section className="section intro-section reveal"><div className="section-heading"><p className="eyebrow">Welcome to 1st Texas Realtors</p><h2>Clarity for buying, selling, and everything between.</h2><p><strong>Family owned since 2004,</strong> we provide expert Realtors in Clear Lake, dedicated customer service, and real-time listings of homes for sale and rent.</p></div><div className="intro-copy"><p><strong>David Karstedt and wife Simone</strong> work as a team, bringing exceptional responsiveness, deep knowledge, strong negotiation skills, and patient service to each client.</p><Link className="text-link" href="/realtor-reviews/">Read our testimonials <span>↗</span></Link></div></section>
    <section className="section section-tint reveal"><div className="section-heading"><p className="eyebrow">How we help</p><h2>A better way forward.</h2></div><div className="service-grid">{services.map(([title, body, href], index) => <article className="service-card" key={title}><p className="eyebrow">0{index + 1}</p><h3>{title}</h3><p>{body}</p><Link href={href}>Explore service <span>↗</span></Link></article>)}</div></section>
    <section className="section split-section reveal"><div><p className="eyebrow">Local knowledge</p><h2>People who know the place.</h2><p>From Clear Lake City and Friendswood to League City, Kemah, Seabrook, and Galveston, we know the neighborhoods, schools, grocery stores, commutes, and local people.</p><Link className="button button-dark" href="/agents/">Meet our Realtors <span>↗</span></Link></div><img src="/assets/reference/1st-Texas-Realtors-Team2.png" alt="The 1st Texas Realtors team" /></section>
    <section className="section section-dark reveal"><div className="section-heading"><p className="eyebrow">Great reviews & testimonials</p><h2>Service people remember.</h2></div><div className="testimonial-grid">{testimonials.slice(0, 3).map(review => <blockquote key={review.author}><p>“{review.quote}”</p><cite>{review.author}</cite></blockquote>)}</div><Link className="button button-light" href="/realtor-reviews/">Read all testimonials <span>↗</span></Link></section>
    <section className="section reveal"><div className="section-heading"><p className="eyebrow">Your next move</p><h2>Let’s make a plan.</h2><p>Call us for immediate assistance or explore our service areas and real-time home search.</p></div><div className="cta-grid"><Link className="cta-card" href="/register/"><span>01</span><strong>Register</strong><small>Build custom searches and receive email alerts.</small></Link><Link className="cta-card" href="/home-search/"><span>02</span><strong>Home search</strong><small>Browse real-time listings of homes for sale and rent.</small></Link><Link className="cta-card" href="/contact/"><span>03</span><strong>Contact us</strong><small>Ask a question and connect with a Realtor.</small></Link></div></section>
    <section className="section areas-section reveal"><div className="section-heading"><p className="eyebrow">Serving the region</p><h2>Local Realtors across Clear Lake NASA.</h2></div><div className="area-grid">{serviceAreas.map(area => <Link key={area} href={`/realtors-in-${areaSlug(area)}/`}>{area}<span>↗</span></Link>)}</div></section>
  </main><SiteFooter /><ScrollReveals /></div>
}
