// Shoreacres homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const shoreacresListings: Listing[] = [
  {
    mls: '16056669',
    address: '625 Shadylawn Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$275,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,248',
    acres: '0.298',
    yearBuilt: '1982',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Set on an oversized lot in the coastal community o ...',
    photo: '/assets/listings/shoreacres/16056669.jpg',
    status: 'Active',
  },
  {
    mls: '26349372',
    address: '217 Baywood Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$404,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,940',
    acres: '0.31',
    yearBuilt: '1996',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Seller is super motivated and ready to move this p ...',
    photo: '/assets/listings/shoreacres/26349372.jpg',
    status: 'Active',
  },
  {
    mls: '16320142',
    address: '626 Shore Acres Boulevard',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$229,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,465',
    acres: '0.224',
    yearBuilt: '1962',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Recently Refreshed + No HOA + Salty Air… You Had M ...',
    photo: '/assets/listings/shoreacres/16320142.jpg',
    status: 'Active',
  },
  {
    mls: '2658879',
    address: '4 Shore Acres Circle',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$589,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,975',
    acres: '0.58',
    yearBuilt: '2022',
    subdivision: 'Shoreacres Hotel Site',
    county: 'Harris',
    remarks: 'Wake up to the bay breeze and end your day on a 63 ...',
    photo: '/assets/listings/shoreacres/2658879.jpg',
    status: 'Active',
  },
  {
    mls: '95764568',
    address: '628 Oakdale Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$300,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,596',
    acres: '0.298',
    yearBuilt: '2024',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'This house is very modern in design with accents o ...',
    photo: '/assets/listings/shoreacres/95764568.jpg',
    status: 'Active',
  },
  {
    mls: '34887515',
    address: '3530 Highway 146 S',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$389,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,205',
    acres: '0.447',
    yearBuilt: '1999',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'This is one of the most unique homes in all of Sho ...',
    photo: '/assets/listings/shoreacres/34887515.jpg',
    status: 'Active',
  },
  {
    mls: '54120660',
    address: '604 Fairfield Street E',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$329,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,664',
    acres: '0.165',
    yearBuilt: '',
    subdivision: 'Bay Village Sec 2',
    county: 'Harris',
    remarks: 'Stunning elevated home designed for both style and ...',
    photo: '/assets/listings/shoreacres/54120660.jpg',
    status: 'Active',
  },
  {
    mls: '60401504',
    address: '502 Oakdale Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$182,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,504',
    acres: '0.597',
    yearBuilt: '1984',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Discover an incredible opportunity in Shoreacres, ...',
    photo: '/assets/listings/shoreacres/60401504.jpg',
    status: 'Active',
  },
  {
    mls: '87201327',
    address: '519 Fairfield Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$322,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,995',
    acres: '0.298',
    yearBuilt: '1985',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Live like every day is a getaway in Shoreacres. Se ...',
    photo: '/assets/listings/shoreacres/87201327.jpg',
    status: 'Active',
  },
  {
    mls: '2893002',
    address: '210 Fairfield Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$278,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,488',
    acres: '0.165',
    yearBuilt: '1945',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Vacation living in Shoreacres with view and extrem ...',
    photo: '/assets/listings/shoreacres/2893002.jpg',
    status: 'Active',
  },
  {
    mls: '53413545',
    address: '632 Meadowlawn Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$320,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,587',
    acres: '0.537',
    yearBuilt: '1960',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Spacious property featuring 2 lots with beautiful ...',
    photo: '/assets/listings/shoreacres/53413545.jpg',
    status: 'Active',
  },
  {
    mls: '18787788',
    address: '3323 Westview Street',
    city: 'Shoreacres',
    state: 'Texas',
    zip: '77571',
    price: '$249,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,576',
    acres: '0.193',
    yearBuilt: '1971',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'PRISTINE HOME THAT HAS BEEN PREPPED BY ...',
    photo: '/assets/listings/shoreacres/18787788.jpg',
    status: 'Active',
  },
]
