// League City homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const leaguecityListings: Listing[] = [
  {
    mls: '20966886',
    address: '231 Creekside Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$515,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,558',
    acres: '0.276',
    yearBuilt: '1993',
    subdivision: 'Creekside Estates Sec 1 93',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully updated one-story home ...',
    photo: '/assets/listings/league-city/20966886.jpg',
    status: 'Active',
  },
  {
    mls: '19586136',
    address: '2146 Brittany Colony Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$499,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,803',
    acres: '0.199',
    yearBuilt: '2004',
    subdivision: 'Brittany Lakes Sec 8 2004',
    county: 'Galveston',
    remarks: 'Imagine waking up the sunrise over the water every ...',
    photo: '/assets/listings/league-city/19586136.jpg',
    status: 'Active',
  },
  {
    mls: '52381293',
    address: '5135 Candlewood Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$355,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,048',
    acres: '0.165',
    yearBuilt: '2001',
    subdivision: 'Countryside Sec 4',
    county: 'Galveston',
    remarks: 'Beautifully maintained home in the heart of League ...',
    photo: '/assets/listings/league-city/52381293.jpg',
    status: 'Active',
  },
  {
    mls: '42811613',
    address: '3206 Wavecrest Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$247,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,355',
    acres: '0.161',
    yearBuilt: '1975',
    subdivision: 'Bay Ridge',
    county: 'Galveston',
    remarks: 'Brand new FENCE(August 2026), NO HOA, New HVAC(202 ...',
    photo: '/assets/listings/league-city/42811613.jpg',
    status: 'Active',
  },
  {
    mls: '8568068',
    address: '2299 Cantabria Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$329,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,997',
    acres: '0.132',
    yearBuilt: '2007',
    subdivision: 'Mar Bella Sec 3 2007',
    county: 'Galveston',
    remarks: 'Brand new roof! Beautiful 3 bedroom/2 bathroom, we ...',
    photo: '/assets/listings/league-city/8568068.jpg',
    status: 'Active',
  },
  {
    mls: '12222223',
    address: '2112 Hyde Acres Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$269,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,538',
    acres: '0.14',
    yearBuilt: '2024',
    subdivision: 'Samara Sec 5',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully maintained 2024 L ...',
    photo: '/assets/listings/league-city/12222223.jpg',
    status: 'Active',
  },
  {
    mls: '88300174',
    address: '2131 Shaly Breeze Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$409,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,305',
    acres: '0.182',
    yearBuilt: '1999',
    subdivision: 'Brittany Lakes Sec 1 97',
    county: 'Galveston',
    remarks: 'Completely beautifully renovated one-story home in ...',
    photo: '/assets/listings/league-city/88300174.jpg',
    status: 'Active',
  },
  {
    mls: '31192524',
    address: '2703 Northern Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$265,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,236',
    acres: '0.167',
    yearBuilt: '1982',
    subdivision: 'The Landing',
    county: 'Galveston',
    remarks: 'Vaulted ceilings, beautifully updated interiors, a ...',
    photo: '/assets/listings/league-city/31192524.jpg',
    status: 'Active',
  },
  {
    mls: '74561961',
    address: '308 Tiegs Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$239,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,438',
    acres: '0.18',
    yearBuilt: '1969',
    subdivision: 'Meadowicke 2',
    county: 'Galveston',
    remarks: 'Welcome to this charming 4 bed, 2 bath single-stor ...',
    photo: '/assets/listings/league-city/74561961.jpg',
    status: 'Active',
  },
  {
    mls: '90608288',
    address: '3606 Pedregal Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$459,998',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,849',
    acres: '0.497',
    yearBuilt: '2021',
    subdivision: 'Pedregal',
    county: 'Galveston',
    remarks: 'Located in Pedregal, this beautifully designed one ...',
    photo: '/assets/listings/league-city/90608288.jpg',
    status: 'Active',
  },
  {
    mls: '21011151',
    address: '2420 Lighthouse Hill Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$287,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,538',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Newlin ...',
    photo: '/assets/listings/league-city/21011151.jpg',
    status: 'Active',
  },
  {
    mls: '82109593',
    address: '2017 Enterprise Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$309,500',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,963',
    acres: '0.059',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour 2 Townhome',
    county: 'Galveston',
    remarks: 'Experience stunning water views and lush waterfron ...',
    photo: '/assets/listings/league-city/82109593.jpg',
    status: 'Active',
  },
  {
    mls: '23038269',
    address: '811 Arlington Pointe Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$399,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,761',
    acres: '0.207',
    yearBuilt: '2011',
    subdivision: 'Centerpointe',
    county: 'Galveston',
    remarks: 'Set on an impressive 80-foot lot in Centerpointe, ...',
    photo: '/assets/listings/league-city/23038269.jpg',
    status: 'Active',
  },
  {
    mls: '20542099',
    address: '429 Blossomwood Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$395,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,740',
    acres: '0.177',
    yearBuilt: '2000',
    subdivision: 'Claremont Park Sec 3 2000',
    county: 'Galveston',
    remarks: 'Great two story home in Claremont Park with no bac ...',
    photo: '/assets/listings/league-city/20542099.jpg',
    status: 'Active',
  },
  {
    mls: '97910292',
    address: '2604 Starfish Crossing Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$347,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,973',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Joplin ...',
    photo: '/assets/listings/league-city/97910292.jpg',
    status: 'Active',
  },
  {
    mls: '26831514',
    address: '1215 E Walker Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$279,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,484',
    acres: '0.255',
    yearBuilt: '1910',
    subdivision: 'Ibarra Add 2002',
    county: 'Galveston',
    remarks: 'CHARACTER & CHARM in the heart of Downtown League ...',
    photo: '/assets/listings/league-city/26831514.jpg',
    status: 'Active',
  },
  {
    mls: '54919589',
    address: '2615 Granite Shadow Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$669,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,567',
    acres: '0.165',
    yearBuilt: '2017',
    subdivision: 'Magnolia Creek',
    county: 'Galveston',
    remarks: 'Impressive 5-bedroom home in exceptional condition ...',
    photo: '/assets/listings/league-city/54919589.jpg',
    status: 'Active',
  },
  {
    mls: '9652170',
    address: '2017 Victoria Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$255,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,349',
    acres: '0.169',
    yearBuilt: '1970',
    subdivision: 'Newport',
    county: 'Galveston',
    remarks: 'Welcome to this welcoming single-story home on a s ...',
    photo: '/assets/listings/league-city/9652170.jpg',
    status: 'Active',
  },
  {
    mls: '66931243',
    address: '6882 Dogwood Cliff Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$360,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,808',
    acres: '0.115',
    yearBuilt: '2014',
    subdivision: 'Enclave At Bay Colony West Sec',
    county: 'Galveston',
    remarks: 'Welcome to 6882 Dogwood Cliff, a spacious Lennar h ...',
    photo: '/assets/listings/league-city/66931243.jpg',
    status: 'Active',
  },
  {
    mls: '8054810',
    address: '118 E Highland Terrace',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$399,900',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,961',
    acres: '0.215',
    yearBuilt: '1976',
    subdivision: 'Highland Terrace',
    county: 'Galveston',
    remarks: 'Spacious 5-bedroom, 3-bathroom home in League City ...',
    photo: '/assets/listings/league-city/8054810.jpg',
    status: 'Active',
  },
  {
    mls: '29095814',
    address: '2725 Palermo Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$334,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,863',
    acres: '0.145',
    yearBuilt: '2005',
    subdivision: 'Tuscan Lakes Sec Sf 55-12005',
    county: 'Galveston',
    remarks: 'Exceptional Opportunity in South Shore Harbor! Nes ...',
    photo: '/assets/listings/league-city/29095814.jpg',
    status: 'Active',
  },
  {
    mls: '26505056',
    address: '5123 Carefree Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$385,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,683',
    acres: '0.217',
    yearBuilt: '1994',
    subdivision: 'Countryside Sec 4',
    county: 'Galveston',
    remarks: 'Welcome to 5123 Carefree Dr. in League City, TX! T ...',
    photo: '/assets/listings/league-city/26505056.jpg',
    status: 'Active',
  },
  {
    mls: '98146309',
    address: '2712 Hidden Gold Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$335,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,974',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Siesta ...',
    photo: '/assets/listings/league-city/98146309.jpg',
    status: 'Active',
  },
  {
    mls: '22728891',
    address: '7114 Frio Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77546',
    price: '$669,497',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,796',
    acres: '0.2',
    yearBuilt: '2026',
    subdivision: 'Legacy',
    county: 'Galveston',
    remarks: 'Westin Homes NEW Construction (Carter IX, Elevatio ...',
    photo: '/assets/listings/league-city/22728891.jpg',
    status: 'Active',
  },
  {
    mls: '24719420',
    address: '4229 Hazy Rock Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$466,990',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,158',
    acres: '0.171',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'The Rome floor plan opens with an inviting porch a ...',
    photo: '/assets/listings/league-city/24719420.jpg',
    status: 'Active',
  },
  {
    mls: '44930893',
    address: '4815 Tascosa Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$485,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,880',
    acres: '0.175',
    yearBuilt: '2017',
    subdivision: 'Mar Bella Sec 15-A &amp; B',
    county: 'Galveston',
    remarks: 'Be prepared to be wowed - This home is beautifully ...',
    photo: '/assets/listings/league-city/44930893.jpg',
    status: 'Active',
  },
  {
    mls: '52067839',
    address: '3418 Horseshoe Trail Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77511',
    price: '$340,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,322',
    acres: '0.115',
    yearBuilt: '2026',
    subdivision: 'Lakes At Westland Ranch',
    county: 'Galveston',
    remarks: 'The Rachael is a well-designed two-story floor pla ...',
    photo: '/assets/listings/league-city/52067839.jpg',
    status: 'Active',
  },
  {
    mls: '9090429',
    address: '14328 Seagrass Knoll Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77510',
    price: '$405,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,455',
    acres: '0.29',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Welcome to the Denison floor plan. This spacious t ...',
    photo: '/assets/listings/league-city/9090429.jpg',
    status: 'Active',
  },
  {
    mls: '38943824',
    address: '6103 Castle Peak Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$485,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,762',
    acres: '0.185',
    yearBuilt: '2007',
    subdivision: 'Westover Park Sec 12 2007',
    county: 'Galveston',
    remarks: 'Fabulous single-story home featuring a sparkling p ...',
    photo: '/assets/listings/league-city/38943824.jpg',
    status: 'Active',
  },
  {
    mls: '69816957',
    address: '2315 Poseidon Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$499,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,640',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Davis Harbor',
    county: 'Galveston',
    remarks: 'Step inside the Quinn and discover a spacious, tho ...',
    photo: '/assets/listings/league-city/69816957.jpg',
    status: 'Active',
  },
  {
    mls: '41270967',
    address: '2412 Lighthouse Hill Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$281,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,318',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Beckman ...',
    photo: '/assets/listings/league-city/41270967.jpg',
    status: 'Active',
  },
  {
    mls: '40356345',
    address: '214 Brookdale Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$274,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,500',
    acres: '0.179',
    yearBuilt: '1979',
    subdivision: 'Countryside',
    county: 'Galveston',
    remarks: 'Welcome to 214 Brookdale Drive in League City! Thi ...',
    photo: '/assets/listings/league-city/40356345.jpg',
    status: 'Active',
  },
  {
    mls: '41557695',
    address: '1028 Rio Grande Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$330,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,981',
    acres: '0.207',
    yearBuilt: '2005',
    subdivision: 'Austin Park 2006',
    county: 'Galveston',
    remarks: '1028 Rio Grande St is a single-story League City h ...',
    photo: '/assets/listings/league-city/41557695.jpg',
    status: 'Active',
  },
  {
    mls: '83420305',
    address: '2407 Mallorca Pass',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$774,990',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,847',
    acres: '0.372',
    yearBuilt: '2011',
    subdivision: 'Mar Bella Sec 9-B 2011',
    county: 'Galveston',
    remarks: 'Welcome to 2407 Mallorca Pass, a beautiful home in ...',
    photo: '/assets/listings/league-city/83420305.jpg',
    status: 'Active',
  },
  {
    mls: '38873030',
    address: '1020 Broad Bay Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$800,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,161',
    acres: '0.209',
    yearBuilt: '2008',
    subdivision: 'South Shore Harbour',
    county: 'Galveston',
    remarks: 'Discover this exceptional 4-bedroom, 3.5-bathroom ...',
    photo: '/assets/listings/league-city/38873030.jpg',
    status: 'Active',
  },
  {
    mls: '33696963',
    address: '2516 Goldeneye Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$393,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,848',
    acres: '0.164',
    yearBuilt: '2007',
    subdivision: 'Brittany Lakes Sec 14 2006',
    county: 'Galveston',
    remarks: 'More space, more possibilities! Offering the large ...',
    photo: '/assets/listings/league-city/33696963.jpg',
    status: 'Active',
  },
  {
    mls: '60216676',
    address: '2344 Autumn Mist Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$349,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,079',
    acres: '0.186',
    yearBuilt: '2001',
    subdivision: 'Harbour Pointe Sec 3 2000',
    county: 'Galveston',
    remarks: 'Charming one-story home nestled in a desirable Lea ...',
    photo: '/assets/listings/league-city/60216676.jpg',
    status: 'Active',
  },
  {
    mls: '40385755',
    address: '2625 Swift Sail Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$378,990',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,162',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Netcher ...',
    photo: '/assets/listings/league-city/40385755.jpg',
    status: 'Active',
  },
  {
    mls: '50282129',
    address: '2402 Golden Reef Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$348,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,984',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Portofi ...',
    photo: '/assets/listings/league-city/50282129.jpg',
    status: 'Active',
  },
  {
    mls: '46276936',
    address: '2406 Lighthouse Hill Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$321,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,984',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Littlet ...',
    photo: '/assets/listings/league-city/46276936.jpg',
    status: 'Active',
  },
  {
    mls: '6367012',
    address: '2242 Beach Cove Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$417,990',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,666',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Somerse ...',
    photo: '/assets/listings/league-city/6367012.jpg',
    status: 'Active',
  },
  {
    mls: '45001370',
    address: '405 Seaway Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,130,990',
    beds: '3 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,291',
    acres: '0.2',
    yearBuilt: '2026',
    subdivision: 'Town Harbour Estates',
    county: 'Galveston',
    remarks: 'Welcome home to luxury in your new Empire Malibu h ...',
    photo: '/assets/listings/league-city/45001370.jpg',
    status: 'Active',
  },
  {
    mls: '92048834',
    address: '1332 Altavilla Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$535,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,685',
    acres: '0.215',
    yearBuilt: '2012',
    subdivision: 'Tuscan Lakes',
    county: 'Galveston',
    remarks: 'Searching for a 4-bedroom pool home in League City ...',
    photo: '/assets/listings/league-city/92048834.jpg',
    status: 'Active',
  },
  {
    mls: '10885626',
    address: '3132 Cambridge Meadows Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$239,998',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,755',
    acres: '0.153',
    yearBuilt: '2008',
    subdivision: 'Bay Colony',
    county: 'Galveston',
    remarks: 'Welcome to this charming 3-bedroom, 2-bath home in ...',
    photo: '/assets/listings/league-city/10885626.jpg',
    status: 'Active',
  },
  {
    mls: '28205357',
    address: '2710 Merrimac Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$315,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,684',
    acres: '0.165',
    yearBuilt: '1981',
    subdivision: 'The Landing',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/league-city/28205357.jpg',
    status: 'Active',
  },
  {
    mls: '62940584',
    address: '2412 Via Montesano',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$419,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,637',
    acres: '0.145',
    yearBuilt: '2011',
    subdivision: 'Tuscan Lakes Sec Sf 55-4-1',
    county: 'Galveston',
    remarks: 'Beautiful two-story home offering 3 bedrooms, 2.5 ...',
    photo: '/assets/listings/league-city/62940584.jpg',
    status: 'Active',
  },
  {
    mls: '13690562',
    address: '2886 Milano Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$389,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,153',
    acres: '0.154',
    yearBuilt: '2010',
    subdivision: 'Tuscan Lakes Sec Sf 55-2',
    county: 'Galveston',
    remarks: 'Like new move in ready home in Tuscan Lakes. This ...',
    photo: '/assets/listings/league-city/13690562.jpg',
    status: 'Active',
  },
  {
    mls: '94142766',
    address: '7027 Texas Wrangler Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77546',
    price: '$504,612',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '2,757',
    acres: '',
    yearBuilt: '',
    subdivision: 'Legacy',
    county: 'Galveston',
    remarks: 'Discover the spacious and sophisticated Linnea flo ...',
    photo: '/assets/listings/league-city/94142766.jpg',
    status: 'Active',
  },
  {
    mls: '83854180',
    address: '2328 Majestic Fairway Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$585,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,924',
    acres: '0.167',
    yearBuilt: '2019',
    subdivision: 'Magnolia Creek',
    county: 'Galveston',
    remarks: 'Rarely does a home this well-kept come available i ...',
    photo: '/assets/listings/league-city/83854180.jpg',
    status: 'Active',
  },
  {
    mls: '34554878',
    address: '129 Coral Bay Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$364,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,592',
    acres: '0.208',
    yearBuilt: '1989',
    subdivision: 'Harbour Park Rep Resv A90',
    county: 'Galveston',
    remarks: 'Welcome to this charming two-story traditional hom ...',
    photo: '/assets/listings/league-city/34554878.jpg',
    status: 'Active',
  },
  {
    mls: '39209659',
    address: '419 Drake Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$329,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,801',
    acres: '0.161',
    yearBuilt: '2006',
    subdivision: 'Westover Park Sec 6a &amp; 6b',
    county: 'Galveston',
    remarks: 'Beautifully maintained 3-bedroom, 2-bath home feat ...',
    photo: '/assets/listings/league-city/39209659.jpg',
    status: 'Active',
  },
  {
    mls: '98028470',
    address: '315 Westwood Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$507,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,573',
    acres: '0.176',
    yearBuilt: '2014',
    subdivision: 'Westwood Sub Ph 1 2007',
    county: 'Galveston',
    remarks: 'Competitively priced with no MUD tax, a unique ben ...',
    photo: '/assets/listings/league-city/98028470.jpg',
    status: 'Active',
  },
  {
    mls: '88498264',
    address: '607 Ivory Stone Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$559,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,390',
    acres: '0.209',
    yearBuilt: '2007',
    subdivision: 'South Shore Harbour Sec Sf 65-',
    county: 'Galveston',
    remarks: 'Summer is almost over! This stunning 3,390 SF pool ...',
    photo: '/assets/listings/league-city/88498264.jpg',
    status: 'Active',
  },
  {
    mls: '69224559',
    address: '1538 Torrance Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$629,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,259',
    acres: '0.188',
    yearBuilt: '2012',
    subdivision: 'Victory Lakes Sec 5 2007',
    county: 'Galveston',
    remarks: 'Welcome home to 1538 Torrance Drive, beautifully s ...',
    photo: '/assets/listings/league-city/69224559.jpg',
    status: 'Active',
  },
  {
    mls: '33979090',
    address: '2833 Mezzomonte Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$475,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,806',
    acres: '0.217',
    yearBuilt: '2014',
    subdivision: 'Tuscan Lakes Sec Sf 50-4-2 Se',
    county: 'Galveston',
    remarks: 'Come tour this 4 bedroom3 full bath home locate on ...',
    photo: '/assets/listings/league-city/33979090.jpg',
    status: 'Active',
  },
  {
    mls: '90426368',
    address: '2119 Kingfisher Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$360,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,337',
    acres: '0.185',
    yearBuilt: '2005',
    subdivision: 'Brittany Lakes',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully maintained 4-bed, ...',
    photo: '/assets/listings/league-city/90426368.jpg',
    status: 'Active',
  },
  {
    mls: '38970678',
    address: '2910 Laguna Shores Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$360,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,979',
    acres: '0.182',
    yearBuilt: '2003',
    subdivision: 'South Shore Harbour Sec Sf 65-',
    county: 'Galveston',
    remarks: 'Charming single-story brick home in sought-after S ...',
    photo: '/assets/listings/league-city/38970678.jpg',
    status: 'Active',
  },
  {
    mls: '38979758',
    address: '1918 Fir Tree Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$310,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,091',
    acres: '0.164',
    yearBuilt: '1990',
    subdivision: 'Brittany Bay',
    county: 'Galveston',
    remarks: 'Big backyard. Recent updates. Great location. Endl ...',
    photo: '/assets/listings/league-city/38979758.jpg',
    status: 'Active',
  },
  {
    mls: '21652308',
    address: '2111 Riverside Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$524,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,358',
    acres: '0.21',
    yearBuilt: '1989',
    subdivision: 'South Shore Harbour 10 89',
    county: 'Galveston',
    remarks: 'Welcome to 2111 Riverside in the gated South Shore ...',
    photo: '/assets/listings/league-city/21652308.jpg',
    status: 'Active',
  },
  {
    mls: '71508498',
    address: '3229 Calm Prairie Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$524,990',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,222',
    acres: '0.231',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'The Milan floor plan combines luxury and modern fu ...',
    photo: '/assets/listings/league-city/71508498.jpg',
    status: 'Active',
  },
  {
    mls: '73975206',
    address: '3003 Pasture Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$444,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,640',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'Step inside the Quinn and discover a spacious, tho ...',
    photo: '/assets/listings/league-city/73975206.jpg',
    status: 'Active',
  },
  {
    mls: '15297827',
    address: '3005 Pasture Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$398,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,907',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'The Fannin floor plan offers a spacious, functiona ...',
    photo: '/assets/listings/league-city/15297827.jpg',
    status: 'Active',
  },
  {
    mls: '90068025',
    address: '1729 Enterprise Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$259,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,412',
    acres: '0.055',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour 2 Townhome',
    county: 'Galveston',
    remarks: 'Beautifully maintained 2-bedroom, 2.5-bath townhou ...',
    photo: '/assets/listings/league-city/90068025.jpg',
    status: 'Active',
  },
  {
    mls: '86710552',
    address: '2307 Poseidon Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$414,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,907',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Davis Harbor',
    county: 'Galveston',
    remarks: 'The Fannin floor plan offers a spacious, functiona ...',
    photo: '/assets/listings/league-city/86710552.jpg',
    status: 'Active',
  },
  {
    mls: '49786017',
    address: '2844 Torano',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$399,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,355',
    acres: '0.155',
    yearBuilt: '2009',
    subdivision: 'Tuscan Lakes Sec Sf 55-3',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully maintained two-st ...',
    photo: '/assets/listings/league-city/49786017.jpg',
    status: 'Active',
  },
  {
    mls: '4619925',
    address: '516 Saint Charles Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$261,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,225',
    acres: '0.174',
    yearBuilt: '1975',
    subdivision: 'Crestwood',
    county: 'Galveston',
    remarks: 'COMPLETELY REMODELED 3 BEDROOM, 2 BATH ...',
    photo: '/assets/listings/league-city/4619925.jpg',
    status: 'Active',
  },
  {
    mls: '4952602',
    address: '1860 Lake Landing Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$989,900',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,535',
    acres: '1.052',
    yearBuilt: '2004',
    subdivision: 'Whispering Lakes Ranch Sec 1',
    county: 'Galveston',
    remarks: 'Absolutely Stunning Trendmaker home located in the ...',
    photo: '/assets/listings/league-city/4952602.jpg',
    status: 'Active',
  },
  {
    mls: '3159614',
    address: '2042 Lodge Crest Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$435,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,046',
    acres: '0.174',
    yearBuilt: '1995',
    subdivision: 'Harbour Park',
    county: 'Galveston',
    remarks: 'Harbour Park living meets generous space, thoughtf ...',
    photo: '/assets/listings/league-city/3159614.jpg',
    status: 'Active',
  },
  {
    mls: '60058192',
    address: '2608 Holbrook Springs Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$539,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,308',
    acres: '0.209',
    yearBuilt: '2015',
    subdivision: 'Magnolia Creek Sec 11 Ph I 20',
    county: 'Galveston',
    remarks: '*NEW 50-YEAR SHINGLE ROOF AS OF 8/5/20 ...',
    photo: '/assets/listings/league-city/60058192.jpg',
    status: 'Active',
  },
  {
    mls: '56865077',
    address: '3716 Masters Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$389,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,685',
    acres: '0.117',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour Golf',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/league-city/56865077.jpg',
    status: 'Active',
  },
  {
    mls: '90681962',
    address: '2109 Victoria Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$285,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,552',
    acres: '0.157',
    yearBuilt: '1973',
    subdivision: 'Newport 5',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully remodeled single-story ...',
    photo: '/assets/listings/league-city/90681962.jpg',
    status: 'Active',
  },
  {
    mls: '36305696',
    address: '736 Somerset Landing Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$485,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,139',
    acres: '0.196',
    yearBuilt: '2013',
    subdivision: 'Westover Park 2012',
    county: 'Galveston',
    remarks: 'Located in Westover Park, this two-story tradition ...',
    photo: '/assets/listings/league-city/36305696.jpg',
    status: 'Active',
  },
  {
    mls: '58066960',
    address: '2430 Fairway Pointe Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$395,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,919',
    acres: '0.152',
    yearBuilt: '1996',
    subdivision: 'South Shore Harbour Sec 15',
    county: 'Galveston',
    remarks: 'Welcome home to 2430 Fairway Pointe, a beautifully ...',
    photo: '/assets/listings/league-city/58066960.jpg',
    status: 'Active',
  },
  {
    mls: '11710505',
    address: '109 Seaway Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,950,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '5,306',
    acres: '0.304',
    yearBuilt: '2026',
    subdivision: 'Townharbour Estates',
    county: 'Galveston',
    remarks: 'EXPERIENCE LUXURIOUS WATERFRONT LIVING ...',
    photo: '/assets/listings/league-city/11710505.jpg',
    status: 'Active',
  },
  {
    mls: '27260535',
    address: '105 Seaway Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,850,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,826',
    acres: '0.304',
    yearBuilt: '2026',
    subdivision: 'Townharbour Estates',
    county: 'Galveston',
    remarks: 'EXCLUSIVE WATERFRONT LIVING AND HIGH-E ...',
    photo: '/assets/listings/league-city/27260535.jpg',
    status: 'Active',
  },
  {
    mls: '23443707',
    address: '2203 Summit Pass Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$449,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,693',
    acres: '0.165',
    yearBuilt: '2011',
    subdivision: 'Magnolia Creek',
    county: 'Galveston',
    remarks: 'Welcome to 2203 Summit Pass in Magnolia Creek, Lea ...',
    photo: '/assets/listings/league-city/23443707.jpg',
    status: 'Active',
  },
  {
    mls: '79504704',
    address: '2425 Spellbrook Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$434,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,843',
    acres: '0.211',
    yearBuilt: '2001',
    subdivision: 'South Shore Harbour Sec 17',
    county: 'Galveston',
    remarks: 'Enjoy the ease of single-story living in this char ...',
    photo: '/assets/listings/league-city/79504704.jpg',
    status: 'Active',
  },
  {
    mls: '86818549',
    address: '804 Driftwood Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$210,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,673',
    acres: '0.187',
    yearBuilt: '1976',
    subdivision: 'Pecan Forest 2',
    county: 'Galveston',
    remarks: 'Upon entering this fabulous home, you will be amaz ...',
    photo: '/assets/listings/league-city/86818549.jpg',
    status: 'Active',
  },
  {
    mls: '34395737',
    address: '3730 Sunrise Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$409,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,446',
    acres: '0.144',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'The Colby floor plan offers a beautifully designed ...',
    photo: '/assets/listings/league-city/34395737.jpg',
    status: 'Active',
  },
  {
    mls: '75997398',
    address: '3509 Wild Mustang Street',
    city: 'League City',
    state: 'Texas',
    zip: '77511',
    price: '$292,490',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,396',
    acres: '0.11',
    yearBuilt: '2026',
    subdivision: 'Lakes At Westland Ranch',
    county: 'Galveston',
    remarks: 'The Brooke floor plan is a thoughtfully designed o ...',
    photo: '/assets/listings/league-city/75997398.jpg',
    status: 'Active',
  },
  {
    mls: '75915969',
    address: '2319 Poseidon Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$529,990',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,983',
    acres: '0.162',
    yearBuilt: '2026',
    subdivision: 'Davis Harbor',
    county: 'Galveston',
    remarks: 'Welcome to the Chloe plan in beautiful Davis Harbo ...',
    photo: '/assets/listings/league-city/75915969.jpg',
    status: 'Active',
  },
  {
    mls: '56470459',
    address: '1314 Altavilla Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$675,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,896',
    acres: '0.215',
    yearBuilt: '2010',
    subdivision: 'Tuscan Lakes Sec Sf 75-3',
    county: 'Galveston',
    remarks: 'Welcome to Tuscan Lakes, where scenic lakes, windi ...',
    photo: '/assets/listings/league-city/56470459.jpg',
    status: 'Active',
  },
  {
    mls: '19930951',
    address: '1327 Graham Trace Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$490,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,679',
    acres: '0.194',
    yearBuilt: '2016',
    subdivision: 'Hidden Lakes Sec 1 2009',
    county: 'Galveston',
    remarks: 'Welcome to this meticulously maintained house in a ...',
    photo: '/assets/listings/league-city/19930951.jpg',
    status: 'Active',
  },
  {
    mls: '24542062',
    address: '3429 Horseshoe Trail Road',
    city: 'League City',
    state: 'Texas',
    zip: '77511',
    price: '$296,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,546',
    acres: '0.111',
    yearBuilt: '2026',
    subdivision: 'Lakes At Westland Ranch',
    county: 'Galveston',
    remarks: 'Discover comfort and convenience in the Olivia flo ...',
    photo: '/assets/listings/league-city/24542062.jpg',
    status: 'Active',
  },
  {
    mls: '58444398',
    address: '3306 Wickfield Pass Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$454,290',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,148',
    acres: '0.172',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'Move In Ready! Welcome to Westland Ranch located i ...',
    photo: '/assets/listings/league-city/58444398.jpg',
    status: 'Active',
  },
  {
    mls: '53148351',
    address: '2317 Poseidon Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$473,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,446',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Davis Harbor',
    county: 'Galveston',
    remarks: 'The Colby floor plan offers a beautifully designed ...',
    photo: '/assets/listings/league-city/53148351.jpg',
    status: 'Active',
  },
  {
    mls: '49694403',
    address: '3302 Wickfield Pass Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$492,672',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,581',
    acres: '0.172',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'Move in Ready! Welcome to Westland Ranch located i ...',
    photo: '/assets/listings/league-city/49694403.jpg',
    status: 'Active',
  },
  {
    mls: '44980287',
    address: '2112 Bristol Breeze Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$349,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,026',
    acres: '0.174',
    yearBuilt: '1999',
    subdivision: 'Brittany Lakes Sec 2 97',
    county: 'Galveston',
    remarks: 'This spacious 4-bedroom, 2-bath split floorplan wa ...',
    photo: '/assets/listings/league-city/44980287.jpg',
    status: 'Active',
  },
  {
    mls: '71130488',
    address: '2124 Llerena Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$372,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,896',
    acres: '0.14',
    yearBuilt: '2017',
    subdivision: 'Mar Bella Sec 16-A',
    county: 'Galveston',
    remarks: 'Welcome to 2124 Llerena Ln, a charming house locat ...',
    photo: '/assets/listings/league-city/71130488.jpg',
    status: 'Active',
  },
  {
    mls: '9188068',
    address: '2011 Victoria Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$259,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,534',
    acres: '0.157',
    yearBuilt: '1973',
    subdivision: 'Newport',
    county: 'Galveston',
    remarks: 'A 4-bedroom home on a quiet street in Newport is a ...',
    photo: '/assets/listings/league-city/9188068.jpg',
    status: 'Active',
  },
  {
    mls: '66682116',
    address: '426 Holly Fern Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$360,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,202',
    acres: '0.201',
    yearBuilt: '1989',
    subdivision: 'Meadow Bend 4',
    county: 'Galveston',
    remarks: 'Beautiful, updated home in Meadow Bend with POOL a ...',
    photo: '/assets/listings/league-city/66682116.jpg',
    status: 'Active',
  },
  {
    mls: '91853859',
    address: '902 Virginia Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$290,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,508',
    acres: '0.298',
    yearBuilt: '2013',
    subdivision: 'Dickinson Townsite',
    county: 'Galveston',
    remarks: 'Welcome to this charming 3-Bedroom, 2-Bath home in ...',
    photo: '/assets/listings/league-city/91853859.jpg',
    status: 'Active',
  },
  {
    mls: '26526719',
    address: '4804 Ladona Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$450,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,420',
    acres: '0.145',
    yearBuilt: '2016',
    subdivision: 'Mar Bella Sec 16-B &amp; C',
    county: 'Galveston',
    remarks: 'Embrace modern comfort in this beautifully maintai ...',
    photo: '/assets/listings/league-city/26526719.jpg',
    status: 'Active',
  },
  {
    mls: '48885810',
    address: '320 Creek Bend Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$329,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,920',
    acres: '',
    yearBuilt: '1980',
    subdivision: 'Countryside',
    county: 'Galveston',
    remarks: 'Welcome home to this charming one-story split floo ...',
    photo: '/assets/listings/league-city/48885810.jpg',
    status: 'Active',
  },
  {
    mls: '41707509',
    address: '235 Magnolia Way',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$459,900',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,141',
    acres: '0.161',
    yearBuilt: '2003',
    subdivision: 'Magnolia Estates Sec 1 2003',
    county: 'Galveston',
    remarks: 'Discover this beautiful 5-bedroom, 3.5-bathroom ho ...',
    photo: '/assets/listings/league-city/41707509.jpg',
    status: 'Active',
  },
  {
    mls: '3728319',
    address: '609 Eagle Hollow Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$499,999',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,860',
    acres: '0.2',
    yearBuilt: '2014',
    subdivision: 'Westover Park',
    county: 'Galveston',
    remarks: 'Welcome home to the sought-after Westover Park com ...',
    photo: '/assets/listings/league-city/3728319.jpg',
    status: 'Active',
  },
  {
    mls: '43056539',
    address: '793 Davis Road 105',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$169,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '705',
    acres: '',
    yearBuilt: '1980',
    subdivision: 'South Point Condos 88',
    county: 'Galveston',
    remarks: 'WATERFRONT LIVING includes BOAT SLIP in desirable ...',
    photo: '/assets/listings/league-city/43056539.jpg',
    status: 'Active',
  },
  {
    mls: '6712641',
    address: '1324 Elkins Hollow Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$624,990',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,300',
    acres: '0.209',
    yearBuilt: '2013',
    subdivision: 'Hidden Lakes Sec 1 2009',
    county: 'Galveston',
    remarks: 'This exquisite 4-bedroom property boasts 4 full ba ...',
    photo: '/assets/listings/league-city/6712641.jpg',
    status: 'Active',
  },
  {
    mls: '31036469',
    address: '3805 Verde River Road',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$493,013',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,527',
    acres: '0.316',
    yearBuilt: '2026',
    subdivision: 'Pedregal South',
    county: 'Galveston',
    remarks: 'Cervelle Homes - Plan 322-The Magic Plan, with gre ...',
    photo: '/assets/listings/league-city/31036469.jpg',
    status: 'Active',
  },
  {
    mls: '87921632',
    address: '930 Groundwater Way',
    city: 'League City',
    state: 'Texas',
    zip: '77546',
    price: '$699,990',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,690',
    acres: '0.179',
    yearBuilt: '2026',
    subdivision: 'Legacy',
    county: 'Galveston',
    remarks: 'Built by SHEA HOMES Est. completion December 2026 ...',
    photo: '/assets/listings/league-city/87921632.jpg',
    status: 'Active',
  },
]
