// Nassau Bay homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const nassaubayListings: Listing[] = [
  {
    mls: '7748696',
    address: '18206 Heritage Lane 8206',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$215,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,280',
    acres: '2.98',
    yearBuilt: '1975',
    subdivision: 'Heritage T/H Condo',
    county: 'Harris',
    remarks: 'Charming townhome in lovely Nassau Bay near Howard ...',
    photo: '/assets/listings/nassau-bay/7748696.jpg',
    status: 'Active',
  },
  {
    mls: '78156059',
    address: '2403 Clippers Square',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$250,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,700',
    acres: '0.068',
    yearBuilt: '2003',
    subdivision: 'Townhomes On Park',
    county: 'Harris',
    remarks: 'Conveniently located near Johnson Space Center, Ho ...',
    photo: '/assets/listings/nassau-bay/78156059.jpg',
    status: 'Active',
  },
  {
    mls: '30463697',
    address: '18 Antilles Lane',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$390,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,130',
    acres: '0.056',
    yearBuilt: '1983',
    subdivision: 'Harbour Martinique R/P',
    county: 'Harris',
    remarks: 'Enjoy waterfront living in this beautifully mainta ...',
    photo: '/assets/listings/nassau-bay/30463697.jpg',
    status: 'Active',
  },
  {
    mls: '95980881',
    address: '18591 Martinique Drive',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$399,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,442',
    acres: '0.22',
    yearBuilt: '1967',
    subdivision: 'Nassau Bay Sec 07',
    county: 'Harris',
    remarks: 'Nestled in the heart of Nassau Bay and a short wal ...',
    photo: '/assets/listings/nassau-bay/95980881.jpg',
    status: 'Active',
  },
  {
    mls: '12222822',
    address: '18623 Point Lookout Drive',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$489,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,856',
    acres: '0.444',
    yearBuilt: '1968',
    subdivision: 'Nassau Bay Sec 05',
    county: 'Harris',
    remarks: 'WATERFRONT DREAM HOME!! MOVE-IN READY 4-bed, 2.5-b ...',
    photo: '/assets/listings/nassau-bay/12222822.jpg',
    status: 'Active',
  },
  {
    mls: '65207819',
    address: '18502 Vinland Drive',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$545,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,998',
    acres: '0.301',
    yearBuilt: '1967',
    subdivision: 'Nassau Bay',
    county: 'Harris',
    remarks: 'Incredible single story home only a block from the ...',
    photo: '/assets/listings/nassau-bay/65207819.jpg',
    status: 'Active',
  },
  {
    mls: '34935572',
    address: '1902 Port Royal Drive',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$562,500',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,400',
    acres: '0.251',
    yearBuilt: '1967',
    subdivision: 'Nassau Bay Sec 8',
    county: 'Harris',
    remarks: '“Our house, is a very very very fine house…” and t ...',
    photo: '/assets/listings/nassau-bay/34935572.jpg',
    status: 'Active',
  },
  {
    mls: '14742792',
    address: '15 Harbour Drive',
    city: 'Nassau Bay',
    state: 'Texas',
    zip: '77058',
    price: '$799,000',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,346',
    acres: '0.115',
    yearBuilt: '1981',
    subdivision: 'Harbour Martinique &amp; Rp',
    county: 'Harris',
    remarks: 'This Nassau Bay waterfront home is being professio ...',
    photo: '/assets/listings/nassau-bay/14742792.jpg',
    status: 'Active',
  },
]
