// Dickinson homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const dickinsonListings: Listing[] = [
  {
    mls: '28710887',
    address: '4206 Leslies Way',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$368,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,500',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Bayou Bend Estates',
    county: 'Galveston',
    remarks: 'Welcome Home to Bayou Bend Estates! **UNDER CONSTR ...',
    photo: '/assets/listings/dickinson/28710887.jpg',
    status: 'Active',
  },
  {
    mls: '62210818',
    address: '3310 Utah Avenue',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$225,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,189',
    acres: '0.372',
    yearBuilt: '1970',
    subdivision: 'Halls Add',
    county: 'Galveston',
    remarks: 'This charming single-story offers a warm, inviting ...',
    photo: '/assets/listings/dickinson/62210818.jpg',
    status: 'Active',
  },
  {
    mls: '51620334',
    address: '2817 Frostwood Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$329,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,039',
    acres: '0.294',
    yearBuilt: '1975',
    subdivision: 'Sherwood Oaks',
    county: 'Galveston',
    remarks: 'Welcome home to this updated 3-bedroom, 2-bath pro ...',
    photo: '/assets/listings/dickinson/51620334.jpg',
    status: 'Active',
  },
  {
    mls: '11838527',
    address: '4139 Gum Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$359,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '806',
    acres: '0.454',
    yearBuilt: '1968',
    subdivision: 'Tropical Gardens',
    county: 'Galveston',
    remarks: 'Discover laid-back coastal living in this beautifu ...',
    photo: '/assets/listings/dickinson/11838527.jpg',
    status: 'Active',
  },
  {
    mls: '63130623',
    address: '939 17th Street Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$265,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,404',
    acres: '0.154',
    yearBuilt: '1975',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Relocated Heights beauty now perched for water vie ...',
    photo: '/assets/listings/dickinson/63130623.jpg',
    status: 'Active',
  },
  {
    mls: '66718512',
    address: '5919 Santa Fe Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$245,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,401',
    acres: '0.233',
    yearBuilt: '1993',
    subdivision: 'Cheyenne',
    county: 'Galveston',
    remarks: 'Nestled in a peaceful cul-de-sac, this well-mainta ...',
    photo: '/assets/listings/dickinson/66718512.jpg',
    status: 'Active',
  },
  {
    mls: '88771008',
    address: '5800 Winding Brook Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$279,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,402',
    acres: '0.133',
    yearBuilt: '2004',
    subdivision: 'Green Isle Sub Ph Iv 2004',
    county: 'Galveston',
    remarks: 'Discover comfortable living in this charming two-s ...',
    photo: '/assets/listings/dickinson/88771008.jpg',
    status: 'Active',
  },
  {
    mls: '20345316',
    address: '1717 Oleander Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$225,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,755',
    acres: '0.936',
    yearBuilt: '1940',
    subdivision: 'Moore C H W 1/2',
    county: 'Galveston',
    remarks: 'Nestled on a private 0.936-acre lot surrounded by ...',
    photo: '/assets/listings/dickinson/20345316.jpg',
    status: 'Active',
  },
  {
    mls: '93006182',
    address: '708 Bayou Crest Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$559,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,575',
    acres: '0.383',
    yearBuilt: '1989',
    subdivision: 'Bayou Crest',
    county: 'Galveston',
    remarks: 'Nestled in a charming tree-lined neighborhood, thi ...',
    photo: '/assets/listings/dickinson/93006182.jpg',
    status: 'Active',
  },
  {
    mls: '56298008',
    address: '4124 E Bayou Maison',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$277,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,820',
    acres: '0.15',
    yearBuilt: '2022',
    subdivision: 'Bayou Maison Sec 1',
    county: 'Galveston',
    remarks: 'This spacious 4 bedroom, 3 bath home perfectly ble ...',
    photo: '/assets/listings/dickinson/56298008.jpg',
    status: 'Active',
  },
  {
    mls: '64194269',
    address: '2704 Yorktown Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$335,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,288',
    acres: '0.238',
    yearBuilt: '1976',
    subdivision: 'Colonial Estates',
    county: 'Galveston',
    remarks: 'Welcome to your forever home! Custom 4/2/2 plus of ...',
    photo: '/assets/listings/dickinson/64194269.jpg',
    status: 'Active',
  },
  {
    mls: '49634216',
    address: '1815 Oakdale Mist Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$299,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,651',
    acres: '',
    yearBuilt: '2020',
    subdivision: 'Bayou Lakes',
    county: 'Galveston',
    remarks: 'WELCOME HOME TO THIS BEAUTIFUL ONE-STO ...',
    photo: '/assets/listings/dickinson/49634216.jpg',
    status: 'Active',
  },
  {
    mls: '31214834',
    address: '816 Sherwood Forest Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$490,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,810',
    acres: '0.382',
    yearBuilt: '1993',
    subdivision: 'Sherwood Forest West',
    county: 'Galveston',
    remarks: 'Beautifully updated home in Dickinson featuring co ...',
    photo: '/assets/listings/dickinson/31214834.jpg',
    status: 'Active',
  },
  {
    mls: '32013462',
    address: '727 18th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$275,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,170',
    acres: '0.308',
    yearBuilt: '2018',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Charming cabin-style 2 bed, 2 bath home with bayou ...',
    photo: '/assets/listings/dickinson/32013462.jpg',
    status: 'Active',
  },
  {
    mls: '3966071',
    address: '409 Old Orchard Way',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$850,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,266',
    acres: '0.315',
    yearBuilt: '2007',
    subdivision: 'Bayou Park Sec 3 2005',
    county: 'Galveston',
    remarks: 'Located within the exclusive gated community of Ba ...',
    photo: '/assets/listings/dickinson/3966071.jpg',
    status: 'Active',
  },
  {
    mls: '37119302',
    address: '1740 N Meridian Greens Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$440,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,799',
    acres: '0.214',
    yearBuilt: '2010',
    subdivision: 'Bayou Lakes Sec 1 2005',
    county: 'Galveston',
    remarks: 'Come check out this beautiful 4/5 bedroom home in ...',
    photo: '/assets/listings/dickinson/37119302.jpg',
    status: 'Active',
  },
  {
    mls: '54711723',
    address: '2803 22nd Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$195,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,470',
    acres: '0.149',
    yearBuilt: '1969',
    subdivision: 'Moores Add',
    county: 'Galveston',
    remarks: 'AFFORDABLE Updated brick home located within walki ...',
    photo: '/assets/listings/dickinson/54711723.jpg',
    status: 'Active',
  },
  {
    mls: '82502509',
    address: '4818 27th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$220,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,200',
    acres: '0.138',
    yearBuilt: '1979',
    subdivision: 'Nicholstone',
    county: 'Galveston',
    remarks: 'Welcome to your private retreat in Dickinson! This ...',
    photo: '/assets/listings/dickinson/82502509.jpg',
    status: 'Active',
  },
  {
    mls: '85397138',
    address: '4027 Bentwood Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$299,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,765',
    acres: '0.138',
    yearBuilt: '2005',
    subdivision: 'Bentwood At Bay Colony Sec 1',
    county: 'Galveston',
    remarks: 'Charming, Well-Maintained residence in Bentwood at ...',
    photo: '/assets/listings/dickinson/85397138.jpg',
    status: 'Active',
  },
  {
    mls: '56884317',
    address: '1218 Edwards Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$409,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,888',
    acres: '0.192',
    yearBuilt: '1987',
    subdivision: 'Edwards Landing',
    county: 'Galveston',
    remarks: 'This waterfront home features an open, airy floor ...',
    photo: '/assets/listings/dickinson/56884317.jpg',
    status: 'Active',
  },
  {
    mls: '7176003',
    address: '3201 Captain&#039;s Grove',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$314,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,912',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'One-Story Living with LVP Flooring and Functional ...',
    photo: '/assets/listings/dickinson/7176003.jpg',
    status: 'Active',
  },
  {
    mls: '48662269',
    address: '3700 Wood Sorrel Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$299,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,109',
    acres: '0.183',
    yearBuilt: '1995',
    subdivision: 'Briar Glen Sec 1 Ph 2',
    county: 'Galveston',
    remarks: 'Discover the perfect family home in a quiet Dickin ...',
    photo: '/assets/listings/dickinson/48662269.jpg',
    status: 'Active',
  },
  {
    mls: '35300945',
    address: '3413 Owens Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$291,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,263',
    acres: '0.485',
    yearBuilt: '1995',
    subdivision: 'Briar Glen Sec 1 Ph 2',
    county: 'Galveston',
    remarks: 'Step inside this charming 3-2-2 brick home just st ...',
    photo: '/assets/listings/dickinson/35300945.jpg',
    status: 'Active',
  },
  {
    mls: '86073509',
    address: '5313 Palm Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$331,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,648',
    acres: '0.6',
    yearBuilt: '1950',
    subdivision: 'Moore C H E 1/2',
    county: 'Galveston',
    remarks: 'Discover comfort and convenience in this inviting ...',
    photo: '/assets/listings/dickinson/86073509.jpg',
    status: 'Active',
  },
  {
    mls: '57137231',
    address: '6115 San Leon Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$585,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,154',
    acres: '2',
    yearBuilt: '2024',
    subdivision: 'Hillman Villas',
    county: 'Galveston',
    remarks: 'Modern coastal living in this beautifully crafted ...',
    photo: '/assets/listings/dickinson/57137231.jpg',
    status: 'Active',
  },
  {
    mls: '89495757',
    address: '2701 Mount Vernon Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$425,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,470',
    acres: '0.4',
    yearBuilt: '1964',
    subdivision: 'Colonial Estates',
    county: 'Galveston',
    remarks: 'Gorgeous Colonial/Traditional 4 Bedroom, 2.5 Bathr ...',
    photo: '/assets/listings/dickinson/89495757.jpg',
    status: 'Active',
  },
  {
    mls: '95674522',
    address: '3002 Overland Trail',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$214,990',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,600',
    acres: '0.156',
    yearBuilt: '1992',
    subdivision: 'Cheyenne',
    county: 'Galveston',
    remarks: 'VERY NICE ONE STORY 4 BD. 2BTH HOME WI ...',
    photo: '/assets/listings/dickinson/95674522.jpg',
    status: 'Active',
  },
  {
    mls: '57744546',
    address: '1813 Avenue A',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$885,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,244',
    acres: '0.326',
    yearBuilt: '2009',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Come see this incredible beachfront home before it ...',
    photo: '/assets/listings/dickinson/57744546.jpg',
    status: 'Active',
  },
  {
    mls: '49659385',
    address: '749 12th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$424,500',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,200',
    acres: '0.294',
    yearBuilt: '2013',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Experience the charm of coastal living with this u ...',
    photo: '/assets/listings/dickinson/49659385.jpg',
    status: 'Active',
  },
  {
    mls: '22993626',
    address: '5022 Casa Grande Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$350,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,099',
    acres: '0.355',
    yearBuilt: '1970',
    subdivision: 'Casa Grande',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully maintained 3 BR, 2.5 ...',
    photo: '/assets/listings/dickinson/22993626.jpg',
    status: 'Active',
  },
  {
    mls: '43354284',
    address: '341 5th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$545,395',
    beds: '0 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,000',
    acres: '0.367',
    yearBuilt: '2007',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Endless possibilities await at 341 5th Street in S ...',
    photo: '/assets/listings/dickinson/43354284.jpg',
    status: 'Active',
  },
  {
    mls: '88400936',
    address: '5003 Meadow Lark Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$265,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,676',
    acres: '0.212',
    yearBuilt: '1986',
    subdivision: 'Bayou Chantilly',
    county: 'Galveston',
    remarks: 'Welcome Home!!! This stunning 3 bedroom 2 bathroom ...',
    photo: '/assets/listings/dickinson/88400936.jpg',
    status: 'Active',
  },
  {
    mls: '5043178',
    address: '3204 Meadow Bay Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$329,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,973',
    acres: '',
    yearBuilt: '2004',
    subdivision: 'The Meadows In Bay Colony',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/dickinson/5043178.jpg',
    status: 'Active',
  },
  {
    mls: '93628740',
    address: '417 Folk Crest Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$233,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,702',
    acres: '0.07',
    yearBuilt: '2004',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'Welcome to 417 Folk Crest Lane, a well-maintained ...',
    photo: '/assets/listings/dickinson/93628740.jpg',
    status: 'Active',
  },
  {
    mls: '22319493',
    address: '4106 Hill Avenue',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$309,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,673',
    acres: '0.145',
    yearBuilt: '2026',
    subdivision: 'High School Add',
    county: 'Galveston',
    remarks: 'Welcome home to this beautiful brand-new construct ...',
    photo: '/assets/listings/dickinson/22319493.jpg',
    status: 'Active',
  },
  {
    mls: '27664534',
    address: '2501 Gulf Freeway 6A',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$95,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '865',
    acres: '865',
    yearBuilt: '1980',
    subdivision: 'Ponderosa Forest-Condo',
    county: 'Galveston',
    remarks: 'Come see this beautifully updated third-floor cond ...',
    photo: '/assets/listings/dickinson/27664534.jpg',
    status: 'Active',
  },
  {
    mls: '68074465',
    address: '615 29th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$500,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,290',
    acres: '0.138',
    yearBuilt: '2016',
    subdivision: 'Broadway Breeze Sub',
    county: 'Galveston',
    remarks: 'Discover timeless Mediterranean-inspired elegance ...',
    photo: '/assets/listings/dickinson/68074465.jpg',
    status: 'Active',
  },
  {
    mls: '55455517',
    address: '2102 Wikiup Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$480,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,275',
    acres: '0.38',
    yearBuilt: '2022',
    subdivision: 'Pedregal',
    county: 'Galveston',
    remarks: 'Welcome to 2102 Wikiup St. in Dickinson! This 4-be ...',
    photo: '/assets/listings/dickinson/55455517.jpg',
    status: 'Active',
  },
  {
    mls: '53946070',
    address: '4318 Meadow Glenn Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$359,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,290',
    acres: '0.517',
    yearBuilt: '1976',
    subdivision: 'Plantation Estates',
    county: 'Galveston',
    remarks: 'Rare one-story home on over ½ acre with room for y ...',
    photo: '/assets/listings/dickinson/53946070.jpg',
    status: 'Active',
  },
  {
    mls: '7830469',
    address: '405 Old Orchard Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$950,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,872',
    acres: '0.337',
    yearBuilt: '2013',
    subdivision: 'Bayou Park',
    county: 'Galveston',
    remarks: 'Nestled within a gated community on a quiet cul-de ...',
    photo: '/assets/listings/dickinson/7830469.jpg',
    status: 'Active',
  },
  {
    mls: '60708264',
    address: '1309 Sunset Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$224,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,620',
    acres: '0.413',
    yearBuilt: '1977',
    subdivision: 'Oak Hollow',
    county: 'Galveston',
    remarks: 'This charming one-story brick home offers a fantas ...',
    photo: '/assets/listings/dickinson/60708264.jpg',
    status: 'Active',
  },
  {
    mls: '88860901',
    address: '3205 Granite Gate Lane Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$305,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,844',
    acres: '0.157',
    yearBuilt: '2009',
    subdivision: 'Bay Colony Pointe West Sec 3 P',
    county: 'Galveston',
    remarks: 'GREAT ONE STORY BRICK HOME MUST SEE. K ...',
    photo: '/assets/listings/dickinson/88860901.jpg',
    status: 'Active',
  },
  {
    mls: '13103344',
    address: '2711 Williamsburg Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$355,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,244',
    acres: '0.232',
    yearBuilt: '1983',
    subdivision: 'Colonial Estates',
    county: 'Galveston',
    remarks: 'Discover this beautiful corner-lot home at 2711 Wi ...',
    photo: '/assets/listings/dickinson/13103344.jpg',
    status: 'Active',
  },
  {
    mls: '9705955',
    address: '8805 Harbour Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$412,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,478',
    acres: '0.366',
    yearBuilt: '1972',
    subdivision: 'Dickinson Bayou Estates',
    county: 'Galveston',
    remarks: 'Waterfront living starts here! Set along Dickinson ...',
    photo: '/assets/listings/dickinson/9705955.jpg',
    status: 'Active',
  },
  {
    mls: '28523664',
    address: '3001 Meadow Bay Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$340,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,722',
    acres: '0.164',
    yearBuilt: '2003',
    subdivision: 'The Meadows In Bay Colony Sec',
    county: 'Galveston',
    remarks: 'Move-in ready and beautifully maintained, this tra ...',
    photo: '/assets/listings/dickinson/28523664.jpg',
    status: 'Active',
  },
  {
    mls: '80703970',
    address: '114 24th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$459,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,598',
    acres: '0.389',
    yearBuilt: '1990',
    subdivision: 'Ponca Beach',
    county: 'Galveston',
    remarks: 'Some homes simply offer a place to live. This one ...',
    photo: '/assets/listings/dickinson/80703970.jpg',
    status: 'Active',
  },
  {
    mls: '25617277',
    address: '208 13th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$208,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,218',
    acres: '0.176',
    yearBuilt: '2006',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Welcome to this charming 2-bedroom, 2-bath home ju ...',
    photo: '/assets/listings/dickinson/25617277.jpg',
    status: 'Active',
  },
  {
    mls: '86036866',
    address: '4220 Alabama Avenue',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$187,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,296',
    acres: '0.314',
    yearBuilt: '1970',
    subdivision: 'Mc Caleb Estates',
    county: 'Galveston',
    remarks: 'Charming and move-in ready, this 3-bedroom home si ...',
    photo: '/assets/listings/dickinson/86036866.jpg',
    status: 'Active',
  },
  {
    mls: '59197201',
    address: '4514 E 24th E Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$105,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,104',
    acres: '0.09',
    yearBuilt: '2005',
    subdivision: 'Nicholstone',
    county: 'Galveston',
    remarks: 'Charming home perfect for starting out or downsizi ...',
    photo: '/assets/listings/dickinson/59197201.jpg',
    status: 'Active',
  },
  {
    mls: '56967975',
    address: '5519 Chisholm Trail',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$225,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,312',
    acres: '0.114',
    yearBuilt: '1995',
    subdivision: 'Cheyenne',
    county: 'Galveston',
    remarks: 'This lovely house has been updated with ceramic ti ...',
    photo: '/assets/listings/dickinson/56967975.jpg',
    status: 'Active',
  },
  {
    mls: '33006444',
    address: '4803 28th Street E',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$260,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,216',
    acres: '0.207',
    yearBuilt: '1974',
    subdivision: 'Nicholstone',
    county: 'Galveston',
    remarks: 'Move-in ready 3-bedroom, 2-bath home in the desira ...',
    photo: '/assets/listings/dickinson/33006444.jpg',
    status: 'Active',
  },
  {
    mls: '13875865',
    address: '641 4th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$239,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,408',
    acres: '0.147',
    yearBuilt: '2011',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Beautifully maintained 3-bedroom, 2 bath home in t ...',
    photo: '/assets/listings/dickinson/13875865.jpg',
    status: 'Active',
  },
  {
    mls: '69357671',
    address: '5113 Cottonwood Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$289,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,349',
    acres: '0.177',
    yearBuilt: '1977',
    subdivision: 'Oak Land 2',
    county: 'Galveston',
    remarks: 'Come and see this move-in ready three-bedroom, two ...',
    photo: '/assets/listings/dickinson/69357671.jpg',
    status: 'Active',
  },
  {
    mls: '78217103',
    address: '1909 Ashlee Court',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$299,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,436',
    acres: '0.239',
    yearBuilt: '2026',
    subdivision: 'Peacock Isles',
    county: 'Galveston',
    remarks: 'Welcome to Peacock Isle! Discover the perfect blen ...',
    photo: '/assets/listings/dickinson/78217103.jpg',
    status: 'Active',
  },
  {
    mls: '66615406',
    address: '2730 Mary Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$425,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,584',
    acres: '0.5',
    yearBuilt: '1972',
    subdivision: 'Chanlee Estates 2',
    county: 'Galveston',
    remarks: 'Welcome to worry-free living on a spacious half-ac ...',
    photo: '/assets/listings/dickinson/66615406.jpg',
    status: 'Active',
  },
  {
    mls: '82501863',
    address: '4055 Bentwood Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$298,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,775',
    acres: '0.141',
    yearBuilt: '2005',
    subdivision: 'Bentwood At Bay Colony Sec 2',
    county: 'Galveston',
    remarks: 'Make the most of the season with this beautiful 3- ...',
    photo: '/assets/listings/dickinson/82501863.jpg',
    status: 'Active',
  },
  {
    mls: '50560036',
    address: '2501 Gulf Freeway 279B',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$61,800',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '639',
    acres: '639',
    yearBuilt: '1980',
    subdivision: 'Ponderosa Forest-Condo',
    county: 'Galveston',
    remarks: 'Investor Opportunity; 1 bedroom, 1 bath condo in a ...',
    photo: '/assets/listings/dickinson/50560036.jpg',
    status: 'Active',
  },
  {
    mls: '22121011',
    address: '1056 Cabot Cove',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$315,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,485',
    acres: '0.138',
    yearBuilt: '2005',
    subdivision: 'Bentwood At Bay Colony',
    county: 'Galveston',
    remarks: 'Nestled on a quiet cul-de-sac street in Bentwood a ...',
    photo: '/assets/listings/dickinson/22121011.jpg',
    status: 'Active',
  },
  {
    mls: '74926640',
    address: '3213 Captain&#039;s Cove',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$319,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,121',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Two-Story Living with LVP Flooring and All Bedroom ...',
    photo: '/assets/listings/dickinson/74926640.jpg',
    status: 'Active',
  },
  {
    mls: '5435788',
    address: '3309 Nautical Mile Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$341,990',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,877',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Spacious One-Story Living with LVP Flooring and Fo ...',
    photo: '/assets/listings/dickinson/5435788.jpg',
    status: 'Active',
  },
  {
    mls: '24200140',
    address: '2221 Blue Mariner Path',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$291,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,412',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Comfortable One-Story Living with LVP Flooring and ...',
    photo: '/assets/listings/dickinson/24200140.jpg',
    status: 'Active',
  },
  {
    mls: '15758985',
    address: '3314 Nautical Mile Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$345,990',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,827',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Spacious One-Story Living with LVP Flooring and Fo ...',
    photo: '/assets/listings/dickinson/15758985.jpg',
    status: 'Active',
  },
  {
    mls: '8471435',
    address: '3301 Nautical Mile Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$399,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,717',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Expansive Two-Story Living with LVP Flooring and F ...',
    photo: '/assets/listings/dickinson/8471435.jpg',
    status: 'Active',
  },
  {
    mls: '92597181',
    address: '3217 Captain&#039;s Grove',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$333,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,260',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Spacious Two-Story Living with LVP Flooring and Fi ...',
    photo: '/assets/listings/dickinson/92597181.jpg',
    status: 'Active',
  },
  {
    mls: '24927701',
    address: '3318 Nautical Mile Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$379,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,406',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Spacious Two-Story Living with LVP Flooring and Fl ...',
    photo: '/assets/listings/dickinson/24927701.jpg',
    status: 'Active',
  },
  {
    mls: '10872843',
    address: '3305 Nautical Mile Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$364,990',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,218',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Spacious One-Story Living with LVP Flooring and Fi ...',
    photo: '/assets/listings/dickinson/10872843.jpg',
    status: 'Active',
  },
  {
    mls: '47035462',
    address: '3205 Captain&#039;s Grove',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$304,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,801',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Spacious Two-Story Living with LVP Flooring and Fo ...',
    photo: '/assets/listings/dickinson/47035462.jpg',
    status: 'Active',
  },
  {
    mls: '19840172',
    address: '3209 Captain&#039;s Grove',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$279,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,536',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Vida Mar',
    county: 'Galveston',
    remarks: 'Open-Concept Living with LVP Flooring in Main Area ...',
    photo: '/assets/listings/dickinson/19840172.jpg',
    status: 'Active',
  },
  {
    mls: '91281645',
    address: '2575 Cliff Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$389,999',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,904',
    acres: '0.386',
    yearBuilt: '1972',
    subdivision: 'Cliffs Of San Leon',
    county: 'Galveston',
    remarks: 'Tired of neighborhoods where every house looks the ...',
    photo: '/assets/listings/dickinson/91281645.jpg',
    status: 'Active',
  },
  {
    mls: '43970890',
    address: '234 Dale Ridge Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$380,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,742',
    acres: '0.144',
    yearBuilt: '2017',
    subdivision: 'Bay View',
    county: 'Galveston',
    remarks: 'Enjoy comfort, convenience, and room to grow in th ...',
    photo: '/assets/listings/dickinson/43970890.jpg',
    status: 'Active',
  },
  {
    mls: '70570407',
    address: '4329 S Meridian Greens Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$419,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,964',
    acres: '0.185',
    yearBuilt: '2015',
    subdivision: 'Bayou Lakes Sec 2a 2012',
    county: 'Galveston',
    remarks: 'Stunning 1-story home in the sought-after Bayou La ...',
    photo: '/assets/listings/dickinson/70570407.jpg',
    status: 'Active',
  },
  {
    mls: '38361219',
    address: '2921 Meridian Bay Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$338,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,760',
    acres: '0.133',
    yearBuilt: '2005',
    subdivision: 'Bay Colony Pointe Sec 6 2004',
    county: 'Galveston',
    remarks: 'This one has it all! Two story entry, formal dinin ...',
    photo: '/assets/listings/dickinson/38361219.jpg',
    status: 'Active',
  },
  {
    mls: '28117969',
    address: '2917 48th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$214,900',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,416',
    acres: '0.472',
    yearBuilt: '1972',
    subdivision: 'Barberia',
    county: 'Galveston',
    remarks: 'Investor Special! Unlock the potential of this fix ...',
    photo: '/assets/listings/dickinson/28117969.jpg',
    status: 'Active',
  },
  {
    mls: '54096485',
    address: '4410 W Bayou Maison Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$286,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,700',
    acres: '0.12',
    yearBuilt: '2026',
    subdivision: 'Bayou Maison-Sec 3',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/dickinson/54096485.jpg',
    status: 'Active',
  },
  {
    mls: '16821610',
    address: '4406 W Bayou Maison Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$281,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,602',
    acres: '0.12',
    yearBuilt: '2026',
    subdivision: 'Bayou Maison-Sec 3',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/dickinson/16821610.jpg',
    status: 'Active',
  },
  {
    mls: '53077425',
    address: '4208 Pine Shadows Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$275,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,223',
    acres: '0.222',
    yearBuilt: '1983',
    subdivision: 'Plantation Estates 1',
    county: 'Galveston',
    remarks: 'Welcome to 4208 Pine Shadows St., where timeless c ...',
    photo: '/assets/listings/dickinson/53077425.jpg',
    status: 'Active',
  },
  {
    mls: '28628479',
    address: '4402 W Bayou Maison Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$270,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,434',
    acres: '0.12',
    yearBuilt: '2026',
    subdivision: 'Bayou Maison-Sec 3',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/dickinson/28628479.jpg',
    status: 'Active',
  },
  {
    mls: '49293024',
    address: '5107 Longshadow Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$269,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,770',
    acres: '0.289',
    yearBuilt: '1986',
    subdivision: 'Long Shadows',
    county: 'Galveston',
    remarks: 'Beautifully maintained single-story home situated ...',
    photo: '/assets/listings/dickinson/49293024.jpg',
    status: 'Active',
  },
  {
    mls: '14614902',
    address: '238 Drake Run Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$257,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,702',
    acres: '0.081',
    yearBuilt: '2005',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'Welcome home to this fully remodeled, move in read ...',
    photo: '/assets/listings/dickinson/14614902.jpg',
    status: 'Active',
  },
  {
    mls: '40728554',
    address: '331 6th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$205,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,479',
    acres: '0.147',
    yearBuilt: '2018',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Experience the laid-back coastal lifestyle that ma ...',
    photo: '/assets/listings/dickinson/40728554.jpg',
    status: 'Active',
  },
  {
    mls: '74886467',
    address: '4318 Parkview Terrace Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$439,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,986',
    acres: '0.185',
    yearBuilt: '2017',
    subdivision: 'Bayou Lakes Sec 3',
    county: 'Galveston',
    remarks: 'Stunning two-story home in the desirable Bayou Lak ...',
    photo: '/assets/listings/dickinson/74886467.jpg',
    status: 'Active',
  },
  {
    mls: '13548562',
    address: '3104 Avenue C',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$165,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,720',
    acres: '0.172',
    yearBuilt: '2002',
    subdivision: 'The New Destiny 2001',
    county: 'Galveston',
    remarks: 'Discover the potential in this spacious 4-bedroom, ...',
    photo: '/assets/listings/dickinson/13548562.jpg',
    status: 'Active',
  },
  {
    mls: '4614119',
    address: '3310 Oak Drive Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$289,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,348',
    acres: '0.607',
    yearBuilt: '1970',
    subdivision: 'Dickinson Add D',
    county: 'Galveston',
    remarks: 'Waterfront Living with Boat Access to Galveston Ba ...',
    photo: '/assets/listings/dickinson/4614119.jpg',
    status: 'Active',
  },
  {
    mls: '46239561',
    address: '4509 Country Club Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$419,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,514',
    acres: '0.62',
    yearBuilt: '1988',
    subdivision: 'Country Club Estates Unrec',
    county: 'Galveston',
    remarks: 'Preferred Lender Credit to Buyer Available. Lovely ...',
    photo: '/assets/listings/dickinson/46239561.jpg',
    status: 'Active',
  },
  {
    mls: '87014394',
    address: '2501 Gulf Freeway 256D',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$99,999',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '800',
    acres: '800',
    yearBuilt: '1980',
    subdivision: 'Ponderosa Forest-Condo',
    county: 'Galveston',
    remarks: '1-Bedroom, 1-bath condo, Retreat and move-in ready ...',
    photo: '/assets/listings/dickinson/87014394.jpg',
    status: 'Active',
  },
  {
    mls: '55940772',
    address: '3230 W Meadow Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$335,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,934',
    acres: '0.515',
    yearBuilt: '1996',
    subdivision: 'Prairie Estates',
    county: 'Galveston',
    remarks: 'Welcome home to this charming 3-bedroom, 2-bathroo ...',
    photo: '/assets/listings/dickinson/55940772.jpg',
    status: 'Active',
  },
  {
    mls: '2951986',
    address: '3040 Longwood Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$269,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,732',
    acres: '0.239',
    yearBuilt: '1963',
    subdivision: 'Shadowland 2',
    county: 'Galveston',
    remarks: 'You need to come see this home on a large lot. NO ...',
    photo: '/assets/listings/dickinson/2951986.jpg',
    status: 'Active',
  },
  {
    mls: '20283494',
    address: '4317 Leslies Way',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$360,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,300',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Bayou Bend Estates',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/dickinson/20283494.jpg',
    status: 'Active',
  },
  {
    mls: '69768446',
    address: '3703 Nichols Avenue',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$280,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,760',
    acres: '0.302',
    yearBuilt: '2005',
    subdivision: 'Berry Field Sub 2005',
    county: 'Galveston',
    remarks: 'Welcome to 3703 Nichols Avenue, where comfort, sty ...',
    photo: '/assets/listings/dickinson/69768446.jpg',
    status: 'Active',
  },
  {
    mls: '12692179',
    address: '106 Easton Glen Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$319,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,427',
    acres: '0.144',
    yearBuilt: '2008',
    subdivision: 'Bay Colony Northpointe Sec 2',
    county: 'Galveston',
    remarks: 'Beautiful home located in Bay Colony! Recently rem ...',
    photo: '/assets/listings/dickinson/12692179.jpg',
    status: 'Active',
  },
  {
    mls: '59164655',
    address: '3430 W Meadow Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$695,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,950',
    acres: '0.515',
    yearBuilt: '2003',
    subdivision: 'Prairie Estates',
    county: 'Galveston',
    remarks: 'Exciting ranch-style home on a 1/2 Acre lot with l ...',
    photo: '/assets/listings/dickinson/59164655.jpg',
    status: 'Active',
  },
  {
    mls: '4892868',
    address: '118 4th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$170,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '416',
    acres: '0.147',
    yearBuilt: '1977',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Cozy 2-bedroom, 2-bath home offering approximately ...',
    photo: '/assets/listings/dickinson/4892868.jpg',
    status: 'Active',
  },
  {
    mls: '33398448',
    address: '1917 Anchor Way',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$999,000',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,844',
    acres: '0.632',
    yearBuilt: '1991',
    subdivision: 'Converse',
    county: 'Galveston',
    remarks: 'Experience exceptional craftsmanship and breathtak ...',
    photo: '/assets/listings/dickinson/33398448.jpg',
    status: 'Active',
  },
  {
    mls: '18699460',
    address: '418 Folk Crest Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$245,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,702',
    acres: '0.089',
    yearBuilt: '2004',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'Beautiful 3-Bedroom Townhome located in the desira ...',
    photo: '/assets/listings/dickinson/18699460.jpg',
    status: 'Active',
  },
  {
    mls: '45398924',
    address: '5421 Thistle Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$255,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,736',
    acres: '0.214',
    yearBuilt: '1976',
    subdivision: 'Briar Glen',
    county: 'Galveston',
    remarks: 'Get in and settled before the start of school! Thi ...',
    photo: '/assets/listings/dickinson/45398924.jpg',
    status: 'Active',
  },
  {
    mls: '95883989',
    address: '3632 W Meadow Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$695,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,989',
    acres: '1.206',
    yearBuilt: '2019',
    subdivision: 'Prairie Estates',
    county: 'Galveston',
    remarks: 'No HOA. 40 X 60 workshop with steel beams, separat ...',
    photo: '/assets/listings/dickinson/95883989.jpg',
    status: 'Active',
  },
  {
    mls: '71597659',
    address: '5116 E Bayou Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$280,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,088',
    acres: '0.189',
    yearBuilt: '1995',
    subdivision: 'Oak Land 2',
    county: 'Galveston',
    remarks: 'Meet 5116 E Bayou Dr, a residence arranged for eve ...',
    photo: '/assets/listings/dickinson/71597659.jpg',
    status: 'Active',
  },
  {
    mls: '10991371',
    address: '6533 Canyon Mist Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$319,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,298',
    acres: '0.172',
    yearBuilt: '2005',
    subdivision: 'Bay Colony Meadows West Sec 2',
    county: 'Galveston',
    remarks: 'Welcome home to 6533 Canyon Mist Ln in the desirab ...',
    photo: '/assets/listings/dickinson/10991371.jpg',
    status: 'Active',
  },
  {
    mls: '79232305',
    address: '2921 Oak Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$324,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,877',
    acres: '0.299',
    yearBuilt: '1980',
    subdivision: 'Pine Grove',
    county: 'Galveston',
    remarks: 'Beautifully updated and thoughtfully designed, thi ...',
    photo: '/assets/listings/dickinson/79232305.jpg',
    status: 'Active',
  },
  {
    mls: '75432742',
    address: '2501 Gulf Freeway 4A',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$98,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '865',
    acres: '865',
    yearBuilt: '1980',
    subdivision: 'Ponderosa Forest-Condo',
    county: 'Galveston',
    remarks: 'Discover comfortable living in this well-maintaine ...',
    photo: '/assets/listings/dickinson/75432742.jpg',
    status: 'Active',
  },
]
