// Texas City homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const texascityListings: Listing[] = [
  {
    mls: '80658203',
    address: '3214 Coral Bluff Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$324,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,907',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'The Fannin floor plan offers a spacious, functiona ...',
    photo: '/assets/listings/texas-city/80658203.jpg',
    status: 'Active',
  },
  {
    mls: '6960726',
    address: '3102 Banyan Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$369,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,941',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Welcome home to this exceptional single-story bric ...',
    photo: '/assets/listings/texas-city/6960726.jpg',
    status: 'Active',
  },
  {
    mls: '80382242',
    address: '1131 2nd Avenue S',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$69,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,321',
    acres: '0.144',
    yearBuilt: '1915',
    subdivision: 'Kohfeldt 1st Add',
    county: 'Galveston',
    remarks: 'Calling all investors and handy homeowners looking ...',
    photo: '/assets/listings/texas-city/80382242.jpg',
    status: 'Active',
  },
  {
    mls: '37965453',
    address: '10716 Discovery Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77951',
    price: '$317,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,688',
    acres: '0.168',
    yearBuilt: '2024',
    subdivision: 'Central Square Park',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully maintained, energ ...',
    photo: '/assets/listings/texas-city/37965453.jpg',
    status: 'Active',
  },
  {
    mls: '79912804',
    address: '211 Estelle Circle',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$185,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,160',
    acres: '0.146',
    yearBuilt: '1973',
    subdivision: 'Estelle',
    county: 'Galveston',
    remarks: 'WELCOME HOME!!!! Exceptional fully remodeled brick ...',
    photo: '/assets/listings/texas-city/79912804.jpg',
    status: 'Active',
  },
  {
    mls: '302018',
    address: '8506 Shiloh Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$179,900',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,327',
    acres: '0.139',
    yearBuilt: '2013',
    subdivision: 'Westland Ridge Sec 1',
    county: 'Galveston',
    remarks: 'Move-in ready and designed for easy, comfortable l ...',
    photo: '/assets/listings/texas-city/302018.jpg',
    status: 'Active',
  },
  {
    mls: '14151503',
    address: '2125 Sand Lily Dr',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$395,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,779',
    acres: '',
    yearBuilt: '2020',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Welcome home to 2125 Sand Lily, nestled on a tranq ...',
    photo: '/assets/listings/texas-city/14151503.jpg',
    status: 'Active',
  },
  {
    mls: '27646388',
    address: '2537 N 21st Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$215,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,910',
    acres: '0.195',
    yearBuilt: '1983',
    subdivision: 'Thunderbird Park',
    county: 'Galveston',
    remarks: 'Finally, a home where you can actually stretch out ...',
    photo: '/assets/listings/texas-city/27646388.jpg',
    status: 'Active',
  },
  {
    mls: '55862585',
    address: '2809 3rd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$215,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,390',
    acres: '0.142',
    yearBuilt: '1980',
    subdivision: 'West Briar',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/texas-city/55862585.jpg',
    status: 'Active',
  },
  {
    mls: '11820988',
    address: '2713 Jumeirah Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$364,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,544',
    acres: '0.23',
    yearBuilt: '2024',
    subdivision: 'Lago Mar Pod 8 Sec 9b',
    county: 'Galveston',
    remarks: 'Why wait to build when you can enjoy better-than-n ...',
    photo: '/assets/listings/texas-city/11820988.jpg',
    status: 'Active',
  },
  {
    mls: '81670277',
    address: '2208 Ruby Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$280,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,604',
    acres: '0.139',
    yearBuilt: '2015',
    subdivision: 'Pearlbrook Sec 3',
    county: 'Galveston',
    remarks: 'Welcome to this well-maintained 4-bedroom, 2-bath ...',
    photo: '/assets/listings/texas-city/81670277.jpg',
    status: 'Active',
  },
  {
    mls: '55810750',
    address: '6026 Diamond Court',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$245,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,012',
    acres: '0.129',
    yearBuilt: '1960',
    subdivision: 'Emerald Terrace',
    county: 'Galveston',
    remarks: 'Fully renovated 4-bedroom, 2.5-bath home with over ...',
    photo: '/assets/listings/texas-city/55810750.jpg',
    status: 'Active',
  },
  {
    mls: '45635994',
    address: '910 San Jacinto Avenue',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$149,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,696',
    acres: '0.2',
    yearBuilt: '1981',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/texas-city/45635994.jpg',
    status: 'Active',
  },
  {
    mls: '57023391',
    address: '4205 Quaker Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$415,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,360',
    acres: '0.223',
    yearBuilt: '1978',
    subdivision: 'Pilgrims Landing',
    county: 'Galveston',
    remarks: 'Welcome to Pilgrims Landing! This spacious 3-bedro ...',
    photo: '/assets/listings/texas-city/57023391.jpg',
    status: 'Active',
  },
  {
    mls: '37591389',
    address: '12808 Narrow Cove Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$380,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,683',
    acres: '0.158',
    yearBuilt: '2019',
    subdivision: 'Lago Mar Pod 7 Sec 1',
    county: 'Galveston',
    remarks: 'Located on an expansive cul-de-sac lot, this beaut ...',
    photo: '/assets/listings/texas-city/37591389.jpg',
    status: 'Active',
  },
  {
    mls: '48838599',
    address: '6414 Woodrow Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$155,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '932',
    acres: '0.12',
    yearBuilt: '1955',
    subdivision: 'Patrick Mary',
    county: 'Galveston',
    remarks: 'This move-in ready 2 bedroom, 1 bath home offers a ...',
    photo: '/assets/listings/texas-city/48838599.jpg',
    status: 'Active',
  },
  {
    mls: '86199205',
    address: '13120 Pinnacle Beach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$316,990',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,922',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Walsh F ...',
    photo: '/assets/listings/texas-city/86199205.jpg',
    status: 'Active',
  },
  {
    mls: '22672335',
    address: '715 20th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$199,900',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,276',
    acres: '0.196',
    yearBuilt: '1977',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Beautifully remodeled 3-bedroom, 1-bath home with ...',
    photo: '/assets/listings/texas-city/22672335.jpg',
    status: 'Active',
  },
  {
    mls: '85817675',
    address: '2907 Golden Isle Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$409,990',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,936',
    acres: '0.152',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Beautiful one-story home featuring 3 bedrooms, 2.5 ...',
    photo: '/assets/listings/texas-city/85817675.jpg',
    status: 'Active',
  },
  {
    mls: '14714129',
    address: '3019 Golden Isle Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$405,990',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,051',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Explore this captivating one-story home featuring ...',
    photo: '/assets/listings/texas-city/14714129.jpg',
    status: 'Active',
  },
  {
    mls: '37228986',
    address: '2203 Port Jackson Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$349,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,377',
    acres: '0.152',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'READY NOW! COME HOME TO YOUR BEAUTIFUL ...',
    photo: '/assets/listings/texas-city/37228986.jpg',
    status: 'Active',
  },
  {
    mls: '94380471',
    address: '2517 Lago Costa Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$318,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,627',
    acres: '0.163',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'WATERFRONT LIVING at its FINEST!!! This beautifull ...',
    photo: '/assets/listings/texas-city/94380471.jpg',
    status: 'Active',
  },
  {
    mls: '51890906',
    address: '2802 Tamarack Lodge Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$372,676',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,801',
    acres: '0.173',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This well-designed home greets you with a large fo ...',
    photo: '/assets/listings/texas-city/51890906.jpg',
    status: 'Active',
  },
  {
    mls: '73046335',
    address: '4617 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$351,267',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,915',
    acres: '0.133',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome to this beautiful 4 bedroom, 3 bath home i ...',
    photo: '/assets/listings/texas-city/73046335.jpg',
    status: 'Active',
  },
  {
    mls: '5471760',
    address: '14419 Lunan Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$380,461',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,507',
    acres: '0.124',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/texas-city/5471760.jpg',
    status: 'Active',
  },
  {
    mls: '29307447',
    address: '2226 Sereno Shores Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$479,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,216',
    acres: '0.138',
    yearBuilt: '2024',
    subdivision: 'Lago Mar Pod 8 Sec 2',
    county: 'Galveston',
    remarks: 'Stunning Westin Home in the highly desirable Lago ...',
    photo: '/assets/listings/texas-city/29307447.jpg',
    status: 'Active',
  },
  {
    mls: '83107074',
    address: '405 N Fulton Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$297,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,272',
    acres: '0.283',
    yearBuilt: '1964',
    subdivision: 'Bell Ollie',
    county: 'Galveston',
    remarks: 'This One-Story Home has it all! An impressive open ...',
    photo: '/assets/listings/texas-city/83107074.jpg',
    status: 'Active',
  },
  {
    mls: '50269808',
    address: '2909 Fair Wind Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$410,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,415',
    acres: '0.151',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This two-story home, located on a lot with no back ...',
    photo: '/assets/listings/texas-city/50269808.jpg',
    status: 'Active',
  },
  {
    mls: '19857237',
    address: '2917 Fair Wind Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$361,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,850',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This beautiful, one-story home is the Hendrie by L ...',
    photo: '/assets/listings/texas-city/19857237.jpg',
    status: 'Active',
  },
  {
    mls: '26957357',
    address: '13717 Blue Breaker Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$380,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,188',
    acres: '0.162',
    yearBuilt: '2024',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This impeccable home is the Dockery plan by LGI H ...',
    photo: '/assets/listings/texas-city/26957357.jpg',
    status: 'Active',
  },
  {
    mls: '88974526',
    address: '14001 Starboard Reach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$384,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,958',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Nestled in the master-planned community of Lago Ma ...',
    photo: '/assets/listings/texas-city/88974526.jpg',
    status: 'Active',
  },
  {
    mls: '67375817',
    address: '9002 Barracuda Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$240,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,352',
    acres: '0.138',
    yearBuilt: '2005',
    subdivision: 'South Point Estates Sec 2 Ph 2',
    county: 'Galveston',
    remarks: '9002 Barracuda Dr is a 1-story Texas City home wit ...',
    photo: '/assets/listings/texas-city/67375817.jpg',
    status: 'Active',
  },
  {
    mls: '12309102',
    address: '2525 40th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$357,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,724',
    acres: '0.18',
    yearBuilt: '1989',
    subdivision: 'Tiffany Park',
    county: 'Galveston',
    remarks: 'Corner Lot in Tiffany Park with side gate to the b ...',
    photo: '/assets/listings/texas-city/12309102.jpg',
    status: 'Active',
  },
  {
    mls: '23390401',
    address: '3902 18th Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$400,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,900',
    acres: '0.231',
    yearBuilt: '1988',
    subdivision: 'Lakeshore 1',
    county: 'Galveston',
    remarks: 'Rare waterfront opportunity! This beautifully main ...',
    photo: '/assets/listings/texas-city/23390401.jpg',
    status: 'Active',
  },
  {
    mls: '26630395',
    address: '13201 Anchor Isle Court',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$330,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,994',
    acres: '0.196',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Sec 3 Pod 4',
    county: 'Galveston',
    remarks: 'Welcome to this immaculate 4 bedroom, 3 bathroom h ...',
    photo: '/assets/listings/texas-city/26630395.jpg',
    status: 'Active',
  },
  {
    mls: '59577545',
    address: '1210 14th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$225,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,557',
    acres: '0.218',
    yearBuilt: '1976',
    subdivision: 'Sunset Terrace',
    county: 'Galveston',
    remarks: 'Charming single story home shaded by beautiful mat ...',
    photo: '/assets/listings/texas-city/59577545.jpg',
    status: 'Active',
  },
  {
    mls: '93199717',
    address: '2818 Coral Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$310,652',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,772',
    acres: '0.152',
    yearBuilt: '2026',
    subdivision: 'Pearlbrook',
    county: 'Galveston',
    remarks: 'NEW CONSTRUCTION in Texas City Low HOA, Low taxes. ...',
    photo: '/assets/listings/texas-city/93199717.jpg',
    status: 'Active',
  },
  {
    mls: '11105174',
    address: '2810 Golden Isle Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$348,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,517',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Glenbro ...',
    photo: '/assets/listings/texas-city/11105174.jpg',
    status: 'Active',
  },
  {
    mls: '91746336',
    address: '2517 Bayrose Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$377,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,568',
    acres: '0.149',
    yearBuilt: '2020',
    subdivision: 'Lago Mar Pod 6 Sec 2',
    county: 'Galveston',
    remarks: 'Located in the gated section of Lago Mar, this bea ...',
    photo: '/assets/listings/texas-city/91746336.jpg',
    status: 'Active',
  },
  {
    mls: '33870584',
    address: '316 S Noble Road',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$209,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,044',
    acres: '0.155',
    yearBuilt: '1980',
    subdivision: 'Super City 1',
    county: 'Galveston',
    remarks: 'Updated brick home with fresh curb appeal, modern ...',
    photo: '/assets/listings/texas-city/33870584.jpg',
    status: 'Active',
  },
  {
    mls: '62227586',
    address: '7502 Nightingale Circle',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$230,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,320',
    acres: '0.313',
    yearBuilt: '1977',
    subdivision: 'South Acre Manor 4',
    county: 'Galveston',
    remarks: 'Impeccably maintained and move-in ready, this invi ...',
    photo: '/assets/listings/texas-city/62227586.jpg',
    status: 'Active',
  },
  {
    mls: '69812314',
    address: '14004 Starboard Reach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$349,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,850',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This beautiful, new one-story home is the Emerald ...',
    photo: '/assets/listings/texas-city/69812314.jpg',
    status: 'Active',
  },
  {
    mls: '35574492',
    address: '13914 Seneca Lake Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$289,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,901',
    acres: '0.138',
    yearBuilt: '',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This Adams Homes 1901 plan offers three bedrooms, ...',
    photo: '/assets/listings/texas-city/35574492.jpg',
    status: 'Active',
  },
  {
    mls: '22677457',
    address: '1217 18th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$259,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,568',
    acres: '0.194',
    yearBuilt: '1965',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully updated 3-bedroom ...',
    photo: '/assets/listings/texas-city/22677457.jpg',
    status: 'Active',
  },
  {
    mls: '27908104',
    address: '14406 Lido Shine Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77539',
    price: '$398,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,452',
    acres: '0.213',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Welcome to resort-style living in the highly sough ...',
    photo: '/assets/listings/texas-city/27908104.jpg',
    status: 'Active',
  },
  {
    mls: '3807242',
    address: '12209 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$337,937',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,642',
    acres: '0.194',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome to the Wise floor plan by Coventry Homes, ...',
    photo: '/assets/listings/texas-city/3807242.jpg',
    status: 'Active',
  },
  {
    mls: '9969281',
    address: '4712 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$351,140',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,128',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome to the Llana by Coventry Homes in Beacon P ...',
    photo: '/assets/listings/texas-city/9969281.jpg',
    status: 'Active',
  },
  {
    mls: '20031636',
    address: '12125 Cannon Cove Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$339,440',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,252',
    acres: '0.125',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome to the Lynn floorplan in Beacon Point at L ...',
    photo: '/assets/listings/texas-city/20031636.jpg',
    status: 'Active',
  },
  {
    mls: '49603806',
    address: '2922 Robinson Boulevard',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$150,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,366',
    acres: '0.139',
    yearBuilt: '1966',
    subdivision: 'Clairmont',
    county: 'Galveston',
    remarks: 'Calling all buyers on a budget and investors looki ...',
    photo: '/assets/listings/texas-city/49603806.jpg',
    status: 'Active',
  },
  {
    mls: '82379451',
    address: '12106 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$341,690',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,915',
    acres: '0.125',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome to the Ellis in Beacon Point at Lago Mar! ...',
    photo: '/assets/listings/texas-city/82379451.jpg',
    status: 'Active',
  },
  {
    mls: '19674053',
    address: '12130 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$357,335',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,949',
    acres: '0.127',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome to the Gregg floorplan, the newest additio ...',
    photo: '/assets/listings/texas-city/19674053.jpg',
    status: 'Active',
  },
  {
    mls: '22073654',
    address: '3217 Banyan Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$385,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '0.201',
    yearBuilt: '2025',
    subdivision: 'Lago Mar Sec 1 Pod 9',
    county: 'Galveston',
    remarks: 'Experience resort-style living in the highly desir ...',
    photo: '/assets/listings/texas-city/22073654.jpg',
    status: 'Active',
  },
  {
    mls: '62801882',
    address: '801 19th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$185,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,041',
    acres: '0.193',
    yearBuilt: '1945',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/texas-city/62801882.jpg',
    status: 'Active',
  },
  {
    mls: '58394337',
    address: '12149 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$324,717',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,759',
    acres: '0.125',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/texas-city/58394337.jpg',
    status: 'Active',
  },
  {
    mls: '47479111',
    address: '12117 Harrington Gate Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$337,667',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,915',
    acres: '0.125',
    yearBuilt: '2026',
    subdivision: 'Beacon Point',
    county: 'Galveston',
    remarks: 'Welcome home to the Ellis in Beacon Point at Lago ...',
    photo: '/assets/listings/texas-city/47479111.jpg',
    status: 'Active',
  },
  {
    mls: '74539186',
    address: '314 S Justice Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$245,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,676',
    acres: '0.139',
    yearBuilt: '2022',
    subdivision: 'Justice Ida',
    county: 'Galveston',
    remarks: 'This well maintained single story home features 3 ...',
    photo: '/assets/listings/texas-city/74539186.jpg',
    status: 'Active',
  },
  {
    mls: '91579173',
    address: '3214 Red Pebble Ln Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$349,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,920',
    acres: '0.155',
    yearBuilt: '2019',
    subdivision: 'Lago Mar Pod 6 Sec 1',
    county: 'Galveston',
    remarks: 'Welcome home! This beautifully kept 3-bed, 2-bath ...',
    photo: '/assets/listings/texas-city/91579173.jpg',
    status: 'Active',
  },
  {
    mls: '42055122',
    address: '13901 Seneca Lake Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$278,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,702',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Come out to Lago Mar to tour this beautiful 1635 p ...',
    photo: '/assets/listings/texas-city/42055122.jpg',
    status: 'Active',
  },
  {
    mls: '45763384',
    address: '3413 Oleander Avenue',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$100,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,519',
    acres: '0.155',
    yearBuilt: '1979',
    subdivision: 'Heights Annex',
    county: 'Galveston',
    remarks: 'Discover the potential at 3413 Oleander Ave! This ...',
    photo: '/assets/listings/texas-city/45763384.jpg',
    status: 'Active',
  },
  {
    mls: '24245048',
    address: '301 N Pecan Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$324,999',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,448',
    acres: '0.911',
    yearBuilt: '1981',
    subdivision: 'Kohfeldts Sub',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully remodeled home offerin ...',
    photo: '/assets/listings/texas-city/24245048.jpg',
    status: 'Active',
  },
  {
    mls: '36244134',
    address: '1101 15th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$280,000',
    beds: '5 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,652',
    acres: '0.287',
    yearBuilt: '1968',
    subdivision: 'Sunset Terrace',
    county: 'Galveston',
    remarks: 'Welcome to this spacious and charming Texas City h ...',
    photo: '/assets/listings/texas-city/36244134.jpg',
    status: 'Active',
  },
  {
    mls: '14163706',
    address: '809 12th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$199,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,179',
    acres: '0.144',
    yearBuilt: '1940',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Welcome to this charming four bedroom home in the ...',
    photo: '/assets/listings/texas-city/14163706.jpg',
    status: 'Active',
  },
  {
    mls: '53473279',
    address: '1830 34th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$150,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,008',
    acres: '0.23',
    yearBuilt: '1992',
    subdivision: 'Lakeview 1',
    county: 'Galveston',
    remarks: 'Investor special!',
    photo: '/assets/listings/texas-city/53473279.jpg',
    status: 'Active',
  },
  {
    mls: '58750582',
    address: '13910 Seneca Lake Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$293,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,820',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Make your appointment to make this 1820 plan from ...',
    photo: '/assets/listings/texas-city/58750582.jpg',
    status: 'Active',
  },
  {
    mls: '90366984',
    address: '613 22nd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$145,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,614',
    acres: '0.226',
    yearBuilt: '1975',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Situated in a sought-after market, close to highwa ...',
    photo: '/assets/listings/texas-city/90366984.jpg',
    status: 'Active',
  },
  {
    mls: '64181693',
    address: '1126 Sandhill Crane Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$289,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,782',
    acres: '0.181',
    yearBuilt: '2024',
    subdivision: 'Heron&#039;s Lndg Sec 3',
    county: 'Galveston',
    remarks: 'Welcome to 1126 Sandhill Crane Drive, Texas City! ...',
    photo: '/assets/listings/texas-city/64181693.jpg',
    status: 'Active',
  },
  {
    mls: '82508175',
    address: '8817 Voyager Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$279,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,740',
    acres: '0.146',
    yearBuilt: '2019',
    subdivision: 'Marlow Lake Sec 1b',
    county: 'Galveston',
    remarks: 'Charming single-story home in Texas City featuring ...',
    photo: '/assets/listings/texas-city/82508175.jpg',
    status: 'Active',
  },
  {
    mls: '53124519',
    address: '2604 Redfish Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$230,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,373',
    acres: '0.152',
    yearBuilt: '2004',
    subdivision: 'South Point Estates',
    county: 'Galveston',
    remarks: 'Welcome home to 2604 Redfish Drive in South Point ...',
    photo: '/assets/listings/texas-city/53124519.jpg',
    status: 'Active',
  },
  {
    mls: '51993913',
    address: '7600 Emmett F Lowry Expressway 1006',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$107,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '986',
    acres: '0.023',
    yearBuilt: '1980',
    subdivision: 'Gatsby Condo',
    county: 'Galveston',
    remarks: 'This beautifully updated second-floor, 2-bedroom, ...',
    photo: '/assets/listings/texas-city/51993913.jpg',
    status: 'Active',
  },
  {
    mls: '81929503',
    address: '12535 Tamaron Dr N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$440,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,790',
    acres: '0.138',
    yearBuilt: '2019',
    subdivision: 'Lago Mar Pod 11 Sec 5',
    county: 'Galveston',
    remarks: 'RARE OPPORTUNITY in the GATED section of Lago Mar. ...',
    photo: '/assets/listings/texas-city/81929503.jpg',
    status: 'Active',
  },
  {
    mls: '34439251',
    address: '1208 N Logan Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$99,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,000',
    acres: '500',
    yearBuilt: '1980',
    subdivision: 'Pilgrim Square Condo',
    county: 'Galveston',
    remarks: 'Charming and renovated 2-bedroom, 1.5-bath condo i ...',
    photo: '/assets/listings/texas-city/34439251.jpg',
    status: 'Active',
  },
  {
    mls: '55365560',
    address: '13601 Gaff Rig Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$345,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,648',
    acres: '0.281',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This beautiful, one-story home is the brand new Ch ...',
    photo: '/assets/listings/texas-city/55365560.jpg',
    status: 'Active',
  },
  {
    mls: '38814105',
    address: '203 22nd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$284,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,585',
    acres: '0.303',
    yearBuilt: '1984',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Move-in ready and fully remodeled, this 4 bedroom, ...',
    photo: '/assets/listings/texas-city/38814105.jpg',
    status: 'Active',
  },
  {
    mls: '22238432',
    address: '2001 14th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$199,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,332',
    acres: '0.181',
    yearBuilt: '1969',
    subdivision: 'Westview 2',
    county: 'Galveston',
    remarks: 'This inviting 3-bedroom, 2-bath home offers 1,332 ...',
    photo: '/assets/listings/texas-city/22238432.jpg',
    status: 'Active',
  },
  {
    mls: '68689559',
    address: '13119 Pinnacle Beach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$293,991',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,627',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Frey Fl ...',
    photo: '/assets/listings/texas-city/68689559.jpg',
    status: 'Active',
  },
  {
    mls: '8471165',
    address: '8109 Quartz Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$254,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,732',
    acres: '0.165',
    yearBuilt: '2016',
    subdivision: 'Pearlbrook',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully maintained 4-bedr ...',
    photo: '/assets/listings/texas-city/8471165.jpg',
    status: 'Active',
  },
  {
    mls: '71074543',
    address: '3330 1st Avenue S',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$84,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '720',
    acres: '0.148',
    yearBuilt: '1950',
    subdivision: 'Kohfeldt 2nd',
    county: 'Galveston',
    remarks: 'The subject property is a distant suburban home si ...',
    photo: '/assets/listings/texas-city/71074543.jpg',
    status: 'Active',
  },
  {
    mls: '61479204',
    address: '1418 16th Ave',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$320,031',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,915',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Steed Landing',
    county: 'Galveston',
    remarks: 'The Sabine Plan. This 1915 SF New CastleRock home ...',
    photo: '/assets/listings/texas-city/61479204.jpg',
    status: 'Active',
  },
  {
    mls: '27612220',
    address: '2903 Core Meadows Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$348,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,907',
    acres: '0.19',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'The Fannin floor plan offers a spacious, functiona ...',
    photo: '/assets/listings/texas-city/27612220.jpg',
    status: 'Active',
  },
  {
    mls: '57535801',
    address: '3009 Robinson Boulevard',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$169,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,212',
    acres: '0.139',
    yearBuilt: '1966',
    subdivision: 'Clairmont',
    county: 'Galveston',
    remarks: 'Amazing price in a cute neighborhood. Roof is new ...',
    photo: '/assets/listings/texas-city/57535801.jpg',
    status: 'Active',
  },
  {
    mls: '49922729',
    address: '5815 Woodrow Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$285,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,620',
    acres: '0.126',
    yearBuilt: '2026',
    subdivision: 'North Oak',
    county: 'Galveston',
    remarks: 'Welcome to 5815 Woodrow St. This beautiful New Cus ...',
    photo: '/assets/listings/texas-city/49922729.jpg',
    status: 'Active',
  },
  {
    mls: '96606676',
    address: '14316 Seagrass Knoll Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77539',
    price: '$383,490',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,621',
    acres: '0.165',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Discover spacious living and modern design in the ...',
    photo: '/assets/listings/texas-city/96606676.jpg',
    status: 'Active',
  },
  {
    mls: '47994173',
    address: '9705 Blue Bonnet Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$270,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,638',
    acres: '0.126',
    yearBuilt: '2009',
    subdivision: 'Lone Trail Village Sec 1 2007',
    county: 'Galveston',
    remarks: 'Welcome to this spacious 4-bedroom, 2.5-bath home ...',
    photo: '/assets/listings/texas-city/47994173.jpg',
    status: 'Active',
  },
  {
    mls: '84036306',
    address: '2122 Lierna Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$499,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,139',
    acres: '0.143',
    yearBuilt: '2023',
    subdivision: 'Lago Mar Sec 1 Pod 8',
    county: 'Galveston',
    remarks: '**WELCOME HOME! Discover your future in the heart ...',
    photo: '/assets/listings/texas-city/84036306.jpg',
    status: 'Active',
  },
  {
    mls: '19283835',
    address: '2605 Lago Costa Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$329,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,819',
    acres: '0.159',
    yearBuilt: '2024',
    subdivision: 'Lago Mar Pod 8 Sec 6',
    county: 'Galveston',
    remarks: 'Beautiful Lennar \\\\"Nash\\\\" Elevation D home in the hi ...',
    photo: '/assets/listings/texas-city/19283835.jpg',
    status: 'Active',
  },
  {
    mls: '73400112',
    address: '13613 Windward Mist Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$389,990',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,778',
    acres: '0.23',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Experience the perfect blend of elegance and comfo ...',
    photo: '/assets/listings/texas-city/73400112.jpg',
    status: 'Active',
  },
  {
    mls: '61565501',
    address: '2220 Manila Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$318,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,759',
    acres: '0.152',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'READY NOW! 4 BEDROOMS, 3 FULL BATHS, H ...',
    photo: '/assets/listings/texas-city/61565501.jpg',
    status: 'Active',
  },
  {
    mls: '80146019',
    address: '3007 Golden Isle Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$403,990',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,778',
    acres: '0.23',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Experience the perfect blend of luxury and conveni ...',
    photo: '/assets/listings/texas-city/80146019.jpg',
    status: 'Active',
  },
  {
    mls: '94667694',
    address: '2212 Manila Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$318,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,800',
    acres: '0.152',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'READY NOW!!! Smart One-Story Plan with 1800 Sq. Ft ...',
    photo: '/assets/listings/texas-city/94667694.jpg',
    status: 'Active',
  },
  {
    mls: '71719255',
    address: '2919 Golden Isle Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$399,990',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,778',
    acres: '0.23',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Explore this captivating one-story home featuring ...',
    photo: '/assets/listings/texas-city/71719255.jpg',
    status: 'Active',
  },
  {
    mls: '52641131',
    address: '1705 20th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$299,900',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,210',
    acres: '0.183',
    yearBuilt: '1973',
    subdivision: 'Westview 4',
    county: 'Galveston',
    remarks: 'Welcome to this spacious and well-maintained 5-bed ...',
    photo: '/assets/listings/texas-city/52641131.jpg',
    status: 'Active',
  },
  {
    mls: '56642831',
    address: '2610 18th Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$335,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,872',
    acres: '0.291',
    yearBuilt: '2016',
    subdivision: 'Godard Park',
    county: 'Galveston',
    remarks: 'Charming single-story brick home in Godard Park! B ...',
    photo: '/assets/listings/texas-city/56642831.jpg',
    status: 'Active',
  },
  {
    mls: '50157757',
    address: '2612 4th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$157,900',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,101',
    acres: '0.138',
    yearBuilt: '1986',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Thank you for taking the time to view this propert ...',
    photo: '/assets/listings/texas-city/50157757.jpg',
    status: 'Active',
  },
  {
    mls: '84231554',
    address: '1011 12th 1/2 Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$183,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,232',
    acres: '0.143',
    yearBuilt: '1944',
    subdivision: 'Snug Harbor',
    county: 'Galveston',
    remarks: 'Completely remodeled 3-bedroom, 2-bath home locate ...',
    photo: '/assets/listings/texas-city/84231554.jpg',
    status: 'Active',
  },
  {
    mls: '23841386',
    address: '702 Lane Road',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$350,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,348',
    acres: '0.484',
    yearBuilt: '1974',
    subdivision: 'Amburn Homesites',
    county: 'Galveston',
    remarks: 'Welcome home! This beautifully remodeled single-st ...',
    photo: '/assets/listings/texas-city/23841386.jpg',
    status: 'Active',
  },
  {
    mls: '59620076',
    address: '31 14th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$150,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,432',
    acres: '0.144',
    yearBuilt: '1970',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Located on a charming street, this home boasts a c ...',
    photo: '/assets/listings/texas-city/59620076.jpg',
    status: 'Active',
  },
  {
    mls: '76580945',
    address: '422 2nd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$79,500',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '667',
    acres: '0.144',
    yearBuilt: '1954',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/texas-city/76580945.jpg',
    status: 'Active',
  },
  {
    mls: '23985243',
    address: '2302 35th Ave N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$230,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,320',
    acres: '0.23',
    yearBuilt: '1968',
    subdivision: 'Northside',
    county: 'Galveston',
    remarks: 'Completely remodeled and move-in ready! This beaut ...',
    photo: '/assets/listings/texas-city/23985243.jpg',
    status: 'Active',
  },
  {
    mls: '19918552',
    address: '13124 Pinnacle Beach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$342,990',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,229',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'New Construction Lennar Houston Home - The Hendrix ...',
    photo: '/assets/listings/texas-city/19918552.jpg',
    status: 'Active',
  },
  {
    mls: '82325408',
    address: '1502 20th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$299,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,954',
    acres: '0.289',
    yearBuilt: '1991',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Welcome to 1502 20th Avenue N in Texas City! This ...',
    photo: '/assets/listings/texas-city/82325408.jpg',
    status: 'Active',
  },
]
