// Clear Lake Shores homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const clearlakeshoresListings: Listing[] = [
  {
    mls: '15263184',
    address: '920 Grove Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$749,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,927',
    acres: '0.161',
    yearBuilt: '1992',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'Fresh opportunity! Back on the market with a massi ...',
    photo: '/assets/listings/clear-lake-shores/15263184.jpg',
    status: 'Active',
  },
  {
    mls: '24359857',
    address: '221 Oak Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$399,999',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,050',
    acres: '0.207',
    yearBuilt: '1977',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'Enjoy this unique coastal living in a tight-knit w ...',
    photo: '/assets/listings/clear-lake-shores/24359857.jpg',
    status: 'Active',
  },
  {
    mls: '86221447',
    address: '701 Pine Road Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$735,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,200',
    acres: '0.092',
    yearBuilt: '2026',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'One-of-a-kind new construction nestled in the isla ...',
    photo: '/assets/listings/clear-lake-shores/86221447.jpg',
    status: 'Active',
  },
  {
    mls: '52642300',
    address: '660 Pine Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$410,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '840',
    acres: '0.092',
    yearBuilt: '1978',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'Welcome to 660 Pine Road in the highly sought-afte ...',
    photo: '/assets/listings/clear-lake-shores/52642300.jpg',
    status: 'Active',
  },
  {
    mls: '47598816',
    address: '631 E Shore Drive',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$529,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,760',
    acres: '0.413',
    yearBuilt: '1980',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'Incredibly rare 18,000 SF lot in Clear Lake Shores ...',
    photo: '/assets/listings/clear-lake-shores/47598816.jpg',
    status: 'Active',
  },
  {
    mls: '95240635',
    address: '209 Queen Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$785,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,643',
    acres: '0.138',
    yearBuilt: '2015',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'This charming, 2015 custom home features a classic ...',
    photo: '/assets/listings/clear-lake-shores/95240635.jpg',
    status: 'Active',
  },
  {
    mls: '30985621',
    address: '403 W Shore Drive',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$1,175,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,019',
    acres: '0.111',
    yearBuilt: '2019',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'Waterfront Home, Water Views, Private Dock & Endle ...',
    photo: '/assets/listings/clear-lake-shores/30985621.jpg',
    status: 'Active',
  },
  {
    mls: '98726713',
    address: '112 Oak Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$599,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,028',
    acres: '0.184',
    yearBuilt: '1982',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'CUTE, LIGHT FILLED HOME SITUARTED ON A ...',
    photo: '/assets/listings/clear-lake-shores/98726713.jpg',
    status: 'Active',
  },
  {
    mls: '36438713',
    address: '222 Oak Road Road',
    city: 'Clear Lake Shores',
    state: 'Texas',
    zip: '77565',
    price: '$559,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,248',
    acres: '0.092',
    yearBuilt: '2006',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'CHARMING COASTAL RETREAT IN CLEAR LAKE SHORES! Si ...',
    photo: '/assets/listings/clear-lake-shores/36438713.jpg',
    status: 'Active',
  },
]
