// Tiki Island homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const tikiislandListings: Listing[] = [
  {
    mls: '21064191',
    address: '426 Sunset Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,689,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,232',
    acres: '0.243',
    yearBuilt: '2001',
    subdivision: 'Tiki Island 10',
    county: 'Galveston',
    remarks: 'TIKI ISLAND BAYFRONT, DOUBLE HOMESITE ...',
    photo: '/assets/listings/tiki-island/21064191.jpg',
    status: 'Active',
  },
  {
    mls: '71892142',
    address: '151 Tamana Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$599,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,220',
    acres: '0.17',
    yearBuilt: '1997',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Waterfront Living on Tiki Island – Spacious & Move ...',
    photo: '/assets/listings/tiki-island/71892142.jpg',
    status: 'Active',
  },
  {
    mls: '68574425',
    address: '1534 Windsong Way',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,299,999',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,455',
    acres: '0.124',
    yearBuilt: '2016',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Experience relaxed coastal living in this waterfro ...',
    photo: '/assets/listings/tiki-island/68574425.jpg',
    status: 'Active',
  },
  {
    mls: '25013000',
    address: '429 Jeanie Lynne Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,279,125',
    beds: '5 Bedrooms',
    baths: '6 Total Baths',
    sqft: '3,375',
    acres: '0.119',
    yearBuilt: '2016',
    subdivision: 'Tiki Yacht Club Colony Sec 2',
    county: 'Galveston',
    remarks: 'Bring your bathing suit — this one is ready to enj ...',
    photo: '/assets/listings/tiki-island/25013000.jpg',
    status: 'Active',
  },
  {
    mls: '22908406',
    address: '223 Easterly Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$619,999',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,400',
    acres: '0.122',
    yearBuilt: '1985',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Perfect Tiki \\\\"ONE STORY\\\\" Bay Front home with wraps ...',
    photo: '/assets/listings/tiki-island/22908406.jpg',
    status: 'Active',
  },
  {
    mls: '94289155',
    address: '423 Hana Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$898,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,358',
    acres: '0.103',
    yearBuilt: '1999',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'MOTIVATED SELLER – NO HOA – NEW ROOF! Most furnitu ...',
    photo: '/assets/listings/tiki-island/94289155.jpg',
    status: 'Active',
  },
  {
    mls: '84344769',
    address: '238 Bamaku Bend',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$625,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,714',
    acres: '0.103',
    yearBuilt: '1981',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'This updated 3 bedroom, 2 bath coastal canal home ...',
    photo: '/assets/listings/tiki-island/84344769.jpg',
    status: 'Active',
  },
  {
    mls: '30863624',
    address: '1319 Coral Way',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$799,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,922',
    acres: '0.163',
    yearBuilt: '2001',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Welcome to your private paradise in the Village of ...',
    photo: '/assets/listings/tiki-island/30863624.jpg',
    status: 'Active',
  },
  {
    mls: '14034091',
    address: '107 Gulf Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,195,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,604',
    acres: '0.107',
    yearBuilt: '2026',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Discover the first home at The Neighborhood at Tik ...',
    photo: '/assets/listings/tiki-island/14034091.jpg',
    status: 'Active',
  },
  {
    mls: '45796966',
    address: '223 Kona Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$649,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,489',
    acres: '0.137',
    yearBuilt: '1999',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Welcome to your waterfront escape on Tiki Island! ...',
    photo: '/assets/listings/tiki-island/45796966.jpg',
    status: 'Active',
  },
  {
    mls: '16710403',
    address: '1435 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$449,999',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,457',
    acres: '0.126',
    yearBuilt: '1976',
    subdivision: 'Tiki Island 5b',
    county: 'Galveston',
    remarks: 'Waterfront investment opportunity ideal for a fix- ...',
    photo: '/assets/listings/tiki-island/16710403.jpg',
    status: 'Active',
  },
  {
    mls: '5163471',
    address: '1751 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$459,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,110',
    acres: '0.197',
    yearBuilt: '1992',
    subdivision: 'Tiki Island 9',
    county: 'Galveston',
    remarks: 'Escape to your own waterfront retreat in desirable ...',
    photo: '/assets/listings/tiki-island/5163471.jpg',
    status: 'Active',
  },
  {
    mls: '15595854',
    address: '519 Westerly Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$995,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,335',
    acres: '0.213',
    yearBuilt: '2000',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Experience waterfront living at its finest in this ...',
    photo: '/assets/listings/tiki-island/15595854.jpg',
    status: 'Active',
  },
  {
    mls: '98736920',
    address: '325 Admiral Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$789,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,884',
    acres: '0.109',
    yearBuilt: '2008',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Wonderful canal property in the Tiki Yacht Club Co ...',
    photo: '/assets/listings/tiki-island/98736920.jpg',
    status: 'Active',
  },
  {
    mls: '93630354',
    address: '12 Tiki Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,500,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,423',
    acres: '0.16',
    yearBuilt: '1998',
    subdivision: 'Tiki Island 15a Th',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/tiki-island/93630354.jpg',
    status: 'Active',
  },
  {
    mls: '74879836',
    address: '506 Westerly Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$996,899',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,922',
    acres: '0.124',
    yearBuilt: '2003',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Swimming Pool great entertaining area with a kitch ...',
    photo: '/assets/listings/tiki-island/74879836.jpg',
    status: 'Active',
  },
  {
    mls: '31932641',
    address: '208 Coconut Street',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,450,000',
    beds: '3 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,072',
    acres: '0.346',
    yearBuilt: '1980',
    subdivision: 'Milans Corner 2nd Rep 2009',
    county: 'Galveston',
    remarks: 'Furnished waterfront living on Tiki Island with a ...',
    photo: '/assets/listings/tiki-island/31932641.jpg',
    status: 'Active',
  },
  {
    mls: '4471571',
    address: '414 Westerly',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$775,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,150',
    acres: '',
    yearBuilt: '2000',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Wake up to the relaxed pace of Tiki Island and enj ...',
    photo: '/assets/listings/tiki-island/4471571.jpg',
    status: 'Active',
  },
  {
    mls: '12949018',
    address: '111 Kona Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$599,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,144',
    acres: '0.115',
    yearBuilt: '2000',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/tiki-island/12949018.jpg',
    status: 'Active',
  },
  {
    mls: '63725719',
    address: '1110 Papeete Street',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,150,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,704',
    acres: '0.125',
    yearBuilt: '2005',
    subdivision: 'Tiki Island 2',
    county: 'Galveston',
    remarks: 'Waterfront living on Tiki Island! This spacious ho ...',
    photo: '/assets/listings/tiki-island/63725719.jpg',
    status: 'Active',
  },
  {
    mls: '28930166',
    address: '1507 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,049,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,441',
    acres: '0.126',
    yearBuilt: '1993',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Tiki Island! A rare waterfront gem on Tiki Lake, o ...',
    photo: '/assets/listings/tiki-island/28930166.jpg',
    status: 'Active',
  },
  {
    mls: '55066563',
    address: '407 Isles End Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,399,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,085',
    acres: '0.124',
    yearBuilt: '1985',
    subdivision: 'Tiki Island 10',
    county: 'Galveston',
    remarks: 'Discover modern luxury in the highly desirable Tik ...',
    photo: '/assets/listings/tiki-island/55066563.jpg',
    status: 'Active',
  },
  {
    mls: '11582066',
    address: '243 Isles End Road RR2',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$699,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,949',
    acres: '0.103',
    yearBuilt: '1994',
    subdivision: 'Tiki Island 11',
    county: 'Galveston',
    remarks: 'Enjoy waterfront living at its finest in this stun ...',
    photo: '/assets/listings/tiki-island/11582066.jpg',
    status: 'Active',
  },
  {
    mls: '33620140',
    address: '106 Quayside Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,760,900',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,626',
    acres: '0.103',
    yearBuilt: '1990',
    subdivision: 'Tiki Island 12',
    county: 'Galveston',
    remarks: 'Welcome to this stunning Bayfront property! Comple ...',
    photo: '/assets/listings/tiki-island/33620140.jpg',
    status: 'Active',
  },
  {
    mls: '32757624',
    address: '318 Sunset Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$985,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,026',
    acres: '0.124',
    yearBuilt: '2001',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: '.Move-in ready canal-front home with easy access t ...',
    photo: '/assets/listings/tiki-island/32757624.jpg',
    status: 'Active',
  },
  {
    mls: '72814554',
    address: '515 Westerly Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$969,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,448',
    acres: '0.121',
    yearBuilt: '2000',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Home is move in READY! Expansive 3 bed, 3 bath pro ...',
    photo: '/assets/listings/tiki-island/72814554.jpg',
    status: 'Active',
  },
  {
    mls: '71950019',
    address: '944 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$399,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,159',
    acres: '0.126',
    yearBuilt: '1985',
    subdivision: 'Tiki Cove Estates',
    county: 'Galveston',
    remarks: 'Enjoy beautiful marsh and water views from this ad ...',
    photo: '/assets/listings/tiki-island/71950019.jpg',
    status: 'Active',
  },
  {
    mls: '30714955',
    address: '438 Amanda Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$998,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,825',
    acres: '0.127',
    yearBuilt: '2021',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Look no further! Impeccable and priced more than $ ...',
    photo: '/assets/listings/tiki-island/30714955.jpg',
    status: 'Active',
  },
  {
    mls: '65842416',
    address: '1614 Castaway Street',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$3,100,000',
    beds: '6 Bedrooms',
    baths: '8 Total Baths',
    sqft: '7,624',
    acres: '0.302',
    yearBuilt: '1992',
    subdivision: 'Tiki Island 7',
    county: 'Galveston',
    remarks: 'Trophy waterfront living-132 feet of deep water ca ...',
    photo: '/assets/listings/tiki-island/65842416.jpg',
    status: 'Active',
  },
  {
    mls: '41700404',
    address: '1007 Tiki',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$613,562',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,132',
    acres: '0.219',
    yearBuilt: '1988',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Charming Newly Renovated Bungalow with oversized l ...',
    photo: '/assets/listings/tiki-island/41700404.jpg',
    status: 'Active',
  },
  {
    mls: '16951993',
    address: '506 Sunset Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$2,750,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '4,592',
    acres: '0.457',
    yearBuilt: '2006',
    subdivision: 'Tiki Island 10',
    county: 'Galveston',
    remarks: 'Beautiful Waterfront Property with Southwestern Fl ...',
    photo: '/assets/listings/tiki-island/16951993.jpg',
    status: 'Active',
  },
  {
    mls: '14586391',
    address: '1330 Coral Way',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$799,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,570',
    acres: '0.227',
    yearBuilt: '1978',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'The most beautiful, lush mature landscaping anyone ...',
    photo: '/assets/listings/tiki-island/14586391.jpg',
    status: 'Active',
  },
  {
    mls: '59981514',
    address: '427 Tahiti Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$551,250',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,280',
    acres: '0.11',
    yearBuilt: '1980',
    subdivision: 'Tiki Island 2',
    county: 'Galveston',
    remarks: 'Opportunity, opportunity to snag this incredible l ...',
    photo: '/assets/listings/tiki-island/59981514.jpg',
    status: 'Active',
  },
  {
    mls: '23152895',
    address: '209 Bora Bora Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$869,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,897',
    acres: '0.138',
    yearBuilt: '1994',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'ELEVATOR ONE LEVEL TIKI ISLAND HOME. O ...',
    photo: '/assets/listings/tiki-island/23152895.jpg',
    status: 'Active',
  },
  {
    mls: '40678760',
    address: '422 Windward Way',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$830,060',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,420',
    acres: '0.098',
    yearBuilt: '2000',
    subdivision: 'Tiki Yacht Club Colony Sec 2',
    county: 'Galveston',
    remarks: 'Enjoy stunning sunsets and excellent fishing right ...',
    photo: '/assets/listings/tiki-island/40678760.jpg',
    status: 'Active',
  },
  {
    mls: '98558208',
    address: '303 Tahiti Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$750,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,180',
    acres: '0.321',
    yearBuilt: '1984',
    subdivision: 'Tiki Island 6',
    county: 'Galveston',
    remarks: 'Great bay home with a shared private boat ramp. ...',
    photo: '/assets/listings/tiki-island/98558208.jpg',
    status: 'Active',
  },
  {
    mls: '82293768',
    address: '918 Long Reach Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$998,679',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,746',
    acres: '0.142',
    yearBuilt: '1996',
    subdivision: 'Tiki Island 13',
    county: 'Galveston',
    remarks: 'This move-in ready home offers newly updated featu ...',
    photo: '/assets/listings/tiki-island/82293768.jpg',
    status: 'Active',
  },
  {
    mls: '18287882',
    address: '1554 Windsong Way',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,299,999',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,680',
    acres: '0.142',
    yearBuilt: '2001',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Come enjoy this inviting \\\\"FURNISHED \\\\"BAYFRONT 4-Be ...',
    photo: '/assets/listings/tiki-island/18287882.jpg',
    status: 'Active',
  },
  {
    mls: '29194840',
    address: '218 Catamaran Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,999,998',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,000',
    acres: '0.338',
    yearBuilt: '2004',
    subdivision: 'Tiki Island 5b',
    county: 'Galveston',
    remarks: 'Welcome to your own Tropical Oasis in Tiki Island! ...',
    photo: '/assets/listings/tiki-island/29194840.jpg',
    status: 'Active',
  },
  {
    mls: '58764253',
    address: '115 Bamaku Bend',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,344,960',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,717',
    acres: '0.216',
    yearBuilt: '1982',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'A Tiki Canal ONE STORY WITH ELEVATOR is tucked on ...',
    photo: '/assets/listings/tiki-island/58764253.jpg',
    status: 'Active',
  },
  {
    mls: '20567339',
    address: '241 Tamana Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,490,000',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,401',
    acres: '0.186',
    yearBuilt: '2001',
    subdivision: 'Tiki Island 5a',
    county: 'Galveston',
    remarks: 'BOAT PARKING WITH 140+ WATERFRONTAGEExperience lux ...',
    photo: '/assets/listings/tiki-island/20567339.jpg',
    status: 'Active',
  },
  {
    mls: '14938553',
    address: '925 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$850,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,267',
    acres: '0.127',
    yearBuilt: '1999',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Well-maintained 4-bed, 3-bath canal-front home off ...',
    photo: '/assets/listings/tiki-island/14938553.jpg',
    status: 'Active',
  },
  {
    mls: '48885135',
    address: '1854 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$599,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,887',
    acres: '0.091',
    yearBuilt: '2001',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'A signature waterfront residence designed by accla ...',
    photo: '/assets/listings/tiki-island/48885135.jpg',
    status: 'Active',
  },
  {
    mls: '15626574',
    address: '1303 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$799,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,878',
    acres: '0.174',
    yearBuilt: '2002',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Great Home to begin your enjoyment on TikiTrue 4 B ...',
    photo: '/assets/listings/tiki-island/15626574.jpg',
    status: 'Active',
  },
  {
    mls: '30977411',
    address: '306 Isles End Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$490,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,406',
    acres: '0.114',
    yearBuilt: '1984',
    subdivision: 'Tiki Island 10',
    county: 'Galveston',
    remarks: 'New outside paint and new deck/porch in Jan 2024. ...',
    photo: '/assets/listings/tiki-island/30977411.jpg',
    status: 'Active',
  },
  {
    mls: '8090554',
    address: '214 Sampan Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$814,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,008',
    acres: '0.132',
    yearBuilt: '1986',
    subdivision: 'Tiki Island 5b',
    county: 'Galveston',
    remarks: 'Coastal Living at its finest!! Stunning, Well Main ...',
    photo: '/assets/listings/tiki-island/8090554.jpg',
    status: 'Active',
  },
  {
    mls: '74851365',
    address: '107 Bamaku Bend',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,280,250',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,845',
    acres: '0.142',
    yearBuilt: '1995',
    subdivision: 'Tiki Island 11',
    county: 'Galveston',
    remarks: 'OWNER/AGENTFOREVER HOME/COASTAL GETAWAYS, this hom ...',
    photo: '/assets/listings/tiki-island/74851365.jpg',
    status: 'Active',
  },
  {
    mls: '84446812',
    address: '1814 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$697,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,250',
    acres: '0.138',
    yearBuilt: '1991',
    subdivision: 'Tiki Island 10',
    county: 'Galveston',
    remarks: 'Home has been totally remodeled. Come enjoy the be ...',
    photo: '/assets/listings/tiki-island/84446812.jpg',
    status: 'Active',
  },
  {
    mls: '42101097',
    address: '270 Isles End Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$779,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,740',
    acres: '0.14',
    yearBuilt: '1995',
    subdivision: 'Tiki Island 11',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/tiki-island/42101097.jpg',
    status: 'Active',
  },
  {
    mls: '89855398',
    address: '1426 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$469,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,097',
    acres: '0.126',
    yearBuilt: '1983',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Charming 3BR/2BA canal-front home on highly desire ...',
    photo: '/assets/listings/tiki-island/89855398.jpg',
    status: 'Active',
  },
  {
    mls: '74377377',
    address: '102 Bamaku Bend',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,450,899',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,161',
    acres: '0.146',
    yearBuilt: '1996',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Live the waterfront dream in this one-of-a-kind co ...',
    photo: '/assets/listings/tiki-island/74377377.jpg',
    status: 'Active',
  },
  {
    mls: '70472961',
    address: '1407 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$700,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,327',
    acres: '0.165',
    yearBuilt: '1975',
    subdivision: 'Tiki Island 5a',
    county: 'Galveston',
    remarks: 'Welcome to your dream coastal home, a spacious wat ...',
    photo: '/assets/listings/tiki-island/70472961.jpg',
    status: 'Active',
  },
  {
    mls: '58435341',
    address: '1226 Oahu Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$799,999',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,720',
    acres: '0.144',
    yearBuilt: '1978',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Call about Owners Terms please and rental terms to ...',
    photo: '/assets/listings/tiki-island/58435341.jpg',
    status: 'Active',
  },
  {
    mls: '39329427',
    address: '1303 Outrigger',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$999,000',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,150',
    acres: '0.094',
    yearBuilt: '1987',
    subdivision: 'Tiki Island 6',
    county: 'Galveston',
    remarks: '*Lot next door is also for sale - see MLS#91361915 ...',
    photo: '/assets/listings/tiki-island/39329427.jpg',
    status: 'Active',
  },
  {
    mls: '96769174',
    address: '214 Easterly Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$624,700',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,764',
    acres: '0.125',
    yearBuilt: '1992',
    subdivision: 'Tiki Island 9',
    county: 'Galveston',
    remarks: 'Discover the ultimate coastal lifestyle with this ...',
    photo: '/assets/listings/tiki-island/96769174.jpg',
    status: 'Active',
  },
  {
    mls: '68469238',
    address: '1302 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$880,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,304',
    acres: '0.248',
    yearBuilt: '1982',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Beautiful 3–4 bedroom, 2 bath home on Tiki Island ...',
    photo: '/assets/listings/tiki-island/68469238.jpg',
    status: 'Active',
  },
  {
    mls: '49368048',
    address: '219 Bora Bora Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$844,484',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,802',
    acres: '0.138',
    yearBuilt: '1974',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Fabulous Tiki Canal Home with Bay ViewsStraight sh ...',
    photo: '/assets/listings/tiki-island/49368048.jpg',
    status: 'Active',
  },
  {
    mls: '80604225',
    address: '1327 Tiki Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$715,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,176',
    acres: '0.282',
    yearBuilt: '1990',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Spacious 3BR/2BA canal-front home with stunning di ...',
    photo: '/assets/listings/tiki-island/80604225.jpg',
    status: 'Active',
  },
  {
    mls: '9902005',
    address: '247 Isles End Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$690,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,488',
    acres: '0.104',
    yearBuilt: '1995',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Stunning bayfront 3BR/3BA home offering breathtaki ...',
    photo: '/assets/listings/tiki-island/9902005.jpg',
    status: 'Active',
  },
  {
    mls: '85190415',
    address: '3 Tiki Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$345,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,463',
    acres: '0.052',
    yearBuilt: '1970',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Multi level bayfront town home with 2 car attached ...',
    photo: '/assets/listings/tiki-island/85190415.jpg',
    status: 'Active',
  },
  {
    mls: '40460960',
    address: '210 Sampan Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$555,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,176',
    acres: '0.146',
    yearBuilt: '1984',
    subdivision: 'Tiki Island 5b',
    county: 'Galveston',
    remarks: 'Immerse yourself in Summer vibes at this 2 bed/2 b ...',
    photo: '/assets/listings/tiki-island/40460960.jpg',
    status: 'Active',
  },
  {
    mls: '57517993',
    address: '442 Jeanie Lynn Street',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$984,477',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,910',
    acres: '0.12',
    yearBuilt: '2001',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Ask about the flooring and the decking for further ...',
    photo: '/assets/listings/tiki-island/57517993.jpg',
    status: 'Active',
  },
  {
    mls: '16532872',
    address: '139 Isles End Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,399,999',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,920',
    acres: '0.112',
    yearBuilt: '1993',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'ONE OF A KIND!! Beautifully renovated bay retreat ...',
    photo: '/assets/listings/tiki-island/16532872.jpg',
    status: 'Active',
  },
  {
    mls: '21274059',
    address: '251 Isles End Road',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$878,976',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,240',
    acres: '0.103',
    yearBuilt: '1968',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'This Tiki SEASIDE Home can be yours just in time f ...',
    photo: '/assets/listings/tiki-island/21274059.jpg',
    status: 'Active',
  },
  {
    mls: '28833578',
    address: '430 Amanda Circle',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,516,480',
    beds: '6 Bedrooms',
    baths: '6 Total Baths',
    sqft: '4,000',
    acres: '0.127',
    yearBuilt: '2022',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Has all the custom touches with out being custom! ...',
    photo: '/assets/listings/tiki-island/28833578.jpg',
    status: 'Active',
  },
  {
    mls: '80326834',
    address: '230 Bora Bora Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$1,299,999',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,540',
    acres: '0.103',
    yearBuilt: '2024',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'BRING REASONABLE OFFERS !!Beautiful NEW Canal home ...',
    photo: '/assets/listings/tiki-island/80326834.jpg',
    status: 'Active',
  },
  {
    mls: '54005542',
    address: '919 Long Reach Drive',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$950,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,238',
    acres: '0.17',
    yearBuilt: '1995',
    subdivision: 'Tiki Island 13',
    county: 'Galveston',
    remarks: 'This lovely two-story has breathtaking views of Ga ...',
    photo: '/assets/listings/tiki-island/54005542.jpg',
    status: 'Active',
  },
  {
    mls: '95168785',
    address: '210 Easterly',
    city: 'Tiki Island',
    state: 'Texas',
    zip: '77554',
    price: '$949,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,746',
    acres: '',
    yearBuilt: '1980',
    subdivision: 'Tiki Island',
    county: 'Galveston',
    remarks: 'Wonderful Canal Home with options of fully furnish ...',
    photo: '/assets/listings/tiki-island/95168785.jpg',
    status: 'Active',
  },
]
