// El Lago homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const ellagoListings: Listing[] = [
  {
    mls: '44018534',
    address: '423 Woodvine Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$275,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,144',
    acres: '0.207',
    yearBuilt: '1966',
    subdivision: 'El Lago Sec 04 R/P',
    county: 'Harris',
    remarks: 'Well-maintained one-story traditional home offerin ...',
    photo: '/assets/listings/el-lago/44018534.jpg',
    status: 'Active',
  },
  {
    mls: '2954646',
    address: '426 Shadow Creek Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$279,999',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,103',
    acres: '0.223',
    yearBuilt: '1965',
    subdivision: 'El Lago Sec 03',
    county: 'Harris',
    remarks: 'Beautifully maintained 4-bedroom, 2-bath home in t ...',
    photo: '/assets/listings/el-lago/2954646.jpg',
    status: 'Active',
  },
  {
    mls: '23040128',
    address: '1735 Les Talley Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$369,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,824',
    acres: '0.238',
    yearBuilt: '1991',
    subdivision: 'Taylorcrest Sec 02',
    county: 'Harris',
    remarks: 'This beautiful 4-bedroom home in the established T ...',
    photo: '/assets/listings/el-lago/23040128.jpg',
    status: 'Active',
  },
  {
    mls: '19782944',
    address: '407 Hedgecroft Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$420,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,746',
    acres: '0.207',
    yearBuilt: '1979',
    subdivision: 'Taylorcrest Sec 01',
    county: 'Harris',
    remarks: 'Welcome to this beautifully renovated (2026) 3-bed ...',
    photo: '/assets/listings/el-lago/19782944.jpg',
    status: 'Active',
  },
  {
    mls: '14977233',
    address: '410 Crestwood Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$437,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,322',
    acres: '0.207',
    yearBuilt: '1984',
    subdivision: 'Taylorcrest Sec1 Corr Pla',
    county: 'Harris',
    remarks: 'Welcome to 410 Crestwood, a custom-built home near ...',
    photo: '/assets/listings/el-lago/14977233.jpg',
    status: 'Active',
  },
  {
    mls: '88030895',
    address: '4001 Nasa Parkway 131',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$79,500',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '782',
    acres: '2.501',
    yearBuilt: '1980',
    subdivision: 'Lakeshore',
    county: 'Harris',
    remarks: 'Spacious one bedroom ready for you to update to yo ...',
    photo: '/assets/listings/el-lago/88030895.jpg',
    status: 'Active',
  },
  {
    mls: '45170024',
    address: '100 Cedar Lane',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$824,999',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '2,797',
    acres: '0.24',
    yearBuilt: '2026',
    subdivision: 'El Lago Estates',
    county: 'Harris',
    remarks: 'Experience luxury living in this stunning brand-ne ...',
    photo: '/assets/listings/el-lago/45170024.jpg',
    status: 'Active',
  },
  {
    mls: '43490635',
    address: '4001 Nasa Parkway 232',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$135,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,085',
    acres: '2.501',
    yearBuilt: '1980',
    subdivision: 'Lakeshore Condos',
    county: 'Harris',
    remarks: 'Beautifully updated condo in a desirable waterfron ...',
    photo: '/assets/listings/el-lago/43490635.jpg',
    status: 'Active',
  },
  {
    mls: '97438729',
    address: '200 Yacht Club Lane 200',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$250,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,092',
    acres: '1.661',
    yearBuilt: '1979',
    subdivision: 'Yacht Club Condo Ph 1',
    county: 'Harris',
    remarks: 'Coastal living with the BEST views of the lake. Co ...',
    photo: '/assets/listings/el-lago/97438729.jpg',
    status: 'Active',
  },
  {
    mls: '7784961',
    address: '1703 E Hedgecroft Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$365,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,392',
    acres: '0.212',
    yearBuilt: '1991',
    subdivision: 'Taylorcrest Sec 01',
    county: 'Harris',
    remarks: 'Located in the desirable Taylorcrest neighborhood ...',
    photo: '/assets/listings/el-lago/7784961.jpg',
    status: 'Active',
  },
  {
    mls: '16180775',
    address: '4001 Nasa 1 Parkway 112',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$234,684',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,210',
    acres: '2.501',
    yearBuilt: '1980',
    subdivision: 'Lakeshore Condo',
    county: 'Harris',
    remarks: 'Nestled right on Clear Lake in El Lago, Texas, thi ...',
    photo: '/assets/listings/el-lago/16180775.jpg',
    status: 'Active',
  },
  {
    mls: '5863912',
    address: '534 Bayview Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$239,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,988',
    acres: '0.2',
    yearBuilt: '1968',
    subdivision: 'El Lago Estates Sec 06',
    county: 'Harris',
    remarks: 'Great location in this quiet wooded neighborhood. ...',
    photo: '/assets/listings/el-lago/5863912.jpg',
    status: 'Active',
  },
  {
    mls: '22527774',
    address: '4011 Nasa Rd 1 Parkway 512',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$200,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,066',
    acres: '0.981',
    yearBuilt: '1983',
    subdivision: 'Marina Bay Condo',
    county: 'Harris',
    remarks: 'Waterfront condo with marina views, private boat s ...',
    photo: '/assets/listings/el-lago/22527774.jpg',
    status: 'Active',
  },
  {
    mls: '37254950',
    address: '714 Crestwood Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$490,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,656',
    acres: '0.233',
    yearBuilt: '1987',
    subdivision: 'Taylorcrest Sec 02 Corr Place',
    county: 'Harris',
    remarks: 'Tucked beneath mature trees, this beautifully main ...',
    photo: '/assets/listings/el-lago/37254950.jpg',
    status: 'Active',
  },
  {
    mls: '95777536',
    address: '702 Huntercrest Street',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$470,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,714',
    acres: '0.276',
    yearBuilt: '1998',
    subdivision: 'Taylorcrest',
    county: 'Harris',
    remarks: 'Welcome to this unique 5-bedroom, 5-bath, 3-car ga ...',
    photo: '/assets/listings/el-lago/95777536.jpg',
    status: 'Active',
  },
  {
    mls: '18281755',
    address: '307 Crestwood Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$559,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,784',
    acres: '0.31',
    yearBuilt: '1982',
    subdivision: 'Taylorcrest',
    county: 'Harris',
    remarks: 'Welcome to lake life! This custom 4-bdrm, 3.5 bath ...',
    photo: '/assets/listings/el-lago/18281755.jpg',
    status: 'Active',
  },
  {
    mls: '20597981',
    address: '427 Biscayne Boulevard',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$359,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,207',
    acres: '0.258',
    yearBuilt: '1963',
    subdivision: 'El Lago Sec 03',
    county: 'Harris',
    remarks: '427 Biscayne, in well established El Lago, is a 4 ...',
    photo: '/assets/listings/el-lago/20597981.jpg',
    status: 'Active',
  },
  {
    mls: '25357273',
    address: '443 Bayou View Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$355,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,426',
    acres: '0.309',
    yearBuilt: '1967',
    subdivision: 'El Lago Sec 03',
    county: 'Harris',
    remarks: 'Discover the possibilities in this one-story ranch ...',
    photo: '/assets/listings/el-lago/25357273.jpg',
    status: 'Active',
  },
  {
    mls: '39347900',
    address: '4001 Nasa Parkway 213',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$115,000',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '782',
    acres: '2.501',
    yearBuilt: '1980',
    subdivision: 'Lakeshore',
    county: 'Harris',
    remarks: 'Spectacular one bedroom corner unit has been updat ...',
    photo: '/assets/listings/el-lago/39347900.jpg',
    status: 'Active',
  },
  {
    mls: '23532935',
    address: '4011 Nasa Rd 1 Parkway 511',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$162,900',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,066',
    acres: '0.982',
    yearBuilt: '1983',
    subdivision: 'Marina Bay Condo',
    county: 'Harris',
    remarks: 'Discover your dream waterfront retreat! This spaci ...',
    photo: '/assets/listings/el-lago/23532935.jpg',
    status: 'Active',
  },
  {
    mls: '30426419',
    address: '114 Yacht Club Lane 114',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$160,000',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '713',
    acres: '1.66',
    yearBuilt: '1979',
    subdivision: 'Yacht Club Condo Ph',
    county: 'Harris',
    remarks: 'Stunning Canal-Front Condo with Breathtaking Views ...',
    photo: '/assets/listings/el-lago/30426419.jpg',
    status: 'Active',
  },
]
