// Friendswood homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const friendswoodListings: Listing[] = [
  {
    mls: '20673946',
    address: '15811 Wandering Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$269,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,580',
    acres: '0.177',
    yearBuilt: '1972',
    subdivision: 'Wedgewood Village Sec 03',
    county: 'Harris',
    remarks: 'Remodeled, single story, three bedrooms, two bathr ...',
    photo: '/assets/listings/friendswood/20673946.jpg',
    status: 'Active',
  },
  {
    mls: '47114891',
    address: '2300 Friendswood Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$739,990',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,808',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Friendswood Trails',
    county: 'Galveston',
    remarks: 'The Amalfi plan perfectly blends elegance and comf ...',
    photo: '/assets/listings/friendswood/47114891.jpg',
    status: 'Active',
  },
  {
    mls: '8862761',
    address: '2505 Barton Creek Trail Dr',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$713,490',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,099',
    acres: '0.201',
    yearBuilt: '2026',
    subdivision: 'Friendswood Trails',
    county: 'Galveston',
    remarks: 'Luxury Living in Friendswood! NEW Move-In Ready Ho ...',
    photo: '/assets/listings/friendswood/8862761.jpg',
    status: 'Active',
  },
  {
    mls: '26222327',
    address: '16738 Barkentine Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$305,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,555',
    acres: '0.169',
    yearBuilt: '1985',
    subdivision: 'Heritage Park',
    county: 'Harris',
    remarks: 'Welcome to Heritage Park in Friendswood! This well ...',
    photo: '/assets/listings/friendswood/26222327.jpg',
    status: 'Active',
  },
  {
    mls: '66888676',
    address: '1109 W Castlewood Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$289,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,156',
    acres: '0.269',
    yearBuilt: '1982',
    subdivision: 'Wilderness Trails',
    county: 'Galveston',
    remarks: 'Bring your vision to this Friendswood fixer-upper, ...',
    photo: '/assets/listings/friendswood/66888676.jpg',
    status: 'Active',
  },
  {
    mls: '94378874',
    address: '210 Brandywyne Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$275,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,321',
    acres: '0.208',
    yearBuilt: '1966',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'Beautifully updated home offering modern finishes, ...',
    photo: '/assets/listings/friendswood/94378874.jpg',
    status: 'Active',
  },
  {
    mls: '30550690',
    address: '1570 Mustang Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$619,999',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,337',
    acres: '0.158',
    yearBuilt: '2021',
    subdivision: 'Friendswood Trls Secs 1 2',
    county: 'Galveston',
    remarks: 'Space, style, & an exceptional location come toget ...',
    photo: '/assets/listings/friendswood/30550690.jpg',
    status: 'Active',
  },
  {
    mls: '35248510',
    address: '4819 Stone Harbor Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$340,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,848',
    acres: '0.152',
    yearBuilt: '1990',
    subdivision: 'Heritage Park Sec 13',
    county: 'Harris',
    remarks: 'Welcome to this beautiful home in Heritage Park co ...',
    photo: '/assets/listings/friendswood/35248510.jpg',
    status: 'Active',
  },
  {
    mls: '16291533',
    address: '15503 Wandering Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$369,900',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,019',
    acres: '0.262',
    yearBuilt: '1968',
    subdivision: 'Wedgewood Village Sec 01',
    county: 'Harris',
    remarks: 'Beautifully updated 2-story home with great curb a ...',
    photo: '/assets/listings/friendswood/16291533.jpg',
    status: 'Active',
  },
  {
    mls: '74599093',
    address: '15810 Pilgrim Hall Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$389,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,346',
    acres: '0.156',
    yearBuilt: '1990',
    subdivision: 'Heritage Park Sec 13',
    county: 'Harris',
    remarks: 'Welcome to 15810 Pilgrim Hall Drive, Friendswood, ...',
    photo: '/assets/listings/friendswood/74599093.jpg',
    status: 'Active',
  },
  {
    mls: '37664541',
    address: '1231 Abigail Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$525,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,283',
    acres: '0.19',
    yearBuilt: '2010',
    subdivision: 'Autumn Lakes Sec 03',
    county: 'Harris',
    remarks: 'Thoughtfully designed for the way you live, this h ...',
    photo: '/assets/listings/friendswood/37664541.jpg',
    status: 'Active',
  },
  {
    mls: '59901734',
    address: '503 Shadywood Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$865,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,460',
    acres: '0.373',
    yearBuilt: '2000',
    subdivision: 'The Forest Sec 6 2001',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/friendswood/59901734.jpg',
    status: 'Active',
  },
  {
    mls: '22001460',
    address: '1501 W Castlewood Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$519,000',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,782',
    acres: '0.266',
    yearBuilt: '1989',
    subdivision: 'Wilderness Trails',
    county: 'Galveston',
    remarks: 'A new roof with transferable warranty was installe ...',
    photo: '/assets/listings/friendswood/22001460.jpg',
    status: 'Active',
  },
  {
    mls: '15012060',
    address: '205 Del Monte Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$699,990',
    beds: '4 Bedrooms',
    baths: '6 Total Baths',
    sqft: '4,179',
    acres: '0.413',
    yearBuilt: '2005',
    subdivision: 'Coward Creek Crossing 2003',
    county: 'Galveston',
    remarks: 'Stunning 4,179 sq ft custom-built home in sought-a ...',
    photo: '/assets/listings/friendswood/15012060.jpg',
    status: 'Active',
  },
  {
    mls: '57675750',
    address: '1746 Spring View',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$899,999',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,402',
    acres: '0.17',
    yearBuilt: '2024',
    subdivision: 'Sterling Creek',
    county: 'Galveston',
    remarks: 'Incredible custom Sterling Builder home in a gated ...',
    photo: '/assets/listings/friendswood/57675750.jpg',
    status: 'Active',
  },
  {
    mls: '94443969',
    address: '906 Quaker Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$850,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,970',
    acres: '0.74',
    yearBuilt: '1976',
    subdivision: 'Friendswood Sub Lts 1 To 12',
    county: 'Galveston',
    remarks: 'Distinctive home on large, wooded lot in the heart ...',
    photo: '/assets/listings/friendswood/94443969.jpg',
    status: 'Active',
  },
  {
    mls: '6110939',
    address: '501 Bellmar Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$235,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,049',
    acres: '0.15',
    yearBuilt: '1967',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'Nestled in the heart of Friendswood, 501 Bellmar o ...',
    photo: '/assets/listings/friendswood/6110939.jpg',
    status: 'Active',
  },
  {
    mls: '22591645',
    address: '608 Tanglewood Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$400,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,353',
    acres: '0.299',
    yearBuilt: '1981',
    subdivision: 'Dunbar Estates 1',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully renovated 3-bedroom, 2 ...',
    photo: '/assets/listings/friendswood/22591645.jpg',
    status: 'Active',
  },
  {
    mls: '92660747',
    address: '15819 Contender Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$318,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,817',
    acres: '0.152',
    yearBuilt: '1989',
    subdivision: 'Heritage Park',
    county: 'Harris',
    remarks: 'Beautifully remodeled 4-bed, 2-bath home in the de ...',
    photo: '/assets/listings/friendswood/92660747.jpg',
    status: 'Active',
  },
  {
    mls: '49845414',
    address: '1618 Stoney Lake Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$699,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,482',
    acres: '0.303',
    yearBuilt: '2003',
    subdivision: 'Friendswood Lakes',
    county: 'Galveston',
    remarks: 'Welcome to 1618 Stoney Lake Drive in Friendswood L ...',
    photo: '/assets/listings/friendswood/49845414.jpg',
    status: 'Active',
  },
  {
    mls: '81553229',
    address: '907 Remington Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$650,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,610',
    acres: '0.313',
    yearBuilt: '1990',
    subdivision: 'Laurelfield',
    county: 'Galveston',
    remarks: 'Wow, wooded oversized lot with gorgeous pool, all ...',
    photo: '/assets/listings/friendswood/81553229.jpg',
    status: 'Active',
  },
  {
    mls: '92952011',
    address: '1111 Haye Road',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$479,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,858',
    acres: '0.185',
    yearBuilt: '2013',
    subdivision: 'Autumn Lakes',
    county: 'Harris',
    remarks: 'This beautifully maintained 4-bedroom, 3.5-bath ho ...',
    photo: '/assets/listings/friendswood/92952011.jpg',
    status: 'Active',
  },
  {
    mls: '7765980',
    address: '1512 Windsor Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$440,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,961',
    acres: '0.269',
    yearBuilt: '1984',
    subdivision: 'Regency Estates 2',
    county: 'Galveston',
    remarks: 'This designer home is a showstopper! This home has ...',
    photo: '/assets/listings/friendswood/7765980.jpg',
    status: 'Active',
  },
  {
    mls: '23537523',
    address: '1109 Winding Way Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$234,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,530',
    acres: '0.035',
    yearBuilt: '1990',
    subdivision: 'Hidden Cove Condo',
    county: 'Galveston',
    remarks: 'There’s something special about 1109 Winding Way—t ...',
    photo: '/assets/listings/friendswood/23537523.jpg',
    status: 'Active',
  },
  {
    mls: '10320143',
    address: '1207 W Edgewood Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$499,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,344',
    acres: '0.373',
    yearBuilt: '1984',
    subdivision: 'Coward Creek 5',
    county: 'Galveston',
    remarks: 'Tucked beneath mature trees and framed by lush cre ...',
    photo: '/assets/listings/friendswood/10320143.jpg',
    status: 'Active',
  },
  {
    mls: '93933997',
    address: '2539 Ravenna Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$545,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,587',
    acres: '0.187',
    yearBuilt: '2021',
    subdivision: 'Friendswood Trls Secs 1 2',
    county: 'Galveston',
    remarks: 'NO BACK NEIGHBORS—Built in 2021, this Friendswood ...',
    photo: '/assets/listings/friendswood/93933997.jpg',
    status: 'Active',
  },
  {
    mls: '58047024',
    address: '11 Haverford Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$900,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,278',
    acres: '0.841',
    yearBuilt: '1975',
    subdivision: 'Quakers Landing',
    county: 'Galveston',
    remarks: 'A rare find in Friendswood, this beautifully updat ...',
    photo: '/assets/listings/friendswood/58047024.jpg',
    status: 'Active',
  },
  {
    mls: '48845456',
    address: '16915 Lighthouse View Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$329,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,945',
    acres: '0.133',
    yearBuilt: '1996',
    subdivision: 'Heritage Park Sec 20',
    county: 'Harris',
    remarks: 'JUST LISTED! ???New home. New possibilities. Could ...',
    photo: '/assets/listings/friendswood/48845456.jpg',
    status: 'Active',
  },
  {
    mls: '89479643',
    address: '1508 Harvest Vine Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$499,999',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,689',
    acres: '0.177',
    yearBuilt: '2020',
    subdivision: 'Friendswood Trails',
    county: 'Galveston',
    remarks: 'Welcome to this spacious 5-bedroom, 3-bathroom hom ...',
    photo: '/assets/listings/friendswood/89479643.jpg',
    status: 'Active',
  },
  {
    mls: '26993408',
    address: '1226 Martinez Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$475,000',
    beds: '6 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,664',
    acres: '0.179',
    yearBuilt: '2010',
    subdivision: 'Autumn Lakes Sec 03',
    county: 'Harris',
    remarks: 'Expansive & bright 2-story home, centrally located ...',
    photo: '/assets/listings/friendswood/26993408.jpg',
    status: 'Active',
  },
  {
    mls: '51279023',
    address: '1728 Pampas Trail Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$899,999',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '6,288',
    acres: '0.269',
    yearBuilt: '2010',
    subdivision: 'Friendswood Lakes Sec 4 2008',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully updated 6 bedroom/4.5 ...',
    photo: '/assets/listings/friendswood/51279023.jpg',
    status: 'Active',
  },
  {
    mls: '10105787',
    address: '1602 Orlando Street',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$529,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,490',
    acres: '0.283',
    yearBuilt: '1998',
    subdivision: 'Boca Raton Sec 2 96',
    county: 'Galveston',
    remarks: 'Welcome to 1602 Orlando Street, a rare find featur ...',
    photo: '/assets/listings/friendswood/10105787.jpg',
    status: 'Active',
  },
  {
    mls: '24977028',
    address: '4634 Stonemede Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$315,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,799',
    acres: '0.18',
    yearBuilt: '1987',
    subdivision: 'Heritage Park',
    county: 'Harris',
    remarks: 'Friendswood \\\\"model\\\\" home just minutes to Baybrook ...',
    photo: '/assets/listings/friendswood/24977028.jpg',
    status: 'Active',
  },
  {
    mls: '48444319',
    address: '1645 Longwood Glen Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$665,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,263',
    acres: '0.166',
    yearBuilt: '2017',
    subdivision: 'Sierra/West Ranch Sec 3',
    county: 'Galveston',
    remarks: 'Exceptional style & thoughtful design define this ...',
    photo: '/assets/listings/friendswood/48444319.jpg',
    status: 'Active',
  },
  {
    mls: '58998473',
    address: '1474 Garden Lakes Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$475,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,488',
    acres: '0.172',
    yearBuilt: '2007',
    subdivision: 'Friendswood Lakes Garden Homes',
    county: 'Galveston',
    remarks: 'Welcome to this beautiful 3-bedroom, 2-bathroom si ...',
    photo: '/assets/listings/friendswood/58998473.jpg',
    status: 'Active',
  },
  {
    mls: '33086891',
    address: '515 Pine Ridge Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$415,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,055',
    acres: '0.159',
    yearBuilt: '2001',
    subdivision: 'Parkwood Village Sec 3 2001',
    county: 'Galveston',
    remarks: 'Welcome to this exquisite property! A beautiful br ...',
    photo: '/assets/listings/friendswood/33086891.jpg',
    status: 'Active',
  },
  {
    mls: '18829123',
    address: '705 Eagle Lakes Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$500,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,512',
    acres: '0.292',
    yearBuilt: '1993',
    subdivision: 'Eagle Lakes Sec 3 94',
    county: 'Galveston',
    remarks: 'OPEN HOUSE THIS SAT. 08/15 1-3 PM. Swing by & See ...',
    photo: '/assets/listings/friendswood/18829123.jpg',
    status: 'Active',
  },
  {
    mls: '76150924',
    address: '2304 Halls Creek Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$899,000',
    beds: '5 Bedrooms',
    baths: '6 Total Baths',
    sqft: '4,554',
    acres: '0.334',
    yearBuilt: '2012',
    subdivision: 'Creekside At West Ranch Sec 3',
    county: 'Galveston',
    remarks: 'Palatial home with a pristine pool & spa on a prem ...',
    photo: '/assets/listings/friendswood/76150924.jpg',
    status: 'Active',
  },
  {
    mls: '90777382',
    address: '2512 Ravenna Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$620,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,456',
    acres: '0.194',
    yearBuilt: '2020',
    subdivision: 'Friendswood Trls Sec 1 2',
    county: 'Galveston',
    remarks: 'Beautiful two-story DR Horton home featuring 5 bed ...',
    photo: '/assets/listings/friendswood/90777382.jpg',
    status: 'Active',
  },
  {
    mls: '48842118',
    address: '300 Castlelake Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$264,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,350',
    acres: '0.171',
    yearBuilt: '1970',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'This exceptional 3-bedroom, 2-bathroom single-stor ...',
    photo: '/assets/listings/friendswood/48842118.jpg',
    status: 'Active',
  },
  {
    mls: '68654195',
    address: '910 High Ridge Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$559,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,848',
    acres: '0.465',
    yearBuilt: '2003',
    subdivision: 'Lakes Of Falcon Ridge',
    county: 'Galveston',
    remarks: 'Welcome home to a very sought after community, 1 s ...',
    photo: '/assets/listings/friendswood/68654195.jpg',
    status: 'Active',
  },
  {
    mls: '47416863',
    address: '1731 Pampas Trail Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$635,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,308',
    acres: '0.269',
    yearBuilt: '2007',
    subdivision: 'Friendswood Lakes Sec 4 2008',
    county: 'Galveston',
    remarks: 'Step through the 8-ft door leading you to a captiv ...',
    photo: '/assets/listings/friendswood/47416863.jpg',
    status: 'Active',
  },
  {
    mls: '41456435',
    address: '325 Old Course Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$380,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,342',
    acres: '0.258',
    yearBuilt: '1979',
    subdivision: 'Sunmeadow 3',
    county: 'Galveston',
    remarks: 'Welcome to this move-in ready 4-bedroom, 2.5-bath ...',
    photo: '/assets/listings/friendswood/41456435.jpg',
    status: 'Active',
  },
  {
    mls: '7552236',
    address: '3812 Laura Leigh Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$198,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,056',
    acres: '0.072',
    yearBuilt: '1972',
    subdivision: 'Forest Bend Sec 03 Reserve F',
    county: 'Harris',
    remarks: 'Beautiful Town home in a very quiet area, close to ...',
    photo: '/assets/listings/friendswood/7552236.jpg',
    status: 'Active',
  },
  {
    mls: '74173207',
    address: '205 Morningside Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$385,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,868',
    acres: '0.231',
    yearBuilt: '1965',
    subdivision: 'Harper Unrec',
    county: 'Galveston',
    remarks: 'Charming 4-bedroom, 2.5-bath home situated on a sp ...',
    photo: '/assets/listings/friendswood/74173207.jpg',
    status: 'Active',
  },
  {
    mls: '22471985',
    address: '403 Trail Head Street',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$749,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,602',
    acres: '0.352',
    yearBuilt: '1999',
    subdivision: 'The Forest Sec 2 99',
    county: 'Galveston',
    remarks: 'Welcome to 403 Trail Head Street! Located in highl ...',
    photo: '/assets/listings/friendswood/22471985.jpg',
    status: 'Active',
  },
  {
    mls: '2578331',
    address: '16910 David Glen Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$289,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,550',
    acres: '0.152',
    yearBuilt: '1971',
    subdivision: 'Forest Bend Sec 01',
    county: 'Harris',
    remarks: 'Welcome to 16910 David Glen in Friendswood! This b ...',
    photo: '/assets/listings/friendswood/2578331.jpg',
    status: 'Active',
  },
  {
    mls: '18778376',
    address: '16003 Salton Point Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$374,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,232',
    acres: '0.151',
    yearBuilt: '1992',
    subdivision: 'Heritage Park Sec 16',
    county: 'Harris',
    remarks: 'Welcome to 16003 Salton Point Drive, where soaring ...',
    photo: '/assets/listings/friendswood/18778376.jpg',
    status: 'Active',
  },
  {
    mls: '74491913',
    address: '422 W Castle Harbour Dr',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$274,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,692',
    acres: '0.207',
    yearBuilt: '1975',
    subdivision: 'Sunmeadow',
    county: 'Galveston',
    remarks: 'Three-bedroom, two-bath, single-story home in the ...',
    photo: '/assets/listings/friendswood/74491913.jpg',
    status: 'Active',
  },
  {
    mls: '84917159',
    address: '15526 Wandering Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$760,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,886',
    acres: '2.03',
    yearBuilt: '1974',
    subdivision: 'Wedgewood Village Sec 01',
    county: 'Harris',
    remarks: 'Welcome to this private Friendswood retreat on 2.3 ...',
    photo: '/assets/listings/friendswood/84917159.jpg',
    status: 'Active',
  },
  {
    mls: '49674604',
    address: '803 Hackberry Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$629,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,107',
    acres: '0.275',
    yearBuilt: '2000',
    subdivision: 'The Forest Sec 7 2001',
    county: 'Galveston',
    remarks: 'Welcome to this stunning single-story home in the ...',
    photo: '/assets/listings/friendswood/49674604.jpg',
    status: 'Active',
  },
  {
    mls: '41043999',
    address: '1504 Windsor Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$354,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,568',
    acres: '0.269',
    yearBuilt: '1984',
    subdivision: 'Regency Estates 2',
    county: 'Galveston',
    remarks: 'This single-story traditional home in Regency Esta ...',
    photo: '/assets/listings/friendswood/41043999.jpg',
    status: 'Active',
  },
  {
    mls: '34881386',
    address: '206 Clearview Avenue B',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$355,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,569',
    acres: '0.087',
    yearBuilt: '2000',
    subdivision: 'Quaker Village Twnhms',
    county: 'Galveston',
    remarks: 'Beautifully renovated single-story townhome in the ...',
    photo: '/assets/listings/friendswood/34881386.jpg',
    status: 'Active',
  },
  {
    mls: '42061990',
    address: '1504 Tallow Chase Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$842,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,946',
    acres: '0.312',
    yearBuilt: '2016',
    subdivision: 'Austin Chase At West Ranch',
    county: 'Galveston',
    remarks: 'Situated on a quiet cul-de-sac in Friendswood ISD, ...',
    photo: '/assets/listings/friendswood/42061990.jpg',
    status: 'Active',
  },
  {
    mls: '44043957',
    address: '2619 Midnight Star Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$350,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,772',
    acres: '0.147',
    yearBuilt: '2005',
    subdivision: 'Heritage Park Sec 21',
    county: 'Harris',
    remarks: 'Welcome to this one-owner, 4-bedroom, 2.5-bath hom ...',
    photo: '/assets/listings/friendswood/44043957.jpg',
    status: 'Active',
  },
  {
    mls: '92199036',
    address: '5427 Timpani Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$285,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,580',
    acres: '0.179',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village Sec 06 Pt Re',
    county: 'Harris',
    remarks: 'Welcome home to this charming 3-bedroom, 2-bath re ...',
    photo: '/assets/listings/friendswood/92199036.jpg',
    status: 'Active',
  },
  {
    mls: '95581471',
    address: '1321 Summer Field Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$735,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,505',
    acres: '0.227',
    yearBuilt: '2017',
    subdivision: 'Arbor Gate/West Ranch Sec 3',
    county: 'Galveston',
    remarks: 'Beautiful Village Builders design tucked inside th ...',
    photo: '/assets/listings/friendswood/95581471.jpg',
    status: 'Active',
  },
  {
    mls: '41681029',
    address: '1305 Wilderness Pines Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$564,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,962',
    acres: '0.269',
    yearBuilt: '1992',
    subdivision: 'Wilderness Trails Sec 3 91',
    county: 'Galveston',
    remarks: 'Lovingly maintained and updated since 2007, this b ...',
    photo: '/assets/listings/friendswood/41681029.jpg',
    status: 'Active',
  },
  {
    mls: '98765330',
    address: '2316 Friendswood Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$788,990',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,885',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Friendswood Trails',
    county: 'Galveston',
    remarks: 'The two-story Positano plan offers an impressive 3 ...',
    photo: '/assets/listings/friendswood/98765330.jpg',
    status: 'Active',
  },
  {
    mls: '9137129',
    address: '1207 Peregrine Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$549,900',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,336',
    acres: '0.269',
    yearBuilt: '2000',
    subdivision: 'Falcon Ridge',
    county: 'Galveston',
    remarks: 'Vacation at home in this stately residence nestled ...',
    photo: '/assets/listings/friendswood/9137129.jpg',
    status: 'Active',
  },
  {
    mls: '50290255',
    address: '904 Cozy Hollow Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$725,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,192',
    acres: '0.255',
    yearBuilt: '2013',
    subdivision: 'West Ranch Lake Ridge Sec 1',
    county: 'Galveston',
    remarks: 'Great neighbors and lots of kids, this 5BR/4BA, 4, ...',
    photo: '/assets/listings/friendswood/50290255.jpg',
    status: 'Active',
  },
  {
    mls: '9048166',
    address: '2519 Colonial Ridge Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$258,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,557',
    acres: '0.145',
    yearBuilt: '1979',
    subdivision: 'Heritage Park Sec 06',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/friendswood/9048166.jpg',
    status: 'Active',
  },
  {
    mls: '66782187',
    address: '2513 Royal Field Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$898,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,927',
    acres: '0.216',
    yearBuilt: '2017',
    subdivision: 'West Ranch',
    county: 'Galveston',
    remarks: 'Rarely found, the home offers two luxurious primar ...',
    photo: '/assets/listings/friendswood/66782187.jpg',
    status: 'Active',
  },
  {
    mls: '32076523',
    address: '16114 Forest Bend Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$345,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,172',
    acres: '0.196',
    yearBuilt: '1974',
    subdivision: 'Wedgewood Village',
    county: 'Harris',
    remarks: 'Beautifully renovated 4-bedroom home in the highly ...',
    photo: '/assets/listings/friendswood/32076523.jpg',
    status: 'Active',
  },
  {
    mls: '73836081',
    address: '5303 Bulen Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$309,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,660',
    acres: '0.337',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village',
    county: 'Harris',
    remarks: 'Welcome to 5303 Bulen Avenue in Wedgewood Village! ...',
    photo: '/assets/listings/friendswood/73836081.jpg',
    status: 'Active',
  },
  {
    mls: '35023854',
    address: '1205 Tall Pines Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,900,000',
    beds: '6 Bedrooms',
    baths: '7 Total Baths',
    sqft: '7,357',
    acres: '0.706',
    yearBuilt: '1989',
    subdivision: 'Coward Creek 3',
    county: 'Galveston',
    remarks: 'Fully renovated custom home rebuilt from the studs ...',
    photo: '/assets/listings/friendswood/35023854.jpg',
    status: 'Active',
  },
  {
    mls: '79910211',
    address: '2814 Rolling Fog Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$350,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,154',
    acres: '0.157',
    yearBuilt: '1995',
    subdivision: 'Heritage Park',
    county: 'Harris',
    remarks: 'Welcome to 2814 Rolling Fog, a charming 3-bedroom, ...',
    photo: '/assets/listings/friendswood/79910211.jpg',
    status: 'Active',
  },
  {
    mls: '70112345',
    address: '304 Chester Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,150,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '5,155',
    acres: '1.334',
    yearBuilt: '1979',
    subdivision: 'Halls Add',
    county: 'Galveston',
    remarks: 'Located in Friendswood ISD on a desirable street w ...',
    photo: '/assets/listings/friendswood/70112345.jpg',
    status: 'Active',
  },
  {
    mls: '39928776',
    address: '940 Gadston Park Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,450,000',
    beds: '5 Bedrooms',
    baths: '6 Total Baths',
    sqft: '5,096',
    acres: '0.461',
    yearBuilt: '2018',
    subdivision: 'Arbor Gate/West Ranch Sec 2',
    county: 'Galveston',
    remarks: 'Experience unparalleled luxury at 940 Gadston Park ...',
    photo: '/assets/listings/friendswood/39928776.jpg',
    status: 'Active',
  },
  {
    mls: '56417173',
    address: '1603 White Wing Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$467,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,384',
    acres: '0.27',
    yearBuilt: '1985',
    subdivision: 'Falcon Ridge',
    county: 'Galveston',
    remarks: 'Beautiful custom home featuring extensive crown mo ...',
    photo: '/assets/listings/friendswood/56417173.jpg',
    status: 'Active',
  },
  {
    mls: '37563084',
    address: '1902 La Salle Street',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$399,995',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,494',
    acres: '0.169',
    yearBuilt: '1993',
    subdivision: 'Mission Estates 3',
    county: 'Galveston',
    remarks: 'This spacious and well-maintained 3-bedroom, 2.5-b ...',
    photo: '/assets/listings/friendswood/37563084.jpg',
    status: 'Active',
  },
  {
    mls: '44666571',
    address: '4220 Walnut Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$649,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,937',
    acres: '0.193',
    yearBuilt: '2017',
    subdivision: 'Autumn Lakes Sec 5',
    county: 'Harris',
    remarks: 'Impressive 4-bedroom, 4-bath home that offers near ...',
    photo: '/assets/listings/friendswood/44666571.jpg',
    status: 'Active',
  },
  {
    mls: '79546178',
    address: '5110 Geneva Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$274,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,474',
    acres: '0.159',
    yearBuilt: '1968',
    subdivision: 'Wedgewood Village',
    county: 'Harris',
    remarks: 'Charming home in Wedgewood Village features stando ...',
    photo: '/assets/listings/friendswood/79546178.jpg',
    status: 'Active',
  },
  {
    mls: '46953156',
    address: '1707 Brill Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$489,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,245',
    acres: '0.275',
    yearBuilt: '1992',
    subdivision: 'Keystone Meadows 91',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully updated home nestled i ...',
    photo: '/assets/listings/friendswood/46953156.jpg',
    status: 'Active',
  },
  {
    mls: '11438355',
    address: '1017 Bolivar Point Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$675,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,229',
    acres: '0.238',
    yearBuilt: '2013',
    subdivision: 'West Ranch West Lake Sec 2',
    county: 'Galveston',
    remarks: 'Located in sought-after West Ranch, this beautiful ...',
    photo: '/assets/listings/friendswood/11438355.jpg',
    status: 'Active',
  },
  {
    mls: '28481931',
    address: '202 Victoria Way',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$412,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,407',
    acres: '0.046',
    yearBuilt: '1984',
    subdivision: 'The Park Twnhms',
    county: 'Galveston',
    remarks: 'Updated & impeccably maintained two-story townhome ...',
    photo: '/assets/listings/friendswood/28481931.jpg',
    status: 'Active',
  },
  {
    mls: '10969800',
    address: '2905 Harvest Hill Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$680,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,586',
    acres: '0.396',
    yearBuilt: '2001',
    subdivision: 'Autumn Creek',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/friendswood/10969800.jpg',
    status: 'Active',
  },
  {
    mls: '94145036',
    address: '2211 Indigo Pass Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,200,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,697',
    acres: '0.346',
    yearBuilt: '2011',
    subdivision: 'West Ranch West Lake Sec 1',
    county: 'Galveston',
    remarks: 'Tucked away on a quiet cul-de-sac, this custom-bui ...',
    photo: '/assets/listings/friendswood/94145036.jpg',
    status: 'Active',
  },
  {
    mls: '27396248',
    address: '2118 Pilgrims Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$244,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,654',
    acres: '0.177',
    yearBuilt: '1984',
    subdivision: 'Heritage Park Sec 10',
    county: 'Harris',
    remarks: 'Beautifully maintained 3-bedroom, 2-bath home in t ...',
    photo: '/assets/listings/friendswood/27396248.jpg',
    status: 'Active',
  },
  {
    mls: '46484886',
    address: '5206 Abercreek Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$315,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,932',
    acres: '0.179',
    yearBuilt: '1975',
    subdivision: 'Wedgewood Village Sec 06',
    county: 'Harris',
    remarks: 'Welcome to this 3-bedroom, 2-bath home in Wedgewoo ...',
    photo: '/assets/listings/friendswood/46484886.jpg',
    status: 'Active',
  },
  {
    mls: '12837096',
    address: '2422 Pilgrims Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$289,777',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,233',
    acres: '0.209',
    yearBuilt: '1981',
    subdivision: 'Heritage Park Sec 07',
    county: 'Harris',
    remarks: 'This smartly designed home and floorplan has somet ...',
    photo: '/assets/listings/friendswood/12837096.jpg',
    status: 'Active',
  },
  {
    mls: '69802909',
    address: '1207 Yorkshire Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$340,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,904',
    acres: '0.269',
    yearBuilt: '1981',
    subdivision: 'Regency Estates 1',
    county: 'Galveston',
    remarks: 'Welcome to this 4-bedroom, 2-bath home in desirabl ...',
    photo: '/assets/listings/friendswood/69802909.jpg',
    status: 'Active',
  },
  {
    mls: '32631842',
    address: '1104 Hackberry Branch Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,150,000',
    beds: '5 Bedrooms',
    baths: '6 Total Baths',
    sqft: '4,385',
    acres: '0.248',
    yearBuilt: '2015',
    subdivision: 'West Ranch Lakeside Sec 1',
    county: 'Galveston',
    remarks: 'Stunning Partners In Building home with thoughtful ...',
    photo: '/assets/listings/friendswood/32631842.jpg',
    status: 'Active',
  },
  {
    mls: '35976155',
    address: '1102 Cowards Creek Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,199,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,350',
    acres: '1.851',
    yearBuilt: '1981',
    subdivision: 'Coward Creek 1',
    county: 'Galveston',
    remarks: 'Nestled on 1.8 acres of lush trees on the prestigi ...',
    photo: '/assets/listings/friendswood/35976155.jpg',
    status: 'Active',
  },
  {
    mls: '83951388',
    address: '5111 Regal Pine Way',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$299,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,004',
    acres: '0.22',
    yearBuilt: '1969',
    subdivision: 'Wedgewood Village Sec 01',
    county: 'Harris',
    remarks: 'WELL MAINTAINED HOME LOCATED CLOSE TO ...',
    photo: '/assets/listings/friendswood/83951388.jpg',
    status: 'Active',
  },
  {
    mls: '34624151',
    address: '5415 Timpani Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$279,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,620',
    acres: '0.179',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village Sec 06 R/P',
    county: 'Harris',
    remarks: 'Welcome home to this charming 4 bedroom, 2 bath, e ...',
    photo: '/assets/listings/friendswood/34624151.jpg',
    status: 'Active',
  },
  {
    mls: '2185201',
    address: '209 Palm Aire Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$299,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,736',
    acres: '0.254',
    yearBuilt: '1979',
    subdivision: 'Sunmeadow 1',
    county: 'Galveston',
    remarks: 'Updated 1.5-story home nestled amongst mature tree ...',
    photo: '/assets/listings/friendswood/2185201.jpg',
    status: 'Active',
  },
  {
    mls: '478848',
    address: '1628 Longwood Glen Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$655,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,256',
    acres: '0.171',
    yearBuilt: '2017',
    subdivision: 'Sierra/West Ranch Sec 2',
    county: 'Galveston',
    remarks: 'Welcome to Village Builders Heartland Collection \\\\" ...',
    photo: '/assets/listings/friendswood/478848.jpg',
    status: 'Active',
  },
  {
    mls: '46489092',
    address: '512 Castlelake Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$265,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,236',
    acres: '0.245',
    yearBuilt: '1966',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'Beautifully refreshed one-story nestled in Friends ...',
    photo: '/assets/listings/friendswood/46489092.jpg',
    status: 'Active',
  },
  {
    mls: '27297035',
    address: '4431 Ravine Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$309,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,482',
    acres: '0.253',
    yearBuilt: '1973',
    subdivision: 'Forest Bend Sec 04',
    county: 'Harris',
    remarks: 'Look no further! This beautifully remodeled 4-bedr ...',
    photo: '/assets/listings/friendswood/27297035.jpg',
    status: 'Active',
  },
  {
    mls: '90673368',
    address: '2204 Stillhouse Hollow Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$829,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,323',
    acres: '0.242',
    yearBuilt: '2014',
    subdivision: 'West Ranch West Lake Sec 3 20',
    county: 'Galveston',
    remarks: 'Architectural elegance meets exceptional design in ...',
    photo: '/assets/listings/friendswood/90673368.jpg',
    status: 'Active',
  },
  {
    mls: '96590068',
    address: '2306 Lakeway Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$759,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,406',
    acres: '0.358',
    yearBuilt: '2013',
    subdivision: 'The Lake San Joaquin',
    county: 'Galveston',
    remarks: 'Absolutely gorgeous and move-in ready, this impecc ...',
    photo: '/assets/listings/friendswood/96590068.jpg',
    status: 'Active',
  },
  {
    mls: '88170579',
    address: '1821 Avery Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$899,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,427',
    acres: '0.318',
    yearBuilt: '2017',
    subdivision: 'Sterling Creek',
    county: 'Galveston',
    remarks: 'Beautiful 1-story on a corner lot in gated Sterlin ...',
    photo: '/assets/listings/friendswood/88170579.jpg',
    status: 'Active',
  },
  {
    mls: '94171924',
    address: '3980 Laura Leigh Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$193,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,460',
    acres: '0.078',
    yearBuilt: '1972',
    subdivision: 'Forest Bend',
    county: 'Harris',
    remarks: '**Join us at the open house this Saturday 7/11 2-4 ...',
    photo: '/assets/listings/friendswood/94171924.jpg',
    status: 'Active',
  },
  {
    mls: '26812317',
    address: '109 Sunset Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,799,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '5,400',
    acres: '1.19',
    yearBuilt: '2001',
    subdivision: 'Friendswood Sub Lts 1 To 12',
    county: 'Galveston',
    remarks: 'Situated on 1.19 acres on Friendswood’s desirable ...',
    photo: '/assets/listings/friendswood/26812317.jpg',
    status: 'Active',
  },
  {
    mls: '83873445',
    address: '5451 Appleblossom Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$345,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,241',
    acres: '0.241',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village Sec 08 U/R',
    county: 'Harris',
    remarks: 'This beautiful 4 bedroom, 2 bath home is nestled o ...',
    photo: '/assets/listings/friendswood/83873445.jpg',
    status: 'Active',
  },
  {
    mls: '86220018',
    address: '2527 Corral Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$265,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,557',
    acres: '0.145',
    yearBuilt: '1979',
    subdivision: 'Heritage Park Sec 06',
    county: 'Harris',
    remarks: 'Welcome home to this charming 3 bed, 2 bath one-st ...',
    photo: '/assets/listings/friendswood/86220018.jpg',
    status: 'Active',
  },
  {
    mls: '3969415',
    address: '4731 Quillback Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$284,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,797',
    acres: '0.096',
    yearBuilt: '1985',
    subdivision: 'Heritage Park Sec 11',
    county: 'Harris',
    remarks: 'Welcome to this charming 4-bedroom, 2.5-bath home ...',
    photo: '/assets/listings/friendswood/3969415.jpg',
    status: 'Active',
  },
  {
    mls: '53152338',
    address: '2400 Lakeway Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$999,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '6,288',
    acres: '0.393',
    yearBuilt: '2013',
    subdivision: 'The Lake At San Joaquin',
    county: 'Galveston',
    remarks: 'Located in the gated Lakes of San Joaquin, this ho ...',
    photo: '/assets/listings/friendswood/53152338.jpg',
    status: 'Active',
  },
  {
    mls: '40654473',
    address: '1808 N Mission Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$454,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,705',
    acres: '0.169',
    yearBuilt: '1992',
    subdivision: 'Mission Estates',
    county: 'Galveston',
    remarks: 'Summer living starts here in highly sought-after F ...',
    photo: '/assets/listings/friendswood/40654473.jpg',
    status: 'Active',
  },
]
