// Deer Park homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const deerparkListings: Listing[] = [
  {
    mls: '2776534',
    address: '1009 N Amy Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$274,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,738',
    acres: '0.158',
    yearBuilt: '1975',
    subdivision: 'Deer Park Gardens Sec 09',
    county: 'Harris',
    remarks: 'Welcome to this charming four-bedroom home in Deer ...',
    photo: '/assets/listings/deer-park/2776534.jpg',
    status: 'Active',
  },
  {
    mls: '20772251',
    address: '513 S Crockett Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$279,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,765',
    acres: '0.161',
    yearBuilt: '1976',
    subdivision: 'Heritage Sec 02 R/P',
    county: 'Harris',
    remarks: 'Charming two-story home in highly sought-after Dee ...',
    photo: '/assets/listings/deer-park/20772251.jpg',
    status: 'Active',
  },
  {
    mls: '60544024',
    address: '2717 Wisdom Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$246,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,776',
    acres: '0.162',
    yearBuilt: '1966',
    subdivision: 'South Pasadena Plaza Sec 02',
    county: 'Harris',
    remarks: 'Welcome to this beautifully refreshed 4-bedroom, 2 ...',
    photo: '/assets/listings/deer-park/60544024.jpg',
    status: 'Active',
  },
  {
    mls: '85847098',
    address: '1809 S Wildflower Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$641,042',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,707',
    acres: '0.188',
    yearBuilt: '2026',
    subdivision: 'East Meadows Place',
    county: 'Harris',
    remarks: 'Don’t miss out–rare opportunity for new constructi ...',
    photo: '/assets/listings/deer-park/85847098.jpg',
    status: 'Active',
  },
  {
    mls: '32655365',
    address: '201 E Temperance Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$279,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,980',
    acres: '0.183',
    yearBuilt: '1975',
    subdivision: 'Heritage Sec 01',
    county: 'Harris',
    remarks: 'Make this house your HOME! Looking for your pool, ...',
    photo: '/assets/listings/deer-park/32655365.jpg',
    status: 'Active',
  },
  {
    mls: '73207720',
    address: '2609 Los Alamos Circle',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$334,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,690',
    acres: '0.138',
    yearBuilt: '2007',
    subdivision: 'East Park Sec 02',
    county: 'Harris',
    remarks: 'Move-in ready 4-bedroom home in Deer Park with fre ...',
    photo: '/assets/listings/deer-park/73207720.jpg',
    status: 'Active',
  },
  {
    mls: '1091650',
    address: '2133 Stoney Brook Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$350,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,452',
    acres: '0.135',
    yearBuilt: '2004',
    subdivision: 'Wincrest',
    county: 'Harris',
    remarks: '**Photos coming soon**4 bedroom 2 1/2 bath on a co ...',
    photo: '/assets/listings/deer-park/1091650.jpg',
    status: 'Active',
  },
  {
    mls: '29719793',
    address: '3618 Filmore Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$269,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,686',
    acres: '0.16',
    yearBuilt: '1980',
    subdivision: 'Park Meadows Sec 03',
    county: 'Harris',
    remarks: 'Welcome to 3618 Filmore, a beautifully maintained ...',
    photo: '/assets/listings/deer-park/29719793.jpg',
    status: 'Active',
  },
  {
    mls: '74227010',
    address: '2110 Hillshire Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$199,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,134',
    acres: '0.161',
    yearBuilt: '1949',
    subdivision: 'South Pasadena Plaza Sec 01',
    county: 'Harris',
    remarks: 'This charming home, fully renovated in 2023, tucke ...',
    photo: '/assets/listings/deer-park/74227010.jpg',
    status: 'Active',
  },
  {
    mls: '31968616',
    address: '2418 Lufkin Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$429,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,381',
    acres: '0.326',
    yearBuilt: '1975',
    subdivision: 'Deer Meadows Sec 03',
    county: 'Harris',
    remarks: 'Welcome home to this beautiful 4-bedroom, 2&#189;- ...',
    photo: '/assets/listings/deer-park/31968616.jpg',
    status: 'Active',
  },
  {
    mls: '25989323',
    address: '2405 Hillshire Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$249,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,312',
    acres: '0.161',
    yearBuilt: '1958',
    subdivision: 'South Pasadena Plaza',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated 3-bedroom, 1.5 ...',
    photo: '/assets/listings/deer-park/25989323.jpg',
    status: 'Active',
  },
  {
    mls: '17216205',
    address: '2414 Alexandra',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$528,000',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,362',
    acres: '0.193',
    yearBuilt: '2014',
    subdivision: 'Cottonwood Estates Sec 1',
    county: 'Harris',
    remarks: 'Located in the sought-after Cottonwood Estates com ...',
    photo: '/assets/listings/deer-park/17216205.jpg',
    status: 'Active',
  },
  {
    mls: '68383859',
    address: '2717 Georgia Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$375,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,164',
    acres: '0.249',
    yearBuilt: '1976',
    subdivision: 'Deer Meadows Sec 03',
    county: 'Harris',
    remarks: 'Beautifully remodeled and packed with desirable fe ...',
    photo: '/assets/listings/deer-park/68383859.jpg',
    status: 'Active',
  },
  {
    mls: '8585524',
    address: '7402 Elbridge Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$245,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,168',
    acres: '0.187',
    yearBuilt: '1955',
    subdivision: 'Spencer View Terrace',
    county: 'Harris',
    remarks: 'Fully Remodeled Gem in the Heart of Deer ParkWelco ...',
    photo: '/assets/listings/deer-park/8585524.jpg',
    status: 'Active',
  },
  {
    mls: '52584239',
    address: '3305 Luella Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$475,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,503',
    acres: '1.35',
    yearBuilt: '1964',
    subdivision: 'Deer Park Outlots',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/deer-park/52584239.jpg',
    status: 'Active',
  },
  {
    mls: '94897314',
    address: '3002 Village Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$285,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,988',
    acres: '0.17',
    yearBuilt: '1976',
    subdivision: 'Pequeno Village',
    county: 'Harris',
    remarks: 'Welcome to this custom-built home with freshly pai ...',
    photo: '/assets/listings/deer-park/94897314.jpg',
    status: 'Active',
  },
  {
    mls: '68126350',
    address: '1906 Wynforest Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$360,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,156',
    acres: '0.168',
    yearBuilt: '1992',
    subdivision: 'Wynfield Estates Sec 01',
    county: 'Harris',
    remarks: 'Welcome home to this beautifully maintained one-st ...',
    photo: '/assets/listings/deer-park/68126350.jpg',
    status: 'Active',
  },
  {
    mls: '20695068',
    address: '905 Ivy Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$259,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,720',
    acres: '0.172',
    yearBuilt: '1957',
    subdivision: 'Deer Park',
    county: 'Harris',
    remarks: 'Adorable Remodeled Home Come see this beautiful up ...',
    photo: '/assets/listings/deer-park/20695068.jpg',
    status: 'Active',
  },
  {
    mls: '59700881',
    address: '1801 N Wildflower Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$584,134',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,856',
    acres: '0.19',
    yearBuilt: '2026',
    subdivision: 'East Meadows Place',
    county: 'Harris',
    remarks: 'Don’t miss out – rare opportunity for new construc ...',
    photo: '/assets/listings/deer-park/59700881.jpg',
    status: 'Active',
  },
  {
    mls: '93843046',
    address: '1610 Seminole Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$430,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,628',
    acres: '0.16',
    yearBuilt: '1992',
    subdivision: 'Runningbrook Sec 02',
    county: 'Harris',
    remarks: '4-bed 2.5-bath offers an ideal blend of spacious l ...',
    photo: '/assets/listings/deer-park/93843046.jpg',
    status: 'Active',
  },
  {
    mls: '41424506',
    address: '2322 Pine Brook Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$590,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,495',
    acres: '0.179',
    yearBuilt: '2004',
    subdivision: 'Piney Point Sec 1',
    county: 'Harris',
    remarks: 'Explore 2322 Pine Brook Dr, an extraordinary 5-bed ...',
    photo: '/assets/listings/deer-park/41424506.jpg',
    status: 'Active',
  },
  {
    mls: '76064964',
    address: '1509 Kilgarlin Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$579,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,340',
    acres: '0.31',
    yearBuilt: '1991',
    subdivision: 'Erin Glen Sec 06b',
    county: 'Harris',
    remarks: 'Beautiful family home on small, quiet cul-de-sac s ...',
    photo: '/assets/listings/deer-park/76064964.jpg',
    status: 'Active',
  },
  {
    mls: '74734552',
    address: '2614 Red River Trail',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$554,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,255',
    acres: '0.262',
    yearBuilt: '2006',
    subdivision: 'Santa Fe Trail',
    county: 'Harris',
    remarks: 'WELCOME HOME TO DEER PARK, TEXAS. This stunning 4 ...',
    photo: '/assets/listings/deer-park/74734552.jpg',
    status: 'Active',
  },
  {
    mls: '37910926',
    address: '2221 Tracy Way',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$589,000',
    beds: '6 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,508',
    acres: '0.199',
    yearBuilt: '2009',
    subdivision: 'Ivy Oaks',
    county: 'Harris',
    remarks: 'Walk into EQUITY from the start! This impressive g ...',
    photo: '/assets/listings/deer-park/37910926.jpg',
    status: 'Active',
  },
  {
    mls: '51221200',
    address: '4616 Luella Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$243,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,626',
    acres: '0.152',
    yearBuilt: '1968',
    subdivision: 'College Park Sec 05',
    county: 'Harris',
    remarks: 'Welcome to this well-maintained 3-bedroom, 2-bath ...',
    photo: '/assets/listings/deer-park/51221200.jpg',
    status: 'Active',
  },
  {
    mls: '53047635',
    address: '1505 Roosevelt Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$289,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,839',
    acres: '0.188',
    yearBuilt: '1984',
    subdivision: 'Park Mdws Sec 04',
    county: 'Harris',
    remarks: 'Beautiful Two-story home with 3 bedrooms, 2.5 bath ...',
    photo: '/assets/listings/deer-park/53047635.jpg',
    status: 'Active',
  },
  {
    mls: '13205660',
    address: '2318 Killarney Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$574,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,463',
    acres: '0.325',
    yearBuilt: '1983',
    subdivision: 'Erin Glen Sec 02',
    county: 'Harris',
    remarks: 'Modern updates meet timeless style in this beautif ...',
    photo: '/assets/listings/deer-park/13205660.jpg',
    status: 'Active',
  },
  {
    mls: '87891502',
    address: '5014 E Meadow Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$349,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,650',
    acres: '0.115',
    yearBuilt: '2026',
    subdivision: 'East Mdw Deer Park',
    county: 'Harris',
    remarks: 'An opportunity unlike any other! Affordable new co ...',
    photo: '/assets/listings/deer-park/87891502.jpg',
    status: 'Active',
  },
  {
    mls: '54173352',
    address: '209 W 6th Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$245,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,408',
    acres: '0.131',
    yearBuilt: '1958',
    subdivision: 'Matlock Kemper',
    county: 'Harris',
    remarks: 'Quaint 4-bedroom house zoned to Deer Park Schools! ...',
    photo: '/assets/listings/deer-park/54173352.jpg',
    status: 'Active',
  },
  {
    mls: '23594426',
    address: '1321 Garden Court',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$309,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,964',
    acres: '0.13',
    yearBuilt: '1985',
    subdivision: 'Asbury Gardens',
    county: 'Harris',
    remarks: 'This side-entry garden home was Asbury Garden’s mo ...',
    photo: '/assets/listings/deer-park/23594426.jpg',
    status: 'Active',
  },
  {
    mls: '93714213',
    address: '2806 Spa Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$289,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,614',
    acres: '0.168',
    yearBuilt: '1967',
    subdivision: 'South Pasadena Plaza Sec 02',
    county: 'Harris',
    remarks: 'Located in Deer Park Ready for new home owner. Fre ...',
    photo: '/assets/listings/deer-park/93714213.jpg',
    status: 'Active',
  },
  {
    mls: '32967151',
    address: '4310 Luella Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$375,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,518',
    acres: '0.365',
    yearBuilt: '1969',
    subdivision: 'College Park Sec 07',
    county: 'Harris',
    remarks: 'Situated on a huge corner lot directly across from ...',
    photo: '/assets/listings/deer-park/32967151.jpg',
    status: 'Active',
  },
  {
    mls: '46226797',
    address: '1817 Mesa Verde Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$739,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,845',
    acres: '0.248',
    yearBuilt: '2007',
    subdivision: 'Park Place',
    county: 'Harris',
    remarks: 'Custom home in Deer Park where elegance meets mode ...',
    photo: '/assets/listings/deer-park/46226797.jpg',
    status: 'Active',
  },
  {
    mls: '74357967',
    address: '4910 E Meadow Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$437,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,180',
    acres: '0.116',
    yearBuilt: '2011',
    subdivision: 'East Meadow',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated former model h ...',
    photo: '/assets/listings/deer-park/74357967.jpg',
    status: 'Active',
  },
  {
    mls: '22352343',
    address: '2301 Zavalla Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$399,900',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,480',
    acres: '0.152',
    yearBuilt: '2007',
    subdivision: 'Sabine',
    county: 'Harris',
    remarks: 'Upgraded to the max! 2007 construction. Original ...',
    photo: '/assets/listings/deer-park/22352343.jpg',
    status: 'Active',
  },
  {
    mls: '79343419',
    address: '2329 Pickerton Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$239,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,442',
    acres: '0.161',
    yearBuilt: '1965',
    subdivision: 'South Pasadena Plaza',
    county: 'Harris',
    remarks: 'This charming 3-bedroom, 2-bathroom single-story h ...',
    photo: '/assets/listings/deer-park/79343419.jpg',
    status: 'Active',
  },
  {
    mls: '33759165',
    address: '1217 Ivy Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$255,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,248',
    acres: '0.172',
    yearBuilt: '1983',
    subdivision: 'Walker',
    county: 'Harris',
    remarks: 'Welcome to this beautifully maintained home that p ...',
    photo: '/assets/listings/deer-park/33759165.jpg',
    status: 'Active',
  },
  {
    mls: '46472623',
    address: '1801 Concord Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$279,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,676',
    acres: '0.209',
    yearBuilt: '1975',
    subdivision: 'Concord Trace Sec 01',
    county: 'Harris',
    remarks: 'Welcome home to this charming single-story brick h ...',
    photo: '/assets/listings/deer-park/46472623.jpg',
    status: 'Active',
  },
  {
    mls: '98866528',
    address: '2709 Los Alamos Circle',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$359,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,171',
    acres: '0.186',
    yearBuilt: '2007',
    subdivision: 'East Park Sec 02',
    county: 'Harris',
    remarks: 'Beautifully updated and move in ready, this home c ...',
    photo: '/assets/listings/deer-park/98866528.jpg',
    status: 'Active',
  },
  {
    mls: '55814730',
    address: '201 W 5th Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$350,000',
    beds: '6 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,692',
    acres: '0.161',
    yearBuilt: '1966',
    subdivision: 'Shell City',
    county: 'Harris',
    remarks: 'This versatile property features a combined 6 bedr ...',
    photo: '/assets/listings/deer-park/55814730.jpg',
    status: 'Active',
  },
  {
    mls: '17876436',
    address: '1710 Brooke Amber Circle',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$615,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,992',
    acres: '0.297',
    yearBuilt: '1993',
    subdivision: 'Tiffany Manor',
    county: 'Harris',
    remarks: 'Fantastic all-brick custom home with new kitchen t ...',
    photo: '/assets/listings/deer-park/17876436.jpg',
    status: 'Active',
  },
  {
    mls: '96616663',
    address: '2205 W Van Trease Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$489,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,993',
    acres: '0.229',
    yearBuilt: '1998',
    subdivision: 'Park Place Sec 2',
    county: 'Harris',
    remarks: 'This is a MUST SEE! SO many updates. Kitchen remod ...',
    photo: '/assets/listings/deer-park/96616663.jpg',
    status: 'Active',
  },
  {
    mls: '28638869',
    address: '1818 S Wildflower Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$568,609',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,856',
    acres: '0.19',
    yearBuilt: '2026',
    subdivision: 'East Meadows Place',
    county: 'Harris',
    remarks: 'Don’t miss out – rare opportunity for new construc ...',
    photo: '/assets/listings/deer-park/28638869.jpg',
    status: 'Active',
  },
  {
    mls: '47573717',
    address: '1910 Wynforest Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$399,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,562',
    acres: '0.184',
    yearBuilt: '1993',
    subdivision: 'Wynfield Estates Sec 1',
    county: 'Harris',
    remarks: '4/5 BR, 2-1/2 BATH, FORMAL DINING, OFF ...',
    photo: '/assets/listings/deer-park/47573717.jpg',
    status: 'Active',
  },
  {
    mls: '61767898',
    address: '822 Dutch Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$260,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,751',
    acres: '0.23',
    yearBuilt: '1957',
    subdivision: 'Poye',
    county: 'Harris',
    remarks: 'Beautifully updated & full of possibilities! This ...',
    photo: '/assets/listings/deer-park/61767898.jpg',
    status: 'Active',
  },
  {
    mls: '50328928',
    address: '414 E Lambuth Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$250,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,488',
    acres: '0.169',
    yearBuilt: '1976',
    subdivision: 'Heritage Add Sec 02 Rep',
    county: 'Harris',
    remarks: 'Welcome to this charming 3-bedroom, 2-bathroom hom ...',
    photo: '/assets/listings/deer-park/50328928.jpg',
    status: 'Active',
  },
  {
    mls: '36144682',
    address: '1126 Jeffrey Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$288,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,776',
    acres: '0.187',
    yearBuilt: '1973',
    subdivision: 'Parkglen Sec 01',
    county: 'Harris',
    remarks: 'Welcome to this charming and updated home situated ...',
    photo: '/assets/listings/deer-park/36144682.jpg',
    status: 'Active',
  },
  {
    mls: '3738648',
    address: '1822 N Wildflower Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$638,351',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,707',
    acres: '0.19',
    yearBuilt: '2026',
    subdivision: 'East Meadows Place',
    county: 'Harris',
    remarks: 'Don’t miss out–rare opportunity for new constructi ...',
    photo: '/assets/listings/deer-park/3738648.jpg',
    status: 'Active',
  },
  {
    mls: '32883266',
    address: '2418 Seguine Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$330,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,291',
    acres: '0.139',
    yearBuilt: '2005',
    subdivision: 'Wimberly',
    county: 'Harris',
    remarks: 'Welcome home to this beautiful low-maintained one- ...',
    photo: '/assets/listings/deer-park/32883266.jpg',
    status: 'Active',
  },
  {
    mls: '58034964',
    address: '505 E Lambuth Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$210,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,360',
    acres: '0.197',
    yearBuilt: '1977',
    subdivision: 'Heritage Sec 02 R/P',
    county: 'Harris',
    remarks: 'Located close to shopping, eateries and schools th ...',
    photo: '/assets/listings/deer-park/58034964.jpg',
    status: 'Active',
  },
  {
    mls: '27902255',
    address: '1402 New Orleans Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$284,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,711',
    acres: '0.178',
    yearBuilt: '1972',
    subdivision: 'Deer Meadows Sec 01',
    county: 'Harris',
    remarks: 'MOVE IN READY!!!! GORGEOUS clean brick home!!! EXC ...',
    photo: '/assets/listings/deer-park/27902255.jpg',
    status: 'Active',
  },
  {
    mls: '44477619',
    address: '1506 Waterford Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$349,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,806',
    acres: '0.175',
    yearBuilt: '1986',
    subdivision: 'Westside Manor Sec 04',
    county: 'Harris',
    remarks: 'Beautifully maintained 4-bedroom, 2.5-bath home fe ...',
    photo: '/assets/listings/deer-park/44477619.jpg',
    status: 'Active',
  },
  {
    mls: '38973278',
    address: '1225 Dutch Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$184,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '648',
    acres: '0.115',
    yearBuilt: '1960',
    subdivision: 'Deer Park',
    county: 'Harris',
    remarks: 'Charming 2-bedroom, 1-bath home in the heart of De ...',
    photo: '/assets/listings/deer-park/38973278.jpg',
    status: 'Active',
  },
  {
    mls: '72669822',
    address: '2206 Lisa Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$515,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,093',
    acres: '0.249',
    yearBuilt: '2010',
    subdivision: 'Ivy Oaks',
    county: 'Harris',
    remarks: 'Experience luxury living in this exquisite 5-bedro ...',
    photo: '/assets/listings/deer-park/72669822.jpg',
    status: 'Active',
  },
  {
    mls: '18946488',
    address: '1103 James Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$205,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,236',
    acres: '0.172',
    yearBuilt: '1955',
    subdivision: 'Liberty Deer Park Ol',
    county: 'Harris',
    remarks: 'This comfortable Deer Park home offers a warm and ...',
    photo: '/assets/listings/deer-park/18946488.jpg',
    status: 'Active',
  },
  {
    mls: '54903675',
    address: '1110 E Rutgers Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$239,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,427',
    acres: '0.165',
    yearBuilt: '1968',
    subdivision: 'College Park Sec 05',
    county: 'Harris',
    remarks: 'Great opportunity for investors! Tenant occupied, ...',
    photo: '/assets/listings/deer-park/54903675.jpg',
    status: 'Active',
  },
  {
    mls: '78842255',
    address: '1601 Washington Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$349,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,908',
    acres: '0.179',
    yearBuilt: '1979',
    subdivision: 'Park Meadows',
    county: 'Harris',
    remarks: 'Welcome to this beautifully remodeled home in the ...',
    photo: '/assets/listings/deer-park/78842255.jpg',
    status: 'Active',
  },
  {
    mls: '55171365',
    address: '4605 Meadow Way Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$345,000',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,902',
    acres: '0.115',
    yearBuilt: '2010',
    subdivision: 'East Meadow',
    county: 'Harris',
    remarks: 'Welcome to this exceptionally spacious 5-bedroom, ...',
    photo: '/assets/listings/deer-park/55171365.jpg',
    status: 'Active',
  },
  {
    mls: '98207769',
    address: '222 W Vaughn Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$325,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,258',
    acres: '0.22',
    yearBuilt: '1962',
    subdivision: 'Deer Park Outlots',
    county: 'Harris',
    remarks: 'Perfect end-of-street find beside Deer Park High S ...',
    photo: '/assets/listings/deer-park/98207769.jpg',
    status: 'Active',
  },
  {
    mls: '85934368',
    address: '610 E X Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$299,989',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,976',
    acres: '0.231',
    yearBuilt: '1971',
    subdivision: 'Deer Park Gardens',
    county: 'Harris',
    remarks: 'Fantastic location in Deer Park! New roof in 2022 ...',
    photo: '/assets/listings/deer-park/85934368.jpg',
    status: 'Active',
  },
  {
    mls: '56865611',
    address: '4313 Ashley Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$578,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,994',
    acres: '0.201',
    yearBuilt: '2014',
    subdivision: 'Cottonwood Estates',
    county: 'Harris',
    remarks: 'Welcome home to the highly sought after neighborho ...',
    photo: '/assets/listings/deer-park/56865611.jpg',
    status: 'Active',
  },
  {
    mls: '92188507',
    address: '1110 E Brown Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$239,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,603',
    acres: '0.168',
    yearBuilt: '1969',
    subdivision: 'College Park Sec 07',
    county: 'Harris',
    remarks: 'Beautifully updated 4-bedroom, 2-bath home offerin ...',
    photo: '/assets/listings/deer-park/92188507.jpg',
    status: 'Active',
  },
  {
    mls: '57737625',
    address: '4314 Juniper Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$499,900',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,213',
    acres: '0.187',
    yearBuilt: '2016',
    subdivision: 'Cottonwood Estates',
    county: 'Harris',
    remarks: 'WoW! This place has it all! Amazing floorplan wi ...',
    photo: '/assets/listings/deer-park/57737625.jpg',
    status: 'Active',
  },
  {
    mls: '67058840',
    address: '2202 Erin Glen Court',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$499,999',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,656',
    acres: '0.338',
    yearBuilt: '1980',
    subdivision: 'Erin Glen Sec 03',
    county: 'Harris',
    remarks: 'Experience more than a new build with this expansi ...',
    photo: '/assets/listings/deer-park/67058840.jpg',
    status: 'Active',
  },
  {
    mls: '9163428',
    address: '2802 White Sands Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$379,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,803',
    acres: '0.132',
    yearBuilt: '2006',
    subdivision: 'East Park Sec 01',
    county: 'Harris',
    remarks: 'Welcome to beautiful 2802 White Sands Dr. Brand ne ...',
    photo: '/assets/listings/deer-park/9163428.jpg',
    status: 'Active',
  },
  {
    mls: '44653412',
    address: '1133 Helen Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$599,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,612',
    acres: '0.944',
    yearBuilt: '1994',
    subdivision: 'Deer Park Outlots',
    county: 'Harris',
    remarks: 'Spread out with almost one acre. One of a kind cus ...',
    photo: '/assets/listings/deer-park/44653412.jpg',
    status: 'Active',
  },
  {
    mls: '94469226',
    address: '1406 New Orleans Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$319,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,150',
    acres: '0.178',
    yearBuilt: '1972',
    subdivision: 'Deer Meadows Sec 01',
    county: 'Harris',
    remarks: 'Charming home featuring a home office, 2 living ar ...',
    photo: '/assets/listings/deer-park/94469226.jpg',
    status: 'Active',
  },
  {
    mls: '39115191',
    address: '1829 N Wildflower Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$568,615',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,209',
    acres: '0.218',
    yearBuilt: '2026',
    subdivision: 'East Meadows Place',
    county: 'Harris',
    remarks: 'Don’t miss out–rare opportunity for new constructi ...',
    photo: '/assets/listings/deer-park/39115191.jpg',
    status: 'Active',
  },
  {
    mls: '8892246',
    address: '3909 Regency Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$264,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,598',
    acres: '0.172',
    yearBuilt: '1988',
    subdivision: 'Regency Park Sec 02',
    county: 'Harris',
    remarks: 'Cute 3/2/2 home located in Regency Park. Living ro ...',
    photo: '/assets/listings/deer-park/8892246.jpg',
    status: 'Active',
  },
  {
    mls: '73345282',
    address: '822 N Kaufman Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$320,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,885',
    acres: '0.193',
    yearBuilt: '1971',
    subdivision: 'Deer Park Gardens Sec 06',
    county: 'Harris',
    remarks: 'Zoned to the highly sought-after Deer Park ISD, th ...',
    photo: '/assets/listings/deer-park/73345282.jpg',
    status: 'Active',
  },
  {
    mls: '47553584',
    address: '2125 Kingsdale Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$215,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,100',
    acres: '0.161',
    yearBuilt: '1953',
    subdivision: 'South Pasadena Plaza',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/deer-park/47553584.jpg',
    status: 'Active',
  },
  {
    mls: '69774442',
    address: '2617 Kingsdale Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$199,900',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,006',
    acres: '0.161',
    yearBuilt: '1955',
    subdivision: 'South Pasadena Plaza',
    county: 'Harris',
    remarks: 'Beautiful 3-bedroom home in the heart of Deer Park ...',
    photo: '/assets/listings/deer-park/69774442.jpg',
    status: 'Active',
  },
  {
    mls: '14837954',
    address: '1818 New Orleans Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$254,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,887',
    acres: '0.178',
    yearBuilt: '1975',
    subdivision: 'Deer Meadows Sec 02',
    county: 'Harris',
    remarks: 'HOME INTERIOR IS BEING PAINTED 8/12-15.Welcome hom ...',
    photo: '/assets/listings/deer-park/14837954.jpg',
    status: 'Active',
  },
  {
    mls: '55757737',
    address: '1822 Georgia Avenue',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$495,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,515',
    acres: '1.591',
    yearBuilt: '1965',
    subdivision: 'Houston Suburban Estates',
    county: 'Harris',
    remarks: 'Land! Land! Land! Lots of beautiful land.This beau ...',
    photo: '/assets/listings/deer-park/55757737.jpg',
    status: 'Active',
  },
  {
    mls: '79220272',
    address: '1218 E Pasadena Boulevard',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$3,250,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,183',
    acres: '13.38',
    yearBuilt: '1966',
    subdivision: 'La Porte Outlots',
    county: 'Harris',
    remarks: 'Nestled in Deer Park, this exceptional 13+ acre pr ...',
    photo: '/assets/listings/deer-park/79220272.jpg',
    status: 'Active',
  },
  {
    mls: '70288490',
    address: '233 E Vaughn Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$394,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '5,186',
    acres: '0.248',
    yearBuilt: '1959',
    subdivision: 'Deer Park Outlots',
    county: 'Harris',
    remarks: 'Multi-Purpose Property Opportunity in Deer Park - ...',
    photo: '/assets/listings/deer-park/70288490.jpg',
    status: 'Active',
  },
  {
    mls: '11649594',
    address: '1118 S Amy Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$359,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,870',
    acres: '0.16',
    yearBuilt: '1973',
    subdivision: 'Deer Park Gardens',
    county: 'Harris',
    remarks: 'Price Improvement!Great opportunity to own a spaci ...',
    photo: '/assets/listings/deer-park/11649594.jpg',
    status: 'Active',
  },
  {
    mls: '15026409',
    address: '1502 Wesley Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$365,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,898',
    acres: '0.231',
    yearBuilt: '1987',
    subdivision: 'Wesley Place',
    county: 'Harris',
    remarks: 'This Story brick home on cul-de-sac street has 5 b ...',
    photo: '/assets/listings/deer-park/15026409.jpg',
    status: 'Active',
  },
  {
    mls: '96557966',
    address: '1222 Elm Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$195,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,025',
    acres: '0.115',
    yearBuilt: '1996',
    subdivision: 'Poye G D Ol 154 Deer Park',
    county: 'Harris',
    remarks: 'Welcome to this meticulously maintained 2-bed, 1-b ...',
    photo: '/assets/listings/deer-park/96557966.jpg',
    status: 'Active',
  },
  {
    mls: '20227925',
    address: '925 N Amy Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$310,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,040',
    acres: '0.264',
    yearBuilt: '1975',
    subdivision: 'Deer Park Gardens Sec 09',
    county: 'Harris',
    remarks: 'Beautiful 2-story single-family home in Deer Park ...',
    photo: '/assets/listings/deer-park/20227925.jpg',
    status: 'Active',
  },
  {
    mls: '80033191',
    address: '1104 E 13th Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$258,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,827',
    acres: '0.152',
    yearBuilt: '1970',
    subdivision: 'Obrien Heights',
    county: 'Harris',
    remarks: 'Back on the market after financial issue. Buyers ...',
    photo: '/assets/listings/deer-park/80033191.jpg',
    status: 'Active',
  },
  {
    mls: '60140865',
    address: '3226 Bayou Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$297,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,756',
    acres: '0.193',
    yearBuilt: '1974',
    subdivision: 'Willow Spgs R/P',
    county: 'Harris',
    remarks: 'Home Sweet Home! Prime location in the middle of D ...',
    photo: '/assets/listings/deer-park/60140865.jpg',
    status: 'Active',
  },
  {
    mls: '50231676',
    address: '4411 Graceland Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$404,990',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,235',
    acres: '0.132',
    yearBuilt: '2012',
    subdivision: 'Enclave/East Mdw Sec 1',
    county: 'Harris',
    remarks: 'This big beauty is close to it all! Schools, dinin ...',
    photo: '/assets/listings/deer-park/50231676.jpg',
    status: 'Active',
  },
  {
    mls: '79560573',
    address: '905 Patricia Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$310,987',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,220',
    acres: '0.172',
    yearBuilt: '1974',
    subdivision: 'Parkglen 2 Deer Park',
    county: 'Harris',
    remarks: 'Just in time for some Summer fun in your own back ...',
    photo: '/assets/listings/deer-park/79560573.jpg',
    status: 'Active',
  },
  {
    mls: '96369847',
    address: '213 Linda Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$229,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,386',
    acres: '0.145',
    yearBuilt: '1955',
    subdivision: 'Deer Park Terrace',
    county: 'Harris',
    remarks: 'Step into this charming 4 bedroom, 2 bathroom home ...',
    photo: '/assets/listings/deer-park/96369847.jpg',
    status: 'Active',
  },
  {
    mls: '36915543',
    address: '822 Harvard Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$194,999',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '987',
    acres: '0.145',
    yearBuilt: '1962',
    subdivision: 'Deer Park',
    county: 'Harris',
    remarks: 'MANY UPDATES! 822 Harvard St is a fantastic proper ...',
    photo: '/assets/listings/deer-park/36915543.jpg',
    status: 'Active',
  },
]
