// La Porte homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const laporteListings: Listing[] = [
  {
    mls: '35966427',
    address: '2110 Parkview Ln',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$80,000',
    beds: '0 Bedrooms',
    baths: 'Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '',
    subdivision: 'Bay Front Add To La Porte',
    county: 'Harris',
    remarks: 'Exceptional opportunity to own three adjoining rea ...',
    photo: '/assets/listings/la-porte/35966427.jpg',
    status: 'Active',
  },
  {
    mls: '26141550',
    address: '408 Bay Oaks Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$99,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '844',
    acres: '0.218',
    yearBuilt: '1950',
    subdivision: 'Bay Oaks',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/la-porte/26141550.jpg',
    status: 'Active',
  },
  {
    mls: '30432936',
    address: '3114 Falk Court 3114',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$99,339',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,007',
    acres: '1.463',
    yearBuilt: '1965',
    subdivision: 'Township Townhome Condo',
    county: 'Harris',
    remarks: 'NICE LA PORTE CONDO! Explore the potential of this ...',
    photo: '/assets/listings/la-porte/30432936.jpg',
    status: 'Active',
  },
  {
    mls: '14775727',
    address: '802 S Virginia Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$124,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,498',
    acres: '0.215',
    yearBuilt: '1948',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Beautiful Interior, Spacious Corner Lot, and Excel ...',
    photo: '/assets/listings/la-porte/14775727.jpg',
    status: 'Active',
  },
  {
    mls: '39315070',
    address: '135 Pine Bluff Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$132,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '884',
    acres: '0.126',
    yearBuilt: '1945',
    subdivision: 'Pine Bluff',
    county: 'Harris',
    remarks: 'Welcome to this beautiful cozy home located close ...',
    photo: '/assets/listings/la-porte/39315070.jpg',
    status: 'Active',
  },
  {
    mls: '83357819',
    address: '1519 S 8th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$155,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,220',
    acres: '0.039',
    yearBuilt: '1973',
    subdivision: 'Garden Walk T/H Sec 01',
    county: 'Harris',
    remarks: 'End unit, at the end of the cul de sac, 2 story, 3 ...',
    photo: '/assets/listings/la-porte/83357819.jpg',
    status: 'Active',
  },
  {
    mls: '58175207',
    address: '1513 Cedar Cove Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$159,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,408',
    acres: '0.04',
    yearBuilt: '1973',
    subdivision: 'Garden Walk Twnhm Sec 01',
    county: 'Harris',
    remarks: 'Recently renovated 2 story townhome in the desirab ...',
    photo: '/assets/listings/la-porte/58175207.jpg',
    status: 'Active',
  },
  {
    mls: '61806467',
    address: '1516 S 8th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$159,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,408',
    acres: '0.04',
    yearBuilt: '1973',
    subdivision: 'Garden Walk T/H Sec 01',
    county: 'Harris',
    remarks: 'Introducing a charming three bedroom, 2 and 1/2 ba ...',
    photo: '/assets/listings/la-porte/61806467.jpg',
    status: 'Active',
  },
  {
    mls: '76045020',
    address: '406 San Jacinto Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$164,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,420',
    acres: '0.215',
    yearBuilt: '1943',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Charming home in the heart of La Porte featuring a ...',
    photo: '/assets/listings/la-porte/76045020.jpg',
    status: 'Active',
  },
  {
    mls: '4479893',
    address: '9326 Montgomery Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$165,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,058',
    acres: '0.229',
    yearBuilt: '1992',
    subdivision: 'Spenwick Place Sec 01',
    county: 'Harris',
    remarks: 'Whether you’re looking for your first home or your ...',
    photo: '/assets/listings/la-porte/4479893.jpg',
    status: 'Active',
  },
  {
    mls: '5289613',
    address: '3911 Dolphin Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$170,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,903',
    acres: '0.188',
    yearBuilt: '1964',
    subdivision: 'Bay Colony',
    county: 'Harris',
    remarks: 'This 4-bedroom, 2-bath home in La Porte, TX is bei ...',
    photo: '/assets/listings/la-porte/5289613.jpg',
    status: 'Active',
  },
  {
    mls: '33298779',
    address: '3122 Hamilton Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$175,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,032',
    acres: '0.459',
    yearBuilt: '1945',
    subdivision: 'Bayside Terrace',
    county: 'Harris',
    remarks: 'GREAT OPPORTUNITY FOR A BUILDER/FLIPPE ...',
    photo: '/assets/listings/la-porte/33298779.jpg',
    status: 'Active',
  },
  {
    mls: '24886201',
    address: '601 N 12th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$179,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '975',
    acres: '0.144',
    yearBuilt: '1978',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'BRICK HOME IN LA PORTE! This beautiful brick home ...',
    photo: '/assets/listings/la-porte/24886201.jpg',
    status: 'Active',
  },
  {
    mls: '65831397',
    address: '3802 Dolphin Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$180,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,638',
    acres: '0.223',
    yearBuilt: '1962',
    subdivision: 'Bay Colony',
    county: 'Harris',
    remarks: 'MASSIVE PRICE DROP! NEW PRICE — DON’T MIS ...',
    photo: '/assets/listings/la-porte/65831397.jpg',
    status: 'Active',
  },
  {
    mls: '77899250',
    address: '730 S Holmes Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$180,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,818',
    acres: '0.258',
    yearBuilt: '1955',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Spacious Home with Galveston Bay Views & Tons of P ...',
    photo: '/assets/listings/la-porte/77899250.jpg',
    status: 'Active',
  },
  {
    mls: '51883134',
    address: '8405 Bandridge Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$185,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,316',
    acres: '0.157',
    yearBuilt: '1975',
    subdivision: 'Brookglen Sec 02 R/P',
    county: 'Harris',
    remarks: 'Investor special in La Porte! This 3 bedroom, 2 ba ...',
    photo: '/assets/listings/la-porte/51883134.jpg',
    status: 'Active',
  },
  {
    mls: '67596678',
    address: '210 S 6th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$189,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,891',
    acres: '0.144',
    yearBuilt: '1935',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'This gorgeous gem with 3 bedrooms and 1 full bath ...',
    photo: '/assets/listings/la-porte/67596678.jpg',
    status: 'Active',
  },
  {
    mls: '80717543',
    address: '317 San Jacinto Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$189,385',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,076',
    acres: '0.144',
    yearBuilt: '1948',
    subdivision: 'San Jacinto Homes',
    county: 'Harris',
    remarks: 'Located just minutes from the beach, this beautifu ...',
    photo: '/assets/listings/la-porte/80717543.jpg',
    status: 'Active',
  },
  {
    mls: '4657732',
    address: '506 S Iowa Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$189,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '988',
    acres: '0.166',
    yearBuilt: '1952',
    subdivision: 'San Jacinto Homes',
    county: 'Harris',
    remarks: 'Welcome to this beautifully remodeled 3 bedroom, 2 ...',
    photo: '/assets/listings/la-porte/4657732.jpg',
    status: 'Active',
  },
  {
    mls: '19616261',
    address: '332 N 7th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$196,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,150',
    acres: '0.169',
    yearBuilt: '1962',
    subdivision: 'Town/La Porte',
    county: 'Harris',
    remarks: 'Welcome to 332 N 7th Street, La Porte, Texas, wher ...',
    photo: '/assets/listings/la-porte/19616261.jpg',
    status: 'Active',
  },
  {
    mls: '25473290',
    address: '322 S Carroll',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$199,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,215',
    acres: '0.144',
    yearBuilt: '1971',
    subdivision: 'Bayfront To Laporte',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/la-porte/25473290.jpg',
    status: 'Active',
  },
  {
    mls: '59369769',
    address: '1004 S 2nd Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$199,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,547',
    acres: '0.164',
    yearBuilt: '1950',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'This beautifully remodeled home feels fresh, welco ...',
    photo: '/assets/listings/la-porte/59369769.jpg',
    status: 'Active',
  },
  {
    mls: '37203862',
    address: '114 N Holmes Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$199,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,378',
    acres: '0.215',
    yearBuilt: '1959',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Opportunity, space, and value in the heart of La P ...',
    photo: '/assets/listings/la-porte/37203862.jpg',
    status: 'Active',
  },
  {
    mls: '82502965',
    address: '622 N 13th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$199,998',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '975',
    acres: '0.144',
    yearBuilt: '1978',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: '\\\\"PRICE TO SELL\\\\" Welcome home to La Porte living! T ...',
    photo: '/assets/listings/la-porte/82502965.jpg',
    status: 'Active',
  },
  {
    mls: '50422280',
    address: '10102 Park Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$205,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,421',
    acres: '0.18',
    yearBuilt: '1981',
    subdivision: 'Fairmont Park West Sec 05',
    county: 'Harris',
    remarks: 'COZY 3-bedroom, 2-bathroom with two car garage ho ...',
    photo: '/assets/listings/la-porte/50422280.jpg',
    status: 'Active',
  },
  {
    mls: '21529891',
    address: '3919 Sunrise Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$209,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,448',
    acres: '0.031',
    yearBuilt: '1986',
    subdivision: 'Sunrise T/H',
    county: 'Harris',
    remarks: 'Extensively updated & meticulously maintained 3-be ...',
    photo: '/assets/listings/la-porte/21529891.jpg',
    status: 'Active',
  },
  {
    mls: '29832862',
    address: '213 N 2nd Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$210,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '900',
    acres: '0.144',
    yearBuilt: '2018',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Great Opportunity in La Porte! This charming 2 Bed ...',
    photo: '/assets/listings/la-porte/29832862.jpg',
    status: 'Active',
  },
  {
    mls: '97638131',
    address: '1414 Cypress Cove Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$217,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,391',
    acres: '0.04',
    yearBuilt: '1997',
    subdivision: 'Garden Walk T/H Sec 01',
    county: 'Harris',
    remarks: 'Come see this picture perfect townhome with lots o ...',
    photo: '/assets/listings/la-porte/97638131.jpg',
    status: 'Active',
  },
  {
    mls: '21638848',
    address: '10127 Quiet Hill Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$219,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,391',
    acres: '0.152',
    yearBuilt: '1977',
    subdivision: 'Fairmont Park West',
    county: 'Harris',
    remarks: 'Situated in the established Fairmont Park West nei ...',
    photo: '/assets/listings/la-porte/21638848.jpg',
    status: 'Active',
  },
  {
    mls: '39728566',
    address: '119 S Carroll Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$220,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,188',
    acres: '0.144',
    yearBuilt: '1967',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Home was taken down to the studs and rebuilt. It i ...',
    photo: '/assets/listings/la-porte/39728566.jpg',
    status: 'Active',
  },
  {
    mls: '16459399',
    address: '3307 Fern Rock Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$223,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,209',
    acres: '0.169',
    yearBuilt: '1975',
    subdivision: 'Brookglen Sec 01 R/P',
    county: 'Harris',
    remarks: 'Welcome to this charming 4 bedroom, 2 bath home in ...',
    photo: '/assets/listings/la-porte/16459399.jpg',
    status: 'Active',
  },
  {
    mls: '94013759',
    address: '702 S 2nd Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$225,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,210',
    acres: '0.215',
    yearBuilt: '1967',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Discover the charm of coastal living in this invit ...',
    photo: '/assets/listings/la-porte/94013759.jpg',
    status: 'Active',
  },
  {
    mls: '66143994',
    address: '306 S Virginia Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$227,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,148',
    acres: '0.215',
    yearBuilt: '1925',
    subdivision: 'San Jacinto Homes',
    county: 'Harris',
    remarks: 'Completely updated 4BD/3BA home located in a charm ...',
    photo: '/assets/listings/la-porte/66143994.jpg',
    status: 'Active',
  },
  {
    mls: '18563470',
    address: '814 Oak Leaf Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$235,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,495',
    acres: '0.287',
    yearBuilt: '1965',
    subdivision: 'Shady River Sec 02',
    county: 'Harris',
    remarks: 'Priced below market value! Spacious 4-bedroom home ...',
    photo: '/assets/listings/la-porte/18563470.jpg',
    status: 'Active',
  },
  {
    mls: '70851009',
    address: '425 S Brownell Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$235,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,180',
    acres: '0.144',
    yearBuilt: '1979',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Looking for room to spread out in a great location ...',
    photo: '/assets/listings/la-porte/70851009.jpg',
    status: 'Active',
  },
  {
    mls: '34291727',
    address: '408 S 4th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$235,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,411',
    acres: '0.143',
    yearBuilt: '1900',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: '408 S 4th St is a charming, thoughtfully updated 3 ...',
    photo: '/assets/listings/la-porte/34291727.jpg',
    status: 'Active',
  },
  {
    mls: '5522655',
    address: '4905 Glenview Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$236,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,162',
    acres: '0.153',
    yearBuilt: '1993',
    subdivision: 'Glen Meadows Sec 04a',
    county: 'Harris',
    remarks: 'This expansive single-family residence boasts an i ...',
    photo: '/assets/listings/la-porte/5522655.jpg',
    status: 'Active',
  },
  {
    mls: '87737386',
    address: '1917 Coupland Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$239,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,460',
    acres: '0.209',
    yearBuilt: '1977',
    subdivision: 'Diamond C',
    county: 'Harris',
    remarks: 'This 3-bedroom, 2-bathroom single-story home offer ...',
    photo: '/assets/listings/la-porte/87737386.jpg',
    status: 'Active',
  },
  {
    mls: '90388150',
    address: '319 S 6th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$244,999',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,812',
    acres: '0.144',
    yearBuilt: '1950',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Picture morning coffee in a kitchen finished with ...',
    photo: '/assets/listings/la-porte/90388150.jpg',
    status: 'Active',
  },
  {
    mls: '75252536',
    address: '11734 Alamo Dr',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$245,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,408',
    acres: '0.163',
    yearBuilt: '1991',
    subdivision: 'Monument Estates Sec 01',
    county: 'Harris',
    remarks: 'Move-in ready and packed with updates! This 3-bedr ...',
    photo: '/assets/listings/la-porte/75252536.jpg',
    status: 'Active',
  },
  {
    mls: '65103864',
    address: '9811 Rocky Hollow Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$246,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,643',
    acres: '0.152',
    yearBuilt: '1980',
    subdivision: 'Fairmont Park West Sec 04',
    county: 'Harris',
    remarks: 'Welcome to 9811 Rocky Hollow Road, a well-designed ...',
    photo: '/assets/listings/la-porte/65103864.jpg',
    status: 'Active',
  },
  {
    mls: '53520189',
    address: '9910 Stonemont Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,392',
    acres: '0.163',
    yearBuilt: '1977',
    subdivision: 'Fairmont Park West Sec 01 Pt',
    county: 'Harris',
    remarks: 'Welcome to this charming 3 bedroom, 2 bath home. L ...',
    photo: '/assets/listings/la-porte/53520189.jpg',
    status: 'Active',
  },
  {
    mls: '41780851',
    address: '9909 Cardinal Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,524',
    acres: '0.142',
    yearBuilt: '1977',
    subdivision: 'M Eadowcrest',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/la-porte/41780851.jpg',
    status: 'Active',
  },
  {
    mls: '45872501',
    address: '1227 Mission Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,274',
    acres: '0.163',
    yearBuilt: '1979',
    subdivision: 'Monument Est Final Plat',
    county: 'Harris',
    remarks: 'FOR SALE OR LEASE. Highly sought after Lomax area! ...',
    photo: '/assets/listings/la-porte/45872501.jpg',
    status: 'Active',
  },
  {
    mls: '13765554',
    address: '3802 Barracuda Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,968',
    acres: '0.135',
    yearBuilt: '2004',
    subdivision: 'Bay Colony',
    county: 'Harris',
    remarks: 'Move-in ready 3-bedroom, 2.5-bath home for sale ne ...',
    photo: '/assets/listings/la-porte/13765554.jpg',
    status: 'Active',
  },
  {
    mls: '62182776',
    address: '10318 Belfast Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,412',
    acres: '0.241',
    yearBuilt: '1962',
    subdivision: 'Fairmont Park',
    county: 'Harris',
    remarks: 'Welcome to 10318 Belfast — a beautifully updated h ...',
    photo: '/assets/listings/la-porte/62182776.jpg',
    status: 'Active',
  },
  {
    mls: '58475912',
    address: '530 N 4th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,590',
    acres: '0.072',
    yearBuilt: '2026',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'New Construction in the Heart of La Porte! Welcome ...',
    photo: '/assets/listings/la-porte/58475912.jpg',
    status: 'Active',
  },
  {
    mls: '70131723',
    address: '501 S Holmes Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$249,999',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,364',
    acres: '0.287',
    yearBuilt: '1978',
    subdivision: 'Bay Front Laporte',
    county: 'Harris',
    remarks: 'JUST LISTED! Welcome to 501 S Holmes St., a charmi ...',
    photo: '/assets/listings/la-porte/70131723.jpg',
    status: 'Active',
  },
  {
    mls: '43273201',
    address: '4918 Valley View Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$250,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,183',
    acres: '0.169',
    yearBuilt: '1981',
    subdivision: 'Glen Meadows Sec 02',
    county: 'Harris',
    remarks: 'Discover this beautifully updated 3-bedroom, 2-bat ...',
    photo: '/assets/listings/la-porte/43273201.jpg',
    status: 'Active',
  },
  {
    mls: '49102391',
    address: '3812 Redbud Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$250,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,678',
    acres: '0.152',
    yearBuilt: '1985',
    subdivision: 'Fairmont Park East Sec 01',
    county: 'Harris',
    remarks: 'The beautiful two-story home is ready for move-in. ...',
    photo: '/assets/listings/la-porte/49102391.jpg',
    status: 'Active',
  },
  {
    mls: '10462364',
    address: '134 Bay Shore Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$252,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,654',
    acres: '0.23',
    yearBuilt: '2006',
    subdivision: 'Pine Bluff',
    county: 'Harris',
    remarks: 'Welcome to 134 Bay Shore Avenue. This charming 3 ...',
    photo: '/assets/listings/la-porte/10462364.jpg',
    status: 'Active',
  },
  {
    mls: '67627379',
    address: '3827 Pecan Circle',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$255,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,861',
    acres: '0.152',
    yearBuilt: '1982',
    subdivision: 'Fairmont Park East Sec 01',
    county: 'Harris',
    remarks: 'Beautiful home in La Porte, located in the quiet a ...',
    photo: '/assets/listings/la-porte/67627379.jpg',
    status: 'Active',
  },
  {
    mls: '88016516',
    address: '1376 Mixander Way',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$256,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,630',
    acres: '0.07',
    yearBuilt: '',
    subdivision: 'Sylvan Beach Enclave Ph 2',
    county: 'Harris',
    remarks: 'FRONT YARD MAINTENANCE IS INCLUDED BY T ...',
    photo: '/assets/listings/la-porte/88016516.jpg',
    status: 'Active',
  },
  {
    mls: '78712561',
    address: '10406 Rocky Hollow Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$258,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,565',
    acres: '0.215',
    yearBuilt: '1977',
    subdivision: 'Fairmont Park Sec 02 R/P',
    county: 'Harris',
    remarks: 'Welcome! This is a charming 3 bedroom, 2 full bath ...',
    photo: '/assets/listings/la-porte/78712561.jpg',
    status: 'Active',
  },
  {
    mls: '97117888',
    address: '306 Oakhurst Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$259,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,087',
    acres: '1.053',
    yearBuilt: '1963',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Welcome to 306 Oakhurst Street, a charming 3-bedro ...',
    photo: '/assets/listings/la-porte/97117888.jpg',
    status: 'Active',
  },
  {
    mls: '48997533',
    address: '9815 Rocky Hollow Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$259,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,454',
    acres: '0.152',
    yearBuilt: '1980',
    subdivision: 'Fairmont Park West Sec 04',
    county: 'Harris',
    remarks: 'Welcome to this charming 3-bedroom, 2-bath home in ...',
    photo: '/assets/listings/la-porte/48997533.jpg',
    status: 'Active',
  },
  {
    mls: '70882487',
    address: '303 Cypress Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$260,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,400',
    acres: '0.15',
    yearBuilt: '1992',
    subdivision: 'Bayou Glen',
    county: 'Harris',
    remarks: '*BANK APPROVED PRICE* Welcome home to this 4-bedro ...',
    photo: '/assets/listings/la-porte/70882487.jpg',
    status: 'Active',
  },
  {
    mls: '24040274',
    address: '116 S 3rd Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$260,922',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,666',
    acres: '0.072',
    yearBuilt: '2025',
    subdivision: 'La Porte/Shoreacres',
    county: 'Harris',
    remarks: 'Come see this beautiful new home you won’t want to ...',
    photo: '/assets/listings/la-porte/24040274.jpg',
    status: 'Active',
  },
  {
    mls: '48486230',
    address: '10406 Winding Trail Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$265,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,596',
    acres: '0.208',
    yearBuilt: '1962',
    subdivision: 'Fairmont Park Sec 02',
    county: 'Harris',
    remarks: 'Step inside this beautifully renovated home locate ...',
    photo: '/assets/listings/la-porte/48486230.jpg',
    status: 'Active',
  },
  {
    mls: '98379670',
    address: '2601 S Broadway Street 9',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$265,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,403',
    acres: '0.093',
    yearBuilt: '1997',
    subdivision: 'Woods On The Bay',
    county: 'Harris',
    remarks: 'Absolutely stunning remodeled and turnkey ready Pe ...',
    photo: '/assets/listings/la-porte/98379670.jpg',
    status: 'Active',
  },
  {
    mls: '54634263',
    address: '10102 Barmont Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$269,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,864',
    acres: '0.192',
    yearBuilt: '1978',
    subdivision: 'Fairmont Park West Sec 02',
    county: 'Harris',
    remarks: 'Welcome to this charming home in a quiet neighborh ...',
    photo: '/assets/listings/la-porte/54634263.jpg',
    status: 'Active',
  },
  {
    mls: '90339853',
    address: '1369 Mixander Way',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$269,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,967',
    acres: '0.069',
    yearBuilt: '',
    subdivision: 'Sylvan Beach Enclave Ph 2',
    county: 'Harris',
    remarks: 'Beautiful 4-bedroom, 2.5-bath single-family attach ...',
    photo: '/assets/listings/la-porte/90339853.jpg',
    status: 'Active',
  },
  {
    mls: '92278048',
    address: '1367 Mixander Way',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$269,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,964',
    acres: '0.069',
    yearBuilt: '',
    subdivision: 'Sylvan Beach Enclave Ph 2',
    county: 'Harris',
    remarks: 'Beautiful 4-bedroom, 2.5-bath single-family attach ...',
    photo: '/assets/listings/la-porte/92278048.jpg',
    status: 'Active',
  },
  {
    mls: '57511110',
    address: '10921 Pecan Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$274,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,605',
    acres: '0.158',
    yearBuilt: '1983',
    subdivision: 'Fairmont Park East',
    county: 'Harris',
    remarks: 'Welcome to this lovely single-story home located i ...',
    photo: '/assets/listings/la-porte/57511110.jpg',
    status: 'Active',
  },
  {
    mls: '87374474',
    address: '313 S Carroll Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$274,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,563',
    acres: '0.144',
    yearBuilt: '1971',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Skip the traditional bank and discover a flexible ...',
    photo: '/assets/listings/la-porte/87374474.jpg',
    status: 'Active',
  },
  {
    mls: '38311190',
    address: '8407 Bandridge Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$275,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,148',
    acres: '0.157',
    yearBuilt: '1975',
    subdivision: 'Brookglen',
    county: 'Harris',
    remarks: 'Discover the flexibility this spacious 4-bedroom, ...',
    photo: '/assets/listings/la-porte/38311190.jpg',
    status: 'Active',
  },
  {
    mls: '73864230',
    address: '606 Meadowlawn Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$279,999',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,964',
    acres: '0.298',
    yearBuilt: '1958',
    subdivision: 'Shores Acres',
    county: 'Harris',
    remarks: 'Possible income producing property or Home!!! Expe ...',
    photo: '/assets/listings/la-porte/73864230.jpg',
    status: 'Active',
  },
  {
    mls: '97195439',
    address: '10915 Pecan Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$280,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,628',
    acres: '0.158',
    yearBuilt: '1983',
    subdivision: 'Fairmont Park East',
    county: 'Harris',
    remarks: 'This charming home boasts numerous updates through ...',
    photo: '/assets/listings/la-porte/97195439.jpg',
    status: 'Active',
  },
  {
    mls: '74759359',
    address: '5225 Creekview Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$285,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,342',
    acres: '0.224',
    yearBuilt: '1977',
    subdivision: 'Glen Meadows Sec 01',
    county: 'Harris',
    remarks: 'Located in La Porte, this charming single story ho ...',
    photo: '/assets/listings/la-porte/74759359.jpg',
    status: 'Active',
  },
  {
    mls: '43648214',
    address: '1106 S 8th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$285,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,818',
    acres: '0.215',
    yearBuilt: '1940',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Completely renovated and move-in ready! This beaut ...',
    photo: '/assets/listings/la-porte/43648214.jpg',
    status: 'Active',
  },
  {
    mls: '28499816',
    address: '3314 Ashton Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$289,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,435',
    acres: '0.161',
    yearBuilt: '1973',
    subdivision: 'Brookglen Sec 02 R/P',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/la-porte/28499816.jpg',
    status: 'Active',
  },
  {
    mls: '61891676',
    address: '501 Valley Brook Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$290,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,146',
    acres: '0.189',
    yearBuilt: '1979',
    subdivision: 'Glen Meadows Sec 01',
    county: 'Harris',
    remarks: 'All New 3 bedroom possible 4 bedroom /study/extra ...',
    photo: '/assets/listings/la-porte/61891676.jpg',
    status: 'Active',
  },
  {
    mls: '65287685',
    address: '226 S Y Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$290,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,550',
    acres: '0.092',
    yearBuilt: '2025',
    subdivision: 'Oakhurst',
    county: 'Harris',
    remarks: 'Welcome home! This beautiful new construction home ...',
    photo: '/assets/listings/la-porte/65287685.jpg',
    status: 'Active',
  },
  {
    mls: '46532140',
    address: '106 Bogey Circle',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$294,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,840',
    acres: '0.154',
    yearBuilt: '2014',
    subdivision: 'Lakes/Fairmont Greens Sec 1',
    county: 'Harris',
    remarks: 'Wonderful 3 bedroom 2 bath DR Horton home. Being o ...',
    photo: '/assets/listings/la-porte/46532140.jpg',
    status: 'Active',
  },
  {
    mls: '74463751',
    address: '5013 Parkcrest Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$295,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,838',
    acres: '0.143',
    yearBuilt: '1992',
    subdivision: 'Glen Meadows Sec 04a',
    county: 'Harris',
    remarks: 'Welcome to the charming 5013 Parkcrest, a delightf ...',
    photo: '/assets/listings/la-porte/74463751.jpg',
    status: 'Active',
  },
  {
    mls: '81805813',
    address: '10340 Rocky Hollow Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$295,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,992',
    acres: '0.249',
    yearBuilt: '1978',
    subdivision: 'Fairmont Park Sec 02 R/P',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated home in Fairmo ...',
    photo: '/assets/listings/la-porte/81805813.jpg',
    status: 'Active',
  },
  {
    mls: '20235010',
    address: '526 N 2nd Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$299,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,848',
    acres: '0.144',
    yearBuilt: '2019',
    subdivision: 'Town/La Porte',
    county: 'Harris',
    remarks: 'Welcome to La Porte living in the heart of Old La ...',
    photo: '/assets/listings/la-porte/20235010.jpg',
    status: 'Active',
  },
  {
    mls: '92385632',
    address: '10842 Mesquite Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$299,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,132',
    acres: '0.158',
    yearBuilt: '1984',
    subdivision: 'Fairmont Park East Sec 2',
    county: 'Harris',
    remarks: '10842 Mesquite Dr is a nicely updated two story ho ...',
    photo: '/assets/listings/la-porte/92385632.jpg',
    status: 'Active',
  },
  {
    mls: '7476045',
    address: '10407 Winding Trail Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$299,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,385',
    acres: '0.222',
    yearBuilt: '1962',
    subdivision: 'Fairmont Park Sec 02',
    county: 'Harris',
    remarks: 'Welcome to this beautifully maintained 3-bed, 2-ba ...',
    photo: '/assets/listings/la-porte/7476045.jpg',
    status: 'Active',
  },
  {
    mls: '18344855',
    address: '370 Weimer Lagoon Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$304,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,566',
    acres: '0.162',
    yearBuilt: '2021',
    subdivision: 'Morgans Lndg Sec 6',
    county: 'Harris',
    remarks: 'This charming home in Morgan’s Landing offers the ...',
    photo: '/assets/listings/la-porte/18344855.jpg',
    status: 'Active',
  },
  {
    mls: '18153727',
    address: '713 Sugar Hill Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$305,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,136',
    acres: '0.149',
    yearBuilt: '1980',
    subdivision: 'Creekmont Sec 01',
    county: 'Harris',
    remarks: 'Nestled in a charming neighborhood, this lovely ho ...',
    photo: '/assets/listings/la-porte/18153727.jpg',
    status: 'Active',
  },
  {
    mls: '26324142',
    address: '526 Heron Bay Circle',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$305,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,514',
    acres: '0.196',
    yearBuilt: '2019',
    subdivision: 'Morgans Lndg Sec 5',
    county: 'Harris',
    remarks: '',
    photo: '/assets/listings/la-porte/26324142.jpg',
    status: 'Active',
  },
  {
    mls: '64705919',
    address: '204 King William Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$310,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,341',
    acres: '0.147',
    yearBuilt: '2006',
    subdivision: 'Fairmont Park East Sec 11',
    county: 'Harris',
    remarks: 'This spacious 3,341-square-foot traditional home f ...',
    photo: '/assets/listings/la-porte/64705919.jpg',
    status: 'Active',
  },
  {
    mls: '59715146',
    address: '635 Meadowlawn St',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$314,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,837',
    acres: '0.269',
    yearBuilt: '1964',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: 'Welcome to this beautiful 4-bedroom, 2-bath single ...',
    photo: '/assets/listings/la-porte/59715146.jpg',
    status: 'Active',
  },
  {
    mls: '6146700',
    address: '502 S Carroll Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$315,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,669',
    acres: '0.144',
    yearBuilt: '2023',
    subdivision: 'Bayfront Add/Laporte',
    county: 'Harris',
    remarks: 'Like new and move-in ready! Tucked away on a quiet ...',
    photo: '/assets/listings/la-porte/6146700.jpg',
    status: 'Active',
  },
  {
    mls: '28808980',
    address: '424 S Holmes Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$319,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,519',
    acres: '0.144',
    yearBuilt: '2017',
    subdivision: 'Bay Front Add',
    county: 'Harris',
    remarks: 'Beautifully renovated and move-in ready, this uniq ...',
    photo: '/assets/listings/la-porte/28808980.jpg',
    status: 'Active',
  },
  {
    mls: '42353256',
    address: '615 S 7th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$319,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,995',
    acres: '0.359',
    yearBuilt: '1978',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Beautifully renovated 4-bedroom, 2-bath home on an ...',
    photo: '/assets/listings/la-porte/42353256.jpg',
    status: 'Active',
  },
  {
    mls: '2357940',
    address: '5034 Glenview Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$319,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,942',
    acres: '0.155',
    yearBuilt: '1993',
    subdivision: 'Glen Meadows Sec 04a',
    county: 'Harris',
    remarks: 'Welcome to this charming 3-bedroom, 2-bath home lo ...',
    photo: '/assets/listings/la-porte/2357940.jpg',
    status: 'Active',
  },
  {
    mls: '26032245',
    address: '507 Shore Acres Boulevard',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$325,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,720',
    acres: '0.522',
    yearBuilt: '2005',
    subdivision: 'Shoreacres',
    county: 'Harris',
    remarks: '507 Shore Acres Blvd offers 3 bedrooms, 2 baths an ...',
    photo: '/assets/listings/la-porte/26032245.jpg',
    status: 'Active',
  },
  {
    mls: '55259865',
    address: '10006 King William Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$328,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,872',
    acres: '0.168',
    yearBuilt: '2005',
    subdivision: 'Fairmont Park East Sec 11',
    county: 'Harris',
    remarks: 'Immaculately maintained and move-in ready! From th ...',
    photo: '/assets/listings/la-porte/55259865.jpg',
    status: 'Active',
  },
  {
    mls: '4910992',
    address: '10943 Spruce Drive N',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$329,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,038',
    acres: '0.16',
    yearBuilt: '1999',
    subdivision: 'Fairmont Park E Sec 4 Ph 4a',
    county: 'Harris',
    remarks: 'Welcome Home to 10943 Spruce Dr. N. in highly desi ...',
    photo: '/assets/listings/la-porte/4910992.jpg',
    status: 'Active',
  },
  {
    mls: '60887859',
    address: '3522 Brookwood Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$330,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,211',
    acres: '0.231',
    yearBuilt: '1995',
    subdivision: 'Brookglen',
    county: 'Harris',
    remarks: 'Well-maintained home featuring 4 bedrooms and 2.5 ...',
    photo: '/assets/listings/la-porte/60887859.jpg',
    status: 'Active',
  },
  {
    mls: '2953525',
    address: '9221 Desirable Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$333,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,992',
    acres: '0.252',
    yearBuilt: '1998',
    subdivision: 'Pecan Crossing Sec 02',
    county: 'Harris',
    remarks: 'Well maintained 1998 built home that is truly move ...',
    photo: '/assets/listings/la-porte/2953525.jpg',
    status: 'Active',
  },
  {
    mls: '34127476',
    address: '212 S Lobit Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$334,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,094',
    acres: '0.144',
    yearBuilt: '2022',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Built in 2022, this modern two-story home in La Po ...',
    photo: '/assets/listings/la-porte/34127476.jpg',
    status: 'Active',
  },
  {
    mls: '96350624',
    address: '1111 San Jacinto Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$335,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,306',
    acres: '0.055',
    yearBuilt: '2021',
    subdivision: 'Beach Park',
    county: 'Harris',
    remarks: 'Turnkey, fully furnished, and currently operating ...',
    photo: '/assets/listings/la-porte/96350624.jpg',
    status: 'Active',
  },
  {
    mls: '38026236',
    address: '3536 Bayou Forest Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$335,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,921',
    acres: '0.223',
    yearBuilt: '2005',
    subdivision: 'Bayou Oaks Sec 2',
    county: 'Harris',
    remarks: 'Immaculately maintained and the most perfect locat ...',
    photo: '/assets/listings/la-porte/38026236.jpg',
    status: 'Active',
  },
  {
    mls: '73825343',
    address: '114 Dwire Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$339,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,648',
    acres: '0.11',
    yearBuilt: '2026',
    subdivision: 'Bay Oaks',
    county: 'Harris',
    remarks: 'Experience elevated coastal living in this beautif ...',
    photo: '/assets/listings/la-porte/73825343.jpg',
    status: 'Active',
  },
  {
    mls: '96813087',
    address: '5202 Valley View Dr Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$339,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,230',
    acres: '0.177',
    yearBuilt: '1993',
    subdivision: 'Glen Meadows Sec 01',
    county: 'Harris',
    remarks: 'Welcome home to 5202 Valley View Drive! This well ...',
    photo: '/assets/listings/la-porte/96813087.jpg',
    status: 'Active',
  },
  {
    mls: '73701485',
    address: '2601 S Broadway Street 71',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$339,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,179',
    acres: '0.107',
    yearBuilt: '1998',
    subdivision: 'Woods On Bay T/H Sec 02 R/P',
    county: 'Harris',
    remarks: 'THIS HOME IS FULL OF QUALITY AND UPGRA ...',
    photo: '/assets/listings/la-porte/73701485.jpg',
    status: 'Active',
  },
  {
    mls: '45867875',
    address: '828 S 1st Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$339,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,807',
    acres: '0.144',
    yearBuilt: '2020',
    subdivision: 'Town/La Porte',
    county: 'Harris',
    remarks: 'Welcome home! Built in 2020, this beautifully main ...',
    photo: '/assets/listings/la-porte/45867875.jpg',
    status: 'Active',
  },
]
