// Kemah homes for sale — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const kemahListings: Listing[] = [
  {
    mls: '17473083',
    address: '1821 E Winn Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$200,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '900',
    acres: '0.125',
    yearBuilt: '1971',
    subdivision: 'Glen Cove Add',
    county: 'Galveston',
    remarks: 'Come enjoy easy living in this quiet waterfront co ...',
    photo: '/assets/listings/kemah/17473083.jpg',
    status: 'Active',
  },
  {
    mls: '72756228',
    address: '1215 Esther Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$230,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,346',
    acres: '0.176',
    yearBuilt: '1965',
    subdivision: 'Laguna Vista Estates',
    county: 'Galveston',
    remarks: 'Check out this home that just got listed today. Be ...',
    photo: '/assets/listings/kemah/72756228.jpg',
    status: 'Active',
  },
  {
    mls: '98932277',
    address: '1217 Esther Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$230,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,846',
    acres: '0.176',
    yearBuilt: '1965',
    subdivision: 'Laguna Vista Estates',
    county: 'Galveston',
    remarks: 'Welcome to Laguna Vista Estates tucked away in the ...',
    photo: '/assets/listings/kemah/98932277.jpg',
    status: 'Active',
  },
  {
    mls: '24120049',
    address: '1911 Kemah Village Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$245,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,462',
    acres: '0.031',
    yearBuilt: '2006',
    subdivision: 'Kemah Village 2005',
    county: 'Galveston',
    remarks: 'DESIRABLE CORNER TOWNHOME OFFERING A H ...',
    photo: '/assets/listings/kemah/24120049.jpg',
    status: 'Active',
  },
  {
    mls: '9031553',
    address: '1827 Oak Ridge Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$266,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,515',
    acres: '0.145',
    yearBuilt: '1994',
    subdivision: 'Kemah Oaks Sub 92',
    county: 'Galveston',
    remarks: 'Nestled in the sought-after Kemah Oaks community, ...',
    photo: '/assets/listings/kemah/9031553.jpg',
    status: 'Active',
  },
  {
    mls: '86683975',
    address: '310 Lakeside Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$269,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,112',
    acres: '0.115',
    yearBuilt: '1994',
    subdivision: 'Lakeside Sub',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/kemah/86683975.jpg',
    status: 'Active',
  },
  {
    mls: '61139446',
    address: '614 Pelican Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$295,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,617',
    acres: '0.046',
    yearBuilt: '2023',
    subdivision: 'Kemah Crossing',
    county: 'Galveston',
    remarks: 'Best available townhome in neighborhood, corner lo ...',
    photo: '/assets/listings/kemah/61139446.jpg',
    status: 'Active',
  },
  {
    mls: '34651334',
    address: '716 Sand Dollar Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$306,540',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,607',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Aug ...',
    photo: '/assets/listings/kemah/34651334.jpg',
    status: 'Active',
  },
  {
    mls: '62172860',
    address: '1710 Oak Valley Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$309,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,148',
    acres: '0.134',
    yearBuilt: '1994',
    subdivision: 'Kemah Oaks Sub 92',
    county: 'Galveston',
    remarks: 'Look no further!! Close proximity to Kemah Boardwa ...',
    photo: '/assets/listings/kemah/62172860.jpg',
    status: 'Active',
  },
  {
    mls: '15583795',
    address: '639 Salt Marsh Trail',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$310,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,749',
    acres: '0.046',
    yearBuilt: '2023',
    subdivision: 'Kemah Xing Sec 1',
    county: 'Galveston',
    remarks: 'Designer-inspired upgrades meet energy-efficient l ...',
    photo: '/assets/listings/kemah/15583795.jpg',
    status: 'Active',
  },
  {
    mls: '63222060',
    address: '1140 Marina Bay Drive 110A',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$314,900',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,710',
    acres: '0.039',
    yearBuilt: '1985',
    subdivision: 'Moon Caye Condo',
    county: 'Galveston',
    remarks: 'This beautiful waterfront condo has relaxing and b ...',
    photo: '/assets/listings/kemah/63222060.jpg',
    status: 'Active',
  },
  {
    mls: '76345689',
    address: '2400 King Mackerel Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$319,790',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,727',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Jul ...',
    photo: '/assets/listings/kemah/76345689.jpg',
    status: 'Active',
  },
  {
    mls: '46310751',
    address: '2168 Blue Heron Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$319,940',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,727',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Sep ...',
    photo: '/assets/listings/kemah/46310751.jpg',
    status: 'Active',
  },
  {
    mls: '95737879',
    address: '2202 Blue Heron Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$320,840',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,727',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Sep ...',
    photo: '/assets/listings/kemah/95737879.jpg',
    status: 'Active',
  },
  {
    mls: '61918708',
    address: '2160 Blue Heron Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$321,140',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,727',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Sep ...',
    photo: '/assets/listings/kemah/61918708.jpg',
    status: 'Active',
  },
  {
    mls: '58333604',
    address: '718 Sand Dollar Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$324,190',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,047',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Aug ...',
    photo: '/assets/listings/kemah/58333604.jpg',
    status: 'Active',
  },
  {
    mls: '27024591',
    address: '714 Sand Dollar Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$326,890',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,852',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Aug ...',
    photo: '/assets/listings/kemah/27024591.jpg',
    status: 'Active',
  },
  {
    mls: '84464462',
    address: '1826 Oak Valley',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$335,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,437',
    acres: '0.145',
    yearBuilt: '1995',
    subdivision: 'Kemah Oaks',
    county: 'Galveston',
    remarks: 'GORGEOUS & AFFORDABLE 3/2.5/2A +GAMER ...',
    photo: '/assets/listings/kemah/84464462.jpg',
    status: 'Active',
  },
  {
    mls: '60911457',
    address: '2206 Blue Heron Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$336,290',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,047',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Aug ...',
    photo: '/assets/listings/kemah/60911457.jpg',
    status: 'Active',
  },
  {
    mls: '18815699',
    address: '2164 Blue Heron Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$337,190',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,047',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Kemah Crossing Th',
    county: 'Galveston',
    remarks: 'Brand new, energy-efficient home available by Sep ...',
    photo: '/assets/listings/kemah/18815699.jpg',
    status: 'Active',
  },
  {
    mls: '70654731',
    address: '315 West Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$339,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,848',
    acres: '0.115',
    yearBuilt: '2006',
    subdivision: 'Lakeside Sub',
    county: 'Galveston',
    remarks: 'Welcome to your coastal retreat in the heart of Ke ...',
    photo: '/assets/listings/kemah/70654731.jpg',
    status: 'Active',
  },
  {
    mls: '86363389',
    address: '606 Oak Hill Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$350,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,592',
    acres: '0.248',
    yearBuilt: '1996',
    subdivision: 'Kemah Oaks Sub 92',
    county: 'Galveston',
    remarks: 'Welcome home to 606 Oak Hill nestled on a double c ...',
    photo: '/assets/listings/kemah/86363389.jpg',
    status: 'Active',
  },
  {
    mls: '5587875',
    address: '2108 Knollwood Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$364,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,194',
    acres: '0.103',
    yearBuilt: '1972',
    subdivision: 'Glen Cove Add',
    county: 'Galveston',
    remarks: 'Water views at this price — truly hard to find. Va ...',
    photo: '/assets/listings/kemah/5587875.jpg',
    status: 'Active',
  },
  {
    mls: '13665531',
    address: '2419 Driftwood Trail',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$365,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,505',
    acres: '0.061',
    yearBuilt: '2023',
    subdivision: 'Kemah Crossing',
    county: 'Galveston',
    remarks: 'Welcome to 2419 Driftwood Trail, where modern desi ...',
    photo: '/assets/listings/kemah/13665531.jpg',
    status: 'Active',
  },
  {
    mls: '39444705',
    address: '2205 Mission Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$375,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,552',
    acres: '0.236',
    yearBuilt: '1979',
    subdivision: 'Glen Cove Park',
    county: 'Galveston',
    remarks: 'Welcome to 2205 Mission St in the charming Glen Co ...',
    photo: '/assets/listings/kemah/39444705.jpg',
    status: 'Active',
  },
  {
    mls: '83766527',
    address: '602 Oak Briar Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$382,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,333',
    acres: '0.147',
    yearBuilt: '1995',
    subdivision: 'Kemah Oaks Sub 92',
    county: 'Galveston',
    remarks: 'Beautifully maintained home with numerous recent u ...',
    photo: '/assets/listings/kemah/83766527.jpg',
    status: 'Active',
  },
  {
    mls: '32568522',
    address: '704 6th Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$385,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '777',
    acres: '0.138',
    yearBuilt: '1969',
    subdivision: 'Kemah Townsite',
    county: 'Galveston',
    remarks: 'A rare opportunity just steps from the bay, this c ...',
    photo: '/assets/listings/kemah/32568522.jpg',
    status: 'Active',
  },
  {
    mls: '98773054',
    address: '550 Morning Tide Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$385,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,920',
    acres: '0.058',
    yearBuilt: '2024',
    subdivision: 'Kemah Crossing',
    county: 'Galveston',
    remarks: 'Almost new, energy-efficient home available! First ...',
    photo: '/assets/listings/kemah/98773054.jpg',
    status: 'Active',
  },
  {
    mls: '23333858',
    address: '1206 Fay Road',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$398,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,248',
    acres: '0.239',
    yearBuilt: '1966',
    subdivision: 'Bay Breeze Add',
    county: 'Galveston',
    remarks: 'Updated Kemah home with the big-ticket items alrea ...',
    photo: '/assets/listings/kemah/23333858.jpg',
    status: 'Active',
  },
  {
    mls: '53217412',
    address: '321 Holly Branch Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$399,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,550',
    acres: '0.177',
    yearBuilt: '2007',
    subdivision: 'Twin Oaks Sub',
    county: 'Galveston',
    remarks: 'Marina Del Sol/Twin Oaks buyers, this is the easy- ...',
    photo: '/assets/listings/kemah/53217412.jpg',
    status: 'Active',
  },
  {
    mls: '92655864',
    address: '310 Waterford Way',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$399,995',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,958',
    acres: '0.137',
    yearBuilt: '2000',
    subdivision: 'The Arbors At Waterford Harbor',
    county: 'Galveston',
    remarks: 'Located in the exclusive waterfront community of W ...',
    photo: '/assets/listings/kemah/92655864.jpg',
    status: 'Active',
  },
  {
    mls: '17559175',
    address: '201 Lago Vista Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$399,999',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,873',
    acres: '0.168',
    yearBuilt: '1996',
    subdivision: 'The Dockside At Marina Del Sol',
    county: 'Galveston',
    remarks: 'Shows even better in person—schedule your tour tod ...',
    photo: '/assets/listings/kemah/17559175.jpg',
    status: 'Active',
  },
  {
    mls: '37071522',
    address: '327 Holly Branch Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$439,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,502',
    acres: '0.177',
    yearBuilt: '2006',
    subdivision: 'Twin Oaks Sub',
    county: 'Galveston',
    remarks: 'Motivated Seller!!! Beautiful updated home in the ...',
    photo: '/assets/listings/kemah/37071522.jpg',
    status: 'Active',
  },
  {
    mls: '22095799',
    address: '22 Tindel Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$475,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,111',
    acres: '0.176',
    yearBuilt: '1974',
    subdivision: 'Silver Lagoon Estates',
    county: 'Galveston',
    remarks: 'Boater’s dream in Clear Lake Shores! This waterfro ...',
    photo: '/assets/listings/kemah/22095799.jpg',
    status: 'Active',
  },
  {
    mls: '84271251',
    address: '432 Glen Cove Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$509,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,512',
    acres: '0.213',
    yearBuilt: '1969',
    subdivision: 'Glen Cove Add',
    county: 'Galveston',
    remarks: 'Park views, lake views, and a layout designed for ...',
    photo: '/assets/listings/kemah/84271251.jpg',
    status: 'Active',
  },
  {
    mls: '97884345',
    address: '488 Mariners Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$539,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,779',
    acres: '0.057',
    yearBuilt: '1997',
    subdivision: 'Regatta Twnhms Sub 97',
    county: 'Galveston',
    remarks: 'Seize your opportunity to live in your dream Regat ...',
    photo: '/assets/listings/kemah/97884345.jpg',
    status: 'Active',
  },
  {
    mls: '15147582',
    address: '616 E Shore Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$559,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,973',
    acres: '0.115',
    yearBuilt: '1998',
    subdivision: 'Clear Lake Shores',
    county: 'Galveston',
    remarks: 'Enjoy a lifestyle filled with outdoor recreation, ...',
    photo: '/assets/listings/kemah/15147582.jpg',
    status: 'Active',
  },
  {
    mls: '80923015',
    address: '322 Marina Oaks Court',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$625,000',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,458',
    acres: '0.249',
    yearBuilt: '2003',
    subdivision: 'The Park At Marina Del Sol',
    county: 'Galveston',
    remarks: 'BEAUTIFULLY UPDATED HOME ON PRIME OVER ...',
    photo: '/assets/listings/kemah/80923015.jpg',
    status: 'Active',
  },
  {
    mls: '37214978',
    address: '1212 Delores Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$625,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,704',
    acres: '0.358',
    yearBuilt: '1973',
    subdivision: 'South Kemah',
    county: 'Galveston',
    remarks: 'Introducing 1212 Delores in Kemah, a rare property ...',
    photo: '/assets/listings/kemah/37214978.jpg',
    status: 'Active',
  },
  {
    mls: '81635908',
    address: '23 Harbor Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$699,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,792',
    acres: '0.181',
    yearBuilt: '1980',
    subdivision: 'Lazy Bend',
    county: 'Galveston',
    remarks: 'Waterfront living awaits in the popular golf cart ...',
    photo: '/assets/listings/kemah/81635908.jpg',
    status: 'Active',
  },
  {
    mls: '42681902',
    address: '67 Harbor Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$724,900',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,704',
    acres: '0.252',
    yearBuilt: '1989',
    subdivision: 'Lazy Bend',
    county: 'Galveston',
    remarks: 'Welcome to your own private oasis in Kemah! Ready ...',
    photo: '/assets/listings/kemah/42681902.jpg',
    status: 'Active',
  },
  {
    mls: '28857946',
    address: '2311 Anders Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$795,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,357',
    acres: '2',
    yearBuilt: '1994',
    subdivision: 'Jarboe',
    county: 'Galveston',
    remarks: 'Beautifully versatile 2-acre property on highly so ...',
    photo: '/assets/listings/kemah/28857946.jpg',
    status: 'Active',
  },
  {
    mls: '23902589',
    address: '320 Harborside Circle',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$799,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,832',
    acres: '0.117',
    yearBuilt: '1998',
    subdivision: 'The Arbors At Waterford Harbor',
    county: 'Galveston',
    remarks: 'Beautiful Mediterranean inspired home located in t ...',
    photo: '/assets/listings/kemah/23902589.jpg',
    status: 'Active',
  },
  {
    mls: '35757927',
    address: '5 Harbor Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$800,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,740',
    acres: '0.3',
    yearBuilt: '1976',
    subdivision: 'Lazy Bend',
    county: 'Galveston',
    remarks: 'Come enjoy true waterfront living in Lazy Bend! Th ...',
    photo: '/assets/listings/kemah/35757927.jpg',
    status: 'Active',
  },
  {
    mls: '70242832',
    address: '308 Bay Avenue',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$850,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,536',
    acres: '0.332',
    yearBuilt: '1986',
    subdivision: 'Kemah Townsite',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/kemah/70242832.jpg',
    status: 'Active',
  },
  {
    mls: '38632090',
    address: '88 Bayou Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$850,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,600',
    acres: '0.23',
    yearBuilt: '2025',
    subdivision: 'Lazy Bend',
    county: 'Galveston',
    remarks: 'Luxury waterfront living with direct canal access ...',
    photo: '/assets/listings/kemah/38632090.jpg',
    status: 'Active',
  },
  {
    mls: '41512652',
    address: '804 Bay Avenue',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$885,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,932',
    acres: '0.166',
    yearBuilt: '1989',
    subdivision: 'Kemah Townsite',
    county: 'Galveston',
    remarks: '4 LEVEL HOME WITH ELEVATOR! EXCELLENT ...',
    photo: '/assets/listings/kemah/41512652.jpg',
    status: 'Active',
  },
  {
    mls: '30422179',
    address: '2174 Marina Way',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$960,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,162',
    acres: '0.154',
    yearBuilt: '2017',
    subdivision: 'Marina Del Sol Villas',
    county: 'Galveston',
    remarks: 'Live the marina lifestyle in this three-story coas ...',
    photo: '/assets/listings/kemah/30422179.jpg',
    status: 'Active',
  },
  {
    mls: '4189508',
    address: '411 Harborside Way',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,000,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,951',
    acres: '0.121',
    yearBuilt: '1999',
    subdivision: 'The Arbors At Waterford Harbor',
    county: 'Galveston',
    remarks: 'Experience waterfront living at its finest in this ...',
    photo: '/assets/listings/kemah/4189508.jpg',
    status: 'Active',
  },
  {
    mls: '84522129',
    address: '313 Harborside Circle',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,025,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,832',
    acres: '0.104',
    yearBuilt: '1998',
    subdivision: 'The Arbors At Waterford Harbor',
    county: 'Galveston',
    remarks: 'Incredible home boasting a carefree lake living vi ...',
    photo: '/assets/listings/kemah/84522129.jpg',
    status: 'Active',
  },
  {
    mls: '90105769',
    address: '628 Appia Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,149,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,864',
    acres: '0.297',
    yearBuilt: '2018',
    subdivision: 'Cypress Bay Sec 1 2009',
    county: 'Galveston',
    remarks: 'A WATERFRONT OASIS BLENDING COMFORT, E ...',
    photo: '/assets/listings/kemah/90105769.jpg',
    status: 'Active',
  },
  {
    mls: '97827064',
    address: '606 Appia Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,289,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,579',
    acres: '0.211',
    yearBuilt: '2025',
    subdivision: 'Cypress Bay Sec 1 2009',
    county: 'Galveston',
    remarks: 'INDULGE IN BESPOKE WATERFRONT LIVING I ...',
    photo: '/assets/listings/kemah/97827064.jpg',
    status: 'Active',
  },
  {
    mls: '92795098',
    address: '50 W 8th Street A-D',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,299,000',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '630',
    acres: '0.172',
    yearBuilt: '2016',
    subdivision: 'West Kemah 4',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/listings/kemah/92795098.jpg',
    status: 'Active',
  },
  {
    mls: '65903352',
    address: '529 Southport Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,310,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,830',
    acres: '0.155',
    yearBuilt: '1995',
    subdivision: 'Waterford Harbor Villas 93',
    county: 'Galveston',
    remarks: 'TUCKED AWAY IN EXCLUSIVE GATED WATERFO ...',
    photo: '/assets/listings/kemah/65903352.jpg',
    status: 'Active',
  },
  {
    mls: '81499649',
    address: '604 Harborside Way',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,399,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,692',
    acres: '0.239',
    yearBuilt: '1999',
    subdivision: 'Waterford Harbor Villas',
    county: 'Galveston',
    remarks: 'BEAUTIFUL CUSTOM HOME, BY RENOWNED MAS ...',
    photo: '/assets/listings/kemah/81499649.jpg',
    status: 'Active',
  },
  {
    mls: '59240603',
    address: '620 Appia Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,649,000',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '5,000',
    acres: '0.264',
    yearBuilt: '2026',
    subdivision: 'Cypress Bay Sec 1 2009',
    county: 'Galveston',
    remarks: 'EXPERIENCE MODERN ELEGANCE WITH THIS E ...',
    photo: '/assets/listings/kemah/59240603.jpg',
    status: 'Active',
  },
  {
    mls: '12699786',
    address: '508 Amalfi Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,649,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,617',
    acres: '0.372',
    yearBuilt: '2025',
    subdivision: 'Cypress Bay',
    county: 'Galveston',
    remarks: 'Stunning new custom waterfront home with over 100f ...',
    photo: '/assets/listings/kemah/12699786.jpg',
    status: 'Active',
  },
  {
    mls: '54595518',
    address: '2230 Marina Way',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,749,999',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,930',
    acres: '0.266',
    yearBuilt: '2018',
    subdivision: 'Lookout Point At Marina Del Sol',
    county: 'Galveston',
    remarks: 'MODERN LUXURY WATERFRONT RETREAT-DESIG ...',
    photo: '/assets/listings/kemah/54595518.jpg',
    status: 'Active',
  },
  {
    mls: '8453008',
    address: '2730 Lawrence Road',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,790,000',
    beds: '6 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,737',
    acres: '4.79',
    yearBuilt: '2006',
    subdivision: 'Muldoon Sur',
    county: 'Galveston',
    remarks: 'Country living without leaving the city behind! In ...',
    photo: '/assets/listings/kemah/8453008.jpg',
    status: 'Active',
  },
  {
    mls: '64316310',
    address: '2240 Marina Way',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,549,900',
    beds: '4 Bedrooms',
    baths: '7 Total Baths',
    sqft: '5,996',
    acres: '0.514',
    yearBuilt: '2005',
    subdivision: 'Lookout Point At Marina Del Sol',
    county: 'Galveston',
    remarks: 'AMAZING CUSTOM MEDITERRANEAN HOME ON 1 ...',
    photo: '/assets/listings/kemah/64316310.jpg',
    status: 'Active',
  },
  {
    mls: '59253257',
    address: '112 Bayou Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$4,600,000',
    beds: '5 Bedrooms',
    baths: '10 Total Baths',
    sqft: '10,040',
    acres: '0.634',
    yearBuilt: '1998',
    subdivision: 'Lazy Bend',
    county: 'Galveston',
    remarks: 'Experience the best of waterfront living at this e ...',
    photo: '/assets/listings/kemah/59253257.jpg',
    status: 'Active',
  },
  {
    mls: '84169251',
    address: '6 Waterford Oaks Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$5,500,000',
    beds: '6 Bedrooms',
    baths: '7 Total Baths',
    sqft: '9,382',
    acres: '0.438',
    yearBuilt: '2006',
    subdivision: 'Waterford Oaks 93',
    county: 'Galveston',
    remarks: 'Tucked behind the exclusive second gate of Waterfo ...',
    photo: '/assets/listings/kemah/84169251.jpg',
    status: 'Active',
  },
]
