// Pearland homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const pearlandRentListings: Listing[] = [
  {
    mls: '72939701',
    address: '3821 Pin Oak Drive N',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,846',
    acres: '0.2',
    yearBuilt: '1993',
    subdivision: 'Oakbrook Sec 1 Ph 1 Rep',
    county: 'Brazoria',
    remarks: 'Spectacular rental home in Oak Brook available for ...',
    photo: '/assets/rentals/pearland/72939701.jpg',
    status: 'Active',
  },
  {
    mls: '78619505',
    address: '7116 Elgin Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,700',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,728',
    acres: '0.048',
    yearBuilt: '2021',
    subdivision: 'Midtown/Magnolia Twnhms',
    county: 'Brazoria',
    remarks: 'Welcome to your new home!!:) Enjoy low-maintenanc ...',
    photo: '/assets/rentals/pearland/78619505.jpg',
    status: 'Active',
  },
  {
    mls: '62429442',
    address: '3502 Wheatmeadow Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,680',
    acres: '0.169',
    yearBuilt: '2000',
    subdivision: 'River Mist Sec 1&amp;2',
    county: 'Brazoria',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/pearland/62429442.jpg',
    status: 'Active',
  },
  {
    mls: '66235257',
    address: '4907 Autumn Hills Trail',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,280',
    acres: '0.19',
    yearBuilt: '2023',
    subdivision: 'Massey Oaks Sec 2',
    county: 'Brazoria',
    remarks: 'Welcome home to this beautifully designed one-stor ...',
    photo: '/assets/rentals/pearland/66235257.jpg',
    status: 'Active',
  },
  {
    mls: '98712058',
    address: '2215 Alberton Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,782',
    acres: '0.201',
    yearBuilt: '1996',
    subdivision: 'Meadowview Sec 1 At Silverlake',
    county: 'Brazoria',
    remarks: 'This 2-story house features 4 bedrooms, 2.5 baths, ...',
    photo: '/assets/rentals/pearland/98712058.jpg',
    status: 'Active',
  },
  {
    mls: '47440889',
    address: '4640 Orange Circle S',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,950',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1984',
    subdivision: 'Orange County Dup Sec 1-2-3',
    county: 'Brazoria',
    remarks: 'Single-family, one-story residential home built in ...',
    photo: '/assets/rentals/pearland/47440889.jpg',
    status: 'Active',
  },
  {
    mls: '79380637',
    address: '2528 S Texas Avenue Street A',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,609',
    acres: '0.144',
    yearBuilt: '2023',
    subdivision: 'Pearland Meadows Sd',
    county: 'Brazoria',
    remarks: 'Modern townhouse available for rent. It is consist ...',
    photo: '/assets/rentals/pearland/79380637.jpg',
    status: 'Active',
  },
  {
    mls: '5444829',
    address: '2007 Orchard Frost Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,439',
    acres: '0.166',
    yearBuilt: '2005',
    subdivision: 'Village Grove Sec 1',
    county: 'Brazoria',
    remarks: 'Move in ready! Two story, four bedroom, two and a ...',
    photo: '/assets/rentals/pearland/5444829.jpg',
    status: 'Active',
  },
  {
    mls: '61208152',
    address: '703 Flower Field Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,300',
    acres: '0.15',
    yearBuilt: '1981',
    subdivision: 'Countryplace Sec 1',
    county: 'Brazoria',
    remarks: 'OVER 55 COUNTRY CLUB COMMUNITY - REMOD ...',
    photo: '/assets/rentals/pearland/61208152.jpg',
    status: 'Active',
  },
  {
    mls: '18896945',
    address: '3523 Pine Valley Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,510',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,210',
    acres: '0.153',
    yearBuilt: '2003',
    subdivision: 'Pine Hollow Sec 2-A 2b',
    county: 'Brazoria',
    remarks: '',
    photo: '/assets/rentals/pearland/18896945.jpg',
    status: 'Active',
  },
  {
    mls: '51410659',
    address: '2711 S Brompton Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,707',
    acres: '0.145',
    yearBuilt: '1982',
    subdivision: 'Southdown',
    county: 'Brazoria',
    remarks: 'Updated 3 bedroom home located in Southdown commun ...',
    photo: '/assets/rentals/pearland/51410659.jpg',
    status: 'Active',
  },
  {
    mls: '64314095',
    address: '3006 Brooks Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$4,500',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,363',
    acres: '0.215',
    yearBuilt: '2001',
    subdivision: 'Creekstone At Silverlake A415',
    county: 'Brazoria',
    remarks: 'Nestled in the desirable Silvercreek community, th ...',
    photo: '/assets/rentals/pearland/64314095.jpg',
    status: 'Active',
  },
  {
    mls: '2324608',
    address: '1816 Oak Lodge Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,120',
    acres: '0.172',
    yearBuilt: '1996',
    subdivision: 'Oakbrook Estates Sec 1',
    county: 'Brazoria',
    remarks: 'This updated corner lot home features 4 bedrooms, ...',
    photo: '/assets/rentals/pearland/2324608.jpg',
    status: 'Active',
  },
  {
    mls: '85337447',
    address: '2801 Field Hollow Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,454',
    acres: '0.168',
    yearBuilt: '2012',
    subdivision: 'Shadow Creek Ranch Sf-55b',
    county: 'Fort Bend',
    remarks: 'Stunning One-story home in the master planned comm ...',
    photo: '/assets/rentals/pearland/85337447.jpg',
    status: 'Active',
  },
  {
    mls: '57837288',
    address: '10015 Dawn Brook Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,800',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,592',
    acres: '0.174',
    yearBuilt: '2001',
    subdivision: 'Autumn Lake Sec 1-2-3',
    county: 'Brazoria',
    remarks: 'Very spacious, move-in ready 5 bed 2.5 bath home z ...',
    photo: '/assets/rentals/pearland/57837288.jpg',
    status: 'Active',
  },
  {
    mls: '13233005',
    address: '2118 N Austin Avenue',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,650',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,155',
    acres: '0.161',
    yearBuilt: '1980',
    subdivision: 'H T &amp; B R R',
    county: 'Brazoria',
    remarks: '',
    photo: '/assets/rentals/pearland/13233005.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '15822970',
    address: '11609 Spill Creek Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,302',
    acres: '0.172',
    yearBuilt: '2004',
    subdivision: 'Shadow Creek Ranch Sf1-Sf2-S',
    county: 'Brazoria',
    remarks: 'Welcome to this stunning single-story home in the ...',
    photo: '/assets/rentals/pearland/15822970.jpg',
    status: 'Active',
  },
  {
    mls: '86750511',
    address: '3230 Vanity Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,495',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,186',
    acres: '0.15',
    yearBuilt: '1998',
    subdivision: 'Southwyck',
    county: 'Brazoria',
    remarks: 'Move-In Ready in Pearland! Welcome to 3230 Vanity ...',
    photo: '/assets/rentals/pearland/86750511.jpg',
    status: 'Active',
  },
  {
    mls: '31255148',
    address: '2003 Sunset Terrace Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77089',
    price: '$2,600',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,622',
    acres: '0.158',
    yearBuilt: '2015',
    subdivision: 'Enclave At Highland Glen',
    county: 'Harris',
    remarks: 'Beautifully maintained 5-bedroom, 3-bath home with ...',
    photo: '/assets/rentals/pearland/31255148.jpg',
    status: 'Active',
  },
  {
    mls: '46360852',
    address: '5817 Village Grove Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,255',
    acres: '0.169',
    yearBuilt: '2005',
    subdivision: 'Village Grove',
    county: 'Brazoria',
    remarks: 'Charming four-bedroom, one-story home on a spaciou ...',
    photo: '/assets/rentals/pearland/46360852.jpg',
    status: 'Active',
  },
  {
    mls: '43997957',
    address: '5008 Rockland Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,418',
    acres: '0.211',
    yearBuilt: '1976',
    subdivision: 'Corrigan Pearland',
    county: 'Brazoria',
    remarks: 'A very nice home with granite counter tops in the ...',
    photo: '/assets/rentals/pearland/43997957.jpg',
    status: 'Active',
  },
  {
    mls: '92977179',
    address: '4135 N Nolan Place',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,158',
    acres: '0.152',
    yearBuilt: '1998',
    subdivision: 'Southwyck',
    county: 'Brazoria',
    remarks: 'Beautiful and well-kept 3-bedroom, 2-bathroom home ...',
    photo: '/assets/rentals/pearland/92977179.jpg',
    status: 'Active',
  },
  {
    mls: '14451548',
    address: '2808 Morenci Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,322',
    acres: '1.9',
    yearBuilt: '1974',
    subdivision: 'Sandoval',
    county: 'Brazoria',
    remarks: 'Open concept home features large living area with ...',
    photo: '/assets/rentals/pearland/14451548.jpg',
    status: 'Active',
  },
  {
    mls: '15799591',
    address: '13804 Rose Bay Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,372',
    acres: '0.282',
    yearBuilt: '2007',
    subdivision: 'Shadow Creek Ranch Sf-59',
    county: 'Fort Bend',
    remarks: 'Beautiful one story home with over 3,300 square fe ...',
    photo: '/assets/rentals/pearland/15799591.jpg',
    status: 'Pending',
  },
  {
    mls: '61227395',
    address: '1401 Paul Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,570',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,642',
    acres: '',
    yearBuilt: '1976',
    subdivision: 'Longwood Park (A0111 Perry &amp; Austin)',
    county: 'Brazoria',
    remarks: 'Charming single-family home located in the peacefu ...',
    photo: '/assets/rentals/pearland/61227395.jpg',
    status: 'Pending',
  },
  {
    mls: '28432295',
    address: '2422 Lansing Circle',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,100',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,211',
    acres: '0.193',
    yearBuilt: '2000',
    subdivision: 'Scofield Sec 1',
    county: 'Brazoria',
    remarks: 'Welcome to this updated 4 bedrooms,3.5 baths prope ...',
    photo: '/assets/rentals/pearland/28432295.jpg',
    status: 'Active',
  },
  {
    mls: '36495305',
    address: '2503 Westerlake Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,875',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,831',
    acres: '0.182',
    yearBuilt: '2004',
    subdivision: 'Shadow Creek Ranch Sf1-Sf2-Sf3',
    county: 'Brazoria',
    remarks: 'Beautiful home in Shadow Creek Ranch, with a lot o ...',
    photo: '/assets/rentals/pearland/36495305.jpg',
    status: 'Active',
  },
  {
    mls: '48653543',
    address: '3327 Summerwood Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,912',
    acres: '0.165',
    yearBuilt: '1998',
    subdivision: 'The Lakes At Countryplace Sec',
    county: 'Brazoria',
    remarks: 'A stunning two-story residence located in Pearland ...',
    photo: '/assets/rentals/pearland/48653543.jpg',
    status: 'Active',
  },
  {
    mls: '34160372',
    address: '4203 Keystone Trail',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,119',
    acres: '0.161',
    yearBuilt: '2006',
    subdivision: 'Twin Lakes Sec 1',
    county: 'Brazoria',
    remarks: 'Welcome to this updated 4 bedroom 2.5 bath home in ...',
    photo: '/assets/rentals/pearland/34160372.jpg',
    status: 'Active',
  },
  {
    mls: '88638167',
    address: '3007 Eagle Lake Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$3,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,532',
    acres: '0.186',
    yearBuilt: '2004',
    subdivision: 'Towne Lake Estates Sec 1',
    county: 'Brazoria',
    remarks: 'Beautifully updated and thoughtfully designed, 300 ...',
    photo: '/assets/rentals/pearland/88638167.jpg',
    status: 'Active',
  },
  {
    mls: '61714366',
    address: '1923 Winding Creek Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,436',
    acres: '0.193',
    yearBuilt: '1976',
    subdivision: 'Woodcreek Sec 1-2-2a-3-4 Pear',
    county: 'Brazoria',
    remarks: 'BEAUTIFUL 3-2-2 IN THE HEART OF PEARLA ...',
    photo: '/assets/rentals/pearland/61714366.jpg',
    status: 'Active',
  },
  {
    mls: '58044976',
    address: '13007 Balsam Lake Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,750',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,713',
    acres: '0.19',
    yearBuilt: '2007',
    subdivision: 'Shadow Creek Ranch',
    county: 'Brazoria',
    remarks: 'Gorgeous 2-Story Home in Shadow Creek Ranch featur ...',
    photo: '/assets/rentals/pearland/58044976.jpg',
    status: 'Active',
  },
  {
    mls: '15023043',
    address: '3611 Sheldon Dr',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,299',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,910',
    acres: '0.145',
    yearBuilt: '1998',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'This beautiful property READY TO MOVE IN. Great sc ...',
    photo: '/assets/rentals/pearland/15023043.jpg',
    status: 'Active',
  },
  {
    mls: '45850049',
    address: '11308 Windy Dawn Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,250',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,825',
    acres: '0.166',
    yearBuilt: '2002',
    subdivision: 'Shadow Creek Ranch Sf-8b Pear',
    county: 'Brazoria',
    remarks: 'Welcome to 11308 Windy Dawn, a beautifully updated ...',
    photo: '/assets/rentals/pearland/45850049.jpg',
    status: 'Active',
  },
  {
    mls: '17089849',
    address: '5012 Great Oaks Drive Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$4,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,241',
    acres: '0.19',
    yearBuilt: '2023',
    subdivision: 'Massey Oaks Sec 2',
    county: 'Brazoria',
    remarks: 'Stunning fully furnished 4-bedroom, 3.5-bath home ...',
    photo: '/assets/rentals/pearland/17089849.jpg',
    status: 'Active',
  },
  {
    mls: '8658900',
    address: '3519 Crescent Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,580',
    acres: '0.152',
    yearBuilt: '1998',
    subdivision: 'Sedgefield Sec 1-2-3 At Silver',
    county: 'Brazoria',
    remarks: 'This beautiful 3-bed, 2-bath home tucked away in a ...',
    photo: '/assets/rentals/pearland/8658900.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '33980481',
    address: '2714 S Brompton Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,426',
    acres: '0.166',
    yearBuilt: '1982',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'Location, Location, Location! This charming one-st ...',
    photo: '/assets/rentals/pearland/33980481.jpg',
    status: 'Active',
  },
  {
    mls: '33122637',
    address: '12112 Bright Landing Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,950',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,048',
    acres: '0.183',
    yearBuilt: '2007',
    subdivision: 'Southern Trails Ph 1 Sec 1-',
    county: 'Brazoria',
    remarks: 'Great location on quiet cul de sac, short walk to ...',
    photo: '/assets/rentals/pearland/33122637.jpg',
    status: 'Pending',
  },
  {
    mls: '3926761',
    address: '10006 Autumn Lake Trail',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,500',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '3,700',
    acres: '0.349',
    yearBuilt: '2002',
    subdivision: 'Autumn Lake Sec 1-2-3',
    county: 'Brazoria',
    remarks: '10006 Autumn Lakes Trail built on an amazing lake ...',
    photo: '/assets/rentals/pearland/3926761.jpg',
    status: 'Pending',
  },
  {
    mls: '18394401',
    address: '4620 W Orange Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,695',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,416',
    acres: '0.169',
    yearBuilt: '1978',
    subdivision: 'Orange County Dup Sec 1-2-3',
    county: 'Brazoria',
    remarks: 'Updated 2-bedroom, 1.5-bath unit in a well-maintai ...',
    photo: '/assets/rentals/pearland/18394401.jpg',
    status: 'Active',
  },
  {
    mls: '47479117',
    address: '2305 Ames Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,596',
    acres: '0.138',
    yearBuilt: '2001',
    subdivision: 'South Hampton Sec 1-2',
    county: 'Brazoria',
    remarks: 'Spacious 4-bedroom, 2.5-bathroom two-story home fo ...',
    photo: '/assets/rentals/pearland/47479117.jpg',
    status: 'Active',
  },
  {
    mls: '97052455',
    address: '1910 Plum Falls Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,500',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,793',
    acres: '0.158',
    yearBuilt: '2003',
    subdivision: 'Village Grove Sec 1',
    county: 'Brazoria',
    remarks: 'Spacious floor plan with 5 large bedrooms or 4 bed ...',
    photo: '/assets/rentals/pearland/97052455.jpg',
    status: 'Active',
  },
  {
    mls: '87955661',
    address: '13208 Sage Meadow Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,120',
    acres: '0.189',
    yearBuilt: '2017',
    subdivision: 'Southlake Sec 11 A0538 Ht&amp;Brr',
    county: 'Brazoria',
    remarks: 'Beautifully maintained 3/4 bedroom, 2-bath Perry h ...',
    photo: '/assets/rentals/pearland/87955661.jpg',
    status: 'Active',
  },
  {
    mls: '29613719',
    address: '3020 Rocky Canyon Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$4,400',
    beds: '5 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,192',
    acres: '0.179',
    yearBuilt: '2015',
    subdivision: 'Pearland Estates',
    county: 'Brazoria',
    remarks: 'Handsome brick and stone two story in Pearland Est ...',
    photo: '/assets/rentals/pearland/29613719.jpg',
    status: 'Active',
  },
  {
    mls: '58498912',
    address: '1103 W Brompton Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,498',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,398',
    acres: '0.158',
    yearBuilt: '1982',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'Nestled on an elevated corner lot, this 4-bed, 2-b ...',
    photo: '/assets/rentals/pearland/58498912.jpg',
    status: 'Active',
  },
  {
    mls: '81031180',
    address: '2703 Wild Lilac Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,523',
    acres: '0.162',
    yearBuilt: '2011',
    subdivision: 'Shadow Creek Ranch Sf-51b',
    county: 'Fort Bend',
    remarks: 'Welcome home to this beautifully maintained one-st ...',
    photo: '/assets/rentals/pearland/81031180.jpg',
    status: 'Active',
  },
  {
    mls: '34337332',
    address: '3511 Paigewood Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,831',
    acres: '0.146',
    yearBuilt: '1999',
    subdivision: 'Sedgefield Sec 1-2-3 At Silver',
    county: 'Brazoria',
    remarks: 'Lovely 3 bedrooms 2 bath home is in the highly sou ...',
    photo: '/assets/rentals/pearland/34337332.jpg',
    status: 'Active',
  },
  {
    mls: '53430575',
    address: '4111 Boulder Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,082',
    acres: '0.145',
    yearBuilt: '2002',
    subdivision: 'Park Village Estates Sec 4 A0',
    county: 'Brazoria',
    remarks: 'Located in a desirable Pearland neighborhood, this ...',
    photo: '/assets/rentals/pearland/53430575.jpg',
    status: 'Active',
  },
  {
    mls: '33012454',
    address: '3602 Brookstone Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,395',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,647',
    acres: '0.145',
    yearBuilt: '2001',
    subdivision: 'Sedgefield Sec 4 At Silverlake',
    county: 'Brazoria',
    remarks: 'Welcoming home on a cul-de-sac street and zoned to ...',
    photo: '/assets/rentals/pearland/33012454.jpg',
    status: 'Active',
  },
  {
    mls: '18722988',
    address: '3705 Burwood Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,270',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,072',
    acres: '0.208',
    yearBuilt: '2006',
    subdivision: 'Canterbury Park Sec 1',
    county: 'Brazoria',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/pearland/18722988.jpg',
    status: 'Pending',
  },
  {
    mls: '53848852',
    address: '8817 Sunforest Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,325',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,225',
    acres: '0.158',
    yearBuilt: '2004',
    subdivision: 'Sunrise Lakes Sec 7',
    county: 'Brazoria',
    remarks: 'Fabulous 1 story home in the Sunrise Lakes Communi ...',
    photo: '/assets/rentals/pearland/53848852.jpg',
    status: 'Active',
  },
  {
    mls: '72760749',
    address: '3904 Waterworth Way',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,112',
    acres: '0.202',
    yearBuilt: '2016',
    subdivision: 'Canterbury Park Sec 4 A0507-A',
    county: 'Brazoria',
    remarks: 'Welcome to this well-kept single-story home in Can ...',
    photo: '/assets/rentals/pearland/72760749.jpg',
    status: 'Active',
  },
  {
    mls: '24965961',
    address: '3821 Houston Lake Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$3,350',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,114',
    acres: '0.193',
    yearBuilt: '2006',
    subdivision: 'Towne Lake Estates',
    county: 'Brazoria',
    remarks: '**Like new and move-in ready!** This beautifully r ...',
    photo: '/assets/rentals/pearland/24965961.jpg',
    status: 'Active',
  },
  {
    mls: '61544498',
    address: '3122 Glen Cullen Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,150',
    acres: '0.152',
    yearBuilt: '1999',
    subdivision: 'Southwyck',
    county: 'Brazoria',
    remarks: 'Open-concept living and an oversized backyard in t ...',
    photo: '/assets/rentals/pearland/61544498.jpg',
    status: 'Active',
  },
  {
    mls: '46102643',
    address: '1011 Melford Avenue',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$1,980',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,089',
    acres: '0.157',
    yearBuilt: '1983',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'WELCOME TO THIS ABSOLUTELY STUNNING, R ...',
    photo: '/assets/rentals/pearland/46102643.jpg',
    status: 'Active',
  },
  {
    mls: '11760315',
    address: '3734 Paigewood Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,450',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,986',
    acres: '0.172',
    yearBuilt: '1999',
    subdivision: 'Sedgefield Sec 1-2-3 At Silver',
    county: 'Brazoria',
    remarks: 'Well-Maintained Home in the Heart of Silverlake, o ...',
    photo: '/assets/rentals/pearland/11760315.jpg',
    status: 'Active',
  },
  {
    mls: '74546211',
    address: '3210 Princess Bay Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,588',
    acres: '0.17',
    yearBuilt: '2003',
    subdivision: 'Villages Of Edgewater Estates',
    county: 'Brazoria',
    remarks: 'This beautiful 3/4 Bedrooms, 2 bathrooms one story ...',
    photo: '/assets/rentals/pearland/74546211.jpg',
    status: 'Active',
  },
  {
    mls: '71686956',
    address: '2202 Drake Falls Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,950',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,767',
    acres: '0.155',
    yearBuilt: '2006',
    subdivision: 'Shadow Creek Ranch',
    county: 'Brazoria',
    remarks: 'Experience the perfect blend of luxury and functio ...',
    photo: '/assets/rentals/pearland/71686956.jpg',
    status: 'Active',
  },
  {
    mls: '10687545',
    address: '2203 Rocky Shores Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77089',
    price: '$3,750',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,554',
    acres: '0.303',
    yearBuilt: '2016',
    subdivision: 'Riverstone Ranch/Clear Crk Sec',
    county: 'Harris',
    remarks: 'SPACIOUS RIVERSTONE RANCH living on an OVERSIZED 1 ...',
    photo: '/assets/rentals/pearland/10687545.jpg',
    status: 'Pending',
  },
  {
    mls: '3266903',
    address: '2606 Cypress Springs Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,450',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,113',
    acres: '0.145',
    yearBuilt: '2005',
    subdivision: 'Shadow Creek Ranch Sf1-Sf2-Sf3',
    county: 'Brazoria',
    remarks: 'Welcome to this Pearland 4-bedroom, 2-bathroom hom ...',
    photo: '/assets/rentals/pearland/3266903.jpg',
    status: 'Pending',
  },
  {
    mls: '91174487',
    address: '1039 Wentworth Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,065',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,315',
    acres: '0.157',
    yearBuilt: '1992',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'Beautiful home offers 4 bedroom and 2 bathroom wit ...',
    photo: '/assets/rentals/pearland/91174487.jpg',
    status: 'Pending',
  },
  {
    mls: '75598679',
    address: '2807 Burgess Hill Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,525',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,322',
    acres: '0.149',
    yearBuilt: '1995',
    subdivision: 'Southwyck',
    county: 'Brazoria',
    remarks: 'Charming 4 bed, 2.5 bath, 2,322 sq ft home in Pear ...',
    photo: '/assets/rentals/pearland/75598679.jpg',
    status: 'Pending',
  },
  {
    mls: '27172010',
    address: '1904 Keswick Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$3,500',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,703',
    acres: '0.177',
    yearBuilt: '2007',
    subdivision: 'Stonebridge Sec 1',
    county: 'Brazoria',
    remarks: 'Welcome to this stunning two-story home in the hig ...',
    photo: '/assets/rentals/pearland/27172010.jpg',
    status: 'Active',
  },
  {
    mls: '6602640',
    address: '3901 Spring Garden Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,875',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,256',
    acres: '0.165',
    yearBuilt: '1991',
    subdivision: 'Springfield Pearland',
    county: 'Brazoria',
    remarks: 'Weekly pool service included in rent! Great Family ...',
    photo: '/assets/rentals/pearland/6602640.jpg',
    status: 'Active',
  },
  {
    mls: '7793975',
    address: '2243 2243 County Road 130 3',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,040',
    acres: '0.732',
    yearBuilt: '2023',
    subdivision: 'West Friendswood',
    county: 'Brazoria',
    remarks: 'https://apply.link/XFYZWvY~ PLEASE REVIEW THE TENA ...',
    photo: '/assets/rentals/pearland/7793975.jpg',
    status: 'Active',
  },
  {
    mls: '13649238',
    address: '2315 Cunningham Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,696',
    acres: '0.224',
    yearBuilt: '1987',
    subdivision: 'Mimosa Acres',
    county: 'Brazoria',
    remarks: 'Welcome to 2315 Cunningham Drive! This well-mainta ...',
    photo: '/assets/rentals/pearland/13649238.jpg',
    status: 'Active',
  },
  {
    mls: '27682726',
    address: '2706 Courtyard Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,873',
    acres: '0.138',
    yearBuilt: '2005',
    subdivision: 'Autumn Lake Sec 1-2-3',
    county: 'Brazoria',
    remarks: 'Move-in ready! 3 bedroom 2 bath single story home ...',
    photo: '/assets/rentals/pearland/27682726.jpg',
    status: 'Active',
  },
  {
    mls: '5760693',
    address: '3209 Wheatmeadow Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,399',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,680',
    acres: '0.152',
    yearBuilt: '2001',
    subdivision: 'River Mist',
    county: 'Brazoria',
    remarks: 'Welcome to 3209 Wheatmeadow Court, a beautifully m ...',
    photo: '/assets/rentals/pearland/5760693.jpg',
    status: 'Active',
  },
  {
    mls: '909476',
    address: '2714 Pebble Creek Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,176',
    acres: '0.193',
    yearBuilt: '2003',
    subdivision: 'Clear Creek Park',
    county: 'Brazoria',
    remarks: 'This charming one-story residence offers the perfe ...',
    photo: '/assets/rentals/pearland/909476.jpg',
    status: 'Pending',
  },
  {
    mls: '51939699',
    address: '11607 Bay Ledge Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,010',
    acres: '0.209',
    yearBuilt: '2003',
    subdivision: 'Shadow Creek Ranch Sf-7a Pear',
    county: 'Brazoria',
    remarks: 'Welcome home to this beautiful two-story residence ...',
    photo: '/assets/rentals/pearland/51939699.jpg',
    status: 'Active',
  },
  {
    mls: '15123694',
    address: '3117 Princess Bay Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,100',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,427',
    acres: '0.204',
    yearBuilt: '2002',
    subdivision: 'Villages Of Edgewater Estates',
    county: 'Brazoria',
    remarks: 'Stop and look no further. This beautiful property ...',
    photo: '/assets/rentals/pearland/15123694.jpg',
    status: 'Active',
  },
  {
    mls: '76005288',
    address: '2515 Lansing Circle',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,692',
    acres: '0.19',
    yearBuilt: '1999',
    subdivision: 'Scofield Sec 1',
    county: 'Brazoria',
    remarks: 'Welcome home to 2515 Lansing Cir, a charming 2-sto ...',
    photo: '/assets/rentals/pearland/76005288.jpg',
    status: 'Pending',
  },
  {
    mls: '16943336',
    address: '2716 Pine Cone Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,495',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,331',
    acres: '0.212',
    yearBuilt: '1979',
    subdivision: 'Pine Shadows Pearland',
    county: 'Brazoria',
    remarks: 'Fantastic home in a wonderfully established neighb ...',
    photo: '/assets/rentals/pearland/16943336.jpg',
    status: 'Pending',
  },
  {
    mls: '65452102',
    address: '2422 Avilion Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$1,750',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1978',
    subdivision: 'Omersetshire Estates',
    county: 'Brazoria',
    remarks: 'RECENTLY REMODELED! Lovely 2 bedroom 2 bathroom ho ...',
    photo: '/assets/rentals/pearland/65452102.jpg',
    status: 'Active',
  },
  {
    mls: '94575748',
    address: '8305 Spinnaker Bay Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,475',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,206',
    acres: '0.173',
    yearBuilt: '1999',
    subdivision: 'Villages Of Edgewater Estates',
    county: 'Brazoria',
    remarks: '',
    photo: '/assets/rentals/pearland/94575748.jpg',
    status: 'Active',
  },
  {
    mls: '75900133',
    address: '2005 Post Oak Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,159',
    acres: '0.19',
    yearBuilt: '2017',
    subdivision: 'Avalon Terrace Sec 5 A0505 H',
    county: 'Brazoria',
    remarks: 'Gorgeous 4 bedroom, 2 full bath, 2 car garage home ...',
    photo: '/assets/rentals/pearland/75900133.jpg',
    status: 'Active',
  },
  {
    mls: '33421504',
    address: '2012 Roaring Springs Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,836',
    acres: '0.138',
    yearBuilt: '2005',
    subdivision: 'Shadow Creek Ranch Sf1-Sf2-Sf3',
    county: 'Brazoria',
    remarks: 'Beautiful 3/2/2 rental home opportunity in a GREAT ...',
    photo: '/assets/rentals/pearland/33421504.jpg',
    status: 'Active',
  },
  {
    mls: '12225668',
    address: '9615 Eden Ridge Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,291',
    acres: '0.195',
    yearBuilt: '2015',
    subdivision: 'Pearland Lakes Sec 1',
    county: 'Brazoria',
    remarks: 'Stunning house with 4 bedrooms, 3.5 baths and lake ...',
    photo: '/assets/rentals/pearland/12225668.jpg',
    status: 'Active',
  },
  {
    mls: '7594283',
    address: '2634 Arbor Hill Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,700',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,913',
    acres: '0.076',
    yearBuilt: '2004',
    subdivision: 'Silverlake Townhomes',
    county: 'Brazoria',
    remarks: 'Beautiful one story townhome in gated community wi ...',
    photo: '/assets/rentals/pearland/7594283.jpg',
    status: 'Active',
  },
  {
    mls: '62294547',
    address: '3105 W Trail Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,821',
    acres: '0.173',
    yearBuilt: '2011',
    subdivision: 'Southern Trails West Sec 3',
    county: 'Brazoria',
    remarks: 'Ready for immediate move-in! Washer, Dryer and Ref ...',
    photo: '/assets/rentals/pearland/62294547.jpg',
    status: 'Pending',
  },
  {
    mls: '88014966',
    address: '2216 Westminister Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,675',
    acres: '0.161',
    yearBuilt: '1991',
    subdivision: 'Banbury Cross Sec I-Ii-Iii-Iv',
    county: 'Brazoria',
    remarks: 'Welcome to this charming one-story home in Pearlan ...',
    photo: '/assets/rentals/pearland/88014966.jpg',
    status: 'Active',
  },
  {
    mls: '46589736',
    address: '2607 Letrim Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$3,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,220',
    acres: '0.22',
    yearBuilt: '2016',
    subdivision: 'Green Tee Terrace Sec 07',
    county: 'Harris',
    remarks: 'Beautiful 2016, one story, full brick home, by the ...',
    photo: '/assets/rentals/pearland/46589736.jpg',
    status: 'Pending',
  },
  {
    mls: '55895293',
    address: '4010 Spring Branch Drive W',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,808',
    acres: '0.162',
    yearBuilt: '1991',
    subdivision: 'Springfield Pearland',
    county: 'Brazoria',
    remarks: 'Welcome home to 4010 Spring Branch W! From the mom ...',
    photo: '/assets/rentals/pearland/55895293.jpg',
    status: 'Active',
  },
  {
    mls: '32718616',
    address: '5105 Redbud Valley Dr',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,857',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Massey Oaks Village',
    county: 'Brazoria',
    remarks: 'Welcome to this beautiful brand-new, never-lived-i ...',
    photo: '/assets/rentals/pearland/32718616.jpg',
    status: 'Active',
  },
  {
    mls: '18917754',
    address: '14108 Wedgewood Lakes Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,528',
    acres: '0.14',
    yearBuilt: '2020',
    subdivision: 'Shadow Grove Sec 6',
    county: 'Fort Bend',
    remarks: 'Welcome to the great community of Pearland! This s ...',
    photo: '/assets/rentals/pearland/18917754.jpg',
    status: 'Active',
  },
  {
    mls: '29845492',
    address: '9006 Sundown Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,225',
    acres: '0.158',
    yearBuilt: '2002',
    subdivision: 'Sunrise Lakes Sec 4',
    county: 'Brazoria',
    remarks: 'Welcome to this beautifully maintained, move-in re ...',
    photo: '/assets/rentals/pearland/29845492.jpg',
    status: 'Active',
  },
  {
    mls: '7253538',
    address: '3039 Orange Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,101',
    acres: '0.228',
    yearBuilt: '2004',
    subdivision: 'Creekside Sec 1',
    county: 'Brazoria',
    remarks: 'Well-maintained Pearland home available for immedi ...',
    photo: '/assets/rentals/pearland/7253538.jpg',
    status: 'Active',
  },
  {
    mls: '44826055',
    address: '13111 Rippling Creek Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,187',
    acres: '0.138',
    yearBuilt: '2006',
    subdivision: 'Shadow Creek Ranch Sf1-Sf2-Sf3',
    county: 'Brazoria',
    remarks: 'LOCATED IN HIGHLY SOUGHT AFTER MASTER ...',
    photo: '/assets/rentals/pearland/44826055.jpg',
    status: 'Active',
  },
  {
    mls: '18036134',
    address: '4711 Buescher Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,635',
    acres: '0.152',
    yearBuilt: '2003',
    subdivision: 'Parks At Walnut Bend',
    county: 'Brazoria',
    remarks: 'Charming single-story home available for immediate ...',
    photo: '/assets/rentals/pearland/18036134.jpg',
    status: 'Active',
  },
  {
    mls: '77793401',
    address: '2245 County Road 130',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,750',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,040',
    acres: '0.732',
    yearBuilt: '2023',
    subdivision: 'West Friendswood',
    county: 'Brazoria',
    remarks: 'https://apply.link/jG6BqeQ~Enjoy the comfort and c ...',
    photo: '/assets/rentals/pearland/77793401.jpg',
    status: 'Active',
  },
  {
    mls: '59062697',
    address: '2808 Arbor Brook Lane',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,195',
    acres: '0.132',
    yearBuilt: '2009',
    subdivision: 'Shadow Creek Ranch Sf1-Sf2-Sf3',
    county: 'Brazoria',
    remarks: 'Welcome to Shadow Creek Ranch in Pearland! This be ...',
    photo: '/assets/rentals/pearland/59062697.jpg',
    status: 'Active',
  },
  {
    mls: '77607284',
    address: '2411 Charter Oaks Court',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,545',
    acres: '0.172',
    yearBuilt: '1993',
    subdivision: 'Southwyck',
    county: 'Brazoria',
    remarks: 'Ready for move in! New paint 2026.6, New Carpet up ...',
    photo: '/assets/rentals/pearland/77607284.jpg',
    status: 'Active',
  },
  {
    mls: '80191140',
    address: '1820 Branch Hill Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,409',
    acres: '0.164',
    yearBuilt: '1996',
    subdivision: 'Oakbrook Estates Sec 1',
    county: 'Brazoria',
    remarks: 'Beautifully spacious 4/2.5/2 home with 2,400+ SF t ...',
    photo: '/assets/rentals/pearland/80191140.jpg',
    status: 'Active',
  },
  {
    mls: '91090396',
    address: '3417 Cypress Village Drive',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,690',
    acres: '0.138',
    yearBuilt: '2007',
    subdivision: 'Cypress Village Sec 1-2',
    county: 'Brazoria',
    remarks: 'Located in the heart of Pearland, this pristine 3- ...',
    photo: '/assets/rentals/pearland/91090396.jpg',
    status: 'Pending',
  },
  {
    mls: '24439204',
    address: '3318 Cotswald Trail',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,480',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,308',
    acres: '0.213',
    yearBuilt: '2001',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'Discover this beautifully updated two-story home n ...',
    photo: '/assets/rentals/pearland/24439204.jpg',
    status: 'Active',
  },
  {
    mls: '95598195',
    address: '1749 Max Road 4',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,550',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,120',
    acres: '',
    yearBuilt: '1981',
    subdivision: 'H T &amp; B R R',
    county: 'Brazoria',
    remarks: 'Welcome to this well-maintained 3-bedroom, 2-bath ...',
    photo: '/assets/rentals/pearland/95598195.jpg',
    status: 'Pending',
  },
  {
    mls: '94442713',
    address: '1138 Sussex Trail',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,308',
    acres: '0.139',
    yearBuilt: '1999',
    subdivision: 'Southdown Sub',
    county: 'Brazoria',
    remarks: 'Move in ready! Beautifully updated home in the des ...',
    photo: '/assets/rentals/pearland/94442713.jpg',
    status: 'Active',
  },
  {
    mls: '16330326',
    address: '11301 Misty Morning Street',
    city: 'Pearland',
    state: 'Texas',
    zip: '77584',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '3,000',
    acres: '0.24',
    yearBuilt: '2002',
    subdivision: 'Shadow Creek Ranch Sf-9b Pear',
    county: 'Brazoria',
    remarks: 'Price Improvement! Enjoy all the amenities of Shad ...',
    photo: '/assets/rentals/pearland/16330326.jpg',
    status: 'Active',
  },
  {
    mls: '91872758',
    address: '2222 N Austin Avenue 23',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '960',
    acres: '',
    yearBuilt: '2009',
    subdivision: 'H T &amp; B R R',
    county: 'Brazoria',
    remarks: 'Charming 2-bedroom, 2-bath trailer located in a gr ...',
    photo: '/assets/rentals/pearland/91872758.jpg',
    status: 'Active',
  },
  {
    mls: '73942805',
    address: '2603 Brom Bones Boulevard',
    city: 'Pearland',
    state: 'Texas',
    zip: '77581',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,252',
    acres: '0.459',
    yearBuilt: '1965',
    subdivision: 'Sleepy Hollow Pearland',
    county: 'Brazoria',
    remarks: 'Welcome to this well-maintained home in Pearland’s ...',
    photo: '/assets/rentals/pearland/73942805.jpg',
    status: 'Pending',
  },
]
