// Deer Park homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const deerparkRentListings: Listing[] = [
  {
    mls: '98133064',
    address: '3428 Hickory Ln Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,149',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,201',
    acres: '',
    yearBuilt: '1968',
    subdivision: 'Deer Park Manor',
    county: 'Harris',
    remarks: 'Fully renovated 3-bedroom, 2-bathroom home with 2- ...',
    photo: '/assets/rentals/deer-park/98133064.jpg',
    status: 'Active',
  },
  {
    mls: '88026393',
    address: '4210 Cork Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,396',
    acres: '0.162',
    yearBuilt: '1964',
    subdivision: 'Ridgeway Sec 02',
    county: 'Harris',
    remarks: 'Welcome to 4210 Cork! Your beautiful rental awaits ...',
    photo: '/assets/rentals/deer-park/88026393.jpg',
    status: 'Active',
  },
  {
    mls: '62408769',
    address: '1104 E 13th Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,827',
    acres: '0.152',
    yearBuilt: '1970',
    subdivision: 'Obrien Heights',
    county: 'Harris',
    remarks: 'Hard to find 4/2/2 in the heart of Deer Park. Clo ...',
    photo: '/assets/rentals/deer-park/62408769.jpg',
    status: 'Active',
  },
  {
    mls: '74935748',
    address: '4218 Ember Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,682',
    acres: '0.178',
    yearBuilt: '1960',
    subdivision: 'Ridge Way',
    county: 'Harris',
    remarks: 'Large 3 bedroom 2 bath home on a corner lot in Dee ...',
    photo: '/assets/rentals/deer-park/74935748.jpg',
    status: 'Active',
  },
  {
    mls: '18530925',
    address: '1505 New Orleans Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,588',
    acres: '0.178',
    yearBuilt: '1972',
    subdivision: 'Deer Meadows',
    county: 'Harris',
    remarks: 'A must see remodeled one story home in Deer Park. ...',
    photo: '/assets/rentals/deer-park/18530925.jpg',
    status: 'Active',
  },
  {
    mls: '90287071',
    address: '3414 Knob Hill Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,094',
    acres: '0.225',
    yearBuilt: '1974',
    subdivision: 'Meadowglen',
    county: 'Harris',
    remarks: 'Spacious 3-bedroom, 2-bath rental located in Deer ...',
    photo: '/assets/rentals/deer-park/90287071.jpg',
    status: 'Active',
  },
  {
    mls: '35127608',
    address: '1621 N Yellowstone Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,950',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,936',
    acres: '0.183',
    yearBuilt: '2002',
    subdivision: 'Park Place Sec 06 R P',
    county: 'Harris',
    remarks: 'Welcome to this pet friendly spacious two-story ho ...',
    photo: '/assets/rentals/deer-park/35127608.jpg',
    status: 'Active',
  },
  {
    mls: '93281558',
    address: '1242 Elm Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,050',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,647',
    acres: '0.115',
    yearBuilt: '2015',
    subdivision: 'Beverly Terrace',
    county: 'Harris',
    remarks: 'Well-kept home in the heart of Deer Park. Conveni ...',
    photo: '/assets/rentals/deer-park/93281558.jpg',
    status: 'Active',
  },
  {
    mls: '68313547',
    address: '1009 Wildwood Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,542',
    acres: '0.175',
    yearBuilt: '1985',
    subdivision: 'Erin Glen Sec 08',
    county: 'Harris',
    remarks: 'Beautiful remodeled 3-2-2 in beautiful Deer Park. ...',
    photo: '/assets/rentals/deer-park/68313547.jpg',
    status: 'Active',
  },
  {
    mls: '40388458',
    address: '4809 College Park Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,665',
    acres: '0.157',
    yearBuilt: '1964',
    subdivision: 'College Park Sec 01',
    county: 'Harris',
    remarks: 'COMING SOON! Beautiful home in Deer Park for rent. ...',
    photo: '/assets/rentals/deer-park/40388458.jpg',
    status: 'Active',
  },
  {
    mls: '56724794',
    address: '1113 E Amherst Lane',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,150',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,992',
    acres: '0.185',
    yearBuilt: '1968',
    subdivision: 'College Park',
    county: 'Harris',
    remarks: '4 Bedrooms 2 baths and 2 car detached garage in De ...',
    photo: '/assets/rentals/deer-park/56724794.jpg',
    status: 'Active',
  },
  {
    mls: '93326759',
    address: '120 W 12th Street A',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '900',
    acres: '0.459',
    yearBuilt: '2020',
    subdivision: 'Deer Park',
    county: 'Harris',
    remarks: 'Cute and very clean, This home has an open floor p ...',
    photo: '/assets/rentals/deer-park/93326759.jpg',
    status: 'Pending',
  },
  {
    mls: '49948746',
    address: '1805 Whitebriar Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,637',
    acres: '0.179',
    yearBuilt: '1982',
    subdivision: 'Westside Manor Sec 03',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated 4-bedroom, 2-b ...',
    photo: '/assets/rentals/deer-park/49948746.jpg',
    status: 'Pending',
  },
  {
    mls: '72292038',
    address: '2806 Spa Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,614',
    acres: '0.168',
    yearBuilt: '1967',
    subdivision: 'South Pasadena Plaza Sec 02',
    county: 'Harris',
    remarks: 'Located in Deer Park Ready for new home owner. Fre ...',
    photo: '/assets/rentals/deer-park/72292038.jpg',
    status: 'Active',
  },
  {
    mls: '17614850',
    address: '2802 White Sands Drive',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,695',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,803',
    acres: '0.132',
    yearBuilt: '2006',
    subdivision: 'East Park Sec 01',
    county: 'Harris',
    remarks: 'Welcome to beautiful 2802 White Sands Dr. This hom ...',
    photo: '/assets/rentals/deer-park/17614850.jpg',
    status: 'Active',
  },
  {
    mls: '53983547',
    address: '1124 E 13th Street',
    city: 'Deer Park',
    state: 'Texas',
    zip: '77536',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,730',
    acres: '0.157',
    yearBuilt: '1970',
    subdivision: 'Obrien Heights Sec 01',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/deer-park/53983547.jpg',
    status: 'Active',
  },
]
