// Friendswood homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const friendswoodRentListings: Listing[] = [
  {
    mls: '41657039',
    address: '428 Old Course Dr',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,635',
    acres: '',
    yearBuilt: '1984',
    subdivision: 'Sunmeadow',
    county: 'Galveston',
    remarks: 'Welcome to this affordable home in established Fri ...',
    photo: '/assets/rentals/friendswood/41657039.jpg',
    status: 'Active',
  },
  {
    mls: '74897272',
    address: '2714 Safe Harbour Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,550',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,459',
    acres: '0.152',
    yearBuilt: '1997',
    subdivision: 'Heritage Park Sec 21',
    county: 'Harris',
    remarks: 'Looking for room to spread out? This spacious 4-be ...',
    photo: '/assets/rentals/friendswood/74897272.jpg',
    status: 'Active',
  },
  {
    mls: '38684335',
    address: '513 Meadow Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,800',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,577',
    acres: '0.262',
    yearBuilt: '1998',
    subdivision: 'The Forest Sec 1 99',
    county: 'Galveston',
    remarks: 'Thoughtfully remodeled home in The Forest of Frien ...',
    photo: '/assets/rentals/friendswood/38684335.jpg',
    status: 'Active',
  },
  {
    mls: '61433570',
    address: '2006 Pebble Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,800',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,041',
    acres: '0.28',
    yearBuilt: '1997',
    subdivision: 'Eagle Lakes Sec 5 96',
    county: 'Galveston',
    remarks: 'Step inside to discover soaring high ceilings, abu ...',
    photo: '/assets/rentals/friendswood/61433570.jpg',
    status: 'Active',
  },
  {
    mls: '61424596',
    address: '16738 Barcelona Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,900',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,473',
    acres: '',
    yearBuilt: '1973',
    subdivision: 'Forest Bend #1-6',
    county: 'Harris',
    remarks: 'Charming single-family home located in the peacefu ...',
    photo: '/assets/rentals/friendswood/61424596.jpg',
    status: 'Active',
  },
  {
    mls: '92906016',
    address: '3830 Misty Falls Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,450',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,742',
    acres: '0.145',
    yearBuilt: '2004',
    subdivision: 'Heritage Park Sec 27',
    county: 'Harris',
    remarks: 'Beautiful 4-Bedroom Home in Friendswood!Welcome ho ...',
    photo: '/assets/rentals/friendswood/92906016.jpg',
    status: 'Active',
  },
  {
    mls: '86152214',
    address: '523 Gleneagles Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,480',
    acres: '0.224',
    yearBuilt: '1984',
    subdivision: 'Sunmeadow',
    county: 'Galveston',
    remarks: 'Large open living room, fireplace and dining room. ...',
    photo: '/assets/rentals/friendswood/86152214.jpg',
    status: 'Active',
  },
  {
    mls: '9879867',
    address: '509 Belmont Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,918',
    acres: '0.219',
    yearBuilt: '1976',
    subdivision: 'Sunmeadow 2',
    county: 'Galveston',
    remarks: 'Welcome to 509 Belmont in Friendswood, located in ...',
    photo: '/assets/rentals/friendswood/9879867.jpg',
    status: 'Active',
  },
  {
    mls: '33927545',
    address: '16702 Sheet Bend Way',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,860',
    acres: '0.174',
    yearBuilt: '1983',
    subdivision: 'Heritage Park Sec 07',
    county: 'Harris',
    remarks: 'Beautiful and updated tastefully- 4-bedroom 2 bath ...',
    photo: '/assets/rentals/friendswood/33927545.jpg',
    status: 'Active',
  },
  {
    mls: '68177296',
    address: '1408 S Friendswood Drive 205',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,957',
    acres: '0.054',
    yearBuilt: '2003',
    subdivision: 'Ashford Village Twnhms',
    county: 'Galveston',
    remarks: 'Beautiful 3-bedroom, 2.5 Bathroom townhome for lea ...',
    photo: '/assets/rentals/friendswood/68177296.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '63512630',
    address: '111 Dunbar Estates Drive 804',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,450',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '728',
    acres: '0.112',
    yearBuilt: '1984',
    subdivision: 'Walden Pond Twnhms',
    county: 'Galveston',
    remarks: 'Cute and Fresh 2 bedroom - 1 bath Townhome availab ...',
    photo: '/assets/rentals/friendswood/63512630.jpg',
    status: 'Active',
  },
  {
    mls: '57382550',
    address: '2406 Pilgrims Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,517',
    acres: '0.146',
    yearBuilt: '1981',
    subdivision: 'Heritage Park Sec 07',
    county: 'Harris',
    remarks: 'Welcome to this three-bedroom, two-bathroom home i ...',
    photo: '/assets/rentals/friendswood/57382550.jpg',
    status: 'Active',
  },
  {
    mls: '33056716',
    address: '16510 Oxnard Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,972',
    acres: '0.335',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village Sec 06 R/P',
    county: 'Harris',
    remarks: 'Take a look at this great one story Home on a mass ...',
    photo: '/assets/rentals/friendswood/33056716.jpg',
    status: 'Active',
  },
  {
    mls: '35219775',
    address: '16806 Tibet Road',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,675',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,137',
    acres: '0.139',
    yearBuilt: '1971',
    subdivision: 'Forest Bend',
    county: 'Harris',
    remarks: 'Updated 3 bedroom 2 bath in Forest Bend. Tile floo ...',
    photo: '/assets/rentals/friendswood/35219775.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '75193324',
    address: '15919 Blue Mesa Ridge Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,199',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,905',
    acres: '0.149',
    yearBuilt: '1992',
    subdivision: 'Heritage Park Sec 17 Amd',
    county: 'Harris',
    remarks: 'Welcome to this well-maintained 3-bedroom, 2.5-bat ...',
    photo: '/assets/rentals/friendswood/75193324.jpg',
    status: 'Active',
  },
  {
    mls: '62147279',
    address: '2804 Creek Bend Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,945',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,384',
    acres: '0.2',
    yearBuilt: '2000',
    subdivision: 'Autumn Creek Sec 02',
    county: 'Harris',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/friendswood/62147279.jpg',
    status: 'Active',
  },
  {
    mls: '81076152',
    address: '2318 Colonial Ridge Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,975',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,550',
    acres: '0.145',
    yearBuilt: '1979',
    subdivision: 'Heritage Park Sec 06',
    county: 'Harris',
    remarks: 'CHARMING 3 BEDROOM, 2 BATH & 2 CAR GAR ...',
    photo: '/assets/rentals/friendswood/81076152.jpg',
    status: 'Active',
  },
  {
    mls: '73901390',
    address: '16614 Blackhawk Boulevard',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,692',
    acres: '0.165',
    yearBuilt: '1974',
    subdivision: 'Forest Bend',
    county: 'Harris',
    remarks: 'This MOVE-IN READY 3-bedroom, 2-bath home offers a ...',
    photo: '/assets/rentals/friendswood/73901390.jpg',
    status: 'Active',
  },
  {
    mls: '6227820',
    address: '4727 Heritage Country Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,166',
    acres: '0.149',
    yearBuilt: '1989',
    subdivision: 'Heritage Park Sec 08 R/P',
    county: 'Harris',
    remarks: 'Welcome to the sought-after Heritage Park communit ...',
    photo: '/assets/rentals/friendswood/6227820.jpg',
    status: 'Active',
  },
  {
    mls: '62451621',
    address: '15322 Wandering Trail',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,975',
    acres: '0.339',
    yearBuilt: '1969',
    subdivision: 'Wedgewood Village Sec 01',
    county: 'Harris',
    remarks: 'This spacious 3-bedroom home on a HUGE lot is read ...',
    photo: '/assets/rentals/friendswood/62451621.jpg',
    status: 'Pending',
  },
  {
    mls: '2938923',
    address: '2875 Wimbledon Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,324',
    acres: '0.269',
    yearBuilt: '2002',
    subdivision: 'Windsor Estates Sec 2 2000',
    county: 'Galveston',
    remarks: 'Situated on just over a quarter-acre lot in desira ...',
    photo: '/assets/rentals/friendswood/2938923.jpg',
    status: 'Active',
  },
  {
    mls: '22757521',
    address: '16814 Square Rigger Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,350',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,864',
    acres: '0.223',
    yearBuilt: '1984',
    subdivision: 'Heritage Park Sec 10',
    county: 'Harris',
    remarks: 'Move-in ready home for rent in Friendswood, Texas! ...',
    photo: '/assets/rentals/friendswood/22757521.jpg',
    status: 'Active',
  },
  {
    mls: '18993343',
    address: '403 Brandywyne Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,721',
    acres: '0.3',
    yearBuilt: '1966',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'Appointment Required. Supra Front Door. VACANT. ...',
    photo: '/assets/rentals/friendswood/18993343.jpg',
    status: 'Pending',
  },
  {
    mls: '66274163',
    address: '16414 Paint Rock Road',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,923',
    acres: '0.209',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village Sec 06 R/P',
    county: 'Harris',
    remarks: 'Welcome to 16414 Paint Rock Rd in Friendswood! Thi ...',
    photo: '/assets/rentals/friendswood/66274163.jpg',
    status: 'Active',
  },
  {
    mls: '33024264',
    address: '108 Annette Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,336',
    acres: '0.288',
    yearBuilt: '1970',
    subdivision: 'Anna Alea',
    county: 'Galveston',
    remarks: 'Now available for lease in Friendswood ISD! This c ...',
    photo: '/assets/rentals/friendswood/33024264.jpg',
    status: 'Active',
  },
  {
    mls: '69254345',
    address: '1016 Glenshannon Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,997',
    acres: '0.297',
    yearBuilt: '1983',
    subdivision: 'Glenshannon',
    county: 'Galveston',
    remarks: 'Come see this beautiful 4 bedroom 2.5 bathroom hom ...',
    photo: '/assets/rentals/friendswood/69254345.jpg',
    status: 'Active',
  },
  {
    mls: '8800529',
    address: '16306 Forest Bend Avenue',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,660',
    acres: '0.149',
    yearBuilt: '1976',
    subdivision: 'Wedgewood Village',
    county: 'Harris',
    remarks: 'Just refreshed: painted throughout, new tile in ki ...',
    photo: '/assets/rentals/friendswood/8800529.jpg',
    status: 'Active',
  },
  {
    mls: '74521136',
    address: '17134 Barcelona Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,371',
    acres: '0.16',
    yearBuilt: '1974',
    subdivision: 'Forest Bend Sec 03',
    county: 'Harris',
    remarks: 'Beautifully updated 3 bedroom / 2bath. Ready for o ...',
    photo: '/assets/rentals/friendswood/74521136.jpg',
    status: 'Active',
  },
  {
    mls: '85320615',
    address: '3714 Townes Forest Road',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,650',
    acres: '0.179',
    yearBuilt: '1973',
    subdivision: 'Forest Bend Sec 06',
    county: 'Harris',
    remarks: 'Immaculately updated 4-bedroom, 2-bath home for le ...',
    photo: '/assets/rentals/friendswood/85320615.jpg',
    status: 'Active',
  },
  {
    mls: '37721658',
    address: '3846 Clobourne Crossing Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,320',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,244',
    acres: '0.165',
    yearBuilt: '2004',
    subdivision: 'Heritage Park Sec 28',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/friendswood/37721658.jpg',
    status: 'Active',
  },
  {
    mls: '51720536',
    address: '717 Cedarwood',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,395',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,401',
    acres: '0.044',
    yearBuilt: '2003',
    subdivision: 'Cedarwood Town Homes',
    county: 'Galveston',
    remarks: 'AFFORDABLE, ADORABLE & CLEAN 3/2/2 SI ...',
    photo: '/assets/rentals/friendswood/51720536.jpg',
    status: 'Active',
  },
  {
    mls: '73355262',
    address: '118 Tower Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,576',
    acres: '0.449',
    yearBuilt: '2011',
    subdivision: 'Tower Estates',
    county: 'Galveston',
    remarks: 'Nice 4-bedroom 2 bath home on 1/2 acre in Friendsw ...',
    photo: '/assets/rentals/friendswood/73355262.jpg',
    status: 'Active',
  },
  {
    mls: '78020913',
    address: '1408 S Friendswood Drive 804',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,966',
    acres: '0.054',
    yearBuilt: '2000',
    subdivision: 'Ashford Village Twnhms',
    county: 'Galveston',
    remarks: 'Available Now! Stunning 3-bed, 3-bath townhome loc ...',
    photo: '/assets/rentals/friendswood/78020913.jpg',
    status: 'Pending',
  },
  {
    mls: '20121158',
    address: '16619 Tibet Road',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '',
    acres: '0.164',
    yearBuilt: '1973',
    subdivision: 'Forest Bend Sec 06',
    county: 'Harris',
    remarks: 'Welcome to this charming 4-bedroom, 2-full bath ho ...',
    photo: '/assets/rentals/friendswood/20121158.jpg',
    status: 'Active',
  },
  {
    mls: '98753131',
    address: '59 Hideaway Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,250',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,590',
    acres: '0.037',
    yearBuilt: '1990',
    subdivision: 'Hidden Cove Condo',
    county: 'Galveston',
    remarks: 'Tucked beneath a canopy of mature trees in one of ...',
    photo: '/assets/rentals/friendswood/98753131.jpg',
    status: 'Active',
  },
  {
    mls: '44784101',
    address: '1567 Harvest Vine Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,950',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,353',
    acres: '0.158',
    yearBuilt: '2020',
    subdivision: 'Commercial Secs 1 2',
    county: 'Galveston',
    remarks: 'Welcome Home, a spacious two-story home offering 5 ...',
    photo: '/assets/rentals/friendswood/44784101.jpg',
    status: 'Active',
  },
  {
    mls: '10504483',
    address: '16030 Blackhawk Boulevard',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,696',
    acres: '0.18',
    yearBuilt: '1974',
    subdivision: 'Wedgewood Village Sec 05',
    county: 'Harris',
    remarks: 'New paint throughout whole house. Tile flooring t ...',
    photo: '/assets/rentals/friendswood/10504483.jpg',
    status: 'Active',
  },
  {
    mls: '40285244',
    address: '2412 N Mission Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,695',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,483',
    acres: '0.181',
    yearBuilt: '1992',
    subdivision: 'Carmel Village Sec Ii 92',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully maintained 4-bedroom, ...',
    photo: '/assets/rentals/friendswood/40285244.jpg',
    status: 'Active',
  },
  {
    mls: '97274299',
    address: '3811 Misty Falls Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,700',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,200',
    acres: '0.172',
    yearBuilt: '2003',
    subdivision: 'Heritage Park',
    county: 'Harris',
    remarks: 'This beautiful 5 bedrooms, 3.5 bathrooms, complete ...',
    photo: '/assets/rentals/friendswood/97274299.jpg',
    status: 'Active',
  },
  {
    mls: '54785533',
    address: '103 Brigadoon Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,441',
    acres: '0.276',
    yearBuilt: '1975',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'Look no further for your perfect lease home! This ...',
    photo: '/assets/rentals/friendswood/54785533.jpg',
    status: 'Active',
  },
  {
    mls: '30196477',
    address: '5115 Tashkent Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,695',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,440',
    acres: '0.179',
    yearBuilt: '1968',
    subdivision: 'Wedgewood Village Sec 01',
    county: 'Harris',
    remarks: 'Nestled in a welcoming community with top-rated sc ...',
    photo: '/assets/rentals/friendswood/30196477.jpg',
    status: 'Active',
  },
  {
    mls: '20793609',
    address: '4710 Meadowthorn Court',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,186',
    acres: '0.158',
    yearBuilt: '2003',
    subdivision: 'Heritage Park Sec 27',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/friendswood/20793609.jpg',
    status: 'Active',
  },
  {
    mls: '79604623',
    address: '15815 Pilgrim Hall Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,855',
    acres: '0.154',
    yearBuilt: '1990',
    subdivision: 'Heritage Park Sec 13',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated 3-bedroom, 2-b ...',
    photo: '/assets/rentals/friendswood/79604623.jpg',
    status: 'Active',
  },
  {
    mls: '98435339',
    address: '2106 Villa Flora Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,211',
    acres: '0.144',
    yearBuilt: '2026',
    subdivision: 'Beamer Villas',
    county: 'Harris',
    remarks: 'Beautiful new construction home in Beamer Villas f ...',
    photo: '/assets/rentals/friendswood/98435339.jpg',
    status: 'Active',
  },
  {
    mls: '54982062',
    address: '509 Avondale Lane',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,850',
    beds: '0 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,116',
    acres: '0.148',
    yearBuilt: '1970',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/54982062.jpg',
    status: 'Active',
  },
  {
    mls: '49605612',
    address: '2715 Sailors Moon Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,195',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,503',
    acres: '0.151',
    yearBuilt: '1994',
    subdivision: 'Heritage Park Sec 20',
    county: 'Harris',
    remarks: 'Neatly kept 3 bedroom home on a culdesac in Herita ...',
    photo: '/assets/rentals/friendswood/49605612.jpg',
    status: 'Pending',
  },
  {
    mls: '27565284',
    address: '16631 Blackhawk Boulevard',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,317',
    acres: '0.172',
    yearBuilt: '1975',
    subdivision: 'Forest Bend Sec 06',
    county: 'Harris',
    remarks: 'BEAUTIFULLY UPDATED and move-in ready! This charmi ...',
    photo: '/assets/rentals/friendswood/27565284.jpg',
    status: 'Active',
  },
  {
    mls: '44283818',
    address: '807 Stadium Circle',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,646',
    acres: '0.26',
    yearBuilt: '1970',
    subdivision: 'Anna Alea Kingspark/Whitehall',
    county: 'Galveston',
    remarks: 'Welcome to 807 Stadium Circle, a truly one-of-a-ki ...',
    photo: '/assets/rentals/friendswood/44283818.jpg',
    status: 'Active',
  },
  {
    mls: '39088585',
    address: '64 Hideaway Drive',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$2,200',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,599',
    acres: '0.037',
    yearBuilt: '1990',
    subdivision: 'Hidden Cove Condo',
    county: 'Galveston',
    remarks: 'Gorgeous 1.5-story condo in Hidden Cove — bright, ...',
    photo: '/assets/rentals/friendswood/39088585.jpg',
    status: 'Active',
  },
  {
    mls: '16574989',
    address: '19100 N Glenwest Drive 233',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,870',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,099',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/16574989.jpg',
    status: 'Active',
  },
  {
    mls: '46917093',
    address: '19100 N Glenwest Drive 1132',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,870',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,099',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/46917093.jpg',
    status: 'Active',
  },
  {
    mls: '43658783',
    address: '19100 N Glenwest Drive 328',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,850',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,095',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/43658783.jpg',
    status: 'Active',
  },
  {
    mls: '11289832',
    address: '19100 N Glenwest Drive 238',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,870',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,099',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/11289832.jpg',
    status: 'Active',
  },
  {
    mls: '86187409',
    address: '19100 N Glenwest Drive 627',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,805',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,099',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/86187409.jpg',
    status: 'Active',
  },
  {
    mls: '95611488',
    address: '19100 N Glenwest Drive 211',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,480',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '802',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/95611488.jpg',
    status: 'Active',
  },
  {
    mls: '39140649',
    address: '19100 N Glenwest Drive 437',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,360',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '711',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/39140649.jpg',
    status: 'Active',
  },
  {
    mls: '39631179',
    address: '19100 N Glenwest Drive 1213',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,360',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '643',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/39631179.jpg',
    status: 'Active',
  },
  {
    mls: '7631961',
    address: '19100 N Glenwest Drive 722',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,380',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '711',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/7631961.jpg',
    status: 'Active',
  },
  {
    mls: '85248863',
    address: '19100 N Glenwest Drive 936',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,410',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '711',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/85248863.jpg',
    status: 'Active',
  },
  {
    mls: '88544113',
    address: '19100 N Glenwest Drive 932',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,410',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '711',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/88544113.jpg',
    status: 'Active',
  },
  {
    mls: '4926406',
    address: '19100 N Glenwest Drive 236',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,480',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '802',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/4926406.jpg',
    status: 'Active',
  },
  {
    mls: '44068526',
    address: '19100 N Glenwest Drive 1135',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,480',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '802',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/44068526.jpg',
    status: 'Active',
  },
  {
    mls: '90779867',
    address: '19100 N Glenwest Drive 221',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,480',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '711',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/90779867.jpg',
    status: 'Active',
  },
  {
    mls: '87746407',
    address: '19100 N Glenwest Drive 1327',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,360',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '643',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/87746407.jpg',
    status: 'Active',
  },
  {
    mls: '10290799',
    address: '19100 N Glenwest Drive 1337',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,360',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '643',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/10290799.jpg',
    status: 'Active',
  },
  {
    mls: '83068898',
    address: '19100 N Glenwest Drive 1332',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,360',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '643',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/83068898.jpg',
    status: 'Active',
  },
  {
    mls: '40115426',
    address: '19100 N Glenwest Drive 210',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,480',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '802',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/40115426.jpg',
    status: 'Active',
  },
  {
    mls: '13972769',
    address: '19100 N Glenwest Drive 1033',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,360',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '643',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/13972769.jpg',
    status: 'Active',
  },
  {
    mls: '18944148',
    address: '19100 N Glenwest Drive 321',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,780',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,095',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/18944148.jpg',
    status: 'Active',
  },
  {
    mls: '34214821',
    address: '19100 N Glenwest Drive 332',
    city: 'Friendswood',
    state: 'Texas',
    zip: '77546',
    price: '$1,410',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '711',
    acres: '',
    yearBuilt: '1999',
    subdivision: '',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/friendswood/34214821.jpg',
    status: 'Active',
  },
]
