// League City homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const leaguecityRentListings: Listing[] = [
  {
    mls: '64408363',
    address: '1206 Halls Bridge',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,370',
    acres: '0.154',
    yearBuilt: '2004',
    subdivision: 'Halls Bridge 2004',
    county: 'Galveston',
    remarks: 'Immaculate, clean home fully remodeled and ready f ...',
    photo: '/assets/rentals/league-city/64408363.jpg',
    status: 'Active',
  },
  {
    mls: '40784385',
    address: '2123 Hollow Reef Circle',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,750',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,446',
    acres: '0.183',
    yearBuilt: '1992',
    subdivision: 'Harbour Park Sec 4 91',
    county: 'Galveston',
    remarks: 'Spacious 3-bedroom home with a dedicated office th ...',
    photo: '/assets/rentals/league-city/40784385.jpg',
    status: 'Pending',
  },
  {
    mls: '41595883',
    address: '3301 Elm Creek Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,750',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,988',
    acres: '0.245',
    yearBuilt: '2004',
    subdivision: 'Park On Clear Creek',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/league-city/41595883.jpg',
    status: 'Active',
  },
  {
    mls: '40098497',
    address: '6102 Timbermoss Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$4,000',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,778',
    acres: '0.18',
    yearBuilt: '2006',
    subdivision: 'Westover Park',
    county: 'Galveston',
    remarks: 'Enjoy an exceptional quality of living in this bea ...',
    photo: '/assets/rentals/league-city/40098497.jpg',
    status: 'Active',
  },
  {
    mls: '38064053',
    address: '6156 Flint Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,191',
    acres: '0.142',
    yearBuilt: '2011',
    subdivision: 'Westover Park Sec Sec 13a',
    county: 'Galveston',
    remarks: 'Welcome to this spacious two-story home with a spl ...',
    photo: '/assets/rentals/league-city/38064053.jpg',
    status: 'Active',
  },
  {
    mls: '18853189',
    address: '2200 Beacon Circle',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,544',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '736',
    acres: '',
    yearBuilt: '2022',
    subdivision: 'Beacon Island',
    county: 'Galveston',
    remarks: 'Wake up to breathtaking waterfront views in this b ...',
    photo: '/assets/rentals/league-city/18853189.jpg',
    status: 'Active',
  },
  {
    mls: '38663188',
    address: '1109 E Walker Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,849',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,490',
    acres: '0.12',
    yearBuilt: '1954',
    subdivision: 'Walker',
    county: 'Galveston',
    remarks: 'Welcome to this quaint 4 bedroom, 2 bathroom home, ...',
    photo: '/assets/rentals/league-city/38663188.jpg',
    status: 'Active',
  },
  {
    mls: '2044290',
    address: '1931 Enterprise Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,400',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,944',
    acres: '0.083',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour 2 Townhome',
    county: 'Galveston',
    remarks: 'WATERFRONT LUXURY IN HARBOUR ISLAND Experience coa ...',
    photo: '/assets/rentals/league-city/2044290.jpg',
    status: 'Active',
  },
  {
    mls: '94411255',
    address: '2714 Ahnya Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,056',
    acres: '0.172',
    yearBuilt: '2019',
    subdivision: 'Tuscan Lakes',
    county: 'Galveston',
    remarks: 'Super Clean Westin Home w/ no back neighbors, priv ...',
    photo: '/assets/rentals/league-city/94411255.jpg',
    status: 'Active',
  },
  {
    mls: '43813007',
    address: '4765 Oakmont Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,805',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,580',
    acres: '0.113',
    yearBuilt: '1986',
    subdivision: 'South Shore Harbour Golf Cours',
    county: 'Galveston',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/league-city/43813007.jpg',
    status: 'Active',
  },
  {
    mls: '67762459',
    address: '1723 Enterprise Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,900',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,868',
    acres: '0.083',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour 2 Townhome',
    county: 'Galveston',
    remarks: 'Stunning corner-unit home in the gated waterfront ...',
    photo: '/assets/rentals/league-city/67762459.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '55514913',
    address: '2777 Forest Point Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,995',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,490',
    acres: '0.142',
    yearBuilt: '1982',
    subdivision: 'Meadow Bend 2',
    county: 'Galveston',
    remarks: 'Please submit a TAR application for each adult ove ...',
    photo: '/assets/rentals/league-city/55514913.jpg',
    status: 'Active',
  },
  {
    mls: '12311461',
    address: '602 N Michigan',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,500',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '624',
    acres: '',
    yearBuilt: '1955',
    subdivision: 'League City Townsite Blk 1-48',
    county: 'Galveston',
    remarks: 'WELCOME HOME!!!!! Very nice recently fully remodel ...',
    photo: '/assets/rentals/league-city/12311461.jpg',
    status: 'Active',
  },
  {
    mls: '75550574',
    address: '229 E Saunders Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,850',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,460',
    acres: '0.35',
    yearBuilt: '1900',
    subdivision: 'Perkins Ella',
    county: 'Galveston',
    remarks: '*Charming home in League City! This home has 2 ful ...',
    photo: '/assets/rentals/league-city/75550574.jpg',
    status: 'Active',
  },
  {
    mls: '12793216',
    address: '3011 Monticello Pines Ln Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,836',
    acres: '0.141',
    yearBuilt: '2014',
    subdivision: 'Hidden Lakes Sec 3 Ph 1 2014',
    county: 'Galveston',
    remarks: 'Welcome to this stunning 4-bed, 2.5-bath rental in ...',
    photo: '/assets/rentals/league-city/12793216.jpg',
    status: 'Active',
  },
  {
    mls: '89700100',
    address: '1306 2nd Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,611',
    acres: '0.177',
    yearBuilt: '1973',
    subdivision: 'Cross Rep',
    county: 'Galveston',
    remarks: 'Beautifully updated 3 bedroom 2 full bath, one sto ...',
    photo: '/assets/rentals/league-city/89700100.jpg',
    status: 'Active',
  },
  {
    mls: '66304251',
    address: '6165 Darlington Ct Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,570',
    acres: '0.174',
    yearBuilt: '2004',
    subdivision: 'Westover Park Sec 3 2003',
    county: 'Galveston',
    remarks: 'Desirable community and exceptional value! This ch ...',
    photo: '/assets/rentals/league-city/66304251.jpg',
    status: 'Active',
  },
  {
    mls: '29902328',
    address: '3133 Moonlit Lake Circle',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,298',
    acres: '0.172',
    yearBuilt: '1993',
    subdivision: 'South Shore Village Sec 3 93',
    county: 'Galveston',
    remarks: 'Beautiful 3-bedroom, 2-bath home on a quiet cul-de ...',
    photo: '/assets/rentals/league-city/29902328.jpg',
    status: 'Active',
  },
  {
    mls: '86670896',
    address: '1833 Oriole Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,325',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '816',
    acres: '',
    yearBuilt: '1973',
    subdivision: 'Clear Creek Heights',
    county: 'Galveston',
    remarks: 'Two bedroom, one bath home with central air and he ...',
    photo: '/assets/rentals/league-city/86670896.jpg',
    status: 'Active',
  },
  {
    mls: '45851771',
    address: '787 Davis Road',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,864',
    acres: '0.025',
    yearBuilt: '1979',
    subdivision: 'Wharf At Clear Lake Ph 2 To',
    county: 'Galveston',
    remarks: 'Welcome to this move-in ready meticulously maintai ...',
    photo: '/assets/rentals/league-city/45851771.jpg',
    status: 'Active',
  },
  {
    mls: '61783319',
    address: '2111 Riverside Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,950',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,358',
    acres: '0.21',
    yearBuilt: '1989',
    subdivision: 'South Shore Harbour 10 89',
    county: 'Galveston',
    remarks: 'Welcome to 2111 Riverside in the gated South Shore ...',
    photo: '/assets/rentals/league-city/61783319.jpg',
    status: 'Active',
  },
  {
    mls: '52254468',
    address: '2210 Bay Haven Way',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,276',
    acres: '0.173',
    yearBuilt: '1994',
    subdivision: 'Marina Bay Park Sec 2 Ph 2',
    county: 'Galveston',
    remarks: 'Welcome home to this beautiful 4-bedroom, 2.5-bath ...',
    photo: '/assets/rentals/league-city/52254468.jpg',
    status: 'Active',
  },
  {
    mls: '81162093',
    address: '4713 La Escalona Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,252',
    acres: '0.177',
    yearBuilt: '2010',
    subdivision: 'Mar Bella Sec 10a 2010',
    county: 'Galveston',
    remarks: 'This stunning 4-bedroom, 3-bathroom single-story h ...',
    photo: '/assets/rentals/league-city/81162093.jpg',
    status: 'Pending',
  },
  {
    mls: '16350897',
    address: '876 Schooner Cove Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,550',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,965',
    acres: '0.149',
    yearBuilt: '2004',
    subdivision: 'South Shore Harbour Sec Sf 50',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/league-city/16350897.jpg',
    status: 'Active',
  },
  {
    mls: '46177317',
    address: '601 Dunlavy Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,995',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,053',
    acres: '0.165',
    yearBuilt: '2013',
    subdivision: 'Westover Park Sec 13 B 2012',
    county: 'Galveston',
    remarks: 'Welcome home to this beautiful 3 bedroom, 2 bathro ...',
    photo: '/assets/rentals/league-city/46177317.jpg',
    status: 'Active',
  },
  {
    mls: '70503772',
    address: '2905 Summer Cape Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,279',
    acres: '0.192',
    yearBuilt: '2007',
    subdivision: 'South Shore Harbour',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully updated Perry Homes on ...',
    photo: '/assets/rentals/league-city/70503772.jpg',
    status: 'Active',
  },
  {
    mls: '92896287',
    address: '321 Westwood Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,986',
    acres: '0.167',
    yearBuilt: '2013',
    subdivision: 'Westwood Sub Ph 1 2007',
    county: 'Galveston',
    remarks: 'Warm and welcoming 1.5-story Gehan Harvard plan in ...',
    photo: '/assets/rentals/league-city/92896287.jpg',
    status: 'Active',
  },
  {
    mls: '33114423',
    address: '2016 Cottage Bridge Road',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,350',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,393',
    acres: '0.144',
    yearBuilt: '2024',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'Lennar Lavender floor plan, a highly sought single ...',
    photo: '/assets/rentals/league-city/33114423.jpg',
    status: 'Active',
  },
  {
    mls: '65382328',
    address: '6544 Turner Fields Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,855',
    acres: '',
    yearBuilt: '2015',
    subdivision: 'Bay Colony Meadows West',
    county: 'Galveston',
    remarks: 'Welcome to this charming one-story home in the des ...',
    photo: '/assets/rentals/league-city/65382328.jpg',
    status: 'Pending',
  },
  {
    mls: '45946379',
    address: '3209 Youngs Meadow Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$2,210',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '1,772',
    acres: '0.17',
    yearBuilt: '2018',
    subdivision: 'Bay Colony Mdws West Ph 2 Sec',
    county: 'Galveston',
    remarks: 'Charming 4 bedroom and 3.5 bathroom home updated w ...',
    photo: '/assets/rentals/league-city/45946379.jpg',
    status: 'Active',
  },
  {
    mls: '89327209',
    address: '1327 Graham Trace Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,750',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,679',
    acres: '0.194',
    yearBuilt: '2016',
    subdivision: 'Hidden Lakes Sec 1 2009',
    county: 'Galveston',
    remarks: 'Welcome to this meticulously maintained house in a ...',
    photo: '/assets/rentals/league-city/89327209.jpg',
    status: 'Active',
  },
  {
    mls: '11759491',
    address: '2535 Flycatcher Cove Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,364',
    acres: '0.169',
    yearBuilt: '2005',
    subdivision: 'Brittany Lakes Sec 11 2005',
    county: 'Galveston',
    remarks: 'This Charming 4-Bedroom Home in Brittany Lakes wi ...',
    photo: '/assets/rentals/league-city/11759491.jpg',
    status: 'Active',
  },
  {
    mls: '23010790',
    address: '5301 Carefree Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,060',
    acres: '0.161',
    yearBuilt: '2002',
    subdivision: 'Countryside Sec 4',
    county: 'Galveston',
    remarks: 'Beautiful one-story home featuring 4 bedrooms, 2 b ...',
    photo: '/assets/rentals/league-city/23010790.jpg',
    status: 'Active',
  },
  {
    mls: '47826829',
    address: '409 Seacrest Boulevard',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,335',
    acres: '0.164',
    yearBuilt: '1983',
    subdivision: 'Bay Ridge Sec 3',
    county: 'Galveston',
    remarks: 'Beautifully updated 4-bedroom, 2.5-bath home featu ...',
    photo: '/assets/rentals/league-city/47826829.jpg',
    status: 'Active',
  },
  {
    mls: '90391801',
    address: '3008 Middletrace Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,092',
    acres: '0.226',
    yearBuilt: '2008',
    subdivision: 'Bay Colony Meadows West Sec 1',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/league-city/90391801.jpg',
    status: 'Active',
  },
  {
    mls: '81807437',
    address: '200 Pecan Drive 702',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,295',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,238',
    acres: '0.018',
    yearBuilt: '1984',
    subdivision: 'Pecan Forest Village Twnhms',
    county: 'Galveston',
    remarks: 'Refreshed two bedroom two bath with a loft in leag ...',
    photo: '/assets/rentals/league-city/81807437.jpg',
    status: 'Active',
  },
  {
    mls: '53901191',
    address: '5113 Orange Blossom Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,420',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,845',
    acres: '0.164',
    yearBuilt: '1999',
    subdivision: 'Countryside Sec 4',
    county: 'Galveston',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/league-city/53901191.jpg',
    status: 'Active',
  },
  {
    mls: '8917410',
    address: '121 Misty Brook Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,790',
    acres: '0.236',
    yearBuilt: '1979',
    subdivision: 'Countryside Sec 2/Countryside',
    county: 'Galveston',
    remarks: 'Beautiful ranch-style home located on a quiet cul- ...',
    photo: '/assets/rentals/league-city/8917410.jpg',
    status: 'Active',
  },
  {
    mls: '95306781',
    address: '2895 Ragusa Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$4,500',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,639',
    acres: '0.198',
    yearBuilt: '2014',
    subdivision: 'Tuscan Lakes Sec Sf 75-4 2014',
    county: 'Galveston',
    remarks: 'Stunning Patterson Floor Plan by WESTIN HOMES. Bea ...',
    photo: '/assets/rentals/league-city/95306781.jpg',
    status: 'Active',
  },
  {
    mls: '86153325',
    address: '1725 Enterprise Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,412',
    acres: '0.055',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour 2 Townhome',
    county: 'Galveston',
    remarks: '**Tenant occupied until Sept. 1st** Updated and ni ...',
    photo: '/assets/rentals/league-city/86153325.jpg',
    status: 'Active',
  },
  {
    mls: '63702502',
    address: '136 Easton Glen Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$2,275',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,415',
    acres: '0.144',
    yearBuilt: '2007',
    subdivision: 'Bay Colony Northpointe Sec 1',
    county: 'Galveston',
    remarks: 'Welcome to 136 Easton Glen Lane, a well-maintained ...',
    photo: '/assets/rentals/league-city/63702502.jpg',
    status: 'Active',
  },
  {
    mls: '65831853',
    address: '328 Meadow Wood Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,406',
    acres: '0.147',
    yearBuilt: '1983',
    subdivision: 'Meadow Bend 2',
    county: 'Galveston',
    remarks: 'Looking for a place to call home? You’ve found it! ...',
    photo: '/assets/rentals/league-city/65831853.jpg',
    status: 'Active',
  },
  {
    mls: '15466616',
    address: '6118 Berwick Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,860',
    acres: '0.207',
    yearBuilt: '2003',
    subdivision: 'Westover Park Sec 2 2002',
    county: 'Galveston',
    remarks: 'Welcome to this spacious one-story home that offer ...',
    photo: '/assets/rentals/league-city/15466616.jpg',
    status: 'Active',
  },
  {
    mls: '20461357',
    address: '302 Morningside Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,195',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,631',
    acres: '0.177',
    yearBuilt: '1979',
    subdivision: 'Countryside Sec 3',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/league-city/20461357.jpg',
    status: 'Pending',
  },
  {
    mls: '54934809',
    address: '405 Magnolia Estates Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,122',
    acres: '0.161',
    yearBuilt: '2006',
    subdivision: 'Magnolia Estates Sec 2 2004',
    county: 'Galveston',
    remarks: 'Beautiful home located within walking distance of ...',
    photo: '/assets/rentals/league-city/54934809.jpg',
    status: 'Active',
  },
  {
    mls: '27558372',
    address: '105 Sweetgum Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,664',
    acres: '0.213',
    yearBuilt: '1978',
    subdivision: 'Countryside',
    county: 'Galveston',
    remarks: 'Cozy, beautifully updated single story home locate ...',
    photo: '/assets/rentals/league-city/27558372.jpg',
    status: 'Active',
  },
  {
    mls: '81688740',
    address: '2533 Knoxville Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,034',
    acres: '0.163',
    yearBuilt: '1981',
    subdivision: 'The Landing',
    county: 'Galveston',
    remarks: 'Beautifully Remodeled 3-Bedroom Home for RentThis ...',
    photo: '/assets/rentals/league-city/81688740.jpg',
    status: 'Active',
  },
  {
    mls: '96424258',
    address: '2805 Fountain Woods Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,538',
    acres: '0.138',
    yearBuilt: '2024',
    subdivision: 'Samara',
    county: 'Galveston',
    remarks: 'Newly built 3 bedroom 2 full bath, 1 story Lennar ...',
    photo: '/assets/rentals/league-city/96424258.jpg',
    status: 'Active',
  },
  {
    mls: '26655184',
    address: '205 Sharnoll Circle',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,970',
    acres: '0.169',
    yearBuilt: '1992',
    subdivision: 'Meadow Bend 6 Ph Iii 89',
    county: 'Galveston',
    remarks: 'Welcome home to this charming one-story home in a ...',
    photo: '/assets/rentals/league-city/26655184.jpg',
    status: 'Active',
  },
  {
    mls: '96291603',
    address: '4808 Ladona Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,709',
    acres: '0.148',
    yearBuilt: '2017',
    subdivision: 'Mar Bella Sec 16-B &amp; C',
    county: 'Galveston',
    remarks: 'Low utility bill due to the landlord-paid solar sy ...',
    photo: '/assets/rentals/league-city/96291603.jpg',
    status: 'Active',
  },
  {
    mls: '63826180',
    address: '2013 Enterprise Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,450',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,906',
    acres: '0.055',
    yearBuilt: '1983',
    subdivision: 'South Shore Harbour 2 Townhome',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/league-city/63826180.jpg',
    status: 'Active',
  },
  {
    mls: '33165936',
    address: '5118 Cherry Blossom',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,725',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,527',
    acres: '0.184',
    yearBuilt: '1997',
    subdivision: 'Rustic Oaks',
    county: 'Galveston',
    remarks: 'GORGEOUS & SPACIOUS 4/2.5/2A IN POPULA ...',
    photo: '/assets/rentals/league-city/33165936.jpg',
    status: 'Active',
  },
  {
    mls: '76994639',
    address: '1830 Sherwood Forest Circle',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,750',
    acres: '0.126',
    yearBuilt: '2004',
    subdivision: 'Sherwood Forest 2004',
    county: 'Galveston',
    remarks: 'Stunning Updates in this 3/2/2 one story in small ...',
    photo: '/assets/rentals/league-city/76994639.jpg',
    status: 'Pending',
  },
  {
    mls: '47687769',
    address: '4934 Dickens Landing Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,900',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,811',
    acres: '0.165',
    yearBuilt: '2024',
    subdivision: 'Coastal Point Sec 5',
    county: 'Galveston',
    remarks: 'Welcome to The Collin, a beautifully designed 4-be ...',
    photo: '/assets/rentals/league-city/47687769.jpg',
    status: 'Pending',
  },
  {
    mls: '35986401',
    address: '6330 Ontario Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,391',
    acres: '0.165',
    yearBuilt: '2021',
    subdivision: 'Westwood',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully maintained, five-year- ...',
    photo: '/assets/rentals/league-city/35986401.jpg',
    status: 'Pending',
  },
  {
    mls: '36723663',
    address: '135 Highland Terrace',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,495',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,688',
    acres: '0.215',
    yearBuilt: '1968',
    subdivision: 'Highland Terrace',
    county: 'Galveston',
    remarks: 'PROFESSIONALLY REMODELED TO LIKE NEW! Move in rea ...',
    photo: '/assets/rentals/league-city/36723663.jpg',
    status: 'Active',
  },
  {
    mls: '5378929',
    address: '2504 Ewell Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,016',
    acres: '0.168',
    yearBuilt: '1980',
    subdivision: 'The Landing',
    county: 'Galveston',
    remarks: 'Welcome to this beautiful home in the highly desir ...',
    photo: '/assets/rentals/league-city/5378929.jpg',
    status: 'Active',
  },
  {
    mls: '33100097',
    address: '411 Forest Hills Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,881',
    acres: '0.161',
    yearBuilt: '1983',
    subdivision: 'Meadow Bend 2',
    county: 'Galveston',
    remarks: 'Welcome home to this charming, single-story retrea ...',
    photo: '/assets/rentals/league-city/33100097.jpg',
    status: 'Active',
  },
  {
    mls: '94663245',
    address: '1803 Flamingo Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,152',
    acres: '0.117',
    yearBuilt: '1973',
    subdivision: 'Clear Creek Heights Sec 2',
    county: 'Galveston',
    remarks: 'Welcome home to this beautifully updated 3-bedroom ...',
    photo: '/assets/rentals/league-city/94663245.jpg',
    status: 'Active',
  },
  {
    mls: '48066725',
    address: '2001 Penwern Alley Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,312',
    acres: '0.192',
    yearBuilt: '2023',
    subdivision: 'Samara Sec 1 &amp; Ervin Street De',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully upgraded 4-bed, 2.5-ba ...',
    photo: '/assets/rentals/league-city/48066725.jpg',
    status: 'Active',
  },
  {
    mls: '32671232',
    address: '423 Blossomwood Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,995',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,790',
    acres: '0.169',
    yearBuilt: '2001',
    subdivision: 'Claremont Park Sec 3',
    county: 'Galveston',
    remarks: 'Enjoy the space and functionality of this 2 story ...',
    photo: '/assets/rentals/league-city/32671232.jpg',
    status: 'Active',
  },
  {
    mls: '62313719',
    address: '2101 Laughing Gull Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,295',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,746',
    acres: '0.192',
    yearBuilt: '2003',
    subdivision: 'Brittany Lakes Sec 8 2004',
    county: 'Galveston',
    remarks: 'Move-in ready corner-lot home in the desirable Bri ...',
    photo: '/assets/rentals/league-city/62313719.jpg',
    status: 'Active',
  },
  {
    mls: '76881363',
    address: '214 Glen Haven Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,560',
    acres: '0.269',
    yearBuilt: '1981',
    subdivision: 'Meadow Bend',
    county: 'Galveston',
    remarks: 'Welcome to this charming cul-de-sac home in a fami ...',
    photo: '/assets/rentals/league-city/76881363.jpg',
    status: 'Pending',
  },
  {
    mls: '74357959',
    address: '4013 Steer Stable Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,042',
    acres: '0.116',
    yearBuilt: '2026',
    subdivision: 'Westland Ranch',
    county: 'Galveston',
    remarks: 'Welcome to this beautiful new construction home in ...',
    photo: '/assets/rentals/league-city/74357959.jpg',
    status: 'Active',
  },
  {
    mls: '6379332',
    address: '3007 Cloverdale',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,095',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,265',
    acres: '0.161',
    yearBuilt: '1986',
    subdivision: 'Meadow Bend',
    county: 'Galveston',
    remarks: 'SIMPLY ADORABLE! CLEAN AND READY FOR A ...',
    photo: '/assets/rentals/league-city/6379332.jpg',
    status: 'Active',
  },
  {
    mls: '88658517',
    address: '752 Mayhill Ridge Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,925',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,544',
    acres: '0.171',
    yearBuilt: '2014',
    subdivision: 'Westover Park Sec 17a 2015 A',
    county: 'Galveston',
    remarks: 'Welcome to 752 Mayhill Ridge Lane! This stunning h ...',
    photo: '/assets/rentals/league-city/88658517.jpg',
    status: 'Active',
  },
  {
    mls: '50394544',
    address: '310 Watercrest Harbor Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,200',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,389',
    acres: '0.207',
    yearBuilt: '2001',
    subdivision: 'Brittany Lakes',
    county: 'Galveston',
    remarks: 'IMPRESSIVE TWO STORY ENTRY TO THIS BIG ...',
    photo: '/assets/rentals/league-city/50394544.jpg',
    status: 'Active',
  },
  {
    mls: '57921754',
    address: '5213 Cottonwood Creek Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,026',
    acres: '0.164',
    yearBuilt: '2003',
    subdivision: 'Magnolia Creek Sec 6 2002',
    county: 'Galveston',
    remarks: 'Great family home in the heart of Magnolia Creek. ...',
    photo: '/assets/rentals/league-city/57921754.jpg',
    status: 'Active',
  },
  {
    mls: '18102068',
    address: '2108 Goldfinch Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,395',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,854',
    acres: '0.175',
    yearBuilt: '2004',
    subdivision: 'Brittany Lakes Sec 9 2004',
    county: 'Galveston',
    remarks: '*HOME IS CURRENTLY OCCUPIED AND WILL B ...',
    photo: '/assets/rentals/league-city/18102068.jpg',
    status: 'Pending',
  },
  {
    mls: '5409880',
    address: '2296 Catalonia Cove',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,756',
    acres: '0.132',
    yearBuilt: '2007',
    subdivision: 'Mar Bella Sec',
    county: 'Galveston',
    remarks: 'MOVE-IN READY! GREAT OPEN FLOOR PLAN I ...',
    photo: '/assets/rentals/league-city/5409880.jpg',
    status: 'Pending',
  },
  {
    mls: '72318168',
    address: '2513 Harpers Ferry Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,266',
    acres: '0.168',
    yearBuilt: '1981',
    subdivision: 'The Landing',
    county: 'Galveston',
    remarks: 'Approaching the front door, discover the courtyard ...',
    photo: '/assets/rentals/league-city/72318168.jpg',
    status: 'Active',
  },
  {
    mls: '65708217',
    address: '1242 Hunter Wood Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,619',
    acres: '0.164',
    yearBuilt: '1996',
    subdivision: 'The Oaks Of Clear Creek Sec 1',
    county: 'Galveston',
    remarks: 'This 3 bedroom, 2 bath home boasts ample space tha ...',
    photo: '/assets/rentals/league-city/65708217.jpg',
    status: 'Active',
  },
  {
    mls: '56245984',
    address: '2918 Meridian Bay Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$2,245',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,020',
    acres: '0.211',
    yearBuilt: '2004',
    subdivision: 'Bay Colony Pointe Sec 6 2004',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/league-city/56245984.jpg',
    status: 'Pending',
  },
  {
    mls: '18186512',
    address: '207 Woodvale Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,195',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,500',
    acres: '0.175',
    yearBuilt: '1979',
    subdivision: 'Countryside',
    county: 'Galveston',
    remarks: 'This newly remodeled house for lease in League Cit ...',
    photo: '/assets/rentals/league-city/18186512.jpg',
    status: 'Active',
  },
  {
    mls: '33274918',
    address: '2521 Black Skimmer Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,975',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,958',
    acres: '0.182',
    yearBuilt: '2005',
    subdivision: 'Brittany Lakes Sec 8 2004',
    county: 'Galveston',
    remarks: 'Step into this beautifully upgraded 4bd home where ...',
    photo: '/assets/rentals/league-city/33274918.jpg',
    status: 'Pending',
  },
  {
    mls: '83200447',
    address: '1104 E Walker Street',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,995',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,456',
    acres: '1.061',
    yearBuilt: '2008',
    subdivision: 'Butcher Special Sub 2004',
    county: 'Galveston',
    remarks: 'MOVE IN READY!! WONDERFULLY UPDATED, S ...',
    photo: '/assets/rentals/league-city/83200447.jpg',
    status: 'Pending',
  },
  {
    mls: '34459070',
    address: '2624 Holbrook Springs Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '3,078',
    acres: '0.206',
    yearBuilt: '2016',
    subdivision: 'Magnolia Creek Sec 11 Ph I 20',
    county: 'Galveston',
    remarks: 'Beautifully maintained 4 bed, 3 full bath home in ...',
    photo: '/assets/rentals/league-city/34459070.jpg',
    status: 'Active',
  },
  {
    mls: '64879268',
    address: '2617 Knoxville Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,336',
    acres: '0.179',
    yearBuilt: '1982',
    subdivision: 'The Landing',
    county: 'Galveston',
    remarks: 'Great 3 bedroom with flex room or extra bedroom in ...',
    photo: '/assets/rentals/league-city/64879268.jpg',
    status: 'Active',
  },
  {
    mls: '63618759',
    address: '2515 Masters Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$5,000',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,057',
    acres: '0.228',
    yearBuilt: '1993',
    subdivision: 'South Shore Harbour Sec 12',
    county: 'Galveston',
    remarks: 'This spacious home, located in a desirable gated c ...',
    photo: '/assets/rentals/league-city/63618759.jpg',
    status: 'Active',
  },
  {
    mls: '52021750',
    address: '2821 Chinaberry Park Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,333',
    acres: '0.179',
    yearBuilt: '2007',
    subdivision: 'Magnolia Creek Sec 9 2007',
    county: 'Galveston',
    remarks: 'Welcome to your new home in the golf course commun ...',
    photo: '/assets/rentals/league-city/52021750.jpg',
    status: 'Active',
  },
  {
    mls: '92896887',
    address: '2004 Landing Boulevard',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,495',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,974',
    acres: '0.166',
    yearBuilt: '1987',
    subdivision: 'The Landing 3',
    county: 'Galveston',
    remarks: 'Charming and affordable one-story home with a spar ...',
    photo: '/assets/rentals/league-city/92896887.jpg',
    status: 'Active',
  },
  {
    mls: '42973091',
    address: '1235 Deer Ridge Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,892',
    acres: '0.163',
    yearBuilt: '1992',
    subdivision: 'The Oaks Of Clear Creek',
    county: 'Galveston',
    remarks: 'Welcome to this beautiful property that offers the ...',
    photo: '/assets/rentals/league-city/42973091.jpg',
    status: 'Active',
  },
  {
    mls: '21146388',
    address: '108 Oak Creek Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,500',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,552',
    acres: '0.244',
    yearBuilt: '1997',
    subdivision: 'Rustic Oaks Sec 1 95',
    county: 'Galveston',
    remarks: 'Discover this stunning 5 bed/4 bath home featuring ...',
    photo: '/assets/rentals/league-city/21146388.jpg',
    status: 'Pending',
  },
  {
    mls: '72463888',
    address: '2246 Oakleaf Trail Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,570',
    acres: '0.197',
    yearBuilt: '2016',
    subdivision: 'Magnolia Creek Sec 11 Ph I 20',
    county: 'Galveston',
    remarks: 'WELCOME. THIS BEAUTIFULLY 4-BEDROOM, 3 ...',
    photo: '/assets/rentals/league-city/72463888.jpg',
    status: 'Pending',
  },
  {
    mls: '24035909',
    address: '4434 Grove Park Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,432',
    acres: '0.171',
    yearBuilt: '2000',
    subdivision: 'Claremont Park Sec 2 99',
    county: 'Galveston',
    remarks: 'Beautiful 4-bedroom, single-story home in a highly ...',
    photo: '/assets/rentals/league-city/24035909.jpg',
    status: 'Active',
  },
  {
    mls: '29177350',
    address: '2108 Lakeway Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$4,750',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,707',
    acres: '0.259',
    yearBuilt: '1989',
    subdivision: 'South Shore Harbour 10 89',
    county: 'Galveston',
    remarks: 'Fabulous large home in golf course gated neighborh ...',
    photo: '/assets/rentals/league-city/29177350.jpg',
    status: 'Active',
  },
  {
    mls: '13698852',
    address: '2181 Brittany Colony Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,200',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,441',
    acres: '0.201',
    yearBuilt: '2004',
    subdivision: 'Brittany Lakes Sec 10',
    county: 'Galveston',
    remarks: 'Beautiful Village Builders home in the highly soug ...',
    photo: '/assets/rentals/league-city/13698852.jpg',
    status: 'Active',
  },
  {
    mls: '83890424',
    address: '2144 Brittany Colony Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,190',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,562',
    acres: '0.193',
    yearBuilt: '2004',
    subdivision: 'Brittany Lakes Sec 8 2004',
    county: 'Galveston',
    remarks: 'Experience waterfront living with stunning Lakevie ...',
    photo: '/assets/rentals/league-city/83890424.jpg',
    status: 'Active',
  },
  {
    mls: '84212986',
    address: '2606 Shear Water Court',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,972',
    acres: '0.179',
    yearBuilt: '2003',
    subdivision: 'Brittany Lakes',
    county: 'Galveston',
    remarks: 'SHINING LEASE HOME! 4/2/2 BEAUTY WITH ...',
    photo: '/assets/rentals/league-city/84212986.jpg',
    status: 'Active',
  },
  {
    mls: '59635117',
    address: '4627 Miramar Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$5,000',
    beds: '6 Bedrooms',
    baths: '4 Total Baths',
    sqft: '4,500',
    acres: '0.23',
    yearBuilt: '2014',
    subdivision: 'Mar Bella Sec 9-B 2011',
    county: 'Galveston',
    remarks: 'This stunning Riviera stucco home offers exception ...',
    photo: '/assets/rentals/league-city/59635117.jpg',
    status: 'Pending',
  },
  {
    mls: '89288312',
    address: '1922 Abilene',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,269',
    acres: '',
    yearBuilt: '1965',
    subdivision: 'Jarboe',
    county: 'Galveston',
    remarks: 'Looking for space? This unique property sits on ne ...',
    photo: '/assets/rentals/league-city/89288312.jpg',
    status: 'Active',
  },
  {
    mls: '96433710',
    address: '1615 Bel Riposo Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,506',
    acres: '0.142',
    yearBuilt: '2011',
    subdivision: 'Tuscan Lakes Sec Sf 50-3-1 Se',
    county: 'Galveston',
    remarks: 'Well maintained and move-in ready! This home is lo ...',
    photo: '/assets/rentals/league-city/96433710.jpg',
    status: 'Active',
  },
  {
    mls: '89054351',
    address: '2778 Glen Haven Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,295',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,492',
    acres: '0.18',
    yearBuilt: '1982',
    subdivision: 'Meadow Bend',
    county: 'Galveston',
    remarks: 'Welcome home to this charming 4-bedroom, 2-bathroo ...',
    photo: '/assets/rentals/league-city/89054351.jpg',
    status: 'Pending',
  },
  {
    mls: '78567927',
    address: '2402 Intrepid Way',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$3,175',
    beds: '2 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,105',
    acres: '0.127',
    yearBuilt: '1982',
    subdivision: 'Leeward Landing 1',
    county: 'Galveston',
    remarks: 'You found it! Updated home with an open floor pla ...',
    photo: '/assets/rentals/league-city/78567927.jpg',
    status: 'Active',
  },
  {
    mls: '11892682',
    address: '2719 Sellers Island Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,999',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,154',
    acres: '0.138',
    yearBuilt: '2024',
    subdivision: 'Coastal Point Sec 4',
    county: 'Galveston',
    remarks: 'Beautiful home nestled in a charming newer Coastal ...',
    photo: '/assets/rentals/league-city/11892682.jpg',
    status: 'Pending',
  },
  {
    mls: '58228450',
    address: '692 Casual Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,799',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,276',
    acres: '0.193',
    yearBuilt: '2007',
    subdivision: 'Leisure Lakes',
    county: 'Galveston',
    remarks: 'Welcome to this stunning two-story home nestled on ...',
    photo: '/assets/rentals/league-city/58228450.jpg',
    status: 'Active',
  },
  {
    mls: '97457044',
    address: '424 Folk Crest Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77539',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,690',
    acres: '0.096',
    yearBuilt: '2005',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'RECENTLY PAINTED WHOLE HOUSE - SPACIOU ...',
    photo: '/assets/rentals/league-city/97457044.jpg',
    status: 'Active',
  },
  {
    mls: '72200432',
    address: '872 Rock Harbor Lane',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,475',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,934',
    acres: '0.144',
    yearBuilt: '2005',
    subdivision: 'South Shore Harbour Sec Sf 50',
    county: 'Galveston',
    remarks: 'Nestled in the desirable South Shore Harbour neigh ...',
    photo: '/assets/rentals/league-city/72200432.jpg',
    status: 'Active',
  },
  {
    mls: '80487106',
    address: '542 Birdsong Drive',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$1,900',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,302',
    acres: '0.068',
    yearBuilt: '1983',
    subdivision: 'Birdsong Resub Twnhms',
    county: 'Galveston',
    remarks: 'Welcome to your next cozy retreat! This beautifull ...',
    photo: '/assets/rentals/league-city/80487106.jpg',
    status: 'Active',
  },
  {
    mls: '57581598',
    address: '409 Perkins Avenue',
    city: 'League City',
    state: 'Texas',
    zip: '77573',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,760',
    acres: '0.23',
    yearBuilt: '1942',
    subdivision: 'Merchants',
    county: 'Galveston',
    remarks: 'Fall in love with this beautifully restored gem in ...',
    photo: '/assets/rentals/league-city/57581598.jpg',
    status: 'Active',
  },
]
