// Texas City homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const texascityRentListings: Listing[] = [
  {
    mls: '95099053',
    address: '225 N Noble Road',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,700',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,587',
    acres: '0.447',
    yearBuilt: '1960',
    subdivision: 'Tarpey &amp; Noble',
    county: 'Galveston',
    remarks: 'Beautifully updated 4-bedroom home featuring new w ...',
    photo: '/assets/rentals/texas-city/95099053.jpg',
    status: 'Active',
  },
  {
    mls: '27327046',
    address: '2218 Regatta Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,664',
    acres: '0.137',
    yearBuilt: '2018',
    subdivision: 'Seacrest Sec. 2',
    county: 'Galveston',
    remarks: 'Lovely Home and Move-in Ready',
    photo: '/assets/rentals/texas-city/27327046.jpg',
    status: 'Active',
  },
  {
    mls: '48644246',
    address: '3210 Banyan Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$3,025',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,941',
    acres: '0.168',
    yearBuilt: '2025',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Welcome home to this exceptional single-story bric ...',
    photo: '/assets/rentals/texas-city/48644246.jpg',
    status: 'Active',
  },
  {
    mls: '17388087',
    address: '3238 Texas Avenue',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,599',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,216',
    acres: '0.148',
    yearBuilt: '1960',
    subdivision: 'Pioneer Terrace',
    county: 'Galveston',
    remarks: 'Completely upgraded 3 to 4 bedroom home with 1 ful ...',
    photo: '/assets/rentals/texas-city/17388087.jpg',
    status: 'Active',
  },
  {
    mls: '89274398',
    address: '428 10th Avenue North',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,700',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '996',
    acres: '0.144',
    yearBuilt: '1967',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Charming 2-bedroom home with a versatile office sp ...',
    photo: '/assets/rentals/texas-city/89274398.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '77424288',
    address: '17 13th Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$850',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,783',
    acres: '0.187',
    yearBuilt: '1967',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'This Duplex is 2-1 come and look',
    photo: '/assets/rentals/texas-city/77424288.jpg',
    status: 'Active',
  },
  {
    mls: '36823353',
    address: '720 4th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,542',
    acres: '0.144',
    yearBuilt: '1962',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Come and check this home out good location, Close ...',
    photo: '/assets/rentals/texas-city/36823353.jpg',
    status: 'Active',
  },
  {
    mls: '54795840',
    address: '2213 Del Mar',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,530',
    acres: '0.124',
    yearBuilt: '2018',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/texas-city/54795840.jpg',
    status: 'Active',
  },
  {
    mls: '21772222',
    address: '13322 Sea Breeze Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,850',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,051',
    acres: '0.179',
    yearBuilt: '2022',
    subdivision: 'Lago Mar Pod 4 Sec 3',
    county: 'Galveston',
    remarks: 'Meticulously maintained 4-bedroom, 2-bath home in ...',
    photo: '/assets/rentals/texas-city/21772222.jpg',
    status: 'Active',
  },
  {
    mls: '96278168',
    address: '3609 Zilker Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,550',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,045',
    acres: '0.161',
    yearBuilt: '2025',
    subdivision: 'Central Park South Sec 3',
    county: 'Galveston',
    remarks: 'The spacious primary suite features a luxurious ba ...',
    photo: '/assets/rentals/texas-city/96278168.jpg',
    status: 'Active',
  },
  {
    mls: '46652049',
    address: '225 19th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,550',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,018',
    acres: '0.144',
    yearBuilt: '1943',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Welcome home! This beautifully updated 3-bedroom, ...',
    photo: '/assets/rentals/texas-city/46652049.jpg',
    status: 'Active',
  },
  {
    mls: '65356793',
    address: '1208 7th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,200',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,000',
    acres: '0.179',
    yearBuilt: '1955',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'Welcome home to this recently renovated and well-m ...',
    photo: '/assets/rentals/texas-city/65356793.jpg',
    status: 'Active',
  },
  {
    mls: '70191672',
    address: '7521 Blue Jay Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,531',
    acres: '',
    yearBuilt: '2016',
    subdivision: 'Blue Jay Sub',
    county: 'Galveston',
    remarks: 'Designed with accessibility in my - Step inside t ...',
    photo: '/assets/rentals/texas-city/70191672.jpg',
    status: 'Active',
  },
  {
    mls: '48106582',
    address: '14305 Port Jackson Dr Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,575',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,899',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'Lago Mar Pod8',
    county: 'Galveston',
    remarks: 'Welcome to Crystal View Townhomes at Lago Mar, a m ...',
    photo: '/assets/rentals/texas-city/48106582.jpg',
    status: 'Active',
  },
  {
    mls: '85613028',
    address: '11012 32nd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$3,200',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,821',
    acres: '0.141',
    yearBuilt: '2020',
    subdivision: 'Park Place South Ph 5 2004',
    county: 'Galveston',
    remarks: 'Stunning move-in ready home built in 2020 and avai ...',
    photo: '/assets/rentals/texas-city/85613028.jpg',
    status: 'Active',
  },
  {
    mls: '23707446',
    address: '7931 Catalpa Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,695',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,825',
    acres: '0.595',
    yearBuilt: '1991',
    subdivision: 'Amburn Park',
    county: 'Galveston',
    remarks: 'Absolutely beautifully remodeled townhome in a qui ...',
    photo: '/assets/rentals/texas-city/23707446.jpg',
    status: 'Active',
  },
  {
    mls: '60225991',
    address: '616 17th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,550',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,163',
    acres: '0.158',
    yearBuilt: '1944',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'This charming 3-bedroom, 2-bath home is full of th ...',
    photo: '/assets/rentals/texas-city/60225991.jpg',
    status: 'Active',
  },
  {
    mls: '6982720',
    address: '122 S Willow Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,325',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,128',
    acres: '0.343',
    yearBuilt: '1968',
    subdivision: 'Williamson A',
    county: 'Galveston',
    remarks: 'Gorgeous Home in Texas City. Humongous backyard. H ...',
    photo: '/assets/rentals/texas-city/6982720.jpg',
    status: 'Active',
  },
  {
    mls: '87919512',
    address: '10520 Deussen Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,590',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,091',
    acres: '0.153',
    yearBuilt: '2024',
    subdivision: 'Central Park South',
    county: 'Galveston',
    remarks: 'Nearly new Meritage home. Designer white cabinets, ...',
    photo: '/assets/rentals/texas-city/87919512.jpg',
    status: 'Active',
  },
  {
    mls: '13253879',
    address: '2209 Onyx Court',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,189',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,232',
    acres: '',
    yearBuilt: '2014',
    subdivision: 'Pearlbrook',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/texas-city/13253879.jpg',
    status: 'Active',
  },
  {
    mls: '29544293',
    address: '14002 Starboard Reach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$2,945',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,850',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'This beautiful, one-story home is the Hendrie by L ...',
    photo: '/assets/rentals/texas-city/29544293.jpg',
    status: 'Active',
  },
  {
    mls: '88198906',
    address: '1107 9th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,350',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '759',
    acres: '0.127',
    yearBuilt: '1962',
    subdivision: 'Snug Harbor',
    county: 'Galveston',
    remarks: 'Nice 2 bedroom home with 2 car garage with washer ...',
    photo: '/assets/rentals/texas-city/88198906.jpg',
    status: 'Active',
  },
  {
    mls: '23743505',
    address: '112 1st Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,529',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '720',
    acres: '0.215',
    yearBuilt: '1967',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Section 8 welcome! Remodeled bungalow with handica ...',
    photo: '/assets/rentals/texas-city/23743505.jpg',
    status: 'Active',
  },
  {
    mls: '61420330',
    address: '3301 Clover Hill Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,295',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,010',
    acres: '0.17',
    yearBuilt: '2005',
    subdivision: 'Rainsong Sec 2 2006',
    county: 'Galveston',
    remarks: 'This stunning home sitting on a corner lot has jus ...',
    photo: '/assets/rentals/texas-city/61420330.jpg',
    status: 'Active',
  },
  {
    mls: '63408536',
    address: '2910 Somerset Avenue',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,850',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,705',
    acres: '0.145',
    yearBuilt: '1977',
    subdivision: 'Somerset',
    county: 'Galveston',
    remarks: 'Nice four bedroom brick home in a great neighborho ...',
    photo: '/assets/rentals/texas-city/63408536.jpg',
    status: 'Active',
  },
  {
    mls: '18522888',
    address: '3417 Fawnwood Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,793',
    acres: '0.184',
    yearBuilt: '2018',
    subdivision: 'Rainsong Sec 3-A',
    county: 'Galveston',
    remarks: 'Beautiful one story home with great floor plan, 3x ...',
    photo: '/assets/rentals/texas-city/18522888.jpg',
    status: 'Active',
  },
  {
    mls: '31084778',
    address: '417 13th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,950',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,563',
    acres: '0.144',
    yearBuilt: '1957',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Updated, spacious 4 bedroom home on a wide, quiet, ...',
    photo: '/assets/rentals/texas-city/31084778.jpg',
    status: 'Active',
  },
  {
    mls: '96872079',
    address: '121 S Willow Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$950',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '645',
    acres: '0.344',
    yearBuilt: '1972',
    subdivision: 'Williamson A',
    county: 'Galveston',
    remarks: 'Great affordable duplex available for immediate mo ...',
    photo: '/assets/rentals/texas-city/96872079.jpg',
    status: 'Active',
  },
  {
    mls: '91444161',
    address: '36 18th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,750',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,500',
    acres: '0.144',
    yearBuilt: '1965',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'This spacious home offers 4 bedrooms and 2 bathroo ...',
    photo: '/assets/rentals/texas-city/91444161.jpg',
    status: 'Active',
  },
  {
    mls: '50084627',
    address: '12426 Cumberland Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,950',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,908',
    acres: '0.183',
    yearBuilt: '2016',
    subdivision: 'Lago Mar Pod 11 Sec 6',
    county: 'Galveston',
    remarks: 'Welcome to this stunning one-story, 3 bedroom, 2 1 ...',
    photo: '/assets/rentals/texas-city/50084627.jpg',
    status: 'Active',
  },
  {
    mls: '48757407',
    address: '3000 2nd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,150',
    acres: '0.289',
    yearBuilt: '1984',
    subdivision: 'Jemison Add',
    county: 'Galveston',
    remarks: 'Charming 3-bedroom, 2-bathroom Texas City retreat ...',
    photo: '/assets/rentals/texas-city/48757407.jpg',
    status: 'Active',
  },
  {
    mls: '52469732',
    address: '3226 Buttercup Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,940',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,398',
    acres: '',
    yearBuilt: '2020',
    subdivision: 'Lone Trail Village',
    county: 'Galveston',
    remarks: 'The Guardian II Plan is a thoughtfully designed si ...',
    photo: '/assets/rentals/texas-city/52469732.jpg',
    status: 'Active',
  },
  {
    mls: '17760220',
    address: '2101 6th Avenue N 3',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$795',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '600',
    acres: '0.349',
    yearBuilt: '1970',
    subdivision: 'Kohfeldt Heights',
    county: 'Galveston',
    remarks: 'ASK ABOUT OUR MOVE IN SPECIAL! EZ Qualifications a ...',
    photo: '/assets/rentals/texas-city/17760220.jpg',
    status: 'Active',
  },
  {
    mls: '78004693',
    address: '7406 Blue Jay Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,650',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,248',
    acres: '',
    yearBuilt: '2016',
    subdivision: 'Blue Jay Sub',
    county: 'Galveston',
    remarks: 'Welcome to your new home in the perfect midpoint l ...',
    photo: '/assets/rentals/texas-city/78004693.jpg',
    status: 'Active',
  },
  {
    mls: '72273207',
    address: '806 3rd Avenue N 12',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$900',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '621',
    acres: '0.036',
    yearBuilt: '1955',
    subdivision: 'Third Ave Villas',
    county: 'Galveston',
    remarks: 'Welcome to 806 3rd Ave. N # 12 , where comfort and ...',
    photo: '/assets/rentals/texas-city/72273207.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '98522413',
    address: '818 3rd Avenue N 28',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$850',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '500',
    acres: '',
    yearBuilt: '1955',
    subdivision: 'Third Ave Villas',
    county: 'Galveston',
    remarks: 'Lovely 1 Bedroom 1 Bath corner apartment. This apa ...',
    photo: '/assets/rentals/texas-city/98522413.jpg',
    status: 'Active',
  },
  {
    mls: '30226288',
    address: '116 12th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,400',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,271',
    acres: '0.215',
    yearBuilt: '1955',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Cute and cozy remodeled 3 bedroom 1 bath ready for ...',
    photo: '/assets/rentals/texas-city/30226288.jpg',
    status: 'Active',
  },
  {
    mls: '75421919',
    address: '13025 Dancing Reed Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,795',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,131',
    acres: '0.117',
    yearBuilt: '2019',
    subdivision: 'Lago Mapod 4 Sec 2',
    county: 'Galveston',
    remarks: 'Move-in ready 4-bedroom, 2.5-bath home in the high ...',
    photo: '/assets/rentals/texas-city/75421919.jpg',
    status: 'Active',
  },
  {
    mls: '31485362',
    address: '6201 Park Avenue',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$895',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '814',
    acres: '0.116',
    yearBuilt: '1974',
    subdivision: 'Hubbard',
    county: 'Galveston',
    remarks: '3-bedroom 1 bath ready for move-in. This cute home ...',
    photo: '/assets/rentals/texas-city/31485362.jpg',
    status: 'Pending',
  },
  {
    mls: '38203318',
    address: '405 13th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,113',
    acres: '0.144',
    yearBuilt: '1976',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Welcome home to this charming two-bedroom, one-bat ...',
    photo: '/assets/rentals/texas-city/38203318.jpg',
    status: 'Pending',
  },
  {
    mls: '24477667',
    address: '7518 Hummingbird Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,650',
    beds: '5 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,200',
    acres: '0.14',
    yearBuilt: '1970',
    subdivision: 'South Acre Manor 2',
    county: 'Galveston',
    remarks: 'Freshly made ready and ready for move-in! This spa ...',
    photo: '/assets/rentals/texas-city/24477667.jpg',
    status: 'Active',
  },
  {
    mls: '87195558',
    address: '405 N Fulton Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,272',
    acres: '0.283',
    yearBuilt: '1964',
    subdivision: 'Bell Ollie',
    county: 'Galveston',
    remarks: 'This One-Story Home has it all! An impressive open ...',
    photo: '/assets/rentals/texas-city/87195558.jpg',
    status: 'Active',
  },
  {
    mls: '13415671',
    address: '1211 1st Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$950',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '856',
    acres: '0.172',
    yearBuilt: '1966',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'Downstairs unit - 2 bedrooms - 1 bathroom with 1 d ...',
    photo: '/assets/rentals/texas-city/13415671.jpg',
    status: 'Pending',
  },
  {
    mls: '53670733',
    address: '705 11th Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,500',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '889',
    acres: '0.165',
    yearBuilt: '1964',
    subdivision: 'Snug Harbor',
    county: 'Galveston',
    remarks: 'Located on a corner lot and secluded behind a 9-fo ...',
    photo: '/assets/rentals/texas-city/53670733.jpg',
    status: 'Active',
  },
  {
    mls: '19708162',
    address: '7301 Hummingbird Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,071',
    acres: '0.145',
    yearBuilt: '1969',
    subdivision: 'South Acre Manor',
    county: 'Galveston',
    remarks: 'Property has been renovated with fresh paint throu ...',
    photo: '/assets/rentals/texas-city/19708162.jpg',
    status: 'Active',
  },
  {
    mls: '64201531',
    address: '1001 9th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,240',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '814',
    acres: '0.141',
    yearBuilt: '1960',
    subdivision: 'Snug Harbor',
    county: 'Galveston',
    remarks: 'Now available for lease! Well-maintained home on a ...',
    photo: '/assets/rentals/texas-city/64201531.jpg',
    status: 'Active',
  },
  {
    mls: '59611528',
    address: '1231 23rd Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,425',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,330',
    acres: '0.147',
    yearBuilt: '1964',
    subdivision: 'Stafford 1',
    county: 'Galveston',
    remarks: 'Discover this 4 Bedroom 2 Bath Home on a Corner Lo ...',
    photo: '/assets/rentals/texas-city/59611528.jpg',
    status: 'Pending',
  },
  {
    mls: '74454384',
    address: '45 17th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,495',
    beds: '4 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,168',
    acres: '0.144',
    yearBuilt: '1959',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Discover this four-bedroom, one-bath home in Texas ...',
    photo: '/assets/rentals/texas-city/74454384.jpg',
    status: 'Pending',
  },
  {
    mls: '98317860',
    address: '2225 Windy Sail Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,670',
    acres: '0.262',
    yearBuilt: '2018',
    subdivision: 'Lago Mar Pod 7 Sec 1',
    county: 'Galveston',
    remarks: 'Welcome to your dream home in the heart of Lago Ma ...',
    photo: '/assets/rentals/texas-city/98317860.jpg',
    status: 'Pending',
  },
  {
    mls: '22763057',
    address: '2102 5th Avenue N 5',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$895',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '780',
    acres: '',
    yearBuilt: '1970',
    subdivision: 'Kohfeldt Heights',
    county: 'Galveston',
    remarks: 'ASK ABOUT OUR MOVE-IN SPECIAL! Welcome to 2102 5th ...',
    photo: '/assets/rentals/texas-city/22763057.jpg',
    status: 'Active',
  },
  {
    mls: '43340009',
    address: '3521 Rockefeller Road',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,411',
    acres: '0.144',
    yearBuilt: '2023',
    subdivision: 'Central Park',
    county: 'Galveston',
    remarks: 'Situated on an oversized lot with no back neighbor ...',
    photo: '/assets/rentals/texas-city/43340009.jpg',
    status: 'Active',
  },
  {
    mls: '41628517',
    address: '9522 Wall Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,415',
    acres: '0.138',
    yearBuilt: '2025',
    subdivision: 'Central Pk-Sec 2',
    county: 'Galveston',
    remarks: 'This bright and inviting Texas City home delivers ...',
    photo: '/assets/rentals/texas-city/41628517.jpg',
    status: 'Active',
  },
  {
    mls: '49278020',
    address: '2722 8th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,191',
    acres: '0.2',
    yearBuilt: '1985',
    subdivision: 'Plaza',
    county: 'Galveston',
    remarks: 'Freshly Updated 3-Bedroom Home for Lease in Texas ...',
    photo: '/assets/rentals/texas-city/49278020.jpg',
    status: 'Active',
  },
  {
    mls: '73334934',
    address: '6218 Woodrow Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,375',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '968',
    acres: '0.123',
    yearBuilt: '1947',
    subdivision: 'Wright Cuney',
    county: 'Galveston',
    remarks: 'Charming 3-bedroom, 1 bath home available now, fea ...',
    photo: '/assets/rentals/texas-city/73334934.jpg',
    status: 'Active',
  },
  {
    mls: '34678896',
    address: '3134 Babin Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,600',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,246',
    acres: '0.309',
    yearBuilt: '2020',
    subdivision: 'Clairmont',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/texas-city/34678896.jpg',
    status: 'Active',
  },
  {
    mls: '54712479',
    address: '1418 2nd Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,700',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,890',
    acres: '0.172',
    yearBuilt: '1976',
    subdivision: 'Wayside Place 1',
    county: 'Galveston',
    remarks: 'BEAUTIFULLY REMODELED 4 BEDROOM 2 BATH ...',
    photo: '/assets/rentals/texas-city/54712479.jpg',
    status: 'Active',
  },
  {
    mls: '20289645',
    address: '9515 Chelsea Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,754',
    acres: '0.144',
    yearBuilt: '2024',
    subdivision: 'Central Park Sec 2',
    county: 'Galveston',
    remarks: 'Discover comfort in this beautifully designed, sin ...',
    photo: '/assets/rentals/texas-city/20289645.jpg',
    status: 'Pending',
  },
  {
    mls: '68235881',
    address: '10218 Hermann Trace',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,839',
    acres: '0.14',
    yearBuilt: '2023',
    subdivision: 'Central Park South Sec 2',
    county: 'Galveston',
    remarks: 'Like-new, energy-efficient home available for imme ...',
    photo: '/assets/rentals/texas-city/68235881.jpg',
    status: 'Active',
  },
  {
    mls: '70782551',
    address: '13517 Bonita Island Way',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,575',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,700',
    acres: '0.144',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Sec 2 Pod 3',
    county: 'Galveston',
    remarks: 'Discover the perfect blend of modern comfort and r ...',
    photo: '/assets/rentals/texas-city/70782551.jpg',
    status: 'Active',
  },
  {
    mls: '79579690',
    address: '14213 Freeboard Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77510',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,624',
    acres: '0.165',
    yearBuilt: '2023',
    subdivision: 'Lago Mar Pod 9 Sec 1',
    county: 'Galveston',
    remarks: 'Discover the charm of the Atchison plan by LGI Hom ...',
    photo: '/assets/rentals/texas-city/79579690.jpg',
    status: 'Active',
  },
  {
    mls: '35425069',
    address: '3213 Cornflower Coast Court',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,537',
    acres: '0.122',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Sec 3 Pod 5',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/texas-city/35425069.jpg',
    status: 'Active',
  },
  {
    mls: '69041724',
    address: '2417 Nautica Terrace Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,150',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,846',
    acres: '0.181',
    yearBuilt: '2018',
    subdivision: 'Seacrest',
    county: 'Galveston',
    remarks: 'Nestled in the Seacrest community of Texas City, t ...',
    photo: '/assets/rentals/texas-city/69041724.jpg',
    status: 'Pending',
  },
  {
    mls: '80274850',
    address: '4010 Southall Place',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,720',
    acres: '0.149',
    yearBuilt: '2020',
    subdivision: 'Cobblestone Sec 1',
    county: 'Galveston',
    remarks: 'This charming single-story home offers a modern, u ...',
    photo: '/assets/rentals/texas-city/80274850.jpg',
    status: 'Active',
  },
  {
    mls: '68515912',
    address: '3022 Sandpiper Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,709',
    acres: '0.163',
    yearBuilt: '2021',
    subdivision: 'Herons Lndg Sec 2',
    county: 'Galveston',
    remarks: 'Beautifully maintained 3-bedroom, 2-bath home feat ...',
    photo: '/assets/rentals/texas-city/68515912.jpg',
    status: 'Active',
  },
  {
    mls: '21568886',
    address: '12617 White Cove Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,750',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,601',
    acres: '0.234',
    yearBuilt: '2018',
    subdivision: 'Lago Mar Pod 7 Sec 1',
    county: 'Galveston',
    remarks: 'Ideal single story floorpan on a cul-de-sac lot in ...',
    photo: '/assets/rentals/texas-city/21568886.jpg',
    status: 'Active',
  },
  {
    mls: '10373788',
    address: '2421 Mar Vista Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$3,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,488',
    acres: '0.153',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Pod 3 Sec 2',
    county: 'Galveston',
    remarks: 'Elegance w/ Stunning Lake Views in Lago Mar! This ...',
    photo: '/assets/rentals/texas-city/10373788.jpg',
    status: 'Active',
  },
  {
    mls: '38251552',
    address: '13513 Bonita Island Way',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,579',
    acres: '0.144',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Pod 3 Sec 2',
    county: 'Galveston',
    remarks: 'Something modern+private+close to walking trails.. ...',
    photo: '/assets/rentals/texas-city/38251552.jpg',
    status: 'Active',
  },
  {
    mls: '76740442',
    address: '2206 Mirror Ridge Court',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,495',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,691',
    acres: '0.113',
    yearBuilt: '2018',
    subdivision: 'Lago Mar Pod 7 Sec 3',
    county: 'Galveston',
    remarks: 'Located in Lago Mar, 1-story, 3 br, 2 bath w/2 car ...',
    photo: '/assets/rentals/texas-city/76740442.jpg',
    status: 'Active',
  },
  {
    mls: '36081905',
    address: '2502 Ocean Key Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$3,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,472',
    acres: '0.152',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Pod 6 Sec 2',
    county: 'Galveston',
    remarks: '2502 Ocean Key Dr is located in a gated section of ...',
    photo: '/assets/rentals/texas-city/36081905.jpg',
    status: 'Active',
  },
  {
    mls: '98155017',
    address: '505 13th Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$755',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '948',
    acres: '0.187',
    yearBuilt: '1965',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'Nicely remodeled 2 bedroom 1 bathroom home in Texa ...',
    photo: '/assets/rentals/texas-city/98155017.jpg',
    status: 'Active',
  },
  {
    mls: '76710034',
    address: '910 7th Avenue N 3',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$850',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '600',
    acres: '0.287',
    yearBuilt: '1970',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'Nicely renovated unit located on the first floor. ...',
    photo: '/assets/rentals/texas-city/76710034.jpg',
    status: 'Pending',
  },
  {
    mls: '11227569',
    address: '13337 Silver Egret Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,045',
    acres: '0.144',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Pod 3 Sec 2',
    county: 'Galveston',
    remarks: 'This beautiful 4-bedroom, 3-bathroom single-story ...',
    photo: '/assets/rentals/texas-city/11227569.jpg',
    status: 'Active',
  },
  {
    mls: '46561434',
    address: '1118 Hunter Drive A',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$950',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '886',
    acres: '0.187',
    yearBuilt: '1965',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'Nice 2 bedroom 1 bathroom duplex home in Chelsea M ...',
    photo: '/assets/rentals/texas-city/46561434.jpg',
    status: 'Active',
  },
  {
    mls: '54436281',
    address: '2202 16th Avenue N 4',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$975',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1969',
    subdivision: 'Looper',
    county: 'Galveston',
    remarks: 'Nice upstairs 2 bedroom 1 bath and 1 half bath rea ...',
    photo: '/assets/rentals/texas-city/54436281.jpg',
    status: 'Active',
  },
  {
    mls: '65200161',
    address: '1517 Wayside Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,142',
    acres: '0.172',
    yearBuilt: '1973',
    subdivision: 'Wayside Place 1',
    county: 'Galveston',
    remarks: 'Updated 3-bedroom, 1-bath home in Texas City with ...',
    photo: '/assets/rentals/texas-city/65200161.jpg',
    status: 'Active',
  },
  {
    mls: '30588162',
    address: '2223 Islawild Way',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,548',
    acres: '0.121',
    yearBuilt: '2023',
    subdivision: 'Lago Mar Sec 5 Pod 4',
    county: 'Galveston',
    remarks: 'Waterfront living in popular Lago Mar! This update ...',
    photo: '/assets/rentals/texas-city/30588162.jpg',
    status: 'Active',
  },
  {
    mls: '57018093',
    address: '12629 Pirate Bend Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,650',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,012',
    acres: '0.127',
    yearBuilt: '2017',
    subdivision: 'Lago Mar Pod 7 Sec 2',
    county: 'Galveston',
    remarks: 'Welcome to Lagoon Life! This beautiful open concep ...',
    photo: '/assets/rentals/texas-city/57018093.jpg',
    status: 'Pending',
  },
  {
    mls: '9049658',
    address: '7600 Emmett F Lowry Expressway 313',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$1,575',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '794',
    acres: '0.018',
    yearBuilt: '1980',
    subdivision: 'Gatsby Condo',
    county: 'Galveston',
    remarks: 'Fully remodeled Two bed Two-bathroom first level c ...',
    photo: '/assets/rentals/texas-city/9049658.jpg',
    status: 'Active',
  },
  {
    mls: '68944907',
    address: '1139 Mainland Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,591',
    acres: '',
    yearBuilt: '1983',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Spacious 3-bedroom, 2-bathroom single-family home ...',
    photo: '/assets/rentals/texas-city/68944907.jpg',
    status: 'Active',
  },
  {
    mls: '14210855',
    address: '13126 Lago Acero Lane',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,488',
    acres: '0.181',
    yearBuilt: '2021',
    subdivision: 'Lago Mar',
    county: 'Galveston',
    remarks: 'Built in 2021, this beautiful 2-story home in Lago ...',
    photo: '/assets/rentals/texas-city/14210855.jpg',
    status: 'Pending',
  },
  {
    mls: '49042220',
    address: '320 17th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,200',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '849',
    acres: '0.144',
    yearBuilt: '1940',
    subdivision: 'Texas City',
    county: 'Galveston',
    remarks: 'FULLY FENCED 2 BEDROOM HOME FOR LEASE ...',
    photo: '/assets/rentals/texas-city/49042220.jpg',
    status: 'Active',
  },
  {
    mls: '97263110',
    address: '3602 Conquest Circle',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,308',
    acres: '0.144',
    yearBuilt: '2021',
    subdivision: 'Marlow Lake',
    county: 'Galveston',
    remarks: 'JUST LIKE NEW! NOT YOUR TYPICAL RENTAL ...',
    photo: '/assets/rentals/texas-city/97263110.jpg',
    status: 'Active',
  },
  {
    mls: '2656841',
    address: '1512 13th Street N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,615',
    acres: '0.203',
    yearBuilt: '2004',
    subdivision: 'Sunset Terrace',
    county: 'Galveston',
    remarks: 'Welcome to this stunning home with fresh paint and ...',
    photo: '/assets/rentals/texas-city/2656841.jpg',
    status: 'Active',
  },
  {
    mls: '21915528',
    address: '2402 21st Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,170',
    acres: '0.161',
    yearBuilt: '1977',
    subdivision: 'Malibu Heights 2',
    county: 'Galveston',
    remarks: 'Welcome to this beautifully updated 4-bedroom, 3-b ...',
    photo: '/assets/rentals/texas-city/21915528.jpg',
    status: 'Active',
  },
  {
    mls: '91753791',
    address: '14424 Wadley Bay Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,599',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '1,888',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'Lago Mar Pod8',
    county: 'Galveston',
    remarks: 'Beautifully designed home in the sought-after Cadi ...',
    photo: '/assets/rentals/texas-city/91753791.jpg',
    status: 'Active',
  },
  {
    mls: '53663228',
    address: '1008 17th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,300',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,350',
    acres: '0.257',
    yearBuilt: '1951',
    subdivision: 'Mainland Park',
    county: 'Galveston',
    remarks: 'Large Lot! Well-maintained 2-bedroom 1 bath with s ...',
    photo: '/assets/rentals/texas-city/53663228.jpg',
    status: 'Active',
  },
  {
    mls: '91644811',
    address: '13125 Cobalt Cove Court',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,870',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,415',
    acres: '0.19',
    yearBuilt: '2021',
    subdivision: 'Lago Mar Pod 5 Sec 3',
    county: 'Galveston',
    remarks: 'Experience the best of Lago Mar in this beautifull ...',
    photo: '/assets/rentals/texas-city/91644811.jpg',
    status: 'Active',
  },
  {
    mls: '14619029',
    address: '13126 Dancing Reed Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,792',
    acres: '0.114',
    yearBuilt: '2020',
    subdivision: 'Lago Mar Pod 4 Sec 1',
    county: 'Galveston',
    remarks: 'Welcome to this charming 3-bedroom, 3-bath home lo ...',
    photo: '/assets/rentals/texas-city/14619029.jpg',
    status: 'Active',
  },
  {
    mls: '93533028',
    address: '2526 3rd 1/2 Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,350',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,246',
    acres: '0.138',
    yearBuilt: '1960',
    subdivision: 'Texas City Heights Sub 1',
    county: 'Galveston',
    remarks: 'Great home with fresh paint throughout and all new ...',
    photo: '/assets/rentals/texas-city/93533028.jpg',
    status: 'Active',
  },
  {
    mls: '41691904',
    address: '1204 7th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$800',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,945',
    acres: '0.179',
    yearBuilt: '1960',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'This unit on this duplex just became available and ...',
    photo: '/assets/rentals/texas-city/41691904.jpg',
    status: 'Active',
  },
  {
    mls: '12052947',
    address: '2125 Windy Grove Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,450',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '2020',
    subdivision: 'Lago Mar Subdivision',
    county: 'Galveston',
    remarks: 'Welcome to Lago Mar Subdivision with the 12 acre L ...',
    photo: '/assets/rentals/texas-city/12052947.jpg',
    status: 'Active',
  },
  {
    mls: '87096873',
    address: '5105 Timothy Street 4',
    city: 'Texas City',
    state: 'Texas',
    zip: '77591',
    price: '$950',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '805',
    acres: '0.776',
    yearBuilt: '1968',
    subdivision: 'Jones-Perez',
    county: 'Galveston',
    remarks: 'Fresh paint and new wood-look laminate flooring th ...',
    photo: '/assets/rentals/texas-city/87096873.jpg',
    status: 'Active',
  },
  {
    mls: '30291574',
    address: '1028 5th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$945',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '847',
    acres: '8',
    yearBuilt: '1965',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'Enjoy coastal living at this charming duplex condo ...',
    photo: '/assets/rentals/texas-city/30291574.jpg',
    status: 'Active',
  },
  {
    mls: '80782775',
    address: '1228 6th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$945',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '847',
    acres: '8',
    yearBuilt: '1965',
    subdivision: 'Chelsea Manor',
    county: 'Galveston',
    remarks: 'Enjoy coastal living at this charming duplex condo ...',
    photo: '/assets/rentals/texas-city/80782775.jpg',
    status: 'Active',
  },
  {
    mls: '58713320',
    address: '202 N Logan Street',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$850',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '700',
    acres: '0.253',
    yearBuilt: '1967',
    subdivision: 'Texas City Heights',
    county: 'Galveston',
    remarks: 'Come on home to this cute 1 bedroom 1 bath \\\\"garage ...',
    photo: '/assets/rentals/texas-city/58713320.jpg',
    status: 'Active',
  },
  {
    mls: '46825918',
    address: '2421 16th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$2,475',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,518',
    acres: '0.136',
    yearBuilt: '1965',
    subdivision: 'Sunnycrest 2',
    county: 'Galveston',
    remarks: 'HOUSING ACCEPTED! Ready for move in! 4 Bedroom 2 b ...',
    photo: '/assets/rentals/texas-city/46825918.jpg',
    status: 'Pending',
  },
  {
    mls: '87972605',
    address: '3006 14th Avenue N',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$1,550',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,542',
    acres: '0.14',
    yearBuilt: '1958',
    subdivision: 'Park View',
    county: 'Galveston',
    remarks: 'Fully bricked 3-bedroom, 1.5-bath home found in a ...',
    photo: '/assets/rentals/texas-city/87972605.jpg',
    status: 'Active',
  },
  {
    mls: '58812038',
    address: '13217 Dalvay Beach Drive',
    city: 'Texas City',
    state: 'Texas',
    zip: '77568',
    price: '$2,750',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,343',
    acres: '0.125',
    yearBuilt: '2022',
    subdivision: 'Lago Mar Pod 3 Sec 3',
    county: 'Galveston',
    remarks: 'Welcome to this beautiful two-story traditional ho ...',
    photo: '/assets/rentals/texas-city/58812038.jpg',
    status: 'Active',
  },
  {
    mls: '13501719',
    address: '2202 16th Ave N Avenue N 10',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$975',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1969',
    subdivision: 'Looper',
    county: 'Galveston',
    remarks: 'Nice upstairs 2 bedroom 1 bath and 1 half bath rea ...',
    photo: '/assets/rentals/texas-city/13501719.jpg',
    status: 'Active',
  },
  {
    mls: '26248851',
    address: '826 3rd Avenue N 34',
    city: 'Texas City',
    state: 'Texas',
    zip: '77590',
    price: '$800',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '500',
    acres: '0.04',
    yearBuilt: '1965',
    subdivision: 'Third Ave Villas - Donna&#039;s Corner',
    county: 'Galveston',
    remarks: 'Lovely 1 bedroom, 1 bath apartment with ceramic ti ...',
    photo: '/assets/rentals/texas-city/26248851.jpg',
    status: 'Active',
  },
]
