// Dickinson homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const dickinsonRentListings: Listing[] = [
  {
    mls: '58777161',
    address: '3808 Armand Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,850',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,562',
    acres: '0.138',
    yearBuilt: '2005',
    subdivision: 'Bayou Village 2004 Abst 19',
    county: 'Galveston',
    remarks: 'Four-bedroom home recently painted interior, with ...',
    photo: '/assets/rentals/dickinson/58777161.jpg',
    status: 'Active',
  },
  {
    mls: '3993303',
    address: '4101 Victoria Avenue B',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,150',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,270',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'Ripke',
    county: 'Galveston',
    remarks: 'Experience this newly constructed home featuring 3 ...',
    photo: '/assets/rentals/dickinson/3993303.jpg',
    status: 'Active',
  },
  {
    mls: '68265874',
    address: '234 Dale Ridge Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,550',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,742',
    acres: '0.144',
    yearBuilt: '2017',
    subdivision: 'Bay View',
    county: 'Galveston',
    remarks: 'Enjoy comfort, convenience, and room to grow in th ...',
    photo: '/assets/rentals/dickinson/68265874.jpg',
    status: 'Active',
  },
  {
    mls: '1077076',
    address: '208 Morgan Isle Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,711',
    acres: '0.128',
    yearBuilt: '2012',
    subdivision: 'Bay View Sec 1 2009',
    county: 'Galveston',
    remarks: 'WELL MAINTAINED HOME IN POPULAR BAY VI ...',
    photo: '/assets/rentals/dickinson/1077076.jpg',
    status: 'Active',
  },
  {
    mls: '13487818',
    address: '135 Rustic Colony Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,950',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,528',
    acres: '0.175',
    yearBuilt: '2006',
    subdivision: 'Bay Colony Northpointe Sec 1',
    county: 'Galveston',
    remarks: 'Conveniently located single-story 3-2-2 home near ...',
    photo: '/assets/rentals/dickinson/13487818.jpg',
    status: 'Active',
  },
  {
    mls: '49099109',
    address: '725 10th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,382',
    acres: '0.147',
    yearBuilt: '2012',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'This professional turnkey renovated home shows bea ...',
    photo: '/assets/rentals/dickinson/49099109.jpg',
    status: 'Active',
  },
  {
    mls: '12359356',
    address: '294 Debbie Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,900',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '900',
    acres: '0.111',
    yearBuilt: '2020',
    subdivision: 'Bay Casa 2013',
    county: 'Galveston',
    remarks: 'Welcome to your new coastal retreat! This 2020 bui ...',
    photo: '/assets/rentals/dickinson/12359356.jpg',
    status: 'Active',
  },
  {
    mls: '63813098',
    address: '3310 Oak Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,348',
    acres: '0.607',
    yearBuilt: '1970',
    subdivision: 'Dickinson Add D',
    county: 'Galveston',
    remarks: 'Fanstastic opportunity, waterfront property that t ...',
    photo: '/assets/rentals/dickinson/63813098.jpg',
    status: 'Active',
  },
  {
    mls: '70009601',
    address: '2501 Gulf Freeway 256D',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,100',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '800',
    acres: '800',
    yearBuilt: '1980',
    subdivision: 'Ponderosa Forest-Condo',
    county: 'Galveston',
    remarks: '1-Bedroom, 1-bath condo, Retreat and move-in ready ...',
    photo: '/assets/rentals/dickinson/70009601.jpg',
    status: 'Active',
  },
  {
    mls: '11220560',
    address: '2302 Ave Avenue N',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$3,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,200',
    acres: '0.551',
    yearBuilt: '1980',
    subdivision: 'San Leon Farm Home Tracts',
    county: 'Galveston',
    remarks: 'ALL furnitures/appliances will stay! GREAT WATERFR ...',
    photo: '/assets/rentals/dickinson/11220560.jpg',
    status: 'Active',
  },
  {
    mls: '32659920',
    address: '217 Brookwood Park Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,550',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,973',
    acres: '0.15',
    yearBuilt: '2016',
    subdivision: 'Bay View Sec 3',
    county: 'Galveston',
    remarks: 'Welcome to 217 Brookwood Park Ln! This well-mainta ...',
    photo: '/assets/rentals/dickinson/32659920.jpg',
    status: 'Active',
  },
  {
    mls: '80129802',
    address: '909 Fm 517 Road E F',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '749',
    acres: '0.3',
    yearBuilt: '1975',
    subdivision: 'Dickinson Add D',
    county: 'Galveston',
    remarks: 'Welcome to this charming 2-bedroom apartment avail ...',
    photo: '/assets/rentals/dickinson/80129802.jpg',
    status: 'Active',
  },
  {
    mls: '20871349',
    address: '418 Folk Crest Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,702',
    acres: '0.089',
    yearBuilt: '2004',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'Beautiful 3-Bedroom Townhome located in the desira ...',
    photo: '/assets/rentals/dickinson/20871349.jpg',
    status: 'Active',
  },
  {
    mls: '56589392',
    address: '5221 Cottonwood Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,009',
    acres: '0.206',
    yearBuilt: '1972',
    subdivision: 'Oak Land 1',
    county: 'Galveston',
    remarks: 'Corner lot home in established neighborhood with r ...',
    photo: '/assets/rentals/dickinson/56589392.jpg',
    status: 'Active',
  },
  {
    mls: '49623778',
    address: '3010 Stonecross Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,557',
    acres: '0.149',
    yearBuilt: '2005',
    subdivision: 'Bay Colony Pointe West Sec 1',
    county: 'Galveston',
    remarks: 'Welcome home to this well-maintained 3-bedroom, 2- ...',
    photo: '/assets/rentals/dickinson/49623778.jpg',
    status: 'Active',
  },
  {
    mls: '26835851',
    address: '3705 Misty Cove Court',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,609',
    acres: '0.187',
    yearBuilt: '1978',
    subdivision: 'Briar Glen Sec 1 Ph 2',
    county: 'Galveston',
    remarks: 'This beautiful Dickinson home is move-in ready and ...',
    photo: '/assets/rentals/dickinson/26835851.jpg',
    status: 'Pending',
  },
  {
    mls: '11453665',
    address: '319 Brandy Ridge Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,702',
    acres: '0.112',
    yearBuilt: '2008',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'Nestled in a desirable location, this townhouse co ...',
    photo: '/assets/rentals/dickinson/11453665.jpg',
    status: 'Active',
  },
  {
    mls: '73007099',
    address: '3205 Granite Gate Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,844',
    acres: '0.157',
    yearBuilt: '2009',
    subdivision: 'Bay Colony Pointe West Sec 3 P',
    county: 'Galveston',
    remarks: 'GREAT ONE STORY BRICK HOME MUST SEE. K ...',
    photo: '/assets/rentals/dickinson/73007099.jpg',
    status: 'Active',
  },
  {
    mls: '96813930',
    address: '2883 Diamond Bay Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,320',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,092',
    acres: '0.138',
    yearBuilt: '2003',
    subdivision: 'Bay Colony Pointe Sec 5 2003',
    county: 'Galveston',
    remarks: 'You’re in for a treat. We’re giving this house a m ...',
    photo: '/assets/rentals/dickinson/96813930.jpg',
    status: 'Active',
  },
  {
    mls: '79283568',
    address: '3902-B Video Street Street B',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$815',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '400',
    acres: '0.125',
    yearBuilt: '',
    subdivision: 'Oak Park Add',
    county: 'Galveston',
    remarks: '1/1 Recently refreshed with re-finished original w ...',
    photo: '/assets/rentals/dickinson/79283568.jpg',
    status: 'Active',
  },
  {
    mls: '61690672',
    address: '4803 28th Street E',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,216',
    acres: '0.207',
    yearBuilt: '1974',
    subdivision: 'Nicholstone',
    county: 'Galveston',
    remarks: 'Move-in ready 3-bedroom, 2-bath home in the desira ...',
    photo: '/assets/rentals/dickinson/61690672.jpg',
    status: 'Active',
  },
  {
    mls: '3240423',
    address: '641 4th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,408',
    acres: '0.147',
    yearBuilt: '2011',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Beautifully maintained 3-bedroom, 2 bath home in t ...',
    photo: '/assets/rentals/dickinson/3240423.jpg',
    status: 'Active',
  },
  {
    mls: '56090160',
    address: '4106 California Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,494',
    acres: '0.243',
    yearBuilt: '1984',
    subdivision: 'Oleander Park',
    county: 'Galveston',
    remarks: 'Beautiful 3 bed/2 bath home on a generous lot. Li ...',
    photo: '/assets/rentals/dickinson/56090160.jpg',
    status: 'Active',
  },
  {
    mls: '67127092',
    address: '341 Capella Oaks Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,995',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,702',
    acres: '0.171',
    yearBuilt: '2005',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'One mile of I45 for easy commuting to Houston or G ...',
    photo: '/assets/rentals/dickinson/67127092.jpg',
    status: 'Active',
  },
  {
    mls: '25864239',
    address: '336 Capella Oaks Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,714',
    acres: '0.083',
    yearBuilt: '2005',
    subdivision: 'Retreat In Bay Colony 2004',
    county: 'Galveston',
    remarks: 'Welcome to this charming 3 bed, 2 bath home featur ...',
    photo: '/assets/rentals/dickinson/25864239.jpg',
    status: 'Active',
  },
  {
    mls: '64299798',
    address: '202 Pebble Walk Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,295',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,415',
    acres: '0.141',
    yearBuilt: '2003',
    subdivision: 'Enclave At Bay Colony 2002',
    county: 'Galveston',
    remarks: 'Beautifully maintained 3-bedroom, 2-bath home loca ...',
    photo: '/assets/rentals/dickinson/64299798.jpg',
    status: 'Pending',
  },
  {
    mls: '15464893',
    address: '4203 W Bayou Maison Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,340',
    acres: '0.11',
    yearBuilt: '2021',
    subdivision: 'Bayou Maison-Sec 2',
    county: 'Galveston',
    remarks: 'Nestled in a desirable Dickinson neighborhood, 420 ...',
    photo: '/assets/rentals/dickinson/15464893.jpg',
    status: 'Active',
  },
  {
    mls: '76100932',
    address: '3011 Main Street 3015',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,300',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,050',
    acres: '0.165',
    yearBuilt: '1980',
    subdivision: 'Parke &amp; Dockrell',
    county: 'Galveston',
    remarks: 'No steps! Two-bedroom, one-bath with recent update ...',
    photo: '/assets/rentals/dickinson/76100932.jpg',
    status: 'Active',
  },
  {
    mls: '45940081',
    address: '1133 9th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,650',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,140',
    acres: '0.154',
    yearBuilt: '1980',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Welcome to this well-maintained 3-bedroom, 1-bath ...',
    photo: '/assets/rentals/dickinson/45940081.jpg',
    status: 'Active',
  },
  {
    mls: '80325468',
    address: '2931 Silver Landing Lane',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$3,175',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,769',
    acres: '0.141',
    yearBuilt: '2006',
    subdivision: 'Bay Colony Pointe Sec 6 2004',
    county: 'Galveston',
    remarks: 'Exceptional Bay Colony Pointe home for sale or for ...',
    photo: '/assets/rentals/dickinson/80325468.jpg',
    status: 'Active',
  },
  {
    mls: '28089194',
    address: '4031 Raspberry Court',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,291',
    acres: '0.172',
    yearBuilt: '2008',
    subdivision: 'Berry Field Sub 2005',
    county: 'Galveston',
    remarks: 'Welcome to Berry Field—where quiet charm meets mod ...',
    photo: '/assets/rentals/dickinson/28089194.jpg',
    status: 'Active',
  },
  {
    mls: '45680024',
    address: '5104 39th Street 3',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$850',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '750',
    acres: '1.62',
    yearBuilt: '2023',
    subdivision: 'Tudors',
    county: 'Galveston',
    remarks: 'Newly built Studio with open floor plan available ...',
    photo: '/assets/rentals/dickinson/45680024.jpg',
    status: 'Active',
  },
  {
    mls: '64268428',
    address: '3206 Teakwood Circle',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,615',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,323',
    acres: '0.15',
    yearBuilt: '1984',
    subdivision: 'Edgewood',
    county: 'Galveston',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/dickinson/64268428.jpg',
    status: 'Pending',
  },
  {
    mls: '51183123',
    address: '717 7th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$900',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '0.07',
    yearBuilt: '2011',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Located in Sunny San Leon. Close to Kemah. League ...',
    photo: '/assets/rentals/dickinson/51183123.jpg',
    status: 'Active',
  },
  {
    mls: '82826330',
    address: '2454 Fm-517',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$7,500',
    beds: '0 Bedrooms',
    baths: 'Total Baths',
    sqft: '',
    acres: '9.827',
    yearBuilt: '',
    subdivision: 'San Leon Farm Home Tracts',
    county: 'Galveston',
    remarks: '9.83 acres of prime commercial land available for ...',
    photo: '/assets/rentals/dickinson/82826330.jpg',
    status: 'Active',
  },
  {
    mls: '81747829',
    address: '3515 Elm Drive',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,077',
    acres: '0.713',
    yearBuilt: '1972',
    subdivision: 'Dickinson Add D',
    county: 'Galveston',
    remarks: 'JUST LISTED NEAR NASA! You will find this beautifu ...',
    photo: '/assets/rentals/dickinson/81747829.jpg',
    status: 'Active',
  },
  {
    mls: '59695229',
    address: '915 24th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,260',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'San Leon Farm Home Tracts',
    county: 'Galveston',
    remarks: 'New apartment for rent in a gated community in San ...',
    photo: '/assets/rentals/dickinson/59695229.jpg',
    status: 'Active',
  },
  {
    mls: '12587086',
    address: '2322 Central Street 4',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,350',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '3,060',
    acres: '0.321',
    yearBuilt: '1970',
    subdivision: 'Central Park - Dickinson',
    county: 'Galveston',
    remarks: '2322 Central Street Unit #4 (2 bedroom 1.5 bath) ...',
    photo: '/assets/rentals/dickinson/12587086.jpg',
    status: 'Active',
  },
  {
    mls: '41040533',
    address: '318 10th Street',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$1,599',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,412',
    acres: '0.147',
    yearBuilt: '1996',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'NEAR THE BAY! We just listed this nice 2 story hom ...',
    photo: '/assets/rentals/dickinson/41040533.jpg',
    status: 'Active',
  },
  {
    mls: '66345599',
    address: '3936 Wagon Road',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$4,800',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,065',
    acres: '0.408',
    yearBuilt: '1972',
    subdivision: 'Dickinson Bayou Park',
    county: 'Galveston',
    remarks: 'Welcome to your ultimate vacation getaway! Nestled ...',
    photo: '/assets/rentals/dickinson/66345599.jpg',
    status: 'Active',
  },
  {
    mls: '10067529',
    address: '8019 W Fm 517 Road W',
    city: 'Dickinson',
    state: 'Texas',
    zip: '77539',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,600',
    acres: '1.015',
    yearBuilt: '2000',
    subdivision: 'Prairie Estates',
    county: 'Galveston',
    remarks: 'High visibility location on 517. Corner Unit. Thre ...',
    photo: '/assets/rentals/dickinson/10067529.jpg',
    status: 'Active',
  },
]
