// San Leon homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const sanleonRentListings: Listing[] = [
  {
    mls: '10524335',
    address: '315 20th',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,695',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,247',
    acres: '0.385',
    yearBuilt: '2011',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'A classic, one story, three-bedroom, two bath hous ...',
    photo: '/assets/rentals/san-leon/10524335.jpg',
    status: 'Active',
  },
  {
    mls: '58662827',
    address: '1578 Railroad Avenue',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,650',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '899',
    acres: '0.095',
    yearBuilt: '1997',
    subdivision: 'Bayville Unrec',
    county: 'Galveston',
    remarks: 'COASTAL LIVING just one block from Galveston Bay! ...',
    photo: '/assets/rentals/san-leon/58662827.jpg',
    status: 'Active',
  },
  {
    mls: '45431925',
    address: '118 14th Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,720',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '800',
    acres: '0.147',
    yearBuilt: '1970',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'This stunning property with new balcony extension ...',
    photo: '/assets/rentals/san-leon/45431925.jpg',
    status: 'Active',
  },
  {
    mls: '20228528',
    address: '903 16th Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,200',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '630',
    acres: '0.154',
    yearBuilt: '1995',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Coastal 1 bedroom home in sunny San Leon/Large wa ...',
    photo: '/assets/rentals/san-leon/20228528.jpg',
    status: 'Active',
  },
  {
    mls: '20381033',
    address: '124 7th Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,600',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '790',
    acres: '0.441',
    yearBuilt: '1971',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Charming 2-bedroom, 1-bath coastal cottage with be ...',
    photo: '/assets/rentals/san-leon/20381033.jpg',
    status: 'Active',
  },
  {
    mls: '77478980',
    address: '215 13th Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,360',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,000',
    acres: '0.15',
    yearBuilt: '1970',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Charming 2 bed, 1 bath home with a wrap around por ...',
    photo: '/assets/rentals/san-leon/77478980.jpg',
    status: 'Active',
  },
  {
    mls: '69535872',
    address: '2535 Broadway Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,937',
    acres: '0.25',
    yearBuilt: '2006',
    subdivision: 'San Leon Farm Home Tracts',
    county: 'Galveston',
    remarks: 'Spacious and well-designed, this property offers 3 ...',
    photo: '/assets/rentals/san-leon/69535872.jpg',
    status: 'Active',
  },
  {
    mls: '84646863',
    address: '501 2nd Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$3,600',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '1,901',
    acres: '0.23',
    yearBuilt: '2009',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Wake up to stunning Galveston Bay sunrises and end ...',
    photo: '/assets/rentals/san-leon/84646863.jpg',
    status: 'Active',
  },
  {
    mls: '5927088',
    address: '926 9th Street SE',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,200',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '800',
    acres: '0.154',
    yearBuilt: '1998',
    subdivision: 'Sanleon-6240',
    county: 'Galveston',
    remarks: 'Enjoy Bay Breezes from covered porch that faces Ea ...',
    photo: '/assets/rentals/san-leon/5927088.jpg',
    status: 'Active',
  },
  {
    mls: '58525962',
    address: '415 12th',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,800',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '0.294',
    yearBuilt: '2009',
    subdivision: 'San Leon Townsite',
    county: 'Galveston',
    remarks: 'Discover a one-of-a-kind rental opportunity at 415 ...',
    photo: '/assets/rentals/san-leon/58525962.jpg',
    status: 'Active',
  },
  {
    mls: '97616610',
    address: '120 5th Street 4',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,000',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '750',
    acres: '0.22',
    yearBuilt: '1975',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Fully Furnished!! Welcome to your charming coastal ...',
    photo: '/assets/rentals/san-leon/97616610.jpg',
    status: 'Active',
  },
  {
    mls: '88099478',
    address: '415 2nd Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,544',
    acres: '0.425',
    yearBuilt: '1992',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'This charming 3 bedroom 2 1/2 bath waterfront home ...',
    photo: '/assets/rentals/san-leon/88099478.jpg',
    status: 'Pending',
  },
  {
    mls: '79002590',
    address: '1010 22nd Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,195',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '800',
    acres: '0.245',
    yearBuilt: '2005',
    subdivision: 'San Leon Farm Home Tracts',
    county: 'Galveston',
    remarks: 'Ground level efficiency apartment with full kitche ...',
    photo: '/assets/rentals/san-leon/79002590.jpg',
    status: 'Active',
  },
  {
    mls: '68402227',
    address: '512 2nd',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$3,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,520',
    acres: '0.11',
    yearBuilt: '2026',
    subdivision: 'Halili Cove',
    county: 'Galveston',
    remarks: 'Dreaming of life on the water but not ready to pur ...',
    photo: '/assets/rentals/san-leon/68402227.jpg',
    status: 'Active',
  },
  {
    mls: '75038153',
    address: '510 2nd Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$3,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,520',
    acres: '0.11',
    yearBuilt: '2026',
    subdivision: 'Halili Cove',
    county: 'Galveston',
    remarks: 'Dreaming of life on the water but not ready to pur ...',
    photo: '/assets/rentals/san-leon/75038153.jpg',
    status: 'Active',
  },
  {
    mls: '68189379',
    address: '2724 Avenue D 9',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '980',
    acres: '',
    yearBuilt: '2023',
    subdivision: 'San Leon Farm Home',
    county: 'Galveston',
    remarks: 'A very cozy home in a nice gated community, ready ...',
    photo: '/assets/rentals/san-leon/68189379.jpg',
    status: 'Active',
  },
  {
    mls: '2474565',
    address: '120 5th Street 1',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$900',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '750',
    acres: '0.22',
    yearBuilt: '1975',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Welcome to your charming coastal retreat! This 1-b ...',
    photo: '/assets/rentals/san-leon/2474565.jpg',
    status: 'Active',
  },
  {
    mls: '29077056',
    address: '642 5th Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,600',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '688',
    acres: '0.367',
    yearBuilt: '1955',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'Welcome to this charming 1/1 cottage by the Bay, s ...',
    photo: '/assets/rentals/san-leon/29077056.jpg',
    status: 'Active',
  },
  {
    mls: '93961988',
    address: '2293 E Bayshore Drive',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$3,700',
    beds: '3 Bedrooms',
    baths: '5 Total Baths',
    sqft: '7,128',
    acres: '3.29',
    yearBuilt: '2004',
    subdivision: 'San Leon Farm Home Tracts',
    county: 'Galveston',
    remarks: 'Are you looking for a unique opportunity to lease ...',
    photo: '/assets/rentals/san-leon/93961988.jpg',
    status: 'Active',
  },
  {
    mls: '13354794',
    address: '203 6th St D',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,750',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '0.147',
    yearBuilt: '2018',
    subdivision: 'San Leon',
    county: 'Galveston',
    remarks: 'READY FOR IMMEDIATE MOVE IN- FULLY FURNISHED unit ...',
    photo: '/assets/rentals/san-leon/13354794.jpg',
    status: 'Active',
  },
  {
    mls: '95803113',
    address: '306 Tennyson Street',
    city: 'San Leon',
    state: 'Texas',
    zip: '77539',
    price: '$1,795',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,148',
    acres: '0.246',
    yearBuilt: '1975',
    subdivision: 'Tennys',
    county: 'Galveston',
    remarks: 'NEAR THE BAY! Discover this charming 3-bedroom, 1- ...',
    photo: '/assets/rentals/san-leon/95803113.jpg',
    status: 'Active',
  },
]
