// El Lago homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const ellagoRentListings: Listing[] = [
  {
    mls: '7507978',
    address: '422 Willow Vista Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,598',
    acres: '0.221',
    yearBuilt: '1968',
    subdivision: 'El Lago Sec 03',
    county: 'Harris',
    remarks: 'Move-in ready and beautifully remodeled, this spac ...',
    photo: '/assets/rentals/el-lago/7507978.jpg',
    status: 'Active',
  },
  {
    mls: '77600092',
    address: '427 Whitecap Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,558',
    acres: '0.202',
    yearBuilt: '1966',
    subdivision: 'El Lago Estates Sec 06',
    county: 'Harris',
    remarks: 'Welcome to this charming 4-bedroom, 2.5-bath home ...',
    photo: '/assets/rentals/el-lago/77600092.jpg',
    status: 'Pending',
  },
  {
    mls: '88036506',
    address: '1623 Lake Arbor Drive',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$7,000',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,508',
    acres: '0.383',
    yearBuilt: '1988',
    subdivision: 'Taylorcrest',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/el-lago/88036506.jpg',
    status: 'Active',
  },
  {
    mls: '56827957',
    address: '4001 Nasa Parkway 213',
    city: 'El Lago',
    state: 'Texas',
    zip: '77586',
    price: '$1,300',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '782',
    acres: '2.501',
    yearBuilt: '1980',
    subdivision: 'Lakeshore',
    county: 'Harris',
    remarks: 'Spectacular one bedroom corner unit has been updat ...',
    photo: '/assets/rentals/el-lago/56827957.jpg',
    status: 'Active',
  },
]
