// Pasadena homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const pasadenaRentListings: Listing[] = [
  {
    mls: '6441177',
    address: '3324 Kathryn Circle',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,795',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,489',
    acres: '0.225',
    yearBuilt: '1968',
    subdivision: 'Berkshire Village Sec 02',
    county: 'Harris',
    remarks: 'Welcome to this charming 3 bed 2 bath home, perfec ...',
    photo: '/assets/rentals/pasadena/6441177.jpg',
    status: 'Active',
  },
  {
    mls: '30706802',
    address: '6220 Stoney Creek Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,596',
    acres: '0.069',
    yearBuilt: '2007',
    subdivision: 'Twin Villas/Red Bluff Sec 01',
    county: 'Harris',
    remarks: 'Welcome Home to 6220 Stoney Creek Dr!Move-in ready ...',
    photo: '/assets/rentals/pasadena/30706802.jpg',
    status: 'Active',
  },
  {
    mls: '80983730',
    address: '324 Johnson Street B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,500',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,010',
    acres: '0.095',
    yearBuilt: '1948',
    subdivision: 'Pasadena Outlot 80',
    county: 'Harris',
    remarks: 'Welcome to this charming 3-bedroom, 1-bathroom hom ...',
    photo: '/assets/rentals/pasadena/80983730.jpg',
    status: 'Active',
  },
  {
    mls: '32284591',
    address: '1314 Bernard Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,399',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '788',
    acres: '0.155',
    yearBuilt: '1944',
    subdivision: 'Pasadena Gardens',
    county: 'Harris',
    remarks: 'VERY NICE 2-bedroom, 1-bath home for rent in the d ...',
    photo: '/assets/rentals/pasadena/32284591.jpg',
    status: 'Active',
  },
  {
    mls: '29177095',
    address: '2922 Randolph Road 4',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '735',
    acres: '0.104',
    yearBuilt: '1968',
    subdivision: 'Kingsdale',
    county: 'Harris',
    remarks: 'Welcome to this 2 bedroom 1 bath in Pasadena, TX. ...',
    photo: '/assets/rentals/pasadena/29177095.jpg',
    status: 'Active',
  },
  {
    mls: '10168378',
    address: '1611 Chippawa Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,850',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,207',
    acres: '0.138',
    yearBuilt: '1975',
    subdivision: 'Burke Meadow Sec 02',
    county: 'Harris',
    remarks: 'Clean and ready for a new family! Located in Pasad ...',
    photo: '/assets/rentals/pasadena/10168378.jpg',
    status: 'Active',
  },
  {
    mls: '48671909',
    address: '4122 Donerail Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$2,150',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,444',
    acres: '0.154',
    yearBuilt: '1972',
    subdivision: 'Bowling Green Sec 01',
    county: 'Harris',
    remarks: 'A bright and comfortable home with spaces that eas ...',
    photo: '/assets/rentals/pasadena/48671909.jpg',
    status: 'Active',
  },
  {
    mls: '14046355',
    address: '3017 Fern Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,800',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,745',
    acres: '0.126',
    yearBuilt: '1952',
    subdivision: 'Deepwater',
    county: 'Harris',
    remarks: 'This beautifully remodeled home features 4 bedroom ...',
    photo: '/assets/rentals/pasadena/14046355.jpg',
    status: 'Active',
  },
  {
    mls: '72887568',
    address: '2612 Primrose Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,228',
    acres: '0.819',
    yearBuilt: '1988',
    subdivision: 'Golden Crest',
    county: 'Harris',
    remarks: 'Unique cabin-style property offering character, pr ...',
    photo: '/assets/rentals/pasadena/72887568.jpg',
    status: 'Active',
  },
  {
    mls: '91516752',
    address: '1206 Gary Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,290',
    acres: '0.174',
    yearBuilt: '1956',
    subdivision: 'Frontier East Sec 03',
    county: 'Harris',
    remarks: 'Fully renovated and move-in ready! This beautiful ...',
    photo: '/assets/rentals/pasadena/91516752.jpg',
    status: 'Active',
  },
  {
    mls: '88062663',
    address: '6219 Canada Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,250',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,044',
    acres: '0.164',
    yearBuilt: '1979',
    subdivision: 'Fairmont Heights Sec 01',
    county: 'Harris',
    remarks: 'Recently Renovated Showstopper with 2026 AC! Welco ...',
    photo: '/assets/rentals/pasadena/88062663.jpg',
    status: 'Active',
  },
  {
    mls: '58929385',
    address: '4834 Pine Avenue A',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,440',
    acres: '0.294',
    yearBuilt: '2024',
    subdivision: 'Golden Acres Sec 01',
    county: 'Harris',
    remarks: 'This beautiful & spacious 3 bedroom, 2.5 bath T/H ...',
    photo: '/assets/rentals/pasadena/58929385.jpg',
    status: 'Active',
  },
  {
    mls: '60541737',
    address: '4422 Park Trail Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,395',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,712',
    acres: '0.072',
    yearBuilt: '2003',
    subdivision: 'Village Grove East T H',
    county: 'Harris',
    remarks: 'Welcome to 4422 Park Trail Lane! This well-maintai ...',
    photo: '/assets/rentals/pasadena/60541737.jpg',
    status: 'Active',
  },
  {
    mls: '98376378',
    address: '3919 Fairmont Parkway 257',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,100',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '705',
    acres: '7.218',
    yearBuilt: '1980',
    subdivision: 'Walnut Hill Condo',
    county: 'Harris',
    remarks: 'Move-in ready 1-bedroom, 1-bath first-floor condo ...',
    photo: '/assets/rentals/pasadena/98376378.jpg',
    status: 'Active',
  },
  {
    mls: '17773973',
    address: '3816 Newton Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,132',
    acres: '0.138',
    yearBuilt: '1963',
    subdivision: 'Bennett Estates Sec 03 R/P',
    county: 'Harris',
    remarks: 'Move-In Ready 3-Bedroom Rental in Pasadena!Welcome ...',
    photo: '/assets/rentals/pasadena/17773973.jpg',
    status: 'Active',
  },
  {
    mls: '85457938',
    address: '1413 George Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,595',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,294',
    acres: '0.144',
    yearBuilt: '1950',
    subdivision: 'Hill',
    county: 'Harris',
    remarks: 'Lists price includes move in special. $100 OFF the ...',
    photo: '/assets/rentals/pasadena/85457938.jpg',
    status: 'Active',
  },
  {
    mls: '27794335',
    address: '1012 W Hart Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,503',
    acres: '0.168',
    yearBuilt: '1948',
    subdivision: 'Sunset Terrace Sec 01',
    county: 'Harris',
    remarks: 'COMPLETELY REMODELED and MOVE-IN READY! This beaut ...',
    photo: '/assets/rentals/pasadena/27794335.jpg',
    status: 'Active',
  },
  {
    mls: '62118944',
    address: '7018 Crystal Dowels Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,097',
    acres: '0.145',
    yearBuilt: '1998',
    subdivision: 'Baywood Oaks Village',
    county: 'Harris',
    remarks: 'Beautiful, spacious home. Wood laminate flooring i ...',
    photo: '/assets/rentals/pasadena/62118944.jpg',
    status: 'Active',
  },
  {
    mls: '81318157',
    address: '3919 Fairmont 148',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,195',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '976',
    acres: '',
    yearBuilt: '1980',
    subdivision: 'Walnut Hill Condo',
    county: 'Harris',
    remarks: 'COZY LIVING SPACE WITH FIREPLACE . KIT ...',
    photo: '/assets/rentals/pasadena/81318157.jpg',
    status: 'Active',
  },
  {
    mls: '32938438',
    address: '5035 Reno Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '810',
    acres: '0.086',
    yearBuilt: '1980',
    subdivision: 'Reno Village R/P',
    county: 'Harris',
    remarks: 'Welcome to 5035 Reno! This renovated single famil ...',
    photo: '/assets/rentals/pasadena/32938438.jpg',
    status: 'Active',
  },
  {
    mls: '45551350',
    address: '2513 Mulberry Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,800',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,618',
    acres: '0.163',
    yearBuilt: '1960',
    subdivision: 'Park View Manor Sec 01',
    county: 'Harris',
    remarks: 'Welcome to this inviting two-story, four-bedroom, ...',
    photo: '/assets/rentals/pasadena/45551350.jpg',
    status: 'Pending',
  },
  {
    mls: '53846529',
    address: '705 Texas Avenue A',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,200',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1938',
    subdivision: 'Pasadena Outlot 102',
    county: 'Harris',
    remarks: 'This charming upstairs unit features one bedroom a ...',
    photo: '/assets/rentals/pasadena/53846529.jpg',
    status: 'Pending',
  },
  {
    mls: '12715924',
    address: '1504 Lawrence Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,786',
    acres: '0.231',
    yearBuilt: '1944',
    subdivision: 'Pasadena Gardens',
    county: 'Harris',
    remarks: 'Welcome to this spacious 3-bedroom, 2-bath home in ...',
    photo: '/assets/rentals/pasadena/12715924.jpg',
    status: 'Active',
  },
  {
    mls: '78626997',
    address: '4422 Haiti Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,375',
    acres: '0.138',
    yearBuilt: '1981',
    subdivision: 'Fairmont Estates Sec 03 R/P',
    county: 'Harris',
    remarks: 'This move-in ready home features new carpet, paint ...',
    photo: '/assets/rentals/pasadena/78626997.jpg',
    status: 'Active',
  },
  {
    mls: '97715268',
    address: '601 Fresa Road',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,850',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,182',
    acres: '0.184',
    yearBuilt: '1955',
    subdivision: 'Alta Vista Terrace',
    county: 'Harris',
    remarks: 'Beautifully remodeled home in a prime Pasadena loc ...',
    photo: '/assets/rentals/pasadena/97715268.jpg',
    status: 'Active',
  },
  {
    mls: '15586331',
    address: '2726 Yale Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,100',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,794',
    acres: '0.137',
    yearBuilt: '1966',
    subdivision: 'Fieldcrest',
    county: 'Harris',
    remarks: 'This beautifully remodeled Pasadena home offers mo ...',
    photo: '/assets/rentals/pasadena/15586331.jpg',
    status: 'Active',
  },
  {
    mls: '90812632',
    address: '3910 Chile Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$2,850',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,431',
    acres: '0.244',
    yearBuilt: '1969',
    subdivision: 'Vista Villas Sec 01',
    county: 'Harris',
    remarks: 'Looking for an amazing Pasadena rental home with p ...',
    photo: '/assets/rentals/pasadena/90812632.jpg',
    status: 'Active',
  },
  {
    mls: '31616086',
    address: '4902 Rainwater Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$1,800',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,729',
    acres: '0.166',
    yearBuilt: '1979',
    subdivision: 'Parkgate North',
    county: 'Harris',
    remarks: 'Discover comfort and convenience in this beautiful ...',
    photo: '/assets/rentals/pasadena/31616086.jpg',
    status: 'Active',
  },
  {
    mls: '39912318',
    address: '705 Texas Avenue B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,499',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1938',
    subdivision: 'Pasadena Outlot 102',
    county: 'Harris',
    remarks: 'This comfortable downstairs unit features two bedr ...',
    photo: '/assets/rentals/pasadena/39912318.jpg',
    status: 'Active',
  },
  {
    mls: '86169352',
    address: '703 Texas Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$2,499',
    beds: '5 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,530',
    acres: '0.437',
    yearBuilt: '1938',
    subdivision: 'Pasadena Outlot 102',
    county: 'Harris',
    remarks: 'This spacious single-story home features five bedr ...',
    photo: '/assets/rentals/pasadena/86169352.jpg',
    status: 'Pending',
  },
  {
    mls: '33553368',
    address: '707 Garrett Street B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,771',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '2017',
    subdivision: 'Pasadena Gardens',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/pasadena/33553368.jpg',
    status: 'Active',
  },
  {
    mls: '78465444',
    address: '1405 Richard Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,450',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,104',
    acres: '0.139',
    yearBuilt: '1944',
    subdivision: 'Pasadena Gardens',
    county: 'Harris',
    remarks: 'Welcome to 1405 Richard Avenue! This charming 3-be ...',
    photo: '/assets/rentals/pasadena/78465444.jpg',
    status: 'Pending',
  },
  {
    mls: '96774223',
    address: '1012 Ann Street F',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$999',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1957',
    subdivision: 'Warren Acres U/R',
    county: 'Harris',
    remarks: 'This 1-bed, 1-bath apartment offers a perfect blen ...',
    photo: '/assets/rentals/pasadena/96774223.jpg',
    status: 'Active',
  },
  {
    mls: '95908031',
    address: '514 Bertloma Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,850',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,220',
    acres: '0.147',
    yearBuilt: '1959',
    subdivision: 'Center Place',
    county: 'Harris',
    remarks: 'Completely Updated and Move In Ready Right Now',
    photo: '/assets/rentals/pasadena/95908031.jpg',
    status: 'Active',
  },
  {
    mls: '63347506',
    address: '3320 Hays Street B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$995',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '750',
    acres: '0.131',
    yearBuilt: '1955',
    subdivision: 'Deepwater Terrace Sec 03',
    county: 'Harris',
    remarks: 'Welcome home to this spacious 1 bedroom,1 bath apa ...',
    photo: '/assets/rentals/pasadena/63347506.jpg',
    status: 'Active',
  },
  {
    mls: '5176172',
    address: '6702 Tamar Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,215',
    acres: '0.145',
    yearBuilt: '1985',
    subdivision: 'Bramley',
    county: 'Harris',
    remarks: 'This 2 bed, 2 bath duplex features a nicely remode ...',
    photo: '/assets/rentals/pasadena/5176172.jpg',
    status: 'Active',
  },
  {
    mls: '26940014',
    address: '1012 Ann Street E',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$799',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1957',
    subdivision: 'Warren Acres U/R',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/pasadena/26940014.jpg',
    status: 'Active',
  },
  {
    mls: '60303585',
    address: '2007 S Rayburn Court',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,000',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,761',
    acres: '0.174',
    yearBuilt: '1965',
    subdivision: 'Parkview Estates Sec 01',
    county: 'Harris',
    remarks: 'Welcome to 2007 S Rayburn, a well-cared-for home i ...',
    photo: '/assets/rentals/pasadena/60303585.jpg',
    status: 'Pending',
  },
  {
    mls: '85809188',
    address: '3902 Paulette Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,999',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,485',
    acres: '0.193',
    yearBuilt: '1975',
    subdivision: 'Parkview South Sec 01',
    county: 'Harris',
    remarks: 'Loving where you live is easy when you have a hous ...',
    photo: '/assets/rentals/pasadena/85809188.jpg',
    status: 'Active',
  },
  {
    mls: '14425901',
    address: '500 W Pitts Avenue 104',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$985',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '5,100',
    acres: '0.782',
    yearBuilt: '1951',
    subdivision: 'Pitts',
    county: 'Harris',
    remarks: 'Discover affordable, comfortable living at Savanna ...',
    photo: '/assets/rentals/pasadena/14425901.jpg',
    status: 'Active',
  },
  {
    mls: '18638767',
    address: '1803 Weeping Oaks Drive B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,895',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,833',
    acres: '',
    yearBuilt: '2018',
    subdivision: 'Enchanted Oaks',
    county: 'Harris',
    remarks: 'Spacious 3-bedroom, 2.5-bath townhome zoned to hig ...',
    photo: '/assets/rentals/pasadena/18638767.jpg',
    status: 'Active',
  },
  {
    mls: '88660751',
    address: '4327 Oak Ridge Drive A',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,895',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,833',
    acres: '',
    yearBuilt: '2018',
    subdivision: 'Enchanted Oaks',
    county: 'Harris',
    remarks: 'Spacious 3-bedroom, 2.5-bath townhome zoned to hig ...',
    photo: '/assets/rentals/pasadena/88660751.jpg',
    status: 'Active',
  },
  {
    mls: '41598374',
    address: '302 Delta Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,124',
    acres: '0.152',
    yearBuilt: '1956',
    subdivision: 'Red Bluff Terrace Sec 05',
    county: 'Harris',
    remarks: 'Charming 3/4 bedroom, 1 bathroom home. Garage has ...',
    photo: '/assets/rentals/pasadena/41598374.jpg',
    status: 'Active',
  },
  {
    mls: '1049281',
    address: '4827 Pine Avenue A',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$899',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '550',
    acres: '1.27',
    yearBuilt: '1945',
    subdivision: 'Golden Acres',
    county: 'Harris',
    remarks: 'Welcome home to this cute downstairs 1-bedroom, 1- ...',
    photo: '/assets/rentals/pasadena/1049281.jpg',
    status: 'Active',
  },
  {
    mls: '39815314',
    address: '1213 Hector Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,595',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '875',
    acres: '0.157',
    yearBuilt: '1954',
    subdivision: 'Frontier East Sec 03',
    county: 'Harris',
    remarks: 'AVAILABLE NOW! Experience the perfect blend of lux ...',
    photo: '/assets/rentals/pasadena/39815314.jpg',
    status: 'Active',
  },
  {
    mls: '10654654',
    address: '303 Brown Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,695',
    beds: '4 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,420',
    acres: '0.152',
    yearBuilt: '1962',
    subdivision: 'Red Bluff Terrace Sec 07',
    county: 'Harris',
    remarks: 'AVAILABLE NOW! Experience the perfect blend of lux ...',
    photo: '/assets/rentals/pasadena/10654654.jpg',
    status: 'Active',
  },
  {
    mls: '32806044',
    address: '3919 Fairmont Parkway 200',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,250',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '780',
    acres: '7.218',
    yearBuilt: '1980',
    subdivision: 'Walnut Hill Condos',
    county: 'Harris',
    remarks: 'Welcome to the Condo Club! This cute little 2 bedr ...',
    photo: '/assets/rentals/pasadena/32806044.jpg',
    status: 'Active',
  },
  {
    mls: '18721905',
    address: '14 W Oaks Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77058',
    price: '$3,200',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,178',
    acres: '0.031',
    yearBuilt: '2017',
    subdivision: 'Armandwilde Twnhms',
    county: 'Harris',
    remarks: 'Welcome to the stunning Mediterranean style townho ...',
    photo: '/assets/rentals/pasadena/18721905.jpg',
    status: 'Active',
  },
  {
    mls: '31313126',
    address: '922 Hector Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,800',
    acres: '0.144',
    yearBuilt: '1954',
    subdivision: 'Frontier East Sec 01',
    county: 'Harris',
    remarks: 'Immaculate condition, move in ready Rental Home! B ...',
    photo: '/assets/rentals/pasadena/31313126.jpg',
    status: 'Active',
  },
  {
    mls: '59121434',
    address: '5606 Hyde Park Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,375',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,703',
    acres: '0.054',
    yearBuilt: '2023',
    subdivision: 'Parkway Trls Villas Amd P',
    county: 'Harris',
    remarks: 'Welcome to 5606 Hyde Park Dr.! This beautifully ma ...',
    photo: '/assets/rentals/pasadena/59121434.jpg',
    status: 'Active',
  },
  {
    mls: '96216288',
    address: '1714 Magnolia Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,950',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,420',
    acres: '0.145',
    yearBuilt: '1979',
    subdivision: 'Pineswept',
    county: 'Harris',
    remarks: 'Charming Pasadena Gem! This beautifully maintained ...',
    photo: '/assets/rentals/pasadena/96216288.jpg',
    status: 'Active',
  },
  {
    mls: '19855822',
    address: '410 Live Oak Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,604',
    acres: '0.123',
    yearBuilt: '1941',
    subdivision: 'Inland Harbor',
    county: 'Harris',
    remarks: 'Charming 3-bedroom home featuring original hardwoo ...',
    photo: '/assets/rentals/pasadena/19855822.jpg',
    status: 'Active',
  },
  {
    mls: '20725905',
    address: '1306 Heights Street C',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$675',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '2,551',
    acres: '0.133',
    yearBuilt: '1955',
    subdivision: 'Satsuma Heights',
    county: 'Harris',
    remarks: 'Discover the perfect blend of comfort and convenie ...',
    photo: '/assets/rentals/pasadena/20725905.jpg',
    status: 'Active',
  },
  {
    mls: '23985542',
    address: '2121 Hickory Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,670',
    acres: '0.152',
    yearBuilt: '1955',
    subdivision: 'Strawberry Hills Sec 04',
    county: 'Harris',
    remarks: '2121 Hickory Lane is a welcoming residential home ...',
    photo: '/assets/rentals/pasadena/23985542.jpg',
    status: 'Active',
  },
  {
    mls: '38075810',
    address: '510 Munger Street Unit A',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '858',
    acres: '',
    yearBuilt: '1945',
    subdivision: 'Jackson Place',
    county: 'Harris',
    remarks: 'Welcome home to a cute unit in a great location. U ...',
    photo: '/assets/rentals/pasadena/38075810.jpg',
    status: 'Active',
  },
  {
    mls: '11834786',
    address: '1805 Thelma Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,550',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,240',
    acres: '0.149',
    yearBuilt: '1954',
    subdivision: 'Stadium Estates Sec 01',
    county: 'Harris',
    remarks: 'Quiet, peaceful neighborhood! Clean 3-1-2 brick ho ...',
    photo: '/assets/rentals/pasadena/11834786.jpg',
    status: 'Active',
  },
  {
    mls: '65174895',
    address: '3751 Pine Cone Trail',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,084',
    acres: '0.179',
    yearBuilt: '1990',
    subdivision: 'Country Briar Sec 01',
    county: 'Harris',
    remarks: 'Make this beautiful house your new home. There is ...',
    photo: '/assets/rentals/pasadena/65174895.jpg',
    status: 'Active',
  },
  {
    mls: '85040471',
    address: '5504 Hyde Park Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,495',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,943',
    acres: '0.056',
    yearBuilt: '2023',
    subdivision: 'Parkway Trls Villas Amd P',
    county: 'Harris',
    remarks: 'MOVE IN READY!!! Full size washer/dryer and fridg ...',
    photo: '/assets/rentals/pasadena/85040471.jpg',
    status: 'Active',
  },
  {
    mls: '9173915',
    address: '5543 Evanston Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,764',
    acres: '0.053',
    yearBuilt: '2021',
    subdivision: 'Parkway Trls Villas Amd P',
    county: 'Harris',
    remarks: 'Welcome home to Parkway Trails! This beautifully d ...',
    photo: '/assets/rentals/pasadena/9173915.jpg',
    status: 'Pending',
  },
  {
    mls: '87654579',
    address: '4814 Windy Way',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,051',
    acres: '0.148',
    yearBuilt: '1999',
    subdivision: 'Preston Trails South Sec 02',
    county: 'Harris',
    remarks: 'Spacious home on cul-de-sac street. Central kitch ...',
    photo: '/assets/rentals/pasadena/87654579.jpg',
    status: 'Active',
  },
  {
    mls: '58245110',
    address: '504 Burke Road',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,675',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '982',
    acres: '0.139',
    yearBuilt: '1953',
    subdivision: 'Red Bluff Terrace Sec 04',
    county: 'Harris',
    remarks: 'Beautifully remodeled and move-in ready! This char ...',
    photo: '/assets/rentals/pasadena/58245110.jpg',
    status: 'Pending',
  },
  {
    mls: '54605088',
    address: '6607 Rockfield Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,095',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,310',
    acres: '0.166',
    yearBuilt: '1981',
    subdivision: 'Village Grove Sec 01',
    county: 'Harris',
    remarks: '*HOME IS IN THE PROCESS OF BEING MADE ...',
    photo: '/assets/rentals/pasadena/54605088.jpg',
    status: 'Active',
  },
  {
    mls: '11954811',
    address: '608 Trinity Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,234',
    acres: '0.165',
    yearBuilt: '2006',
    subdivision: 'Red Bluff Terrace Sec 04',
    county: 'Harris',
    remarks: 'Charming 3-bedroom, 2-bathroom home available for ...',
    photo: '/assets/rentals/pasadena/11954811.jpg',
    status: 'Pending',
  },
  {
    mls: '36401167',
    address: '603 Alvin Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '735',
    acres: '0.179',
    yearBuilt: '1944',
    subdivision: 'Pasadena Gardens',
    county: 'Harris',
    remarks: 'Welcome to this charming 2-bedroom, 1-bath home. T ...',
    photo: '/assets/rentals/pasadena/36401167.jpg',
    status: 'Active',
  },
  {
    mls: '84652633',
    address: '1502 Sudbury Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,352',
    acres: '0.191',
    yearBuilt: '1984',
    subdivision: 'Parkview South Sec 06',
    county: 'Harris',
    remarks: 'THIS HOME IS READY FOR IMMEDIATE MOVE ...',
    photo: '/assets/rentals/pasadena/84652633.jpg',
    status: 'Active',
  },
  {
    mls: '24285853',
    address: '1209 Glenn Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,650',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,281',
    acres: '0.187',
    yearBuilt: '1944',
    subdivision: 'Pasadena Gardens',
    county: 'Harris',
    remarks: 'Home in a desirable neighborhood 4 bed 2 full bath ...',
    photo: '/assets/rentals/pasadena/24285853.jpg',
    status: 'Active',
  },
  {
    mls: '89884041',
    address: '12242 Rutgers Park Court',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77058',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,103',
    acres: '0.122',
    yearBuilt: '1997',
    subdivision: 'University Park Patio Homes 02',
    county: 'Harris',
    remarks: 'Welcome home to this charming single-story, 3-bed, ...',
    photo: '/assets/rentals/pasadena/89884041.jpg',
    status: 'Pending',
  },
  {
    mls: '24294666',
    address: '605 Center Street B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,650',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,382',
    acres: '0.146',
    yearBuilt: '2011',
    subdivision: 'Brown G A Resub Blk Ol 115 Pas',
    county: 'Harris',
    remarks: 'Features:Two-story layoutDownstairs tiled flooring ...',
    photo: '/assets/rentals/pasadena/24294666.jpg',
    status: 'Active',
  },
  {
    mls: '10825727',
    address: '2107 Garvey Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$2,200',
    beds: '5 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,029',
    acres: '0.165',
    yearBuilt: '1951',
    subdivision: 'Red Bluff Terrace Sec 02',
    county: 'Harris',
    remarks: 'Available for showings end of October / beginning ...',
    photo: '/assets/rentals/pasadena/10825727.jpg',
    status: 'Active',
  },
  {
    mls: '87290788',
    address: '814 Mobile Drive B',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,002',
    acres: '0.185',
    yearBuilt: '2017',
    subdivision: 'Sunset Terrace Sec 03',
    county: 'Harris',
    remarks: 'Available for immediate move-in, 814 Mobile Drive ...',
    photo: '/assets/rentals/pasadena/87290788.jpg',
    status: 'Active',
  },
  {
    mls: '76320272',
    address: '1206-B Pinewood Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,550',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '850',
    acres: '0.185',
    yearBuilt: '1952',
    subdivision: 'Southmore Plaza Sec 02',
    county: 'Harris',
    remarks: 'Now available for lease! Welcome to 1206-B Pinewoo ...',
    photo: '/assets/rentals/pasadena/76320272.jpg',
    status: 'Active',
  },
  {
    mls: '97647743',
    address: '1206 Pinewood Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$1,850',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,450',
    acres: '0.185',
    yearBuilt: '1952',
    subdivision: 'Southmore Plaza Sec 02',
    county: 'Harris',
    remarks: 'Now available for lease! Welcome to 1206 Pinewood ...',
    photo: '/assets/rentals/pasadena/97647743.jpg',
    status: 'Active',
  },
  {
    mls: '37966210',
    address: '408 Randall Street 9',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$950',
    beds: '1 Bedrooms',
    baths: '2 Total Baths',
    sqft: '500',
    acres: '0.144',
    yearBuilt: '1948',
    subdivision: 'Pasadena Outlot 96',
    county: 'Harris',
    remarks: 'This beautifully updated 1-bedroom, 2-bathroom apa ...',
    photo: '/assets/rentals/pasadena/37966210.jpg',
    status: 'Active',
  },
  {
    mls: '16731334',
    address: '4210 Wyatt Street 7',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,296',
    acres: '0.031',
    yearBuilt: '1974',
    subdivision: 'Bowling Green T/H',
    county: 'Harris',
    remarks: 'Well-maintained 3-bedroom, 2-bath townhouse conven ...',
    photo: '/assets/rentals/pasadena/16731334.jpg',
    status: 'Active',
  },
  {
    mls: '9285087',
    address: '4701 Crepe Myrtle Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$1,875',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,516',
    acres: '0.176',
    yearBuilt: '1966',
    subdivision: 'Huntington Sec 03',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/pasadena/9285087.jpg',
    status: 'Active',
  },
  {
    mls: '41943982',
    address: '410 Randall Street 7',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$950',
    beds: '1 Bedrooms',
    baths: '2 Total Baths',
    sqft: '500',
    acres: '0.144',
    yearBuilt: '1948',
    subdivision: 'Pasadena Outlot 96',
    county: 'Harris',
    remarks: 'Welcome to 410 Randall St #7 Pasadena, TX 77506! T ...',
    photo: '/assets/rentals/pasadena/41943982.jpg',
    status: 'Active',
  },
  {
    mls: '26206238',
    address: '3602 Cedarcrest Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,750',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,297',
    acres: '0.177',
    yearBuilt: '1970',
    subdivision: 'Tanglebriar Sec 06',
    county: 'Harris',
    remarks: 'Welcome to your next home in Pasadena! This inviti ...',
    photo: '/assets/rentals/pasadena/26206238.jpg',
    status: 'Active',
  },
  {
    mls: '60466409',
    address: '938 Vivian Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,800',
    beds: '4 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,412',
    acres: '0.174',
    yearBuilt: '1954',
    subdivision: 'Revelon Terrace',
    county: 'Harris',
    remarks: 'Welcome home to this beautifully updated 4-bedroom ...',
    photo: '/assets/rentals/pasadena/60466409.jpg',
    status: 'Active',
  },
  {
    mls: '75313497',
    address: '4305 Fairway Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$1,895',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,292',
    acres: '0.158',
    yearBuilt: '1977',
    subdivision: 'Fairmont Estates Sec 02',
    county: 'Harris',
    remarks: 'GREAT 3-2-2, FRESH PAINT, NEW CARPET, ...',
    photo: '/assets/rentals/pasadena/75313497.jpg',
    status: 'Pending',
  },
  {
    mls: '28856159',
    address: '411 Harris Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,222',
    acres: '0.135',
    yearBuilt: '1942',
    subdivision: 'Inland Harbor',
    county: 'Harris',
    remarks: 'Step into this delightful home right in the heart ...',
    photo: '/assets/rentals/pasadena/28856159.jpg',
    status: 'Pending',
  },
  {
    mls: '10796885',
    address: '3003 Briar Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,700',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,148',
    acres: '0.152',
    yearBuilt: '1983',
    subdivision: 'Tanglebriar Village',
    county: 'Harris',
    remarks: 'Adorable 2/3 bedroom, 2 bath, 2 car garage. Beaut ...',
    photo: '/assets/rentals/pasadena/10796885.jpg',
    status: 'Pending',
  },
  {
    mls: '46931913',
    address: '501 1/2 Johnson Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$795',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '900',
    acres: '0.172',
    yearBuilt: '1940',
    subdivision: 'Turner',
    county: 'Harris',
    remarks: 'Charming 1 bed, 1 bath upstairs unit in the heart ...',
    photo: '/assets/rentals/pasadena/46931913.jpg',
    status: 'Active',
  },
  {
    mls: '77646891',
    address: '1145 Lyric Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,105',
    acres: '0.035',
    yearBuilt: '1980',
    subdivision: 'San Augustine Th',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/pasadena/77646891.jpg',
    status: 'Active',
  },
  {
    mls: '91552576',
    address: '523 Spring Drive 4',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$985',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '980',
    acres: '0.209',
    yearBuilt: '1972',
    subdivision: 'Alta Vista Acres Sec 03',
    county: 'Harris',
    remarks: 'This second-floor unit is a 2-bedroom 1 bath with ...',
    photo: '/assets/rentals/pasadena/91552576.jpg',
    status: 'Active',
  },
  {
    mls: '16715296',
    address: '3368 Burke Road 163',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,195',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '945',
    acres: '',
    yearBuilt: '1969',
    subdivision: 'Bayshore T/H Condo',
    county: 'Harris',
    remarks: 'Welcome to Bayshore Townhomes! Conveniently locate ...',
    photo: '/assets/rentals/pasadena/16715296.jpg',
    status: 'Active',
  },
  {
    mls: '71225970',
    address: '2611 Prairie Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,384',
    acres: '0.176',
    yearBuilt: '1959',
    subdivision: 'Preston Villa Sec 02',
    county: 'Harris',
    remarks: 'This lovely Home is ready for new tenants! With 3 ...',
    photo: '/assets/rentals/pasadena/71225970.jpg',
    status: 'Active',
  },
  {
    mls: '35349244',
    address: '2628 Dupont Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,752',
    acres: '0.502',
    yearBuilt: '1970',
    subdivision: 'Spencer Hwy Gardens Sec 03',
    county: 'Harris',
    remarks: 'This beautifully renovated 3-bedroom, 2.5-bath res ...',
    photo: '/assets/rentals/pasadena/35349244.jpg',
    status: 'Active',
  },
  {
    mls: '35921097',
    address: '2112 Walnut Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,000',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,486',
    acres: '0.15',
    yearBuilt: '1957',
    subdivision: 'Strawberry Hill 5',
    county: 'Harris',
    remarks: 'Welcome to this Gorgeous Fully remodeled home in t ...',
    photo: '/assets/rentals/pasadena/35921097.jpg',
    status: 'Active',
  },
  {
    mls: '2821981',
    address: '616 Center Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,345',
    beds: '4 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,218',
    acres: '0.146',
    yearBuilt: '1941',
    subdivision: 'Pasadena Outlot 115',
    county: 'Harris',
    remarks: 'Welcome to this stylish 1-story home, offering app ...',
    photo: '/assets/rentals/pasadena/2821981.jpg',
    status: 'Pending',
  },
  {
    mls: '67150496',
    address: '706 Harris Avenue 4',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,095',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '700',
    acres: '0.918',
    yearBuilt: '1943',
    subdivision: 'Warren Acres U/R',
    county: 'Harris',
    remarks: 'APARTMENT!! Embrace urban living in this downstair ...',
    photo: '/assets/rentals/pasadena/67150496.jpg',
    status: 'Active',
  },
  {
    mls: '33073774',
    address: '401 Trichelle Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,450',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,706',
    acres: '0.202',
    yearBuilt: '1945',
    subdivision: 'West Jackson Park',
    county: 'Harris',
    remarks: 'Welcome to this well-kept and inviting home locate ...',
    photo: '/assets/rentals/pasadena/33073774.jpg',
    status: 'Active',
  },
  {
    mls: '41417218',
    address: '217 Johnson Street 1',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$795',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '550',
    acres: '0.144',
    yearBuilt: '1950',
    subdivision: 'Pasadena Outlot 74',
    county: 'Harris',
    remarks: 'Welcome to 217 Johnson St. Apartment 1 – a beautif ...',
    photo: '/assets/rentals/pasadena/41417218.jpg',
    status: 'Active',
  },
  {
    mls: '68342441',
    address: '1905 Zapp Lane',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,325',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,324',
    acres: '0.177',
    yearBuilt: '1964',
    subdivision: 'Maurice',
    county: 'Harris',
    remarks: 'Discover the charm of 1905 Zapp Lane, a spacious 4 ...',
    photo: '/assets/rentals/pasadena/68342441.jpg',
    status: 'Active',
  },
  {
    mls: '37164574',
    address: '718 E Belmont Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$1,250',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '976',
    acres: '0.144',
    yearBuilt: '1944',
    subdivision: 'San Jacinto Terrace',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/pasadena/37164574.jpg',
    status: 'Active',
  },
  {
    mls: '28131369',
    address: '6223 Denmark Drive',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77505',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,762',
    acres: '0.164',
    yearBuilt: '1983',
    subdivision: 'Fairmont Heights Sec 01',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated 3-bedroom, 2.5 ...',
    photo: '/assets/rentals/pasadena/28131369.jpg',
    status: 'Pending',
  },
  {
    mls: '67602108',
    address: '3119 Earl Street',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77503',
    price: '$1,750',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,294',
    acres: '0.126',
    yearBuilt: '1951',
    subdivision: 'Deepwater',
    county: 'Harris',
    remarks: 'Welcome to 3119 Earl St.!! Welcome to your new san ...',
    photo: '/assets/rentals/pasadena/67602108.jpg',
    status: 'Active',
  },
  {
    mls: '2175709',
    address: '3919 Fairmont Parkway 180',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77504',
    price: '$1,050',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '694',
    acres: '7.218',
    yearBuilt: '1980',
    subdivision: 'Walnut Hill Condo',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated 1 bedroom, 1 b ...',
    photo: '/assets/rentals/pasadena/2175709.jpg',
    status: 'Active',
  },
  {
    mls: '88090293',
    address: '1211 Trimm Avenue',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77502',
    price: '$2,600',
    beds: '6 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,112',
    acres: '0.167',
    yearBuilt: '1954',
    subdivision: 'Frontier East Sec 02',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/pasadena/88090293.jpg',
    status: 'Active',
  },
  {
    mls: '21699130',
    address: '904 Herbert D',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$750',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '0.257',
    yearBuilt: '1940',
    subdivision: 'Westfall',
    county: 'Harris',
    remarks: 'ALL BILLS PAID. Renovated in 2015, this 1-bedroom, ...',
    photo: '/assets/rentals/pasadena/21699130.jpg',
    status: 'Active',
  },
  {
    mls: '72951492',
    address: '311 Randall Street 1',
    city: 'Pasadena',
    state: 'Texas',
    zip: '77506',
    price: '$650',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '539',
    acres: '0.144',
    yearBuilt: '1940',
    subdivision: 'Pasadena Outlot 80',
    county: 'Harris',
    remarks: 'Welcome to this two-bedroom, one-bathroom unit, lo ...',
    photo: '/assets/rentals/pasadena/72951492.jpg',
    status: 'Active',
  },
]
