// Galveston homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const galvestonRentListings: Listing[] = [
  {
    mls: '11969499',
    address: '1406 Moody Avenue 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '750',
    acres: '0.04',
    yearBuilt: '1935',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Conveniently located near the seawall, shopping ce ...',
    photo: '/assets/rentals/galveston/11969499.jpg',
    status: 'Active',
  },
  {
    mls: '48921793',
    address: '3914 Bernardo De Galvez Avenue',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,700',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,000',
    acres: '0.119',
    yearBuilt: '1960',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Located in Mid Galveston, this 3 bedroom, 1 bath r ...',
    photo: '/assets/rentals/galveston/48921793.jpg',
    status: 'Active',
  },
  {
    mls: '95369855',
    address: '1115 32nd Street B',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,494',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,514',
    acres: '0.139',
    yearBuilt: '2021',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Centrally located on Galveston Island, this 4 Bedr ...',
    photo: '/assets/rentals/galveston/95369855.jpg',
    status: 'Active',
  },
  {
    mls: '86036544',
    address: '2914 Avenue K 4',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$950',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '0.119',
    yearBuilt: '1917',
    subdivision: 'Hoskins Square',
    county: 'Galveston',
    remarks: 'Beautifully remodeled and furnished 1-bedroom, 1-b ...',
    photo: '/assets/rentals/galveston/86036544.jpg',
    status: 'Active',
  },
  {
    mls: '23136719',
    address: '5006 Avenue M 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$850',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '500',
    acres: '0.138',
    yearBuilt: '1958',
    subdivision: '',
    county: 'Galveston',
    remarks: '1st floor apartment available! 1 Bed / 1 Bath - Of ...',
    photo: '/assets/rentals/galveston/23136719.jpg',
    status: 'Active',
  },
  {
    mls: '71891586',
    address: '928 Postoffice 12',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '950',
    acres: '0.355',
    yearBuilt: '1971',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: '2 Bedroom / 1.5-bathroom apartment available! 2 be ...',
    photo: '/assets/rentals/galveston/71891586.jpg',
    status: 'Active',
  },
  {
    mls: '47721007',
    address: '4418 N Live Oak Circle',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,275',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,162',
    acres: '0.103',
    yearBuilt: '2007',
    subdivision: 'The Oaks',
    county: 'Galveston',
    remarks: 'Charming one story Craftsman-style home for lease ...',
    photo: '/assets/rentals/galveston/47721007.jpg',
    status: 'Active',
  },
  {
    mls: '54919697',
    address: '2520 Avenue P 1/2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$3,400',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,980',
    acres: '0.061',
    yearBuilt: '1960',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: '**Roof replaced April 2026** Welcome to 2520 Avenu ...',
    photo: '/assets/rentals/galveston/54919697.jpg',
    status: 'Active',
  },
  {
    mls: '84513085',
    address: '2309 67th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,200',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,240',
    acres: '0.103',
    yearBuilt: '2022',
    subdivision: 'Pabst Add Sec 1',
    county: 'Galveston',
    remarks: 'Discover the ease of island living in this central ...',
    photo: '/assets/rentals/galveston/84513085.jpg',
    status: 'Active',
  },
  {
    mls: '64938269',
    address: '1615 Winnie Street 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,849',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,232',
    acres: '0.118',
    yearBuilt: '1932',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Charming c.1932 Historic Apartment in the Heart of ...',
    photo: '/assets/rentals/galveston/64938269.jpg',
    status: 'Active',
  },
  {
    mls: '2382699',
    address: '921 Marine Drive 332',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,400',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,178',
    acres: '0.027',
    yearBuilt: '1980',
    subdivision: 'Marina Pointe Condo',
    county: 'Galveston',
    remarks: 'Live the coastal lifestyle in this nice fully furn ...',
    photo: '/assets/rentals/galveston/2382699.jpg',
    status: 'Active',
  },
  {
    mls: '5348199',
    address: '1806 Church Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,000',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '450',
    acres: '0.237',
    yearBuilt: '1955',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Adorable one bedroom apartment located in the hear ...',
    photo: '/assets/rentals/galveston/5348199.jpg',
    status: 'Active',
  },
  {
    mls: '90100010',
    address: '1901 Back Bay Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,124',
    acres: '0.035',
    yearBuilt: '1975',
    subdivision: 'Backbay Twnhms',
    county: 'Galveston',
    remarks: 'Welcome to Back Bay Townhouses, ideally located ne ...',
    photo: '/assets/rentals/galveston/90100010.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '13137172',
    address: '1724 33rd Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$3,400',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,536',
    acres: '0.059',
    yearBuilt: '1911',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Location, lifestyle, and island charm come togethe ...',
    photo: '/assets/rentals/galveston/13137172.jpg',
    status: 'Active',
  },
  {
    mls: '48289097',
    address: '620 Ball Down',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,200',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,696',
    acres: '0.059',
    yearBuilt: '1960',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Welcome to coastal living in the heart of Galvesto ...',
    photo: '/assets/rentals/galveston/48289097.jpg',
    status: 'Active',
  },
  {
    mls: '19130130',
    address: '3228 Avenue R 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,200',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '972',
    acres: '0.076',
    yearBuilt: '1955',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Renovated and new exterior and interior 2/2 up and ...',
    photo: '/assets/rentals/galveston/19130130.jpg',
    status: 'Pending',
  },
  {
    mls: '55310767',
    address: '4129 Fort Bend Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,419',
    acres: '0.144',
    yearBuilt: '2017',
    subdivision: 'Sea Isle Ext 5',
    county: 'Galveston',
    remarks: 'Fully Furnished Beachside Retreat in Sea Isle. Esc ...',
    photo: '/assets/rentals/galveston/55310767.jpg',
    status: 'Active',
  },
  {
    mls: '15810048',
    address: '1206 30th Street 4',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,100',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '6,720',
    acres: '0.167',
    yearBuilt: '1969',
    subdivision: 'None',
    county: 'Galveston',
    remarks: 'FOR LEASE! Affordable Galveston living at $1,100 p ...',
    photo: '/assets/rentals/galveston/15810048.jpg',
    status: 'Active',
  },
  {
    mls: '22363433',
    address: '9420 Seawall Boulevard 605',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,900',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '893',
    acres: '0.021',
    yearBuilt: '2006',
    subdivision: 'Ocean Grove Condo',
    county: 'Galveston',
    remarks: '**Stunning Gulf Views!** Fully furnished and turnk ...',
    photo: '/assets/rentals/galveston/22363433.jpg',
    status: 'Active',
  },
  {
    mls: '12668406',
    address: '7523 Beaudelaire Circle',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,595',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,639',
    acres: '0.053',
    yearBuilt: '',
    subdivision: 'Lafitte Twnhms',
    county: 'Galveston',
    remarks: 'This stunning 3 bed 2.5 bath townhouse features th ...',
    photo: '/assets/rentals/galveston/12668406.jpg',
    status: 'Active',
  },
  {
    mls: '49171386',
    address: '1805 Avenue N 1/2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,544',
    acres: '0.127',
    yearBuilt: '1958',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'This charming 1958 coastal getaway is nestled in G ...',
    photo: '/assets/rentals/galveston/49171386.jpg',
    status: 'Active',
  },
  {
    mls: '57745470',
    address: '12835 E Conquistador Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$3,300',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,771',
    acres: '0.103',
    yearBuilt: '2022',
    subdivision: 'Spanish Grant 2',
    county: 'Galveston',
    remarks: 'Welcome to coastal living in the popular Spanish G ...',
    photo: '/assets/rentals/galveston/57745470.jpg',
    status: 'Active',
  },
  {
    mls: '52222207',
    address: '1927 Harborside Drive 302',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,275',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,432',
    acres: '0.237',
    yearBuilt: '2008',
    subdivision: 'Peanut Butter Warehouse Harbor',
    county: 'Galveston',
    remarks: 'Corner unit with expansive living space. Large win ...',
    photo: '/assets/rentals/galveston/52222207.jpg',
    status: 'Active',
  },
  {
    mls: '83379405',
    address: '4211 Surf Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,224',
    acres: '0.078',
    yearBuilt: '1970',
    subdivision: 'Palm Beach',
    county: 'Galveston',
    remarks: 'Welcome to the beautifully designed beach house at ...',
    photo: '/assets/rentals/galveston/83379405.jpg',
    status: 'Active',
  },
  {
    mls: '63536275',
    address: '2309 Harborside Drive 206',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,700',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '900',
    acres: '0.357',
    yearBuilt: '1970',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'LIVE IN THE HEART OF DOWNTOWN GALVESTON just minut ...',
    photo: '/assets/rentals/galveston/63536275.jpg',
    status: 'Active',
  },
  {
    mls: '56135164',
    address: '702 N Holiday Drive 3',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,000',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,136',
    acres: '0.039',
    yearBuilt: '1980',
    subdivision: 'Port Aux Prince Twnhms',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/galveston/56135164.jpg',
    status: 'Active',
  },
  {
    mls: '37664585',
    address: '5309 Avenue O Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,100',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '606',
    acres: '0.826',
    yearBuilt: '1955',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Charming 1-bedroom home featuring bright and airy ...',
    photo: '/assets/rentals/galveston/37664585.jpg',
    status: 'Active',
  },
  {
    mls: '49386905',
    address: '2119 67th St Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,352',
    acres: '0.187',
    yearBuilt: '1980',
    subdivision: 'Hansen',
    county: 'Galveston',
    remarks: 'Recently renovated 3 bedroom/2 bath cottage with w ...',
    photo: '/assets/rentals/galveston/49386905.jpg',
    status: 'Active',
  },
  {
    mls: '43126419',
    address: '2814 Avenue O 1/2 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,100',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,100',
    acres: '0.138',
    yearBuilt: '1962',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Charming 2-bedroom upstairs apartment full of char ...',
    photo: '/assets/rentals/galveston/43126419.jpg',
    status: 'Active',
  },
  {
    mls: '20631639',
    address: '1824 Biovu Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '852',
    acres: '0.333',
    yearBuilt: '1955',
    subdivision: 'Bayou Shore Aka Wheelers',
    county: 'Galveston',
    remarks: 'Centrally located just off 61st St and Heards Lane ...',
    photo: '/assets/rentals/galveston/20631639.jpg',
    status: 'Active',
  },
  {
    mls: '92405848',
    address: '7307 Magnolia Blossom',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,678',
    acres: '0.084',
    yearBuilt: '2014',
    subdivision: 'Magnolia Court Sub 2007',
    county: 'Galveston',
    remarks: 'Modern rental home on a desirable corner lot! This ...',
    photo: '/assets/rentals/galveston/92405848.jpg',
    status: 'Active',
  },
  {
    mls: '30337793',
    address: '9680 Airways Lane',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$7,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,338',
    acres: '0.474',
    yearBuilt: '2004',
    subdivision: 'Airport Homesites 2',
    county: 'Galveston',
    remarks: 'Incredible resort style Bay front 4/4/3+ home in s ...',
    photo: '/assets/rentals/galveston/30337793.jpg',
    status: 'Active',
  },
  {
    mls: '83996261',
    address: '905 Post Office Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,200',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,610',
    acres: '0.06',
    yearBuilt: '1920',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'UTMB - home is located within 2 blocks of UTMB med ...',
    photo: '/assets/rentals/galveston/83996261.jpg',
    status: 'Active',
  },
  {
    mls: '10209751',
    address: '5107 Avenue Q',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,728',
    acres: '0.138',
    yearBuilt: '1967',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Beautifully updated and exceptionally well-maintai ...',
    photo: '/assets/rentals/galveston/10209751.jpg',
    status: 'Active',
  },
  {
    mls: '54554063',
    address: '3730 Avenue T',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,456',
    acres: '0.126',
    yearBuilt: '1935',
    subdivision: 'Lyons Robt Sub',
    county: 'Galveston',
    remarks: 'Newly updated in 2026, this 3-bedroom, 2-bath home ...',
    photo: '/assets/rentals/galveston/54554063.jpg',
    status: 'Active',
  },
  {
    mls: '91294600',
    address: '620 Ball Up',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,650',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '792',
    acres: '0.059',
    yearBuilt: '1960',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Welcome to coastal living in the heart of Galvesto ...',
    photo: '/assets/rentals/galveston/91294600.jpg',
    status: 'Active',
  },
  {
    mls: '21225840',
    address: '6102 Seawall Boulevard 244',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,100',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '462',
    acres: '462',
    yearBuilt: '1985',
    subdivision: 'Casa Del Mar Condo',
    county: 'Galveston',
    remarks: 'Turnkey, fully furnished vacation rental available ...',
    photo: '/assets/rentals/galveston/21225840.jpg',
    status: 'Active',
  },
  {
    mls: '28277575',
    address: '1812 Winnie Rear',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,075',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1912',
    subdivision: 'East End Historical',
    county: 'Galveston',
    remarks: 'Gorgeous Furnished Carriage House in Nice Historic ...',
    photo: '/assets/rentals/galveston/28277575.jpg',
    status: 'Active',
  },
  {
    mls: '3028538',
    address: '710 91st Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,205',
    acres: '0.126',
    yearBuilt: '1973',
    subdivision: 'Laguna De Oro',
    county: 'Galveston',
    remarks: 'Charming canal-front retreat with a beautifully la ...',
    photo: '/assets/rentals/galveston/3028538.jpg',
    status: 'Active',
  },
  {
    mls: '26125046',
    address: '2102 Mechanic Street 104',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,600',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '948',
    acres: '0.196',
    yearBuilt: '1941',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Large, light, and bright 2 bedroom, 2 bathroom uni ...',
    photo: '/assets/rentals/galveston/26125046.jpg',
    status: 'Active',
  },
  {
    mls: '47309804',
    address: '13 Lyncrest Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,750',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,126',
    acres: '0.126',
    yearBuilt: '1970',
    subdivision: 'Lyncrest Manor',
    county: 'Galveston',
    remarks: 'Adorable 3 Bedroom, 2 Bath home close to UTMB. Cu ...',
    photo: '/assets/rentals/galveston/47309804.jpg',
    status: 'Pending',
  },
  {
    mls: '17939896',
    address: '1915 44th Street UP',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,250',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '648',
    acres: '0.088',
    yearBuilt: '1960',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Fully furnished 1-bedroom, 1-bath upstairs unit in ...',
    photo: '/assets/rentals/galveston/17939896.jpg',
    status: 'Active',
  },
  {
    mls: '20082971',
    address: '801 E Beach Drive BC0412',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$3,500',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,044',
    acres: '',
    yearBuilt: '2008',
    subdivision: 'Palisade Palms',
    county: 'Galveston',
    remarks: 'Enjoy breathtaking views of the bay and surroundin ...',
    photo: '/assets/rentals/galveston/20082971.jpg',
    status: 'Active',
  },
  {
    mls: '17479163',
    address: '1927 Broadway Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$3,200',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,652',
    acres: '0.083',
    yearBuilt: '1895',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Own a piece of Galveston history with this romanti ...',
    photo: '/assets/rentals/galveston/17479163.jpg',
    status: 'Active',
  },
  {
    mls: '61474826',
    address: '3716 Avenue O',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,700',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,328',
    acres: '0.177',
    yearBuilt: '1955',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Centrally located, cute house ready to move in! Th ...',
    photo: '/assets/rentals/galveston/61474826.jpg',
    status: 'Active',
  },
  {
    mls: '50160134',
    address: '115 Marlin Avenue',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,623',
    acres: '0.138',
    yearBuilt: '1960',
    subdivision: 'Lindale Park',
    county: 'Galveston',
    remarks: 'Fantastic location - close to UTMB, Downtown/Stran ...',
    photo: '/assets/rentals/galveston/50160134.jpg',
    status: 'Active',
  },
  {
    mls: '84402811',
    address: '4712 Avenue Q',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$3,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,748',
    acres: '0.069',
    yearBuilt: '2023',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Enjoy coastal living from this recently built home ...',
    photo: '/assets/rentals/galveston/84402811.jpg',
    status: 'Active',
  },
  {
    mls: '33039095',
    address: '6300 Seawall Boulevard 7201',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,600',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '480',
    acres: '0.011',
    yearBuilt: '1980',
    subdivision: 'Victorian Condo',
    county: 'Galveston',
    remarks: 'Fully furnished all bills included except electric ...',
    photo: '/assets/rentals/galveston/33039095.jpg',
    status: 'Active',
  },
  {
    mls: '70571687',
    address: '1110 64th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$3,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,971',
    acres: '0.115',
    yearBuilt: '1972',
    subdivision: 'Broadway',
    county: 'Galveston',
    remarks: 'FOR LEASE! YOUR GALVESTON BAY LIFESTYL ...',
    photo: '/assets/rentals/galveston/70571687.jpg',
    status: 'Active',
  },
  {
    mls: '54159581',
    address: '1009 8th Street A',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,250',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '425',
    acres: '',
    yearBuilt: '2024',
    subdivision: 'Galveston City',
    county: 'Galveston',
    remarks: 'Experience modern coastal living in this condomini ...',
    photo: '/assets/rentals/galveston/54159581.jpg',
    status: 'Active',
  },
  {
    mls: '5514760',
    address: '119 Barracuda Avenue',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,395',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,838',
    acres: '0.138',
    yearBuilt: '1965',
    subdivision: 'Lindale Park',
    county: 'Galveston',
    remarks: 'ISLAND RENTAL!! Large very nice 3-4BR/2BA layout w ...',
    photo: '/assets/rentals/galveston/5514760.jpg',
    status: 'Active',
  },
  {
    mls: '53632151',
    address: '3506 Cove View Boulevard 303',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '773',
    acres: '5.611',
    yearBuilt: '1983',
    subdivision: 'Palms At Cove View Condo',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/galveston/53632151.jpg',
    status: 'Active',
  },
  {
    mls: '38801732',
    address: '3602 Avenue M',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,100',
    beds: '5 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,444',
    acres: '0.091',
    yearBuilt: '1960',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'A Galveston Charmer!!! A traditional, classic bea ...',
    photo: '/assets/rentals/galveston/38801732.jpg',
    status: 'Active',
  },
  {
    mls: '9182715',
    address: '3920 2nd Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$3,900',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,960',
    acres: '0.23',
    yearBuilt: '2023',
    subdivision: 'Bay Harbor',
    county: 'Galveston',
    remarks: 'Looking for a comfortable place to call home just ...',
    photo: '/assets/rentals/galveston/9182715.jpg',
    status: 'Active',
  },
  {
    mls: '49992107',
    address: '3010 Avenue Q 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,350',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,045',
    acres: '0.177',
    yearBuilt: '1960',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'This unit is on the first floor of a 4-plex. Each ...',
    photo: '/assets/rentals/galveston/49992107.jpg',
    status: 'Active',
  },
  {
    mls: '42206976',
    address: '1319 Postoffice',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,850',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,239',
    acres: '0.119',
    yearBuilt: '1873',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Circa 1873 Widow Katharine Burke House. High raise ...',
    photo: '/assets/rentals/galveston/42206976.jpg',
    status: 'Active',
  },
  {
    mls: '76766231',
    address: '215 Post Office Street 302',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,750',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,079',
    acres: '',
    yearBuilt: '1980',
    subdivision: 'Mariner House Condo',
    county: 'Galveston',
    remarks: 'Introducing our spacious 2 story, 2 bedroom, 1.5 b ...',
    photo: '/assets/rentals/galveston/76766231.jpg',
    status: 'Active',
  },
  {
    mls: '10739569',
    address: '508 Georgia Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77573',
    price: '$2,700',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '2026',
    subdivision: 'Lenaburg Add',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/galveston/10739569.jpg',
    status: 'Active',
  },
  {
    mls: '12089532',
    address: '2219 72nd Street B',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,195',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,100',
    acres: '0.16',
    yearBuilt: '1955',
    subdivision: 'Trimble &amp; Lindsey Sec 1',
    county: 'Galveston',
    remarks: 'DOWNSTAIRS UNIT -2 bedroom, 1 bathroom apartment c ...',
    photo: '/assets/rentals/galveston/12089532.jpg',
    status: 'Active',
  },
  {
    mls: '39846673',
    address: '2015 51st Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,355',
    acres: '0.069',
    yearBuilt: '1970',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Gorgeous 3 bed, 2 bath home with 2 car garage. Upd ...',
    photo: '/assets/rentals/galveston/39846673.jpg',
    status: 'Active',
  },
  {
    mls: '20625081',
    address: '121 Albacore Avenue',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,875',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,504',
    acres: '0.138',
    yearBuilt: '1965',
    subdivision: 'Lindale Park',
    county: 'Galveston',
    remarks: 'Spacious 3/2 in the highly desirable Fish Village ...',
    photo: '/assets/rentals/galveston/20625081.jpg',
    status: 'Active',
  },
  {
    mls: '25561878',
    address: '415 14th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,726',
    acres: '0.042',
    yearBuilt: '1962',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'RENTED FURNISHED. Spacious 4-bedroom, 2-bath home ...',
    photo: '/assets/rentals/galveston/25561878.jpg',
    status: 'Active',
  },
  {
    mls: '2078820',
    address: '215 Post Office Street 701',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,200',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '578',
    acres: '0.013',
    yearBuilt: '1980',
    subdivision: 'Mariner House Condo',
    county: 'Galveston',
    remarks: 'ALL UTILITIES PD!! 1/1 GATED PROPERTY, and secure ...',
    photo: '/assets/rentals/galveston/2078820.jpg',
    status: 'Active',
  },
  {
    mls: '72645222',
    address: '4401 Avenue Q 1/2 2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,250',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,620',
    acres: '0.118',
    yearBuilt: '1977',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Affordable island living awaits in this charming u ...',
    photo: '/assets/rentals/galveston/72645222.jpg',
    status: 'Active',
  },
  {
    mls: '65380885',
    address: '4025 Avenue R',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$775',
    beds: '0 Bedrooms',
    baths: '1 Total Baths',
    sqft: '360',
    acres: '',
    yearBuilt: '1955',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'ADORABLE GARAGE EFFICIENCY APARTMENT D ...',
    photo: '/assets/rentals/galveston/65380885.jpg',
    status: 'Active',
  },
  {
    mls: '73662525',
    address: '3228 Avenue R 1',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,200',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '972',
    acres: '0.076',
    yearBuilt: '1955',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Renovated and new exterior and interior 2/2 up and ...',
    photo: '/assets/rentals/galveston/73662525.jpg',
    status: 'Active',
  },
  {
    mls: '32811252',
    address: '1418 30th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,000',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '880',
    acres: '0.118',
    yearBuilt: '1925',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Be the first to live in this just remodeled 2 bed, ...',
    photo: '/assets/rentals/galveston/32811252.jpg',
    status: 'Active',
  },
  {
    mls: '95576786',
    address: '4107 Long Tom Court',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,760',
    acres: '0.138',
    yearBuilt: '1980',
    subdivision: 'Pirates Beach',
    county: 'Galveston',
    remarks: 'This charming, fully furnished 4-bedroom, 2-bath r ...',
    photo: '/assets/rentals/galveston/95576786.jpg',
    status: 'Active',
  },
  {
    mls: '85675268',
    address: '3510 Avenue S 1/2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,900',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,600',
    acres: '0.118',
    yearBuilt: '1958',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: '1 BLOCK FROM THE SEAWALL WITH A VIEW!!!!! Lovely u ...',
    photo: '/assets/rentals/galveston/85675268.jpg',
    status: 'Active',
  },
  {
    mls: '33598564',
    address: '5403 Ave Q 1/2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '979',
    acres: '',
    yearBuilt: '1960',
    subdivision: '(2965.1) Denver Resurvey (Nha)',
    county: 'Galveston',
    remarks: '2 Bed | 1.5 Bath | Close to UTMB, the Beach & Down ...',
    photo: '/assets/rentals/galveston/33598564.jpg',
    status: 'Active',
  },
  {
    mls: '68620808',
    address: '2102 Mechanic Street 205',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,850',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,166',
    acres: '0.196',
    yearBuilt: '1941',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Large light and bright 2/2 located on the 2nd floo ...',
    photo: '/assets/rentals/galveston/68620808.jpg',
    status: 'Active',
  },
  {
    mls: '15799547',
    address: '114 Dolphin Avenue',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,468',
    acres: '0.138',
    yearBuilt: '',
    subdivision: 'Lindale Park',
    county: 'Galveston',
    remarks: 'Well maintained 3 bedroom 2 bath with bonus room, ...',
    photo: '/assets/rentals/galveston/15799547.jpg',
    status: 'Active',
  },
  {
    mls: '42712242',
    address: '14110 Miramar Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,400',
    acres: '0.217',
    yearBuilt: '2017',
    subdivision: 'Palm Beach',
    county: 'Galveston',
    remarks: 'Welcome to your dream coastal retreat! This spacio ...',
    photo: '/assets/rentals/galveston/42712242.jpg',
    status: 'Active',
  },
  {
    mls: '83189996',
    address: '5102 Avenue L',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,800',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,782',
    acres: '0.138',
    yearBuilt: '1965',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Completely renovated and move-in ready, this 4-bed ...',
    photo: '/assets/rentals/galveston/83189996.jpg',
    status: 'Active',
  },
  {
    mls: '44594589',
    address: '121 Mackeral Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,133',
    acres: '0.135',
    yearBuilt: '1965',
    subdivision: 'Lyncrest Manor 2',
    county: 'Galveston',
    remarks: 'Beautifully remodeled and move-in ready! This 3-be ...',
    photo: '/assets/rentals/galveston/44594589.jpg',
    status: 'Active',
  },
  {
    mls: '56476534',
    address: '921 Marine Drive 200',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,000',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '561',
    acres: '561',
    yearBuilt: '1980',
    subdivision: 'Marina Pointe Condo',
    county: 'Galveston',
    remarks: 'Rare Find at Marina Pointe | Walk to UTMB & Yacht ...',
    photo: '/assets/rentals/galveston/56476534.jpg',
    status: 'Active',
  },
  {
    mls: '2839034',
    address: '1314 Avenue M 1/2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,499',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '570',
    acres: '0.059',
    yearBuilt: '1955',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Charming 2 bedroom cottage near beach. Hardwood F ...',
    photo: '/assets/rentals/galveston/2839034.jpg',
    status: 'Active',
  },
  {
    mls: '10051898',
    address: '2417 Gerol Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$4,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '3,545',
    acres: '0.209',
    yearBuilt: '1993',
    subdivision: 'Havre Lafitte Sec 1',
    county: 'Galveston',
    remarks: 'Experience the best of Galveston island living in ...',
    photo: '/assets/rentals/galveston/10051898.jpg',
    status: 'Active',
  },
  {
    mls: '43797250',
    address: '2305 55th Street 1',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,200',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '600',
    acres: '0.138',
    yearBuilt: '1979',
    subdivision: 'Denver Re-Survey',
    county: 'Galveston',
    remarks: 'Freshly painted and move-in ready, this updated on ...',
    photo: '/assets/rentals/galveston/43797250.jpg',
    status: 'Active',
  },
  {
    mls: '33050237',
    address: '1818 Church 3',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,499',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1960',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Lovely Victorian 1 bedroom unit in the heart of Ga ...',
    photo: '/assets/rentals/galveston/33050237.jpg',
    status: 'Pending',
  },
  {
    mls: '21381639',
    address: '21812 Frio Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$4,250',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '1,881',
    acres: '0.142',
    yearBuilt: '1986',
    subdivision: 'Sea Isle Ext 11',
    county: 'Galveston',
    remarks: 'This beautiful 4-bedroom, 3.5-bath home showcases ...',
    photo: '/assets/rentals/galveston/21381639.jpg',
    status: 'Active',
  },
  {
    mls: '12673246',
    address: '1314 27th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,550',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '826',
    acres: '0.027',
    yearBuilt: '1955',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Beautifully maintained, conveniently located home ...',
    photo: '/assets/rentals/galveston/12673246.jpg',
    status: 'Active',
  },
  {
    mls: '84763458',
    address: '14 Gulf Lane',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,350',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,540',
    acres: '0.158',
    yearBuilt: '1972',
    subdivision: 'Lyncrest Manor',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/galveston/84763458.jpg',
    status: 'Active',
  },
  {
    mls: '84302190',
    address: '4015 Warchest Court',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$4,200',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '2,624',
    acres: '0.265',
    yearBuilt: '2007',
    subdivision: 'Pirates Beach',
    county: 'Galveston',
    remarks: 'Experience coastal living in this updated 4-bed, 4 ...',
    photo: '/assets/rentals/galveston/84302190.jpg',
    status: 'Active',
  },
  {
    mls: '43772173',
    address: '4517 Avenue K',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$1,600',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '792',
    acres: '0.069',
    yearBuilt: '1930',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Available 8/22/2026. Great 2-bedroom home located ...',
    photo: '/assets/rentals/galveston/43772173.jpg',
    status: 'Active',
  },
  {
    mls: '82224137',
    address: '9520 Seawall Boulevard 353',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$2,375',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,175',
    acres: '0.027',
    yearBuilt: '2011',
    subdivision: 'Maravilla Condos',
    county: 'Galveston',
    remarks: 'Enjoy sweeping Gulf views from this rare two-story ...',
    photo: '/assets/rentals/galveston/82224137.jpg',
    status: 'Active',
  },
  {
    mls: '14004798',
    address: '2102 Mechanic Street 305',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,900',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,166',
    acres: '0.196',
    yearBuilt: '1941',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Large, light, and bright 2 bedroom, 2 bathroom uni ...',
    photo: '/assets/rentals/galveston/14004798.jpg',
    status: 'Active',
  },
  {
    mls: '23280269',
    address: '2415 Church Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$4,250',
    beds: '3 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,622',
    acres: '0.376',
    yearBuilt: '1967',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'This Downtown residence is truly a gem and feature ...',
    photo: '/assets/rentals/galveston/23280269.jpg',
    status: 'Active',
  },
  {
    mls: '45374312',
    address: '918 Winnie 110',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,050',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '692',
    acres: '0.236',
    yearBuilt: '1970',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Located in a quiet East End community, this 2-bedr ...',
    photo: '/assets/rentals/galveston/45374312.jpg',
    status: 'Active',
  },
  {
    mls: '51661354',
    address: '3602 Avenue S 1/2',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,400',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '984',
    acres: '0.114',
    yearBuilt: '1940',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'This charming 2 bedroom, 1 bathroom home is ready ...',
    photo: '/assets/rentals/galveston/51661354.jpg',
    status: 'Active',
  },
  {
    mls: '34541564',
    address: '4131 Jackson Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$3,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,350',
    acres: '0.152',
    yearBuilt: '2011',
    subdivision: 'Sea Isle',
    county: 'Galveston',
    remarks: 'Enjoy ocean views from the front porch balcony at ...',
    photo: '/assets/rentals/galveston/34541564.jpg',
    status: 'Active',
  },
  {
    mls: '66206110',
    address: '4006 Fort Bend Drive',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    price: '$3,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,582',
    acres: '0.144',
    yearBuilt: '2023',
    subdivision: 'Sea Isle Ext 4',
    county: 'Galveston',
    remarks: 'Beautiful newer construction featuring a reverse f ...',
    photo: '/assets/rentals/galveston/66206110.jpg',
    status: 'Active',
  },
  {
    mls: '70647281',
    address: '2115 33rd Street Down',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,499',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,176',
    acres: '0.08',
    yearBuilt: '1911',
    subdivision: 'Lot B Baker Estates',
    county: 'Galveston',
    remarks: 'LESS THAN 5 BLOCKS FROM THE BEACH! This first leve ...',
    photo: '/assets/rentals/galveston/70647281.jpg',
    status: 'Active',
  },
  {
    mls: '11803761',
    address: '2627 Ave K 3',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,100',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '600',
    acres: '',
    yearBuilt: '1950',
    subdivision: 'Galveston',
    county: 'Galveston',
    remarks: 'COOL, CREATIVE LOFT NEXT TO ART GALLERY! Walking D ...',
    photo: '/assets/rentals/galveston/11803761.jpg',
    status: 'Active',
  },
  {
    mls: '93319529',
    address: '1117 37th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,400',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '873',
    acres: '0.118',
    yearBuilt: '1955',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'Welcome to your charming Craftsman-style retreat i ...',
    photo: '/assets/rentals/galveston/93319529.jpg',
    status: 'Active',
  },
  {
    mls: '88886344',
    address: '2006 31st Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,370',
    acres: '0.079',
    yearBuilt: '1958',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Enjoy coastal living in this spacious 3-bedroom, 2 ...',
    photo: '/assets/rentals/galveston/88886344.jpg',
    status: 'Active',
  },
  {
    mls: '94061406',
    address: '114 Tarpon Avenue',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,536',
    acres: '0.146',
    yearBuilt: '1960',
    subdivision: 'Lindale Park',
    county: 'Galveston',
    remarks: 'Nestled in the peaceful and sought-after Lindale P ...',
    photo: '/assets/rentals/galveston/94061406.jpg',
    status: 'Active',
  },
  {
    mls: '41580985',
    address: '2207 Avenue P',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$3,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,298',
    acres: '0.138',
    yearBuilt: '1906',
    subdivision: 'Galveston Outlots',
    county: 'Galveston',
    remarks: 'Tucked away on a delightfully quiet street where t ...',
    photo: '/assets/rentals/galveston/41580985.jpg',
    status: 'Active',
  },
  {
    mls: '38275361',
    address: '614 16th Street',
    city: 'Galveston',
    state: 'Texas',
    zip: '77550',
    price: '$1,995',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,320',
    acres: '0.043',
    yearBuilt: '1878',
    subdivision: 'Galveston Townsite',
    county: 'Galveston',
    remarks: 'This 1878-built East End charmer has been lovingly ...',
    photo: '/assets/rentals/galveston/38275361.jpg',
    status: 'Active',
  },
  {
    mls: '44782542',
    address: '5222 Avenue O',
    city: 'Galveston',
    state: 'Texas',
    zip: '77551',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,432',
    acres: '0.089',
    yearBuilt: '1967',
    subdivision: 'Denver Resurvey',
    county: 'Galveston',
    remarks: 'Well-maintained 3-bedroom, 3-bath home featuring t ...',
    photo: '/assets/rentals/galveston/44782542.jpg',
    status: 'Active',
  },
]
