// Baytown homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const baytownRentListings: Listing[] = [
  {
    mls: '44834523',
    address: '2005 Utah Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,201',
    acres: '0.145',
    yearBuilt: '2012',
    subdivision: 'Britton Cravens',
    county: 'Harris',
    remarks: 'WONDERFULLY RENOVATED 3bdrm/2bth HOME!! BRAND NEW ...',
    photo: '/assets/rentals/baytown/44834523.jpg',
    status: 'Active',
  },
  {
    mls: '52411333',
    address: '4503 Coachman Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,733',
    acres: '0.207',
    yearBuilt: '1969',
    subdivision: 'Kountry Klub Village Sec 01',
    county: 'Harris',
    remarks: 'This home is located in the Latern Park Subdivisio ...',
    photo: '/assets/rentals/baytown/52411333.jpg',
    status: 'Active',
  },
  {
    mls: '88761433',
    address: '4431 Green Tee Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,950',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,987',
    acres: '0.224',
    yearBuilt: '1998',
    subdivision: 'Country Club Oaks Sec 16',
    county: 'Harris',
    remarks: 'Extra spacious home in Country Club Oaks! Primary ...',
    photo: '/assets/rentals/baytown/88761433.jpg',
    status: 'Active',
  },
  {
    mls: '67374111',
    address: '5415 Espuela Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,070',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,120',
    acres: '0.132',
    yearBuilt: '2008',
    subdivision: 'Highlands Ranch',
    county: 'Harris',
    remarks: 'Interested in this home? You clearly have exceptio ...',
    photo: '/assets/rentals/baytown/67374111.jpg',
    status: 'Active',
  },
  {
    mls: '18884160',
    address: '216 W Republic Street 4',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$795',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '570',
    acres: '0.344',
    yearBuilt: '1938',
    subdivision: 'Goose Creek',
    county: 'Harris',
    remarks: 'Quiet area. upstairs apt. Breakfast area in kitche ...',
    photo: '/assets/rentals/baytown/18884160.jpg',
    status: 'Active',
  },
  {
    mls: '81210208',
    address: '1315 Squire Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,380',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,814',
    acres: '0.124',
    yearBuilt: '2014',
    subdivision: 'Country Club Manor Sec 4',
    county: 'Harris',
    remarks: 'Welcome to this beautiful 3-bedroom, 2-bathroom ho ...',
    photo: '/assets/rentals/baytown/81210208.jpg',
    status: 'Active',
  },
  {
    mls: '13149409',
    address: '8734 Baywood Court',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,180',
    acres: '0.155',
    yearBuilt: '2021',
    subdivision: 'Wooster Xing',
    county: 'Harris',
    remarks: 'Welcome to 8734 Baywood Ct, Baytown, TX 77521! Thi ...',
    photo: '/assets/rentals/baytown/13149409.jpg',
    status: 'Active',
  },
  {
    mls: '70109085',
    address: '9815 Bellwick Hollow Court',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,827',
    acres: '0.133',
    yearBuilt: '2024',
    subdivision: 'Sterling Point Sec 8',
    county: 'Harris',
    remarks: 'Welcome to 9815 Bellwick Hollow Court! Step inside ...',
    photo: '/assets/rentals/baytown/70109085.jpg',
    status: 'Active',
  },
  {
    mls: '35311890',
    address: '9323 Speckled Trout Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,084',
    acres: '0.133',
    yearBuilt: '2025',
    subdivision: 'Scotts Bend Sec 5',
    county: 'Harris',
    remarks: 'Discover the convenience of single-floor living at ...',
    photo: '/assets/rentals/baytown/35311890.jpg',
    status: 'Active',
  },
  {
    mls: '46379129',
    address: '12007 Rushing Ridge Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '0.164',
    yearBuilt: '2025',
    subdivision: 'Heights/Baytown Sec 2',
    county: 'Chambers',
    remarks: '',
    photo: '/assets/rentals/baytown/46379129.jpg',
    status: 'Active',
  },
  {
    mls: '94429220',
    address: '505 Peggy Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,225',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '874',
    acres: '0.115',
    yearBuilt: '1940',
    subdivision: 'Aron',
    county: 'Harris',
    remarks: 'Nice spacious home features 2 bedrooms, 1 remodele ...',
    photo: '/assets/rentals/baytown/94429220.jpg',
    status: 'Active',
  },
  {
    mls: '31987308',
    address: '515 Riggs Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,482',
    acres: '0.202',
    yearBuilt: '1950',
    subdivision: 'Middletown',
    county: 'Harris',
    remarks: 'Charming Baytown home situated on a spacious corne ...',
    photo: '/assets/rentals/baytown/31987308.jpg',
    status: 'Active',
  },
  {
    mls: '60948339',
    address: '1306 Squire Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,175',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,902',
    acres: '0.151',
    yearBuilt: '2014',
    subdivision: 'Country Club Manor Sec 4',
    county: 'Harris',
    remarks: '**COMING SOON! CURRENTLY TENANT OCCUPI ...',
    photo: '/assets/rentals/baytown/60948339.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '6829540',
    address: '110 William Avenue',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,750',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,410',
    acres: '0.306',
    yearBuilt: '1953',
    subdivision: 'Woodlawn',
    county: 'Harris',
    remarks: 'CALLING ALL PET ENTHUSIASTS! The homeowners adore ...',
    photo: '/assets/rentals/baytown/6829540.jpg',
    status: 'Active',
  },
  {
    mls: '67420825',
    address: '7515 Bayway Drive 3',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$900',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '850',
    acres: '0.321',
    yearBuilt: '1953',
    subdivision: 'Nathaniel Lynch Surv Abs #44',
    county: 'Harris',
    remarks: 'MOVE-IN SPECIAL – PAY $0 RENT FOR AUGUST! Move in ...',
    photo: '/assets/rentals/baytown/67420825.jpg',
    status: 'Active',
  },
  {
    mls: '75097871',
    address: '4151 Brazos Brook Trail',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,188',
    acres: '0.121',
    yearBuilt: '2023',
    subdivision: 'Burnet Fields Sec 3',
    county: 'Harris',
    remarks: 'Welcome to 4151 Brazos Brook Trail! This charming ...',
    photo: '/assets/rentals/baytown/75097871.jpg',
    status: 'Active',
  },
  {
    mls: '97023178',
    address: '8014 Blackcherry Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,558',
    acres: '0.136',
    yearBuilt: '2005',
    subdivision: 'Country Meadows Sec 06',
    county: 'Chambers',
    remarks: 'Welcome home! This property is all about location! ...',
    photo: '/assets/rentals/baytown/97023178.jpg',
    status: 'Active',
  },
  {
    mls: '13268162',
    address: '4418 Legends Bay Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,361',
    acres: '0.186',
    yearBuilt: '2012',
    subdivision: 'Legends Bay',
    county: 'Chambers',
    remarks: 'Check out this adorable new rental available in BH ...',
    photo: '/assets/rentals/baytown/13268162.jpg',
    status: 'Active',
  },
  {
    mls: '48350425',
    address: '11 Jennische St',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,350',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '850',
    acres: '',
    yearBuilt: '1950',
    subdivision: 'Smith',
    county: 'Harris',
    remarks: 'Now available for lease at $1,350/month, this one- ...',
    photo: '/assets/rentals/baytown/48350425.jpg',
    status: 'Active',
  },
  {
    mls: '29128709',
    address: '8 Jennische St',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,300',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '850',
    acres: '',
    yearBuilt: '1950',
    subdivision: 'Smith',
    county: 'Harris',
    remarks: 'Welcome to 8 Jennische Street, a single-story 2-be ...',
    photo: '/assets/rentals/baytown/29128709.jpg',
    status: 'Active',
  },
  {
    mls: '46167273',
    address: '8438 Tranquil Bay Court',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,599',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,121',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'Ascend At Legends Bay',
    county: 'Chambers',
    remarks: 'Brand New Like Rental in High Acclaimed BARBERS HI ...',
    photo: '/assets/rentals/baytown/46167273.jpg',
    status: 'Active',
  },
  {
    mls: '63096425',
    address: '4126 Brazos Brook Trail',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,150',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,859',
    acres: '0.142',
    yearBuilt: '2023',
    subdivision: 'Burnet Fields Sec 3',
    county: 'Harris',
    remarks: 'This two-story home offers a classic layout ideal ...',
    photo: '/assets/rentals/baytown/63096425.jpg',
    status: 'Active',
  },
  {
    mls: '67525321',
    address: '8018 Sesame Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,819',
    acres: '0.124',
    yearBuilt: '2009',
    subdivision: 'Springfield Estates Sub Sec 8',
    county: 'Harris',
    remarks: 'Welcome to this well-maintained 3-bedroom, 2-bath ...',
    photo: '/assets/rentals/baytown/67525321.jpg',
    status: 'Active',
  },
  {
    mls: '68593880',
    address: '14007 S River Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,044',
    acres: '0.178',
    yearBuilt: '2022',
    subdivision: 'River Farms',
    county: 'Chambers',
    remarks: 'Beautiful 4-bedroom, 2-bath home in the River Farm ...',
    photo: '/assets/rentals/baytown/68593880.jpg',
    status: 'Active',
  },
  {
    mls: '37369812',
    address: '8831 Bar Harbor Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,683',
    acres: '',
    yearBuilt: '2022',
    subdivision: 'Wooster Crossing',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/baytown/37369812.jpg',
    status: 'Active',
  },
  {
    mls: '52849711',
    address: '3417 Wisconsin Street B',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,300',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,678',
    acres: '0.313',
    yearBuilt: '1950',
    subdivision: 'East Baytown',
    county: 'Harris',
    remarks: 'Spacious upper-unit duplex featuring 3 bedrooms an ...',
    photo: '/assets/rentals/baytown/52849711.jpg',
    status: 'Active',
  },
  {
    mls: '21896779',
    address: '1503 Donovan Street 6',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,200',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '900',
    acres: '0.792',
    yearBuilt: '1965',
    subdivision: 'Knowlton Mollie',
    county: 'Harris',
    remarks: 'Clean and well-maintained two-bedroom, one bath un ...',
    photo: '/assets/rentals/baytown/21896779.jpg',
    status: 'Active',
  },
  {
    mls: '24886941',
    address: '4118 Saw Mill Peak Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,859',
    acres: '0.106',
    yearBuilt: '2022',
    subdivision: 'Burnet Fields Sec 2',
    county: 'Harris',
    remarks: 'Welcome Home! This two-story home has the perfect ...',
    photo: '/assets/rentals/baytown/24886941.jpg',
    status: 'Active',
  },
  {
    mls: '55068636',
    address: '5002 Creekside Avenue',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$3,200',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,160',
    acres: '0.219',
    yearBuilt: '2009',
    subdivision: 'Creekside/Cotton Crk Ph I',
    county: 'Chambers',
    remarks: 'Great rental in highly sought-after Barbers Hill ...',
    photo: '/assets/rentals/baytown/55068636.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '17438057',
    address: '512 Stimpson Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,425',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '976',
    acres: '0.201',
    yearBuilt: '1952',
    subdivision: 'Wheatley Acres',
    county: 'Harris',
    remarks: 'Nice 2 bedroom home with extra small room great fo ...',
    photo: '/assets/rentals/baytown/17438057.jpg',
    status: 'Active',
  },
  {
    mls: '53246666',
    address: '8723 W Crescent Lake Circle',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,700',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,562',
    acres: '0.138',
    yearBuilt: '2018',
    subdivision: 'Goose Creek Landing Sec 2',
    county: 'Harris',
    remarks: 'Large home with 4 bedrooms on first floor. Upstai ...',
    photo: '/assets/rentals/baytown/53246666.jpg',
    status: 'Active',
  },
  {
    mls: '71479970',
    address: '8430 Sunset Isles Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,350',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,931',
    acres: '0.132',
    yearBuilt: '2022',
    subdivision: 'Hunters Crk Sec 7',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/baytown/71479970.jpg',
    status: 'Active',
  },
  {
    mls: '39431449',
    address: '907 Northbend Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,186',
    acres: '0.144',
    yearBuilt: '1973',
    subdivision: 'Glen Meadow Sec 03',
    county: 'Harris',
    remarks: 'Welcome home to this beautiful 4-bedroom, 2.5-bath ...',
    photo: '/assets/rentals/baytown/39431449.jpg',
    status: 'Pending',
  },
  {
    mls: '5519585',
    address: '5404 Hazel Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,795',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,063',
    acres: '0.171',
    yearBuilt: '1962',
    subdivision: 'Craigmont Place Sec 04',
    county: 'Harris',
    remarks: 'Amazingly remodeled 3 bedroom 2 bathroom home in C ...',
    photo: '/assets/rentals/baytown/5519585.jpg',
    status: 'Active',
  },
  {
    mls: '81794213',
    address: '9123 Estes Lakes Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,350',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,293',
    acres: '0.113',
    yearBuilt: '2023',
    subdivision: 'Burnet Fields',
    county: 'Harris',
    remarks: 'Built in 2023, this pristine two-story home in Bay ...',
    photo: '/assets/rentals/baytown/81794213.jpg',
    status: 'Active',
  },
  {
    mls: '79042289',
    address: '8318 Black Pool Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,795',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,296',
    acres: '0.154',
    yearBuilt: '1997',
    subdivision: 'Eastpoint R/P',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/baytown/79042289.jpg',
    status: 'Active',
  },
  {
    mls: '49829965',
    address: '4912 Goose Creek Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,495',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,732',
    acres: '0.276',
    yearBuilt: '1965',
    subdivision: 'Country Club Oaks Sec 01',
    county: 'Harris',
    remarks: 'HUGE home in the Country Club Oaks! New carpet and ...',
    photo: '/assets/rentals/baytown/49829965.jpg',
    status: 'Active',
  },
  {
    mls: '43948345',
    address: '1206 Olive Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,112',
    acres: '0.201',
    yearBuilt: '1950',
    subdivision: 'Milby Dale Sec 01',
    county: 'Harris',
    remarks: 'Charming, Move-In Ready Home on a corner Lot! Welc ...',
    photo: '/assets/rentals/baytown/43948345.jpg',
    status: 'Active',
  },
  {
    mls: '72516186',
    address: '1606 E Fayle Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,800',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,554',
    acres: '0.281',
    yearBuilt: '1955',
    subdivision: 'Milby Dale Sec 02',
    county: 'Harris',
    remarks: 'Welcome home to this stunning, fully updated resid ...',
    photo: '/assets/rentals/baytown/72516186.jpg',
    status: 'Active',
  },
  {
    mls: '24353402',
    address: '3106 1/2 Michigan Unit B Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$800',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '427',
    acres: '0.138',
    yearBuilt: '1928',
    subdivision: 'East Baytown',
    county: 'Harris',
    remarks: 'Welcome to 3106 1/2 Michigan Street! This entire a ...',
    photo: '/assets/rentals/baytown/24353402.jpg',
    status: 'Active',
  },
  {
    mls: '8596775',
    address: '3106 Michigan Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,650',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,200',
    acres: '0.138',
    yearBuilt: '1928',
    subdivision: 'East Baytown',
    county: 'Harris',
    remarks: 'Welcome to 3106 Michigan Street! This pet friendly ...',
    photo: '/assets/rentals/baytown/8596775.jpg',
    status: 'Active',
  },
  {
    mls: '9243420',
    address: '6934 Orchid Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,600',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,124',
    acres: '0.131',
    yearBuilt: '2014',
    subdivision: 'West Mdws Sec 5 Final Plat',
    county: 'Harris',
    remarks: 'This beautifully refreshed home is move-in ready a ...',
    photo: '/assets/rentals/baytown/9243420.jpg',
    status: 'Active',
  },
  {
    mls: '20383437',
    address: '417 E Jack Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,500',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,520',
    acres: '0.172',
    yearBuilt: '1953',
    subdivision: 'Gwenette Court',
    county: 'Harris',
    remarks: 'Cute 3 bedroom with 1 bathroom home offering an ad ...',
    photo: '/assets/rentals/baytown/20383437.jpg',
    status: 'Active',
  },
  {
    mls: '57153892',
    address: '3208 Woodstone Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,650',
    acres: '0.172',
    yearBuilt: '1976',
    subdivision: 'Quail Hollow Sec 01',
    county: 'Harris',
    remarks: 'Beautifully remodeled and exceptionally well-maint ...',
    photo: '/assets/rentals/baytown/57153892.jpg',
    status: 'Active',
  },
  {
    mls: '49328167',
    address: '9311 Sierra Point Way',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,995',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,470',
    acres: '0.111',
    yearBuilt: '2022',
    subdivision: 'Burnet Fields Sec 1',
    county: 'Harris',
    remarks: 'Welcome to this beautiful single-story home locate ...',
    photo: '/assets/rentals/baytown/49328167.jpg',
    status: 'Active',
  },
  {
    mls: '44115126',
    address: '218 E Hunnicutt Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,450',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,164',
    acres: '0.115',
    yearBuilt: '1940',
    subdivision: 'Goose Creek',
    county: 'Harris',
    remarks: '3 Bedrooms, 1 Bathroom. Property is move in ready. ...',
    photo: '/assets/rentals/baytown/44115126.jpg',
    status: 'Active',
  },
  {
    mls: '35559390',
    address: '9602 Atwood Lake Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,150',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,847',
    acres: '',
    yearBuilt: '2023',
    subdivision: 'Sterling Point',
    county: 'Harris',
    remarks: 'Introducing a 4 Beds/2 Baths and a Study that nest ...',
    photo: '/assets/rentals/baytown/35559390.jpg',
    status: 'Active',
  },
  {
    mls: '5159065',
    address: '9018 Burnet Bay Court',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,050',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,470',
    acres: '0.164',
    yearBuilt: '2023',
    subdivision: 'Burnet Fields Sec 3',
    county: 'Harris',
    remarks: 'Beautiful 3-bedroom, 2-bath home available for lea ...',
    photo: '/assets/rentals/baytown/5159065.jpg',
    status: 'Active',
  },
  {
    mls: '92085206',
    address: '8434 Tranquil Bay Court',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,499',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,827',
    acres: '',
    yearBuilt: '2025',
    subdivision: 'Ascend At Legends Bay',
    county: 'Chambers',
    remarks: 'This Like Brand New 1-Story with 4beds/3baths/& a ...',
    photo: '/assets/rentals/baytown/92085206.jpg',
    status: 'Active',
  },
  {
    mls: '20405560',
    address: '1307 Dwinnell Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,750',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,548',
    acres: '0.24',
    yearBuilt: '1960',
    subdivision: 'Plumwood Sec 02',
    county: 'Harris',
    remarks: 'Welcome home to this beautifully updated 3-bedroom ...',
    photo: '/assets/rentals/baytown/20405560.jpg',
    status: 'Active',
  },
  {
    mls: '45989915',
    address: '8510 Amber Bend Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,813',
    acres: '0.184',
    yearBuilt: '2022',
    subdivision: 'Hunters Crk Sec 4',
    county: 'Harris',
    remarks: 'Welcome home to this beautifully maintained, moder ...',
    photo: '/assets/rentals/baytown/45989915.jpg',
    status: 'Pending',
  },
  {
    mls: '30141709',
    address: '14407 Sweet Water Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,575',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,355',
    acres: '0.169',
    yearBuilt: '',
    subdivision: 'Rain Tree Sec 1',
    county: 'Chambers',
    remarks: 'Like-New 4-Bedroom Corner Lot Home with Game Room, ...',
    photo: '/assets/rentals/baytown/30141709.jpg',
    status: 'Active',
  },
  {
    mls: '3383696',
    address: '4151 Saw Mill Peak Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,765',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,619',
    acres: '0.144',
    yearBuilt: '2023',
    subdivision: 'Burnet Fields Sec 2',
    county: 'Harris',
    remarks: 'Charming 4 bedroom and 2 bathroom home updated wit ...',
    photo: '/assets/rentals/baytown/3383696.jpg',
    status: 'Pending',
  },
  {
    mls: '95702353',
    address: '9919 Oakheath Bluff Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,095',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,720',
    acres: '',
    yearBuilt: '2024',
    subdivision: 'Sterling Point',
    county: 'Harris',
    remarks: 'Welcome to this beautiful one-story home featuring ...',
    photo: '/assets/rentals/baytown/95702353.jpg',
    status: 'Active',
  },
  {
    mls: '45610585',
    address: '306 Red Bud Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,028',
    acres: '0.303',
    yearBuilt: '1973',
    subdivision: 'Lakewood',
    county: 'Harris',
    remarks: 'Back on the market due to buyer circumstances—no f ...',
    photo: '/assets/rentals/baytown/45610585.jpg',
    status: 'Pending',
  },
  {
    mls: '69850768',
    address: '304 Stimson Avenue',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,675',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,432',
    acres: '0.115',
    yearBuilt: '1930',
    subdivision: 'Casey Sec 01',
    county: 'Harris',
    remarks: 'Beautifully updated 3-bedroom, 2-bath home offerin ...',
    photo: '/assets/rentals/baytown/69850768.jpg',
    status: 'Active',
  },
  {
    mls: '2337127',
    address: '1007 E Baker Road',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,056',
    acres: '0.372',
    yearBuilt: '1978',
    subdivision: 'Chaparral Village',
    county: 'Harris',
    remarks: 'Spacious 3-4 bedroom, 2.5-bath home on an oversize ...',
    photo: '/assets/rentals/baytown/2337127.jpg',
    status: 'Active',
  },
  {
    mls: '15726307',
    address: '605 E Hunnicutt Street C',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$950',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,040',
    acres: '0.181',
    yearBuilt: '1935',
    subdivision: 'Wright W P',
    county: 'Harris',
    remarks: '1 bed / 1 bath. HVAC mini splits. Large parking d ...',
    photo: '/assets/rentals/baytown/15726307.jpg',
    status: 'Active',
  },
  {
    mls: '83842173',
    address: '14814 Cold Water Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,636',
    acres: '0.158',
    yearBuilt: '2022',
    subdivision: 'Rain Tree Sec 3',
    county: 'Chambers',
    remarks: 'Welcome to 14814 Cold Water in Rain Tree subdivisi ...',
    photo: '/assets/rentals/baytown/83842173.jpg',
    status: 'Pending',
  },
  {
    mls: '10698595',
    address: '1731 William Scott Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,039',
    acres: '0.138',
    yearBuilt: '2021',
    subdivision: 'Trinity Oaks Sec 1',
    county: 'Harris',
    remarks: 'Spacious, stylish, and tucked away in a quiet Bayt ...',
    photo: '/assets/rentals/baytown/10698595.jpg',
    status: 'Active',
  },
  {
    mls: '41538514',
    address: '139 Horn Court',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,785',
    acres: '0.175',
    yearBuilt: '2008',
    subdivision: 'Lanai Sub',
    county: 'Chambers',
    remarks: 'Welcome to this well-maintained 4 bedroom, 2 bath ...',
    photo: '/assets/rentals/baytown/41538514.jpg',
    status: 'Active',
  },
  {
    mls: '90363504',
    address: '4035 Cary Creek Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,750',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,378',
    acres: '0.132',
    yearBuilt: '2007',
    subdivision: 'Cary Crk Estate',
    county: 'Harris',
    remarks: 'Welcome home! 3 Bedroom 2 Bath Home located in the ...',
    photo: '/assets/rentals/baytown/90363504.jpg',
    status: 'Active',
  },
  {
    mls: '34676394',
    address: '219 E James Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,375',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '864',
    acres: '0.057',
    yearBuilt: '1945',
    subdivision: 'Goose Creek Townsite',
    county: 'Harris',
    remarks: 'Fully renovated and move-in ready, this beautifull ...',
    photo: '/assets/rentals/baytown/34676394.jpg',
    status: 'Active',
  },
  {
    mls: '29154675',
    address: '4310 Sand Pebble Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,360',
    acres: '0.15',
    yearBuilt: '2021',
    subdivision: 'Wooster Crossing',
    county: 'Harris',
    remarks: 'Beautiful 4 bedroom, 2.5 baths ready for a new fam ...',
    photo: '/assets/rentals/baytown/29154675.jpg',
    status: 'Active',
  },
  {
    mls: '65576943',
    address: '805 Northbend Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,091',
    acres: '0.181',
    yearBuilt: '1968',
    subdivision: 'Glen Meadow Sec 03',
    county: 'Harris',
    remarks: 'Looking for your next place to call home? This 3 b ...',
    photo: '/assets/rentals/baytown/65576943.jpg',
    status: 'Pending',
  },
  {
    mls: '97656046',
    address: '109 Schilling Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,375',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,053',
    acres: '0.138',
    yearBuilt: '1939',
    subdivision: 'Morrell Park Sec 01',
    county: 'Harris',
    remarks: 'Charming property featuring 2 spacious bedrooms, a ...',
    photo: '/assets/rentals/baytown/97656046.jpg',
    status: 'Active',
  },
  {
    mls: '22198364',
    address: '3631 Apache Meadows Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,145',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,917',
    acres: '',
    yearBuilt: '2014',
    subdivision: 'Apache Meadows',
    county: 'Harris',
    remarks: 'The Drake Plan is a spacious two story home design ...',
    photo: '/assets/rentals/baytown/22198364.jpg',
    status: 'Active',
  },
  {
    mls: '23386722',
    address: '4806 Ripple Creek Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,850',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,250',
    acres: '0.158',
    yearBuilt: '1978',
    subdivision: 'Quail Hollow Sec 02 R/P',
    county: 'Harris',
    remarks: 'Charming 4bd-2ba home in Houston, where modern upd ...',
    photo: '/assets/rentals/baytown/23386722.jpg',
    status: 'Active',
  },
  {
    mls: '85909426',
    address: '800 E Adoue Street 1/2',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$800',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '550',
    acres: '0.115',
    yearBuilt: '1958',
    subdivision: 'Wright J W',
    county: 'Harris',
    remarks: 'Freshly renovated 1 bed, 1 bath unit for lease in ...',
    photo: '/assets/rentals/baytown/85909426.jpg',
    status: 'Active',
  },
  {
    mls: '22660781',
    address: '706 E Humble Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,110',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,134',
    acres: '0.142',
    yearBuilt: '1964',
    subdivision: 'Bennie Gray',
    county: 'Harris',
    remarks: 'Charming 3 bedroom and 1 bathroom home updated wit ...',
    photo: '/assets/rentals/baytown/22660781.jpg',
    status: 'Pending',
  },
  {
    mls: '32097993',
    address: '2906 Heatherwood Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,050',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,450',
    acres: '0.253',
    yearBuilt: '1978',
    subdivision: 'Quail Hollow',
    county: 'Harris',
    remarks: 'Welcome home! Beautiful 3 bedroom two bathroom hom ...',
    photo: '/assets/rentals/baytown/32097993.jpg',
    status: 'Active',
  },
  {
    mls: '69228609',
    address: '1826 Plantation Place',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,039',
    acres: '0.145',
    yearBuilt: '2021',
    subdivision: 'Trinity Oaks Sec 1',
    county: 'Harris',
    remarks: 'Beautiful 5-year-new home in a quiet neighborhood ...',
    photo: '/assets/rentals/baytown/69228609.jpg',
    status: 'Active',
  },
  {
    mls: '89144948',
    address: '1008 Wright Boulevard',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$2,150',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,730',
    acres: '0.162',
    yearBuilt: '1957',
    subdivision: 'Danubina Court Sec 02-B',
    county: 'Harris',
    remarks: 'Spacious 4-bedroom, 2.5-bath lease home with a ver ...',
    photo: '/assets/rentals/baytown/89144948.jpg',
    status: 'Active',
  },
  {
    mls: '22881204',
    address: '2629 W Main Street HOME',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,200',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'East Baytown Add',
    county: 'Harris',
    remarks: 'Stunning brand-new super spacious 3 bedroom, 2 bat ...',
    photo: '/assets/rentals/baytown/22881204.jpg',
    status: 'Active',
  },
  {
    mls: '62196687',
    address: '2633 W Main Street DPLX',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,850',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,624',
    acres: '0.138',
    yearBuilt: '2026',
    subdivision: 'East Baytown Add',
    county: 'Harris',
    remarks: 'Stunning brand-new super spacious 3 bedroom, 2 bat ...',
    photo: '/assets/rentals/baytown/62196687.jpg',
    status: 'Active',
  },
  {
    mls: '86915177',
    address: '8834 Bar Harbor Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,470',
    acres: '0.161',
    yearBuilt: '2022',
    subdivision: 'Wooster Crossing',
    county: 'Harris',
    remarks: 'Lovely brick home is located in the cul-de-sac on ...',
    photo: '/assets/rentals/baytown/86915177.jpg',
    status: 'Active',
  },
  {
    mls: '70118719',
    address: '903 Christopher',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,037',
    acres: '0.191',
    yearBuilt: '2004',
    subdivision: 'Baybrook Place Sec 01',
    county: 'Harris',
    remarks: 'Located on a corner lot, this spacious and well-ma ...',
    photo: '/assets/rentals/baytown/70118719.jpg',
    status: 'Active',
  },
  {
    mls: '23458945',
    address: '1521 Barcelona Way Way',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,350',
    acres: '0.079',
    yearBuilt: '1970',
    subdivision: 'Colony Madrid T/H',
    county: 'Harris',
    remarks: 'BIG 3 BEDROOM 2 BATH HOME WITH TILE FL ...',
    photo: '/assets/rentals/baytown/23458945.jpg',
    status: 'Active',
  },
  {
    mls: '71472891',
    address: '4714 Jasmine Heather Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,775',
    acres: '0.158',
    yearBuilt: '2023',
    subdivision: 'Sterling Point',
    county: 'Harris',
    remarks: 'Welcome to this beautifully maintained 4-bedroom, ...',
    photo: '/assets/rentals/baytown/71472891.jpg',
    status: 'Active',
  },
  {
    mls: '35963345',
    address: '1902 Amy Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,875',
    acres: '0.23',
    yearBuilt: '1958',
    subdivision: 'Eva Maud Sec 02',
    county: 'Harris',
    remarks: 'Welcome to your lovely move-in ready one story hom ...',
    photo: '/assets/rentals/baytown/35963345.jpg',
    status: 'Active',
  },
  {
    mls: '71846808',
    address: '8515 Lake Groove Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,900',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,845',
    acres: '0.169',
    yearBuilt: '2023',
    subdivision: 'Heights/Baytown Sec 1',
    county: 'Chambers',
    remarks: 'Looking for space, comfort, and a newer home? This ...',
    photo: '/assets/rentals/baytown/71846808.jpg',
    status: 'Active',
  },
  {
    mls: '18795094',
    address: '430 Walnut Branch Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,800',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,850',
    acres: '0.218',
    yearBuilt: '2021',
    subdivision: 'Rain Tree Sec 1',
    county: 'Chambers',
    remarks: '',
    photo: '/assets/rentals/baytown/18795094.jpg',
    status: 'Active',
  },
  {
    mls: '21978078',
    address: '211 Hunt Road 211',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,566',
    acres: '0.11',
    yearBuilt: '2002',
    subdivision: 'Huntcrest Condo Amd Ph 01',
    county: 'Harris',
    remarks: 'Experience the charm of Hunt Crest Condominiums, a ...',
    photo: '/assets/rentals/baytown/21978078.jpg',
    status: 'Active',
  },
  {
    mls: '86545307',
    address: '1703 Raintree Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$2,250',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,668',
    acres: '0.22',
    yearBuilt: '1960',
    subdivision: 'Bowie Sec 01',
    county: 'Harris',
    remarks: 'Welcome to 1703 Raintree Street, a beautifully upd ...',
    photo: '/assets/rentals/baytown/86545307.jpg',
    status: 'Active',
  },
  {
    mls: '24505420',
    address: '1401 Edison Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,325',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '936',
    acres: '0.138',
    yearBuilt: '1930',
    subdivision: 'Lee Heights',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/baytown/24505420.jpg',
    status: 'Active',
  },
  {
    mls: '21057712',
    address: '14911 Spring Forest Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,250',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,933',
    acres: '0.163',
    yearBuilt: '2022',
    subdivision: 'Raintree',
    county: 'Chambers',
    remarks: 'Welcome to 14911 Spring Forest Lane in Baytown. Th ...',
    photo: '/assets/rentals/baytown/21057712.jpg',
    status: 'Pending',
  },
  {
    mls: '23165288',
    address: '8422 Bay Orchard Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,856',
    acres: '0.153',
    yearBuilt: '2022',
    subdivision: 'Hunters Crk Sec 8',
    county: 'Harris',
    remarks: 'Discover this beautifully maintained single-story ...',
    photo: '/assets/rentals/baytown/23165288.jpg',
    status: 'Pending',
  },
  {
    mls: '61480893',
    address: '5410 Carriage Trails Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$1,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,612',
    acres: '0.457',
    yearBuilt: '1993',
    subdivision: 'Carriage Trails',
    county: 'Chambers',
    remarks: '3 bedroom 2 bath manufactured home with washer dry ...',
    photo: '/assets/rentals/baytown/61480893.jpg',
    status: 'Pending',
  },
  {
    mls: '15306697',
    address: '10426 Briar Patch Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,396',
    acres: '0.127',
    yearBuilt: '2004',
    subdivision: 'Hunters Chase Sec 02',
    county: 'Chambers',
    remarks: 'cute home in middle of booming area near Walmart, ...',
    photo: '/assets/rentals/baytown/15306697.jpg',
    status: 'Pending',
  },
  {
    mls: '27772281',
    address: '6614 Hunters Creek Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,500',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,680',
    acres: '0.139',
    yearBuilt: '2014',
    subdivision: 'Hunters Crk Sec 2',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/baytown/27772281.jpg',
    status: 'Active',
  },
  {
    mls: '41965576',
    address: '5130 Red Drum Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,050',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,522',
    acres: '0.125',
    yearBuilt: '2025',
    subdivision: 'Scotts Bend Sec 5',
    county: 'Harris',
    remarks: 'This home is conveniently laid out on a single flo ...',
    photo: '/assets/rentals/baytown/41965576.jpg',
    status: 'Pending',
  },
  {
    mls: '97473977',
    address: '1701 Gillette Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,900',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,940',
    acres: '0.23',
    yearBuilt: '1956',
    subdivision: 'Eva Maud',
    county: 'Harris',
    remarks: '“Beautiful and spacious 4-bedroom, 2.5-bath , Gas ...',
    photo: '/assets/rentals/baytown/97473977.jpg',
    status: 'Active',
  },
  {
    mls: '84132977',
    address: '4435 Bearberry Avenue',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,840',
    acres: '0.219',
    yearBuilt: '2015',
    subdivision: 'Bay River Colony',
    county: 'Harris',
    remarks: 'Welcome home! This beautifully maintained, move-in ...',
    photo: '/assets/rentals/baytown/84132977.jpg',
    status: 'Active',
  },
  {
    mls: '5812890',
    address: '4835 Evergreen Hills Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$3,100',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,950',
    acres: '0.227',
    yearBuilt: '2020',
    subdivision: 'Ashbel Crossing',
    county: 'Harris',
    remarks: 'This spacious 2,950 sq ft Beazer home overlooking ...',
    photo: '/assets/rentals/baytown/5812890.jpg',
    status: 'Active',
  },
  {
    mls: '9014975',
    address: '6807 Vista Ledge Drive',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$2,650',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,400',
    acres: '0.184',
    yearBuilt: '2021',
    subdivision: 'Hunters Crk Sec 8',
    county: 'Harris',
    remarks: 'Welcome to your new home! Step into this elegant 4 ...',
    photo: '/assets/rentals/baytown/9014975.jpg',
    status: 'Active',
  },
  {
    mls: '10731935',
    address: '1215 Wallflower Avenue',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,950',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,672',
    acres: '0.128',
    yearBuilt: '2014',
    subdivision: 'West Meadows',
    county: 'Harris',
    remarks: 'Welcome to your new home. A stunning rental home i ...',
    photo: '/assets/rentals/baytown/10731935.jpg',
    status: 'Active',
  },
  {
    mls: '50473160',
    address: '419 W Cleveland Street',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,425',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '720',
    acres: '0.115',
    yearBuilt: '1940',
    subdivision: 'Middletown',
    county: 'Harris',
    remarks: 'AVAILABLE NOW! Experience the perfect blend of lux ...',
    photo: '/assets/rentals/baytown/50473160.jpg',
    status: 'Active',
  },
  {
    mls: '87131076',
    address: '2801 Virginia Street A',
    city: 'Baytown',
    state: 'Texas',
    zip: '77520',
    price: '$1,250',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '2,358',
    acres: '0.149',
    yearBuilt: '1935',
    subdivision: 'East Baytown',
    county: 'Harris',
    remarks: 'WELCOME TO A 2 BEDRROM 1 BATHROOM HOME ...',
    photo: '/assets/rentals/baytown/87131076.jpg',
    status: 'Active',
  },
  {
    mls: '55485614',
    address: '5431 Harbor Mist',
    city: 'Baytown',
    state: 'Texas',
    zip: '77521',
    price: '$1,975',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,614',
    acres: '0.133',
    yearBuilt: '2004',
    subdivision: 'Preston Place Sec 02',
    county: 'Harris',
    remarks: 'This property will not last long! It is a one stor ...',
    photo: '/assets/rentals/baytown/55485614.jpg',
    status: 'Pending',
  },
  {
    mls: '19701317',
    address: '511 Louis Lane',
    city: 'Baytown',
    state: 'Texas',
    zip: '77523',
    price: '$2,400',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,814',
    acres: '0.231',
    yearBuilt: '2026',
    subdivision: 'Windcress',
    county: 'Chambers',
    remarks: 'This lovely 4 bedroom, 2 bath home is still new an ...',
    photo: '/assets/rentals/baytown/19701317.jpg',
    status: 'Active',
  },
]
