// La Porte homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const laporteRentListings: Listing[] = [
  {
    mls: '61147563',
    address: '9514 Catlett Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$950',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '784',
    acres: '0.219',
    yearBuilt: '1978',
    subdivision: 'Spenwick Place Sec 02',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/la-porte/61147563.jpg',
    status: 'Active',
  },
  {
    mls: '11758249',
    address: '211 W F Street 211',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,050',
    beds: '1 Bedrooms',
    baths: '1 Total Baths',
    sqft: '680',
    acres: '1.181',
    yearBuilt: '1975',
    subdivision: 'Bayshore Condo',
    county: 'Harris',
    remarks: 'Welcome to this charming well-maintained condo loc ...',
    photo: '/assets/rentals/la-porte/11758249.jpg',
    status: 'Active',
  },
  {
    mls: '49094468',
    address: '3344 Scotch Moss Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,321',
    acres: '0.164',
    yearBuilt: '1971',
    subdivision: 'Brookglen Sec 02 R/P',
    county: 'Harris',
    remarks: 'Nice duplex featuring 3 bedrooms and 2 full baths, ...',
    photo: '/assets/rentals/la-porte/49094468.jpg',
    status: 'Active',
  },
  {
    mls: '3973721',
    address: '302 S 5th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,500',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,062',
    acres: '0.144',
    yearBuilt: '1948',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Welcome home to this beautifully updated 2-bedroom ...',
    photo: '/assets/rentals/la-porte/3973721.jpg',
    status: 'Pending',
  },
  {
    mls: '67827337',
    address: '313 S Blackwell Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,600',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,326',
    acres: '0.215',
    yearBuilt: '1950',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Welcome to 313 S Blackwell St in La Porte, Texas! ...',
    photo: '/assets/rentals/la-porte/67827337.jpg',
    status: 'Active',
  },
  {
    mls: '28418797',
    address: '8306 Oakhaven Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,650',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,160',
    acres: '0.028',
    yearBuilt: '1978',
    subdivision: 'Oakhaven T/H U/R',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/la-porte/28418797.jpg',
    status: 'Active',
  },
  {
    mls: '29867711',
    address: '212 N 2nd Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,650',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,028',
    acres: '0.287',
    yearBuilt: '2005',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Welcome to 212 N 2nd Street a beautifully updated ...',
    photo: '/assets/rentals/la-porte/29867711.jpg',
    status: 'Active',
  },
  {
    mls: '39128402',
    address: '1519 S 8th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,650',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,220',
    acres: '0.039',
    yearBuilt: '1973',
    subdivision: 'Garden Walk T/H Sec 01',
    county: 'Harris',
    remarks: 'End unit, at the end of the cul de sac, 2 story, 3 ...',
    photo: '/assets/rentals/la-porte/39128402.jpg',
    status: 'Active',
  },
  {
    mls: '49693621',
    address: '622 N 13th Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,700',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '975',
    acres: '0.144',
    yearBuilt: '1978',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: '\\\\"PRICE TO SELL\\\\" Welcome home to La Porte living! T ...',
    photo: '/assets/rentals/la-porte/49693621.jpg',
    status: 'Active',
  },
  {
    mls: '32675897',
    address: '9911 Cardinal Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,800',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,240',
    acres: '0.142',
    yearBuilt: '1977',
    subdivision: 'Meadowcrest Sec 01',
    county: 'Harris',
    remarks: '3 Bed 2 Bath, 2 Car Garage Brick Home with large b ...',
    photo: '/assets/rentals/la-porte/32675897.jpg',
    status: 'Active',
  },
  {
    mls: '94971281',
    address: '312 S Utah Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,899',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,368',
    acres: '0.158',
    yearBuilt: '1940',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'NEWLY RENOVATED home in the heart of La Porte is r ...',
    photo: '/assets/rentals/la-porte/94971281.jpg',
    status: 'Active',
  },
  {
    mls: '72881470',
    address: '3877 Pecan Circle',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,451',
    acres: '0.143',
    yearBuilt: '1983',
    subdivision: 'Fairmont Park East Sec 01',
    county: 'Harris',
    remarks: 'Welcome to this inviting 3-bedroom, 2-bathroom hom ...',
    photo: '/assets/rentals/la-porte/72881470.jpg',
    status: 'Active',
  },
  {
    mls: '10549290',
    address: '1227 Mission Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,990',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,274',
    acres: '0.163',
    yearBuilt: '1979',
    subdivision: 'Monument Est Final Plat',
    county: 'Harris',
    remarks: 'FOR SALE OR LEASE. Highly sought after Lomax area! ...',
    photo: '/assets/rentals/la-porte/10549290.jpg',
    status: 'Active',
  },
  {
    mls: '73031395',
    address: '303 S Utah Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$1,999',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,728',
    acres: '0.072',
    yearBuilt: '2024',
    subdivision: 'Bay Front La Porte',
    county: 'Harris',
    remarks: 'Beautiful new construction home for rent featuring ...',
    photo: '/assets/rentals/la-porte/73031395.jpg',
    status: 'Active',
  },
  {
    mls: '97386923',
    address: '626 12th Street N',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '',
    acres: '',
    yearBuilt: '1978',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Welcome to this charming 3-bedroom, 2-bath home lo ...',
    photo: '/assets/rentals/la-porte/97386923.jpg',
    status: 'Active',
  },
  {
    mls: '20850868',
    address: '317 San Jacinto Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,050',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,076',
    acres: '0.144',
    yearBuilt: '1948',
    subdivision: 'San Jacinto Homes',
    county: 'Harris',
    remarks: 'Located just minutes from the beach, this beautifu ...',
    photo: '/assets/rentals/la-porte/20850868.jpg',
    status: 'Active',
  },
  {
    mls: '15632300',
    address: '3310 Ashwyne Court',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,100',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,235',
    acres: '0.237',
    yearBuilt: '1976',
    subdivision: 'Brookglen Sec 02 R/P',
    county: 'Harris',
    remarks: 'Schedule a tour today of of this well-maintained 4 ...',
    photo: '/assets/rentals/la-porte/15632300.jpg',
    status: 'Active',
  },
  {
    mls: '21789596',
    address: '9910 Willmont Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,526',
    acres: '0.183',
    yearBuilt: '1978',
    subdivision: 'Fairmont Park West Sec 02',
    county: 'Harris',
    remarks: 'Charming 3-bedroom ,2 bath home in La Porte featur ...',
    photo: '/assets/rentals/la-porte/21789596.jpg',
    status: 'Active',
  },
  {
    mls: '15742163',
    address: '9734 Willmont Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,100',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,561',
    acres: '0.158',
    yearBuilt: '1977',
    subdivision: 'Fairmont Park West Sec 01 R/P',
    county: 'Harris',
    remarks: 'Welcome to this beautifully updated 3-bedroom, 2-b ...',
    photo: '/assets/rentals/la-porte/15742163.jpg',
    status: 'Active',
  },
  {
    mls: '38702239',
    address: '1413 Highway 146 S',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,955',
    acres: '0.04',
    yearBuilt: '2002',
    subdivision: 'Garden Walk T/H Sec 1',
    county: 'Harris',
    remarks: 'Fully furnished and move-in ready, this well-locat ...',
    photo: '/assets/rentals/la-porte/38702239.jpg',
    status: 'Active',
  },
  {
    mls: '56469551',
    address: '9842 Shell Rock Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,476',
    acres: '0.15',
    yearBuilt: '1979',
    subdivision: 'Fairmont Park West Sec 04',
    county: 'Harris',
    remarks: 'Welcome home to this beautifully updated **4-bedro ...',
    photo: '/assets/rentals/la-porte/56469551.jpg',
    status: 'Active',
  },
  {
    mls: '68287379',
    address: '10263 Old Orchard Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,389',
    acres: '0.257',
    yearBuilt: '1960',
    subdivision: 'Fairmont Park Sec 01',
    county: 'Harris',
    remarks: 'This charming 3 bedroom, 2 bath rental property is ...',
    photo: '/assets/rentals/la-porte/68287379.jpg',
    status: 'Active',
  },
  {
    mls: '49857047',
    address: '9906 Rocky Hollow Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,200',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,454',
    acres: '0.15',
    yearBuilt: '1980',
    subdivision: 'Fairmont Park West Sec 04',
    county: 'Harris',
    remarks: 'Charming one story home featuring an open floor pl ...',
    photo: '/assets/rentals/la-porte/49857047.jpg',
    status: 'Active',
  },
  {
    mls: '69581286',
    address: '3210 Valley Brook Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,200',
    beds: '4 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,265',
    acres: '0.224',
    yearBuilt: '1962',
    subdivision: 'Fairmont Park',
    county: 'Harris',
    remarks: 'Updated four-bedroom, two-bath home available in L ...',
    photo: '/assets/rentals/la-porte/69581286.jpg',
    status: 'Active',
  },
  {
    mls: '59853458',
    address: '10923 Birch Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,250',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,440',
    acres: '0.152',
    yearBuilt: '1984',
    subdivision: 'Fairmont Park East Sec 02',
    county: 'Harris',
    remarks: 'This charming home has been lovingly cared for. S ...',
    photo: '/assets/rentals/la-porte/59853458.jpg',
    status: 'Active',
  },
  {
    mls: '54811775',
    address: '10911 Pecan Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,300',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,861',
    acres: '0.158',
    yearBuilt: '1983',
    subdivision: 'Fairmont Park East Sec 01',
    county: 'Harris',
    remarks: 'Welcome to 10911 Pecan Drive! This spacious 3-bedr ...',
    photo: '/assets/rentals/la-porte/54811775.jpg',
    status: 'Pending',
  },
  {
    mls: '47804945',
    address: '10904 Birch Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,300',
    beds: '4 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,954',
    acres: '0.152',
    yearBuilt: '1984',
    subdivision: 'Fairmont Park East Sec 02',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/la-porte/47804945.jpg',
    status: 'Active',
  },
  {
    mls: '44535355',
    address: '501 S Holmes Street',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,495',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,364',
    acres: '0.287',
    yearBuilt: '1978',
    subdivision: 'Bay Front Laporte',
    county: 'Harris',
    remarks: 'JUST LISTED! Welcome to 501 S Holmes St., a charmi ...',
    photo: '/assets/rentals/la-porte/44535355.jpg',
    status: 'Active',
  },
  {
    mls: '83954403',
    address: '9735 Stonemont Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,550',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,726',
    acres: '0.164',
    yearBuilt: '1977',
    subdivision: 'Fairmont Park West',
    county: 'Harris',
    remarks: 'Charming 3 Bedroom, 2 Bath HomeWelcome to your new ...',
    photo: '/assets/rentals/la-porte/83954403.jpg',
    status: 'Active',
  },
  {
    mls: '96453387',
    address: '10917 Spruce Drive S',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$2,875',
    beds: '5 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,992',
    acres: '0.27',
    yearBuilt: '1993',
    subdivision: 'Fairmont Park E Sec 4 Ph 4a',
    county: 'Harris',
    remarks: '',
    photo: '/assets/rentals/la-porte/96453387.jpg',
    status: 'Active',
  },
  {
    mls: '78860030',
    address: '288 Kara Mist Court',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$3,300',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,753',
    acres: '0.239',
    yearBuilt: '2020',
    subdivision: 'Morgans Lndg Sec 7',
    county: 'Harris',
    remarks: 'This is a gorgeous, well maintained, 4 bedroom 3.5 ...',
    photo: '/assets/rentals/la-porte/78860030.jpg',
    status: 'Pending',
  },
  {
    mls: '21383855',
    address: '8510 Ashwyne Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$3,900',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,198',
    acres: '0.145',
    yearBuilt: '1975',
    subdivision: 'Brookglen Sec 02 R/P',
    county: 'Harris',
    remarks: '$165 Per night (two night Minimum) One week $1,500 ...',
    photo: '/assets/rentals/la-porte/21383855.jpg',
    status: 'Active',
  },
  {
    mls: '45813088',
    address: '618 Bayridge Road',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$3,900',
    beds: '3 Bedrooms',
    baths: '1 Total Baths',
    sqft: '1,641',
    acres: '0.844',
    yearBuilt: '1933',
    subdivision: 'La Porte',
    county: 'Harris',
    remarks: 'Livestock welcomed: ponies, goats, sheep, female t ...',
    photo: '/assets/rentals/la-porte/45813088.jpg',
    status: 'Active',
  },
  {
    mls: '43468438',
    address: '603 Beachman Shore Lane',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$4,300',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,558',
    acres: '0.182',
    yearBuilt: '2021',
    subdivision: 'Morgans Lndg Sec 8',
    county: 'Harris',
    remarks: 'This immaculate 2-story home offers an EV charger, ...',
    photo: '/assets/rentals/la-porte/43468438.jpg',
    status: 'Active',
  },
  {
    mls: '8106594',
    address: '2011 Crescent Drive',
    city: 'La Porte',
    state: 'Texas',
    zip: '77571',
    price: '$5,800',
    beds: '4 Bedrooms',
    baths: '5 Total Baths',
    sqft: '4,654',
    acres: '0.388',
    yearBuilt: '2021',
    subdivision: 'Crescent Shores',
    county: 'Harris',
    remarks: 'Welcome to 2011 Crescent Shores. This is a stunnin ...',
    photo: '/assets/rentals/la-porte/8106594.jpg',
    status: 'Active',
  },
]
