// Kemah homes for rent — scraped from 1sttexasrealtors.com (IDX Broker) on 2026-08-15.

import type { Listing } from "./listing-type"

export const kemahRentListings: Listing[] = [
  {
    mls: '76362593',
    address: '175 W 6th Street C',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$1,850',
    beds: '2 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,100',
    acres: '0.149',
    yearBuilt: '2024',
    subdivision: 'West Kemah 2',
    county: 'Galveston',
    remarks: 'Introducing a stunning fourplex in prime Kemah, of ...',
    photo: '/assets/rentals/kemah/76362593.jpg',
    status: 'Active',
  },
  {
    mls: '39439220',
    address: '120 W 8th Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,000',
    beds: '2 Bedrooms',
    baths: '1 Total Baths',
    sqft: '896',
    acres: '0.115',
    yearBuilt: '2010',
    subdivision: 'West Kemah 4',
    county: 'Galveston',
    remarks: 'This great beach style Kemah home comes fully furn ...',
    photo: '/assets/rentals/kemah/39439220.jpg',
    status: 'Active',
  },
  {
    mls: '89569939',
    address: '2131 Kemah Village Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,150',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,570',
    acres: '0.039',
    yearBuilt: '2005',
    subdivision: 'Kemah Village 2005',
    county: 'Galveston',
    remarks: 'Beautifully maintained townhome available for leas ...',
    photo: '/assets/rentals/kemah/89569939.jpg',
    status: 'Active',
  },
  {
    mls: '72734308',
    address: '1140 Marina Bay Drive 110A',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,200',
    beds: '2 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,710',
    acres: '0.039',
    yearBuilt: '1985',
    subdivision: 'Moon Caye Condo',
    county: 'Galveston',
    remarks: 'This beautiful waterfront condo has relaxing and b ...',
    photo: '/assets/rentals/kemah/72734308.jpg',
    status: 'Active',
  },
  {
    mls: '64880532',
    address: '605 6 Street D',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,400',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,000',
    acres: '',
    yearBuilt: '2000',
    subdivision: 'Kemah Townsite',
    county: 'Galveston',
    remarks: 'Entertainment District Apartment. Beautiful Spacio ...',
    photo: '/assets/rentals/kemah/64880532.jpg',
    status: 'Active',
  },
  {
    mls: '12547962',
    address: '1835 Oak Ridge Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,500',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '1,515',
    acres: '0.122',
    yearBuilt: '1994',
    subdivision: 'Kemah Oaks Sub 92',
    county: 'Galveston',
    remarks: 'This charming single-story home in Kemah Oaks offe ...',
    photo: '/assets/rentals/kemah/12547962.jpg',
    status: 'Coming Soon',
  },
  {
    mls: '84170892',
    address: '624 Pelican Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,600',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,749',
    acres: '0.046',
    yearBuilt: '2023',
    subdivision: 'Kemah Crossing',
    county: 'Galveston',
    remarks: 'Enjoy the best of Kemah living in this beautiful 3 ...',
    photo: '/assets/rentals/kemah/84170892.jpg',
    status: 'Active',
  },
  {
    mls: '20491157',
    address: '2186 Shady Pier Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,695',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '1,617',
    acres: '0.053',
    yearBuilt: '2024',
    subdivision: 'Kemah Xing Sec 3',
    county: 'Galveston',
    remarks: 'Welcome home to this practically new 3-bedroom, 2. ...',
    photo: '/assets/rentals/kemah/20491157.jpg',
    status: 'Active',
  },
  {
    mls: '78112730',
    address: '2418 Yacht Harbor Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,700',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,021',
    acres: '0.061',
    yearBuilt: '2023',
    subdivision: 'Kemah Crossing Ph',
    county: 'Galveston',
    remarks: 'Discover the epitome of modern living in this bran ...',
    photo: '/assets/rentals/kemah/78112730.jpg',
    status: 'Pending',
  },
  {
    mls: '17705529',
    address: '602 Oak Briar Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,700',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,333',
    acres: '0.147',
    yearBuilt: '1995',
    subdivision: 'Kemah Oaks Sub 92',
    county: 'Galveston',
    remarks: '',
    photo: '/assets/rentals/kemah/17705529.jpg',
    status: 'Active',
  },
  {
    mls: '89809759',
    address: '612 8th Street',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,800',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,352',
    acres: '0.067',
    yearBuilt: '2005',
    subdivision: 'Kipp Ave Twnhms 2006',
    county: 'Galveston',
    remarks: 'Live where most people vacation. Enjoy coastal liv ...',
    photo: '/assets/rentals/kemah/89809759.jpg',
    status: 'Active',
  },
  {
    mls: '46626639',
    address: '2419 Driftwood Trail',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$2,950',
    beds: '3 Bedrooms',
    baths: '3 Total Baths',
    sqft: '2,505',
    acres: '0.061',
    yearBuilt: '2023',
    subdivision: 'Kemah Crossing',
    county: 'Galveston',
    remarks: 'Welcome to 2419 Driftwood Trail, where modern desi ...',
    photo: '/assets/rentals/kemah/46626639.jpg',
    status: 'Active',
  },
  {
    mls: '47709747',
    address: '327 Twin Timbers Lane',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$3,500',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '2,631',
    acres: '0.161',
    yearBuilt: '2015',
    subdivision: 'Cypress Bay Sec 2 2010',
    county: 'Galveston',
    remarks: 'Welcome to this Beautiful, Move-In ready Home in C ...',
    photo: '/assets/rentals/kemah/47709747.jpg',
    status: 'Active',
  },
  {
    mls: '47189007',
    address: '806 Kipp Avenue',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$4,000',
    beds: '3 Bedrooms',
    baths: '2 Total Baths',
    sqft: '2,050',
    acres: '0.166',
    yearBuilt: '2016',
    subdivision: 'Kemah Townsite',
    county: 'Galveston',
    remarks: 'Coastal living awaits in this fully furnished 3-be ...',
    photo: '/assets/rentals/kemah/47189007.jpg',
    status: 'Active',
  },
  {
    mls: '2124837',
    address: '502 Amalfi Drive',
    city: 'Kemah',
    state: 'Texas',
    zip: '77565',
    price: '$6,200',
    beds: '4 Bedrooms',
    baths: '4 Total Baths',
    sqft: '3,446',
    acres: '0.325',
    yearBuilt: '2022',
    subdivision: 'Cypress Bay Sec 3 2010',
    county: 'Galveston',
    remarks: 'BOATER’S DREAM! EXPERIENCE TRUE ELEGANC ...',
    photo: '/assets/rentals/kemah/2124837.jpg',
    status: 'Active',
  },
]
