import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ContactForm } from '@/components/ContactForm'
import { SiteFooter } from '@/components/SiteFooter'
import { SiteHeader } from '@/components/SiteHeader'
import { ScrollReveals } from '@/components/Motion'
import { agents, allStaticPaths, areaSlug, email, phone, rentPath, serviceAreas, servicePages, testimonials } from '@/content/site'

export function generateStaticParams() { return allStaticPaths.map(path => ({ slug: path.split('/') })) }

function AreaPage({ area, rent }: { area: string; rent: boolean }) {
  const title = rent ? `${area} Homes for Rent` : `${area} Realtors & Homes for Sale`
  return <PageFrame eyebrow="Local service area" title={title} intro={rent ? `Find homes for rent in ${area} with local guidance on neighborhoods, schools, commutes, and leasing.` : `Work with 1st Texas Realtors for homes for sale and expert local service in ${area}.`}><div className="area-hero-card"><h2>{rent ? 'View homes for rent' : 'View homes for sale'}</h2><p>Use our real-time Home Search or contact a Realtor for current listings, market guidance, and a plan tailored to your move.</p><div className="hero-actions"><Link className="button button-dark" href="/home-search/">Search listings <span>↗</span></Link><Link className="button button-red" href="/contact/">Contact a Realtor <span>↗</span></Link></div></div><h2 className="subheading">Nearby service areas</h2><div className="area-grid">{serviceAreas.filter(item => item !== area).slice(0, 10).map(item => <Link key={item} href={rentPath(item)}>{item}<span>↗</span></Link>)}</div></PageFrame>
}

function PageFrame({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) {
  return <div className="site-shell"><SiteHeader /><main className="page-main"><section className="page-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p></section><section className="page-content reveal">{children}</section></main><SiteFooter /><ScrollReveals /></div>
}

export default async function Page({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params
  const key = slug.join('/')
  const areaSale = key.startsWith('realtors-in-') ? serviceAreas.find(area => `realtors-in-${areaSlug(area)}` === key) : undefined
  const areaRent = serviceAreas.find(area => `${areaSlug(area)}-tx-homes-for-rent` === key)
  if (areaSale || areaRent) return <AreaPage area={(areaSale || areaRent)!} rent={Boolean(areaRent)} />
  if (servicePages[key]) { const page = servicePages[key]; return <PageFrame eyebrow={page.eyebrow} title={page.title} intro={page.intro}><div className="rich-layout">{page.image && <img className="feature-image" src={page.image} alt="Clear Lake area real estate" />}<div className="rich-sections">{page.sections.map(section => <article key={section.title}><h2>{section.title}</h2><p>{section.body}</p></article>)}</div></div><div className="page-cta"><p>For immediate assistance, call <strong>{phone}</strong>.</p><Link className="button button-dark" href="/contact/">Talk with a Realtor <span>↗</span></Link></div></PageFrame> }
  if (key === 'about') return <PageFrame eyebrow="About 1st Texas Realtors" title="Experience that stays personal." intro="Since 2004, 1st Texas Realtors has operated as a full-service real estate brokerage led by David & Simone Karstedt."><div className="rich-sections"><article><h2>When you hire one, you get the experience and knowledge of all.</h2><p>We know the Clear Lake NASA area, its neighborhoods, schools, grocery stores, commutes, and many people. Our team provides dedicated service and real-time property listings for buyers, sellers, renters, and commercial clients.</p></article><article><h2>Full-service support</h2><p>Our services include brokerage and expert Realtors, MLS Home Search, representing buyers and sellers, REO and foreclosure support, negotiation and transaction coordination, commercial real estate, new home construction, relocation, leasing, and property management.</p></article></div><img className="wide-image" src="/assets/reference/1st-Texas-Realtors-Team2.png" alt="1st Texas Realtors team" /></PageFrame>
  if (key === 'realtor-reviews') return <PageFrame eyebrow="Great reviews & testimonials" title="Service people remember." intro="Clients across Clear Lake NASA and the surrounding communities value responsiveness, local knowledge, negotiation, patience, and personalized support."><div className="testimonial-grid testimonial-grid-large">{testimonials.map(review => <blockquote key={review.author}><p>“{review.quote}”</p><cite>{review.author}</cite></blockquote>)}</div><p className="area-note">Serving Baytown, Clear Lake City, Clear Lake Shores, Deer Park, Dickinson, El Lago, Friendswood, Galveston, Kemah, La Porte, League City, Nassau Bay, Pasadena, Pearland, Seabrook, Taylor Lake Village, Texas City, Tiki Island, and Webster.</p></PageFrame>
  if (key === 'agents') return <PageFrame eyebrow="Meet our agents" title="A team for the whole journey." intro="David, Simone, and our Realtors bring local experience, dedicated customer service, and real-time property listings to every conversation."><div className="agent-grid agent-grid-large">{agents.map(agent => <Link className="agent-card" key={agent.slug} href={`/agents/${agent.slug}/`}><img src={agent.image} alt={agent.name} /><div className="agent-info"><h2>{agent.name}</h2><p>{agent.role}</p><span>View profile ↗</span></div></Link>)}</div></PageFrame>
  if (key.startsWith('agents/')) { const agent = agents.find(item => item.slug === slug[1]); if (!agent) notFound(); return <PageFrame eyebrow={agent.role} title={agent.name} intro={agent.bio}><div className="agent-profile"><img className="profile-image" src={agent.image} alt={agent.name} /><div><h2>Professional and caring from first conversation through closing and funding.</h2><p>{agent.bio} Contact {agent.name} through the 1st Texas Realtors team to discuss your next move.</p>{agent.phone && agent.email && <div className="agent-contact-list"><div className="agent-contact"><strong>{agent.name}</strong><a href={`tel:${agent.phone.replaceAll('-', '')}`}>{agent.phone}</a><a href={`mailto:${agent.email}`}>{agent.email}</a></div></div>}<Link className="button button-dark" href="/contact/">Contact the team <span>↗</span></Link></div></div></PageFrame> }
  if (key === 'contact') return <PageFrame eyebrow="Contact" title="Contact the 1st Texas Realtors" intro="Contact the 1st Texas Realtors for expert and local real estate service on homes, land, and commercial property for rent"><div className="contact-layout"><div><h2>We’re here to help.</h2><p>Hours: Monday through Saturday from 9am to 6pm.</p><a className="contact-detail" href="tel:+12812413121">{phone}</a><a className="contact-detail" href={`mailto:${email}`}>{email}</a><p>To contact one of our Realtors, please click <Link className="text-link" href="/agents/">Meet Our Agents <span>↗</span></Link>.</p><div className="agent-contact-list">{agents.map(agent => <div className="agent-contact" key={agent.slug}><strong>{agent.name}</strong><a href={`tel:${agent.phone?.replaceAll('-', '')}`}>{agent.phone}</a><a href={`mailto:${agent.email}`}>{agent.email}</a></div>)}</div></div><ContactForm /></div></PageFrame>
  if (key === 'privacy-policy') return <PageFrame eyebrow="1st Texas Realtors" title="Privacy Policy" intro="We respect your privacy and collect only the information required to provide the services you request."><div className="rich-sections"><article><h2>Information we collect</h2><p>Information is collected only as required for membership registration and custom Home Searches. It is not shared, distributed, sold, or used for unrelated purposes.</p></article><article><h2>Security and choices</h2><p>Security partners may include GoDaddy, WordPress, IDX Broker, and Google Recaptcha. Registered users can unsubscribe through account settings or by contacting the company.</p></article></div></PageFrame>
  if (['home-search', 'register', 'login'].includes(key)) return <PageFrame eyebrow="1st Texas Realtors" title={key === 'home-search' ? 'Real-time Home Search' : key === 'register' ? 'Register for custom searches' : 'Member login'} intro="Our property search tools are being connected for the redesigned site. Contact a Realtor now for immediate listing assistance."><div className="area-hero-card"><p>{key === 'register' ? 'Register to save custom home searches and receive automatic email alerts when matching listings are added.' : key === 'login' ? 'Existing members can contact us for assistance accessing their saved searches.' : 'Use our free MLS Home Search to browse homes for sale and rent available today.'}</p><Link className="button button-dark" href="/contact/">Get immediate assistance <span>↗</span></Link></div></PageFrame>
  notFound()
}
